### ISSUE TITLE
Checkbox state with mysql

### ISSUE THREAD

**Issue by harwenSt** [vitmalina/w2ui#1002]
I've modified the php mysql example by adding a checkbox to to the edit-user popup which refers to a thinyint column in the mysql table. By performing a double click on the grid row the popup shows up, all field values are loaded properly, except the state of the checkbox. It is always checked. 

It seams that there is some reload issue with the checkbox after rendering the popup, because all other fields show the right values.

**Comment by vitmalina** [comment]
Please be more specific what is wrong. Creating jsFiddle might shed more light.

**Comment by vitmalina** [comment]
Since no further response, closing the issue.
