### ISSUE TITLE
Subgrid appearance problem

### ISSUE THREAD

**Issue by adilek** [vitmalina/w2ui#1004]
Subgird has appearance problem in recent version:

![w2ui_grid_bug](https://cloud.githubusercontent.com/assets/1143625/8837003/90758e1c-30dd-11e5-8cf1-6cb4b7487fdb.png)

**Comment by vitmalina** [comment]
Yes. And there is already a issue for tracking that.

**Comment by adilek** [comment]
This issue can be considered as closed when the corresponding pull request will be merged as well.

**Comment by ppearson111** [comment]
Good fix -- thank you!  Is this available on the master branch now?

**Comment by adilek** [comment]
It is available in my fork. Hope this will be merged soon.

On Friday, August 7, 2015, Paul <notifications@github.com> wrote:

> Good fix -- thank you! Is this available on the master branch now?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vitmalina/w2ui/issues/1004#issuecomment-128770328>.
>


-- 
Adil Aliyev
Mobile: +99450 244 07 07
PGP: 0x17A71712
Website: http://adil.az

*Please don`t print this e-mail unless you really need to!*
