### ISSUE TITLE
grid: adjusting row height causes slow/strange behavior

### ISSUE THREAD

**Issue by erco77** [vitmalina/w2ui#1009]
I think I found a problem setting the height of the rows to e.g. "1em". I found if I do that it mostly works, but the UI acts strangely at first, if the row data doesn't quite fill the table, e.g. content fills only 2/3 of the table's size. Smaller data, or data larger than the display doesn't seem to show the issue. 

I canned the problem here:
http://seriss.com/people/erco/tmp/w2ui-height-problem.html
..which is basically the demo code from this page:
http://w2ui.com/web/demo/grid
..with just style: "height: 1em;" added to all the records.

In my browsers (Firefox 38.1.0/linux + Safari 8.0.5/osx 10.10), when I first load the page, hovering over the table acts "slowly", and dragging a selection causes the selected rows to get larger in size (their default size?).
Then, when the vertical scrollbar appears (due to the selection enlarging the rows), things start working normally; "slowness" goes away, and redoing the selection a few times over the entire table  makes it begin to act normally, and the size starts being consistent.

Seems like the table assumes the row heights are still the default during selection, but the appearance of the vertical scrollbar triggers the table to recalculate the row heights properly, and prevents the "slowness" (which seems to be the javascript being overworked).

The problem seems specific to the height of the table data; if the data with the default height would cause the table's scrollbar to appear, but not with the smaller height I set for the rows using 'style', then the problem occurs until the scrollbar is forced to appear.

Seems like a bug, or maybe I shouldn't be setting the row height this way?
Assuming this is the correct way to set the row height, curious if there's a workaround where I can call the w2ui function that recalculates the table (same code the scrollbar's appearance causes)

**Comment by erco77** [comment]
Oh, and I should add, to cause the scrollbar to appear, you probably have to select /all/ the rows..

**Comment by vitmalina** [comment]
The correct way to set height of the records would be http://w2ui.com/web/docs/w2grid.recordHeight.
