### ISSUE TITLE
sorry is Is it possible to paint a cell of a different color? independently painting the entire row

### ISSUE THREAD

**Issue by chalchis** [vitmalina/w2ui#1012]
Is it possible to paint a cell of a different color?
independently painting the entire row

this my code json return in php

```php
//array del grid
								$datos_materia[] = array(
											'recid'	 		=> $contador_mat,//identificador para el grid											
											'keymateria'	=> $id_mat_segura,//identificador del registro													
											'matgrado'		=> $matPlan_kardex['acad_mat_grado'],//grado																	
											'matdesc'		=> $matPlan_kardex['acad_mat_nom'],//nombre de la materia
											'matclave'		=> $matPlan_kardex['acad_mat_clave'],//clave de la materia
											'matseriada' 	=> $perfil_materia_seriada['acad_mat_clave'],//clave materia seriada											
											'style'			=> ''//fila pintada
										);											

								//incrementar
								$contador_mat++;
```
![cell_paint](https://cloud.githubusercontent.com/assets/2206648/9080652/91af8ace-3b1b-11e5-8f83-6862251d1be5.jpg)

Greetings and I hope your comments

**Comment by adilek** [comment]
Have you looked at http://w2ui.com/web/demos/#!combo/combo-3 ?

**Comment by chalchis** [comment]
Oh, that's good
thanks friend

**Comment by chalchis** [comment]
just to be clear as in the array from the server side
in this case php

´´´php
//array del grid
								$datos_materia[] = array(
											'recid'	 		=> $contador_mat,//identificador para el grid											
											'keymateria'	=> $id_mat_segura,//identificador del registro		
											'cursando'		=> $ban_cursando_mat,//indica si esta cursando la materia											
											'matgrado'		=> $matPlan_kardex['acad_mat_grado'],//grado																	
											'matdesc'		=> $matPlan_kardex['acad_mat_nom'],//nombre de la materia
											'matclave'		=> $matPlan_kardex['acad_mat_clave'],//clave de la materia
											'matseriada' 	=> $perfil_materia_seriada['acad_mat_clave'],//clave materia seriada
											'style'			=> array('3' => 'color: #6A6A6A', '4' => 'background: rgba(0, 0, 0, 0) url(\'/imagen/icons/block_row.png\') no-repeat scroll right top; color: #6A6A6A')//fila pintada
										);	


´´´

![testgrid](https://cloud.githubusercontent.com/assets/2206648/9179773/56666526-3f64-11e5-84e1-e816ac7a1412.png)

**Comment by vitmalina** [comment]
If there is a "style" property in a records object, and if it is a string, it will apply to whole row, if it is an object, it will apply to each cell individually:
```js
style = { 5: 'color: red; background-color: whilte' };
```

Please re-open id if does not work.
