### ISSUE TITLE
Changed cells when selectType is 'cell'

### ISSUE THREAD

**Issue by adilek** [vitmalina/w2ui#1015]
There is no little red triangle when you change the value when selectType is 'cell'

![g1](https://cloud.githubusercontent.com/assets/1143625/9156529/1bffa1bc-3ef7-11e5-8f8e-6e073d1871d9.png)

**Comment by chalchis** [comment]
what version you're using?

**Comment by adilek** [comment]
Tested on 1.4 an 1.5. Same result.

On Mon, Aug 10, 2015 at 12:53 AM, chalchis <notifications@github.com> wrote:

> what version you're using?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vitmalina/w2ui/issues/1015#issuecomment-129232372>.
>



-- 
Adil Aliyev
Mobile: +99450 244 07 07
PGP: 0x17A71712
Website: http://adil.az

*Please don`t print this e-mail unless you really need to!*

**Comment by vitmalina** [comment]
Works in my test files. See in main repositor folder test/grid2.html - on my local all is good. Can you please create a jsFiddle to illustrate the problem. It will actully be the case if after changing you will immediately merge changes by calling mergeChanges()

**Comment by vitmalina** [comment]
Since no further response, closing the issue.

**Comment by ponyEdp** [comment]
There is no little red triangle when you change the value when selectType is 'cell'.
I'm using version 1.5.rc1.
I try also in your code in your repositor folder test/grid2.html, I add the line
selectTYpe: cell
and the triangle is not show.
May you help me ?
Thanks 
Regards
