### ISSUE TITLE
w2ui sidebar, Changing style of a node

### ISSUE THREAD

**Issue by atari83** [vitmalina/w2ui#1016]
Dears,
I cannot seems to find a way to change the style of specific node in sidebar.
It's the code I've used so far:

    $('#mainSidebar').w2sidebar({
        name: 'mainSidebar',
        nodes: [ 
            { id: 'menu1', text: 'Main Menu', expanded: true, group: true,
              nodes: [ 			  		  	
			   { id: 'rptGSMMenu_Cell', text: 'Cell Level', icon: 'fa fa-bar-chart', style: 'color: red'}
              ............

Can anybody tell me what is the proper way to modify the default style of the nodes ?

Thank you,

**Comment by vitmalina** [comment]
I think that is it not working as intended and I am not sure what to do. I have this comment "*   - node.style is misleading - should be there to apply color for example" in the code. However, you can do some styles if you include it in text property of the node.

**Comment by atari83** [comment]
Thank you for response! 
Including the node styles in text property solved the issue. I'm looking forward to see that actually it is getting fixed in style property ;)

Thanks again.
