### ISSUE TITLE
Script executed twice while loading body to w2popup (new in w2ui 1.5.x)

### ISSUE THREAD

**Issue by Delgan** [vitmalina/w2ui#1017]
Hello.

I found a very annoying bug using the last nightly 1.5.x version.

When I try to open a popup, the `<script>` tag inside the `body` string is executed twice.
This is problematic, because I often use popup to load external page obtained from an ajax request.

With w2ui 1.4.2, script is executed once: http://jsfiddle.net/5jfdg9e5/
It is executed twice with the last release: http://jsfiddle.net/5jfdg9e5/1/

**Comment by vitmalina** [comment]
I think this needs to be addressed again. Please add .remove('script') again and submit a pull request. Please also do testing for you conditions.
