### ISSUE TITLE
Possible typo in  getCellHTML

### ISSUE THREAD

**Issue by rliskovenko** [vitmalina/w2ui#1023]
Looks like a typo in _getCellHTML()_:

    if (tmp[0] == 'time') {
        if (typeof tmp[1] == 'undefined' || tmp[1] == '') tmp[1] = w2utils.settings.time_format;
        data = '<div>' + prefix + w2utils.formatTime(data, tmp[1] == 'h12' ? 'hh:mi pm': 'h24:min') + suffix + '</div>';
    //                                                                                  ^^^^^^^^^^^
    }

...and when formatting is happening in _formatTime()_:

    return format.toLowerCase()
            .replace('am', type)
            .replace('pm', type)
            .replace('hhh', (hour < 10 ? '0' + hour : hour))
            .replace('hh24', (h24 < 10 ? '0' + h24 : h24))
            .replace('h24', h24)
            .replace('hh', hour)
            .replace('mm', min)
            .replace('mi', min)
    //               ^^^^^
            .replace('ss', sec)
            .replace(/(^|[^a-z$])h/g, '$1' + hour)    // only y's that are not preceeded by a letter
            .replace(/(^|[^a-z$])m/g, '$1' + min)     // only y's that are not preceeded by a letter
            .replace(/(^|[^a-z$])s/g, '$1' + sec);    // only y's that are not preceeded by a letter

...only 'mi' is replaced, leaving additional character 'n' in a cell

**Comment by vitmalina** [comment]
It appears to be in 1.4.x branch. In current master it was already fixed. I have applied the change, but there is no plans to release any new versions in 1.4.x. branch and 1.4.3 was the last one. If there will be more bugs, I might re-think it. Thanks.
