### ISSUE TITLE
Wrong style rendering in text fields

### ISSUE THREAD

**Issue by samoilis** [vitmalina/w2ui#1024]
Hi 
I have use the last version of repo (1.5.x) and noticed that the css class `w2field` is not properly applied in text fields of my forms

The same issue also exist in the demo of w2ui 1.5.x

**Comment by vitmalina** [comment]
Can you please be more specific. Please specify files in demo it is not working and provide some screenshots. Thanks.

**Comment by vitmalina** [comment]
Since no reply, closing this issue.
