### ISSUE TITLE
Search Date shows popup after pressing enter

### ISSUE THREAD

**Issue by collanders** [vitmalina/w2ui#1027]
The following steps cause the datepicker calendar to appear it the top left corner of the window.
1.  Click the "Search" button on a w2ui grid
2.  Enter a date into a date field
3.  Press Enter

The search criterion dialog disappears and the grid searches on the chosen date, but the calendar dialog remains at the top left of the window.
![image](https://cloud.githubusercontent.com/assets/12200117/9415533/9de2fb18-4805-11e5-839c-2e386dc3b3c0.png)

The user can just click somewhere in the window and the calendar disappears so it's not a major issue, but it is a bit unexpected so it confuses people a little.

Thanks for the awesome library!

**Comment by vitmalina** [comment]
Please specify the version it is happening. I have tried in the current master branch and was not able to repeat the problem.

**Comment by vitmalina** [comment]
Since no reply, closing this issue.

**Comment by sohamnavadiya** [comment]
I am also facing same issue in version 1.5.rc1

**Comment by hirenalken** [comment]
I am also facing the same issue in version 1.5.rc1. Please help.

**Comment by AliAzh1991** [comment]
Facing the same issue on the 1.5.rc1 version !
