### ISSUE TITLE
Read the column data in the grid

### ISSUE THREAD

**Issue by ueoka** [vitmalina/w2ui#1030]
It was confirmed in the latest source of GitHub.
The download source, renamed to w2ui.1.4.x.js
In Ver1.3.2, it was confirmed to operate normally, but does not work with the latest source.

Write the source code that was tested in the sample below.

<pre>
&lt;!DOCTYPE html&gt;
&lt;html&gt;
&lt;head&gt;
&lt;meta http-equiv="Content-Type" content="text/html; charset=UTF-8"&gt;
&lt;meta charset=UTF-8" /&gt;
&lt;meta name="robots" content="noindex,nofollow"&gt;
&lt;link rel="stylesheet" type="text/css" href="js/w2ui.1.4.x.css" /&gt;
 
&lt;script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"&gt;&lt;/script&gt;
&lt;!--&lt;script type="text/javascript" src="js/w2ui.1.4.x.js"&gt;&lt;/script&gt;--&gt;
&lt;script type="text/javascript" src="js/w2ui-1.3.2.js"&gt;&lt;/script&gt;
&lt;script&gt;
     
var main = {
    layout: {
        name: 'lmain',
        panels: [
            { type: 'top', content: 'top',resizable: true },
            { type: 'left',  content: 'left', resizable: true },
            { type: 'main', content: 'main', resizable: true }
        ]
    },
    grid:{
        name:'gmain',
		columns: [{}]
    }
};
 
$(function () {
    var wheight=$(window).height()-20;
    $("#layout").css("height",wheight);
    $('#layout').w2layout(main.layout);
     
    $().w2grid(main.grid);
     
    w2ui.lmain.content('main', w2ui.gmain);
     
	w2ui.gmain.load('data/demo.json'); 
	
});
 
&lt;/script&gt;
&lt;/head&gt;
&lt;body&gt;
    &lt;div id="layout"&gt;&lt;/div&gt;
&lt;/body&gt;
&lt;/html&gt;
</pre>

<h2>data/demo.json</h2>
<pre>
{
    "total": 9,
    "columns": [
         { field: "lname", caption: "Last Name", size: "30%", sortable: true },
         { field: "fname", caption: "First Name", size: "30%", sortable: true },
         { field: "email", caption: "Email", size: "40%", sortable: true },
         { field: "sdate", caption: "Start Date", size: "120px", sortable: true }
     ],
    "records": [
        { "recid": 1, "fname": "John", "lname": "Doe", "email": "jdoe@gmail.com", "sdate": "4/3/2012" },
        { "recid": 2, "fname": "Stuart", "lname": "Motzart", "email": "jdoe@gmail.com", "sdate": "4/3/2012" },
        { "recid": 3, "fname": "Jin", "lname": "Franson", "email": "jdoe@gmail.com", "sdate": "4/3/2012" },
        { "recid": 4, "fname": "Susan", "lname": "Ottie", "email": "jdoe@gmail.com", "sdate": "4/3/2012" },
        { "recid": 5, "fname": "Kelly", "lname": "Silver", "email": "jdoe@gmail.com", "sdate": "4/3/2012" },
        { "recid": 6, "fname": "Francis", "lname": "Gatos", "email": "jdoe@gmail.com", "sdate": "4/3/2012" },
        { "recid": 7, "fname": "Mark", "lname": "Welldo", "email": "jdoe@gmail.com", "sdate": "4/3/2012" },
        { "recid": 8, "fname": "Thomas", "lname": "Bahh", "email": "jdoe@gmail.com", "sdate": "4/3/2012" },
        { "recid": 9, "fname": "Sergei", "lname": "Rachmaninov", "email": "jdoe@gmail.com", "sdate": "4/3/2012" }
    ]
}
</pre>

**Comment by chalchis** [comment]
you want to read the specific column of the grid?

**Comment by ueoka** [comment]
On the server side program, such as PHP, I want to dynamically get the column to display

**Comment by vitmalina** [comment]
Grid will no longer merge anything but records that returned from the server due to XSS vulnerability considerations. However, this desired behavior is not hard to implement. You can parse this requests manually and create columns on the fly.
