### ISSUE TITLE
Checkbox on Grid with values 0/1

### ISSUE THREAD

**Issue by exemony** [vitmalina/w2ui#1038]
Hi Vit,

First of all, great job. Now the problem I have, I am currently working with a Grid and i have a checkbox and works only with true and false, and actually my DB works with "0" / "1" . Is there any chance i can change the way it works?

Hope my question is understandable. Thank you

**Comment by vitmalina** [comment]
Please do not submit questions here. Only bug reports. All questions to stackoverflow or as comments on w2ui.com
