### ISSUE TITLE
probably bug for typeof 'udefined' => 'undefined' ?

### ISSUE THREAD

**Issue by DynamicaSRL** [vitmalina/w2ui#1042]
![istantanea - 11092015 - 17 32 29](https://cloud.githubusercontent.com/assets/14236930/9818915/26477654-58ab-11e5-9152-c25baa8aec6d.png)

thanks

**Comment by vitmalina** [comment]
Well, it is not a bug. This is how you determine is variable is not set. This is the older syntax that works in old browser, such as IE5.5. I have move to a different one, but this one still works.
