### ISSUE TITLE
How to export w2 ui grid in excel format?

### ISSUE THREAD

**Issue by rajb21** [vitmalina/w2ui#1044]
I am using w2-ui grid for displaying data table.I would like to export the table in excel. I tried different jquery for exporting the data.Some works but when I open a file in excel a warning come as file format not supported.Please assist.

**Comment by vitmalina** [comment]
Please only submit bugs here.

**Comment by bwl21** [comment]
Isn't this a feature request?

**Comment by vitmalina** [comment]
grid.records - is an array of all data in the grid. To get CSV out of it, you just need to loop through it and build you CSV file. So, it is not a feature request :)

**Comment by jackryu** [comment]
- Please suggest a code if possible its helpful for me.
