### ISSUE TITLE
Bug with Subgrids version 1.4.3

### ISSUE THREAD

**Issue by deding** [vitmalina/w2ui#1045]
Hi - first of all, great library!  I've found it immensely helpful and easy to use.  Awesome job!

I wanted to submit a bug report of an issue I'm having with subgrids - the scrollbar does not automatically appear in all scenarios when expanding a sub grid.  Please visit this fiddle https://jsfiddle.net/afdo0btf/2/ to see it in action.  When you expand the second to last row - everything expands properly but some records are pushed off the screen and no scrollbar appears for the user to scroll to the hidden records.  Please let me know if you have any trouble reproducing this - thanks!

**Comment by chalchis** [comment]
I think my solution
is also to resize the main grid
to show subgrid

//resize

w2ui['gridrecursos'].resize();
w2ui['subgrid-' + event.recid].resize();

check
https://github.com/vitmalina/w2ui/issues/799

**Comment by deding** [comment]
Thanks chalchis - unfortunately this does not resolve my problem.  I've tried adding a resize of all the subgrids and the main grid in various orders and with various setTimeout values.  Nothing seems to get around this issue.  As soon as a second row is expanded - everything is fine.  But the first row to get expanded does not present the scrollbar

**Comment by chalchis** [comment]
sorry this my code in event onExpand

```javascript

 onExpand: function (event) 
	        {
	        	//var expanded = w2ui.find({ expanded: true });
				//for (var e in expanded) w2ui.collapse(expanded[e].recid);

	            if (w2ui.hasOwnProperty('subgrid-' + event.recid)) w2ui['subgrid-' + event.recid].destroy();

	            jQuery('#'+ event.box_id).css({ margin: '0px', padding: '0px', width: '100%' }).animate({ height: '400px' }, 100);

	            setTimeout(function () 
	            {
	            	jQuery('#'+ event.box_id).w2grid(
	            	{
	                    name: 'subgrid-' + event.recid, 
		                show: { columnHeaders: true },
		                fixedBody: true,
		                 columns: [                
					    	{ field: 'fname', caption: 'First Name', size: '30%' },
				            { field: 'lname', caption: 'Last Name', size: '30%' },
				            { field: 'email', caption: 'Email', size: '40%' },
				            { field: 'sdate', caption: 'Start Date', size: '120px' }
					    ],					                   
					    onLoad: function(target, eventData)
			            { 
			                var serverJSON = jQuery.parseJSON(eventData.xhr.responseText);			                           
			                
			                if (serverJSON.status_respuesta === 'false')
			                {
			                    
			                }
			                else
			                {
			                	if (serverJSON.tipo_respuesta === 'login')
			                	{			                		 
			                		 setTimeout(function(){window.location.replace('/');},1); 
			                	}
			                }
			            }
		            });

		           
					
					w2ui['subgrid-' + event.recid].resize();
					w2ui['gridrecursos'].resize();

	            }, 300);
	        },


```

**Comment by chalchis** [comment]
in your code test 
// change height: '200px'
  $('#' + event.box_id).css({ margin: '0px', padding: '0px', width: '100%' }).animate({ height: '200px' }, 100);


//comment
  /*$.each(w2ui, function (index, value) {
                if (index.indexOf("_toolbar") === -1 && index !== "grid") {
                    value.resize();
                }
            });*/

add this
            w2ui['subgrid-' + event.recid].resize();
			w2ui['importHouseholdsGrid'].resize();

**Comment by vitmalina** [comment]
I do not like current subgrids behavior. I will be refactoring it. I have also noticed that calling resize for the grid (both parent and child) is necessary, just as @chalchis pointed out.
