### ISSUE TITLE
strange ctrl key behaviour

### ISSUE THREAD

**Issue by adilek** [vitmalina/w2ui#1046]
I have a grid and selectType is 'cell'. 

When I select some cells and click Ctrl+C. When I click Ctrl immediately the page(document) scrolls to top. 

I am using version 1.4.3, jQuery version: 2.1.0. Interestingly in demos page with 1.4.3 there is no such problem.

**Comment by adilek** [comment]
In demos no such problem because no scroll for body. Actually it is also persist on demos it is just "hidden".

**Comment by adilek** [comment]
I have found the reason and the following workaround will work well. I will fix it more elegantly soon:

var sy = window.scrollY + 50;
                    $('body').append('<textarea id="_tmp_copy_data" '+
                        '   onpaste="var obj = this; setTimeout(function () { w2ui[\''+ obj.name + '\'].paste(obj.value); }, 1);" '+
                        '   onkeydown="w2ui[\''+ obj.name +'\'].keydown(event)"'+
                        '   style="position: absolute; top: '+sy+'px;  height: 1px; width: 1px">'+ text +'</textarea>');

**Comment by vitmalina** [comment]
Please submit pull request when you fix it

**Comment by adilek** [comment]
Hi, 

I am sorry. It is already solved in 1.5. My workaround can be used for 1.4.
