### ISSUE TITLE
Grid code infinite loop (was: weird onDblClick issue in 1.4)

### ISSUE THREAD

**Issue by elaw01887** [vitmalina/w2ui#1048]
Major edit: the problem here appears to be different from what I originally thought so I'm changing the title of the issue and making these edits...

Executive summary: in the version 1.4.3 grid, when certain conditions are met and refresh() is called, the code at line 4730 in refresh() calls the function scroll().  In the scroll() function at line 6176, it calls refresh() (again, only when specific conditions are met).  This creates an infinite loop.

In my case the problem manifested as the onDblClick event not firing reliably when the grid was filtered.  Here's a JSFiddle that shows the behavior: http://jsfiddle.net/elaw/my66gs6x/9/

For reasons I haven't determined, in this case it seems to depend on the "url: { save:  }" property being set for the grid... if I don't set that property the problem doesn't occur.

That seems to be because when "url: { save:  }" is set, the "records.css('overflow-y') == 'hidden'" test at line 6175 in scroll() returns true.  When "url: { save:  }" is not set, the CSS property referenced in that test is set to "auto" and the test fails, thus the infinite loop is not created.

To see the problem with the fiddle I reference above, run it, double-click any line in the grid, and an alert will pop up.  Then filter the grid so it shows a few records (enter "30" for example) and try double-clicking again and the alert doesn't display.  I think that is because the JS code is stuck in a loop and therefore not detecting the double-click properly.

Oh and just to clarify one thing, I understand the way the "save URL" is being used in the fiddle is invalid.  But on my system I've verified that when this problem occurs, the save URL is not actually being called, and whether the save URL points to a page that returns valid info or not seems to have no effect on the problem.

**Comment by elaw01887** [comment]
Some more info that hopefully is helpful...

I've been trying to figure out what's going on here and have determined the issue is not with the onDblClick event directly.

Instead, it seems to relate to the "overflow-y" CSS property being set to "hidden" on the grid records CSS when "url: { save: }" is set.

In w2ui-1.4.3.js at line 6175 in the "scroll" function there is this code:
            if (records.height() < buffered * this.recordHeight && records.css('overflow-y') == 'hidden') {
                if (this.total > 0) this.refresh();
                return;
            }

What's happening is that the "refresh" grid code, at line 4720, is calling scroll().  In scroll(), when the condition I show above at line 6175 is satisfied, scroll() calls refresh(), and creates a continuous loop.  At least in my particular circumstance, the condition is satisfied by records.css('overflow-y') equaling "hidden" when "url: { save: }" is set, whereas when when "url: { save: }" is not set, records.css('overflow-y') is "auto" and the condition on line 6175 thus is not met and scroll() does not call refresh().

**Comment by vitmalina** [comment]
Fixed in both branches. Also recompiled in 1.4.x branch. You can download form that branch /dist folder and all will be working great.

**Comment by elaw01887** [comment]
Fantastic... thanks!



    Eric



________________________________
