### ISSUE TITLE
How work without DOCTYPE tag

### ISSUE THREAD

**Issue by xijun-j** [vitmalina/w2ui#1049]
Hi

I found w2ui does not work without DOCTYPE tag.
Because svg namespace conflict in my html, I can not use <! DOCTYPE> tag,
Can you tell me how can I use w2ui without <! DOCTYPE>?

thanks

**Comment by vitmalina** [comment]
I have tested in my local and there is no problem without DOCTYPE tag. What kind of problems do you see?

**Comment by xijun-j** [comment]
Hi @vitmalina 

My environment is IE9, it does not work without DOCTYPE tag, 
but when I joined the following statement it is a good job.
```
<meta http-equiv = "X-UA-Compatible" content = "IE = edge, chrome = 1">
```
On the other way, I'm used IE11 with in IE9 compatibility mode, it can also work fine, so I think this might be my browser environmental problems, or problems IE9.

thanks

**Comment by vitmalina** [comment]
Well, since it affects only IE and there is a quick fix, I am closing this issue.
