### ISSUE TITLE
event/method to retrieve visible rows after scrolling?

### ISSUE THREAD

**Issue by alexpmorris** [vitmalina/w2ui#1050]
I'm trying to implement a sparkline into a w2ui grid column that only shows and updates for rows that are visible.  I have it working in a hacky way using the jquery.appear plugin, but it only works after the grid has been refreshed.  Is there a way I am missing to access which rows are actually being rendered to the screen.  Perhaps a more publicly facing version of: http://w2ui.com/web/docs/w2grid.scroll 

that let's us do something like  onScroll: function () { getVisibleRows(); }

**Comment by vitmalina** [comment]
Please submit only bugs here. All questions to stackoverflow.com or comments at w2ui.com.
