### ISSUE TITLE
Radio field is not working?

### ISSUE THREAD

**Issue by codymihai** [vitmalina/w2ui#1052]
Below is how the radio field comes from javascript. But when is rendered to the view is as field type text.

"type":"radio","label":null,"required":"false","options":{"items":{"id":1}},"value":1,"id":null,"version":null

<input type="text" name="type" id="type">

**Comment by vitmalina** [comment]
Please create jsFiddle to illustrate the problem.

**Comment by codymihai** [comment]
http://jsfiddle.net/dav9zrkp/1/

Above is jsFiddle.

Probably I do not do something good or I do not understand something of how I should use radio buttons.

Thanks

**Comment by vitmalina** [comment]
In version 1.4 it will not generate HTML with radio buttons, but if you create it manually it should work. In current master version, here is an example.

http://jsfiddle.net/dav9zrkp/2/
