### ISSUE TITLE
w2sidebar.expandAll method does not work properly

### ISSUE THREAD

**Issue by mpis** [vitmalina/w2ui#1056]
In the sidebar, I have several levels.
W2sidebar.collapseAll method works properly - The method will set .expanded property of all children of the node to false. It is OK.
But W2sidebar.expandAll method is not working properly, because the method w2sidebar.expandAll does not set .expanded property of all children of the node to true. That's not OK.
See the attached screenshot.

![sidebar1](https://cloud.githubusercontent.com/assets/6403556/10276696/8770eb5a-6b51-11e5-922e-365eed5894c4.png)

**Comment by vitmalina** [comment]
I have checked in current master and all seems to be fine. Here is collapseAll function

```js
        expandAll: function (parent) {
            if (parent == null) parent = this;
            if (typeof parent == 'string') parent = this.get(parent);
            if (parent.nodes == null) return false;
            for (var i = 0; i < parent.nodes.length; i++) {
                if (parent.nodes[i].expanded === false) parent.nodes[i].expanded = true;
                if (parent.nodes[i].nodes && parent.nodes[i].nodes.length > 0) this.expandAll(parent.nodes[i]);
            }
            this.refresh(parent.id);
        },
```
The problem was in 1.4.x branch. I have fixed it. Download latest from that branch in the /dist folder. I have recompiled JS.
