### ISSUE TITLE
Grid fixedRecord issue

### ISSUE THREAD

**Issue by 5pHiNxX** [vitmalina/w2ui#1058]
Hello,

i have an issue with fixedRecord: false.
As you can see it is not working for me: http://jsfiddle.net/mv7zwsgt/

When i understood right, the 'First Name' column in the first row should be multiline, but is still showing the dots...

Thanks in advance.

**Comment by 5pHiNxX** [comment]
Ok, my fault ... Just saw that the documentation was for version 1.2 and i'm using 1.4...
But it seems that the fixedRecord property was removed. Is there any possibility to get the same result as using fixedRecord?

**Comment by vitmalina** [comment]
Unfortunately fixedRecord cannot be implemented. Records must be of same height, which is needed for virtual scrolling. You still can change height of the record (see recordHeight), but it will be same for each record. Otherwise, it is really hard to implement virtual scrolling.
