### ISSUE TITLE
Unclear documentation in demo

### ISSUE THREAD

**Issue by davehayes** [vitmalina/w2ui#1060]
In the "Add/Remove" records demo, I'm not quite sure what you mean when you say:

"You can always change grid.records array and then refresh the grid by calling grid.refresh() method."

So I tried this:

```javascript
  var data = [];
  grid.w2grid({ name: foo, ..., records: data, ... });
```
  
Then I did a button event with this in it:

```javascript
  data.push({ <record> });
  w2ui['foo'].refresh();
```

but firing this event did not update the grid. I had to do this:

```javascript
  data.push({ <record> });
  var g = w2ui['foo'];
  g.clear();
  g.add(data)
  g.refresh();
```
  
Perhaps you could clarify in the Add/Remove records demo what you mean by "change grid.records array". Or am I missing something? Thanks in advance. :)

**Comment by vitmalina** [comment]
Well, a bit different. First, you create grid
```js
$().w2grid({ name: grid });
w2ui.grid.records.push({ recid: 4, ...});
w2ui.grid.refresh()
```
When grid initialized, it will redefine records array. But after that you can grab reference to this array and add/remove records and then call refresh() method.

**Comment by davehayes** [comment]
What if I am maintaining my own records array and I just want the grid to use that?

**Comment by vitmalina** [comment]
If records are not selectable, most likely they do not have unique recid
