### ISSUE TITLE
w2ui custom sort icon not displaying

### ISSUE THREAD

**Issue by alaksandarjesus** [vitmalina/w2ui#1065]
Hi,

I am trying to do a custom sort by placing onSort:function(){ ......} to a specific column only. Its sorting as expected.

But i miss the up and down arrows in the header. How could i set it up? The other columns with sort is showing up the arrows on respective sorts.

**Comment by vitmalina** [comment]
I think you need to add to grid.sortData array and then refresh. See how regular sort does it. Plus refreshing will use that array.

**Comment by alaksandarjesus** [comment]
I solved it by added CSS to w2ui header to this element.".w2ui-grid .w2ui-grid-body table .w2ui-head"
