### ISSUE TITLE
error use combo as grid cell editor

### ISSUE THREAD

**Issue by hawkxu** [vitmalina/w2ui#1067]
I use combo as grid cell editor, when I press a key (char or digit) in combo control, the error occured:
TypeError: input.val(...) is undefined
	if (input.val().length == 1) this.refresh()  (the line 14961 in w2ui.js)

I use the latest nightly build (2015-10-18)

**Comment by vitmalina** [comment]
I was getting slightly different error, but in the same place. I have fixed it. Will recompile lib later today. I hope it helps, reopen if you still have the issue.
