### ISSUE TITLE
use list and combo as grid cell editor, and text field in form

### ISSUE THREAD

**Issue by hawkxu** [vitmalina/w2ui#1068]
I use the latest nightly build (Oct 11, 2015).

1. use list as grid cell editor, the cell always shows "change indicator" after click the list control, even I select same value of the cell. in aditional, the list always select 1th item every time popup, can it select current value in cell?

2. use combo as grid cell editor, after I choose an item from combo, the cell value changed to the "text" of combo item, neither combo item nor item id.

3. It seems that a new "w2ui-input" class added to css file, but the generated html code of text field not used it, then all readonly text field display with white background color.

**Comment by vitmalina** [comment]
1. Fixed.

2. Combo box is a text box with suggestions. So, when you select an item it will get its text into the text field. Possibly I should rename it to "suggest" instead of combo or "autocomplete", which possibly will also be confusing, or something else.

3. Good catch. Fixed. Just posted

**Comment by hawkxu** [comment]
Thanks for your reply.

I have a little idea for the combo box, we can add a property to combo box, if the property set to "id", then set field value to the item selected (like list), otherwise set to text, in most cases, I need the combo box to work in "id" mode.

Just a suggestion, thanks!

**Comment by vitmalina** [comment]
Why not use list in this case? 

I assume other problems are fixed.

**Comment by hawkxu** [comment]
When the column has more than hundreds items, user may not want to select through scroll, they want to input some prefix characters to search, thanks!
