### ISSUE TITLE
Allow w2ui grid to use an external array for the records property

### ISSUE THREAD

**Issue by davehayes** [vitmalina/w2ui#1071]
Referencing #1060, but making the title more meaningful. I'd like to not have to call add() for each record (or set of records) I want to add. It would be great if I could just assign an arbitrary array to `grid.records` and call refresh() to have the grid display these records. 

The use case for this is getting data over websockets, which w2ui doesn't support. (This is most definitely not a request to support websockets!). 

As it is now, I can do something like this:

```javascript
grid.w2grid({ name: 'foo', recid: 'bar', columns: [ {...}, ...] );
var data = w2ui.foo.records;
data.push({...});
w2ui.foo.refresh();
```
However if I do this, selection breaks in the grid. Brief investigation showed this in the HTML:
```html
<tr id="grid_grid-testmodel_rec_undefined"  ...   recid="undefined">
```
I'm not entirely sure if this is a bug report or feature quest. Thanks in advance for your attention to this matter.

**Comment by hawkxu** [comment]
I make a demo for your reference, hope I understood what you meaning.
You must use recid in your data record, ingore the recid property of w2grid.

http://plnkr.co/edit/zpxYvvkR974FLpo9rkOP?p=preview

**Comment by davehayes** [comment]
Thank you for the demo and the clarification.  Your demo illustrates the problem I am talking about, if you remove adding any "recid" manually. 

I'm must admit I am confused looking at the source. The add function (line 338 of  w2ui/src/w2grid.js) doesn't appear to add this recid or do anything special. It does check for a recid as far as I can see, but that's about it.

If I am adding to an existing grid dataset, I would hesitate to add a manual recid. Still, at least now I know how to do it this way.

**Comment by hawkxu** [comment]
if you are interested in "recid", you can search "recid" in source code, you can seen that a few place used "recid", for example, delete record.

btw, I'm a user, not developer of w2ui. I also confused why the grid dependent on "recid", but all I known is that I must manually add a "recid" for every record, that's it.

**Comment by vitmalina** [comment]
Let me try to explain what recid is. Recid is a unique field that should be present for each record. Think of it as a primary key of the table in the database that you are trying to edit. See http://w2ui.com/web/docs/w2grid.records for explanation.

Internally, recid is used in many methods. For example grid.get(recid), grid.select(recid), grid.click(recid), etc. Recid is also added into generated HTML. Grid will not add any id for the record, but would use recid for identification. If you do not care about recid, just generate one based on some unique generator.

As for grid.recid, it is used to remap some other unique property. If you defined it, then when records are loaded from server it will take field you specified in grid.recid and create recid with same value. It is just for convenience.

As I mentioned before, once the grid created you can grab reference to the grid.records array and use it elsewhere, adding and removing records. 

If this explains the issue, please close the bug as I strive to keep issues resolved as they pile up.

**Comment by davehayes** [comment]
I think I understand what you wrote. :)

Do you understand what I wrote? 

This does not work:

```javascript
var foo = grid.w2grid({ name: 'foo', recid: 'bar', columns: [ {...}, ...] );
var data = [];
data.push({bar: <some value>, ..});
foo.refresh();
```
You can see the records but you cannot select them. I tried to write a jsfiddle, but you don't appear to have https: enabled for w2ui.com so I can't.

**Comment by hawkxu** [comment]
@davehayes I created a demo for your reference, please see this: http://plnkr.co/edit/FEp0IgflZp6D14hF4YE5?p=preview

**Comment by davehayes** [comment]
Thank you. I've now identified that the issue is 1.4.3. http://plnkr.co/edit/FEp0IgflZp6D14hF4YE5?p=preview
