### ISSUE TITLE
transitions are losing tabs

### ISSUE THREAD

**Issue by tristenator** [vitmalina/w2ui#1072]
hey vitman,

i'm trying to toggle between layouts in/out of a preview layout. one has tabs the other doesn't. when i make a specific transition back to a layout with tabs the tabs aren't displayed, although the original content of the layout is. if however i do not specify a transition (pop-in, flip-up, etc.) then the tabs are preserved as expected.

some detail:

the container layout is a preview panel. the two transition layouts each have a single main panel (one with tabs and the other without.) as a workaround i did try assigning the tabs to a global and re-assigning post-transition, but no luck.

also: i'm running with the latest source straight from github.

cheers and thanks again for an awesome library.

**Comment by mpf82** [comment]
Can you create a fiddle with the latest sources to demonstrate your issue?

**Comment by mpf82** [comment]
Closing issue: no response, reproducer missing
