### ISSUE TITLE
Field name of summary and value of 1 triggers summary field

### ISSUE THREAD

**Issue by deployable** [vitmalina/w2ui#1073]
The find() check that is being used for the `summary: true` check also turns a field of "1" into a summary row.  

https://github.com/vitmalina/w2ui/blob/adb278847b625d57ca96de16f829033c08265334/src/w2grid.js#L3910-L3914

Results in this check:

https://github.com/vitmalina/w2ui/blob/adb278847b625d57ca96de16f829033c08265334/src/w2grid.js#L371

That check should be `!==` in this case. `find()` seems to be used a lot of other places though. 

```
> true != 1
false
> true !== 1
true
```

From previous issues, there was mention of 1.5 moving all w2ui controlling options in data into a sub object. It was something to do with `style` I think.  I assume this summary field should be moving into that metadata object too?

**Comment by deployable** [comment]
Found it https://github.com/vitmalina/w2ui/issues/904

`record.w2ui.style` so `record.w2ui.summary` ?

**Comment by vitmalina** [comment]
I moved all I found to w2ui. Now, record can be of the following structure
```
 record: {
        field1
        ...
        fieldN
        w2ui: {
            colspan: { field: 5, ...}
            editable: true/false
            changes: {
                field: chagned_value,
                ....
            },
            children: [
                // similar to records array
                // can have sub children
            ]
            parent_recid: (internally set, id of the parent record, when children are copied to records array)
            summary: true/false
            style: 'string' - for entire row OR { field: 'string', ...} - per field
        }
```
