### ISSUE TITLE
w2layout.onShow isn't firing?

### ISSUE THREAD

**Issue by tristenator** [vitmalina/w2ui#1074]
hello vitman,

sorry to trouble you again but i don't appear to be able to get w2layout.onShow to fire with either an onShow object property or by using the after-object-creation method, as per:

http://w2ui.com/web/docs/w2layout.onShow

is something broken with it atm?

edit: some more information:

i'm showing the layout using w2layout.content after the page has been loaded, triggered by the user clicking a button.

**Comment by vitmalina** [comment]
onShow only fires if you use layout.show(...) and layout.hide(...) methods. It is not effected by layout.content(...)

**Comment by tristenator** [comment]
vman, i don't mean to be a pain, but i think the fundamental problem is there isn't a callback option for parent.content()

in essence i was just hoping to be able to keep many child layouts loaded and swap them in/out of a parent layout without having to resort to parent.load() in order to reload/repopulate the child layouts.

but i'll try and hack a workaround, so you may close this again!

**Comment by tristenator** [comment]
update: ok i worked around this by using a setTimeout immediately after calling parent.content()

**Comment by dzona** [comment]
I have content loaded with angular via async request, and I want to attach behavior to an element inside it's content. How can I know when element is created, meaning when content has been rendered inside panel?
 Thanks
````
$('#layout').w2layout({
                name: 'name',
                panels: [
                    {
                        type: 'top',
                        hidden: false,
                        resizeable: false,
                        content: $compile('<div ng-include="\'panel.html\'"></div>')($scope),
                        size: 32,
                        ...
                        }
                    },
});
````

**Comment by vitmalina** [comment]
http://w2ui.com/web/docs/w2layout.onRefresh
