### ISSUE TITLE
copy from grid with selectType=cell disorder

### ISSUE THREAD

**Issue by hawkxu** [vitmalina/w2ui#1076]
copy from grid with selectType=cell, the copied rows disorder.
note: select more than 10 rows (or across the 10th row).

please check the line in w2grid.copy method:
<code>recs.sort();</code>
I guess this code result the issue

**Comment by vitmalina** [comment]
Please create jsFiddle for it. I use this type of grid a lot and all is fine.

**Comment by hawkxu** [comment]
Please see this: http://plnkr.co/edit/wZU2pJkKAlgu9cP0rVRv?p=preview
As you can see, the rows displayed from 1 to 16.
I selected line 9 to 12 by mouse drag and pressed CTRL+C, I got data in order 11, 12, 9, 10.

BTW, if I select rows by click the "select checkbox", I can not copy anything, I pressed CTRL+C and the computer sound 'ding' without any other action.

**Comment by vitmalina** [comment]
Fixed both issues in 1.4.x branch. You can download latest that is compatible with 1.4.x from here https://github.com/vitmalina/w2ui/tree/w2ui-1.4/dist
