### ISSUE TITLE
Grid List editField Not Persisting

### ISSUE THREAD

**Issue by skiplist** [vitmalina/w2ui#1084]
According to the W2UI Grid w2grid.editField Documentation: http://w2ui.com/web/docs/w2grid.editField
The value of a grid field can be programmatically set via javascript.  The following js fiddle demonstrates that a call to editField for a grid column with type list does not persist to the grid record, even though it visually changes the appearance of the control:

http://jsfiddle.net/appliedsd/05jx9poL/6/

This functionality is required for doing selenium testing in a selenium grid where depending on the focus()  to manipulate the control in others ways is not possible.

(Sorry for hotlinking the scripts to w2ui.com from the jsfiddle, but didn't see a recent version of w2ui that supported the render from the demo code used in any js cdn).

**Comment by vitmalina** [comment]
Calling editField will start edit mode, not finish it. The same way as if user dbl clicked it. Your jsFidle seems to be working just fine. If you want to change record, you merely need to change proper data in grid.records array. Do this.

1. Open grid and change first record manually.
2. Go to console and do w2ui.grid_name.records[0] - see what was changed
3. In your function apply the same change directly to the reocrds array and the do grid.refresh()
4. Call grid.save()

you will have similar results.
