### ISSUE TITLE
Grid onDeleted Not Being Called

### ISSUE THREAD

**Issue by skiplist** [vitmalina/w2ui#1085]
onDeleted is not being called for a w2ui grid.  jsfiddle is here:

http://jsfiddle.net/appliedsd/cwvv2p7u/3/

**Comment by skiplist** [comment]
I see in the changelog that this was removed in version 1.5, but the docs are still online.

**Comment by vitmalina** [comment]
Yes, it was removed. However, http://w2ui.com/web/docs/w2grid.onDeleted says that it is called when server responds back after records where deleted. In your jsFiddle it is local data, not remove. In this case you can just use onComplete loop of the event. 

With server side, it will work. Just checked.
