### ISSUE TITLE
Form in the popup

### ISSUE THREAD

**Issue by devidao** [vitmalina/w2ui#1092]
i have below code, but form actions is not executed, whats can be wrong?

	jQuery('#bLogin').click(function(){
		 jQuery('#login').w2popup();
	});
	jQuery('#form').w2form({
		name     : 'form',
		url      : 'server/post',

		fields: [
			{ name: 'loginUsername', type: 'text', required: true },
			{ name: 'loginPassword', type: 'password', required: true }
		],
		actions: {
			reset: function () {
				this.clear();
			},
			save: function () {
				var obj = this;
				this.save({}, function (data) {
					if (data.status == 'error') {
						console.log('ERROR: '+ data.message);
						return;
					}
					obj.clear();
				});
			}
		}
	});

**Comment by vitmalina** [comment]
I tried this core, it works for me just fine. Please create jsFiddle to illustrate the problem.

**Comment by vitmalina** [comment]
Since no response, assuming all is find.
