### ISSUE TITLE
conflict with w2ui 1.4.3.css and bootstrap css with respect to .btn class

### ISSUE THREAD

**Issue by reddypulyala** [vitmalina/w2ui#1093]
Hi,

I upgraded the w2ui 1.3.2 to the version w2ui 1.4.3. I am using bootstrap css and w2ui 1.4.3 in my application. With the upgraded version I'm facing a conflict with button.btn class in w2Ui1.4.3.css with .btn class in bootstrap css. button.btn class in w2ui is overriding the .btn class in bootstrap. I want to use use bootstrap css for that particular part of the application . I would really appreciate if i can get some suggestions on how to resolve the conflict.

Thanks
Abhinav

**Comment by vitmalina** [comment]
I do not have good suggestion to you. In current master version I have prefixes .btn with w2ui-btn so it would not conflict. There will be no more updates in 1.4.x branch. You can rename it manually in your version.

**Comment by vitmalina** [comment]
I prefixed in 1.4.x branch buttons with w2ui- You can download latest that is compatible with 1.4.x from here https://github.com/vitmalina/w2ui/tree/w2ui-1.4/dist

**Comment by ZuchaoWang** [comment]
the compiled w2ui.js file seems to be incomplete

**Comment by vitmalina** [comment]
Details, please.

**Comment by ZuchaoWang** [comment]
The last few lines in https://github.com/vitmalina/w2ui/blob/w2ui-1.4/dist/w2ui.js are:

    // ====================================================
        // -- Registers as a jQuery plugin
    
        $.fn.w2field = function (method, options) {
            // call direct
            if (this.length == 0) {
                var pr = w2field.prototype;
                if (pr[method]) {
                    return pr[method].apply(pr, Array.prototype.slice.call(arguments, 1));
                }
            } else {
                // if without

The definition of $.fn.w2field is incomplete.

**Comment by ZuchaoWang** [comment]
Pretty strange, it looks complete here:

https://raw.githubusercontent.com/vitmalina/w2ui/39cead9c7de8a64a8cf04a5bf79da830e10867bf/dist/w2ui.js

**Comment by AlissonRS** [comment]
The `w2ui-1.4.3.css` doesn't contain the prefix, it's straign a `button.btn`, thus overriding bootstrap styles. I downloaded the `w2ui.css` and `w2ui.js` instead of `w2ui-1.4.3.css` and `w2ui-1.4.3.js` and it's ok now. Thanks!!!
