### ISSUE TITLE
Grid auto formats all editable cell numbers (even unix timestamps) 

### ISSUE THREAD

**Issue by dejang** [vitmalina/w2ui#1097]
w2grid will format all number values if the cell is editable. Sometimes this is desirable but sometimes it is not. If the number is actually a timestamp it will format it even if you have the type of the cell set as "text".

To reproduce the issue try setting the type to text to all cells and then load a json which contains timestamps. Timestamps must be of data type number, and not string. 
{"cell1": 1447308150862, "cell2": "1447308150862"}

Cell must be editable. Double click on "cell1" value to edit, it will format the value using decimal separators. Click away to cancel edit and the cell value changes to the formatted value.

**Comment by dejang** [comment]
Created pull request https://github.com/vitmalina/w2ui/pull/1098 with the fix.

**Comment by vitmalina** [comment]
I merged the pull request, I assume it fixes the problem.
