### ISSUE TITLE
Grid. onSave check error

### ISSUE THREAD

**Issue by munfor** [vitmalina/w2ui#1099]
I don't know if it is an issue or I don't understand how it works.

After sending Grid changes to the server, I would like reload the Grid only if the data was correctly store into database.

When a error occurs, the server sends this Json:

```javascript
{
    "status":"error",
    "message":"Ups! Error occurred"}
}
```

Then to reload the Grid only if was success, I tried:

```javascript
 onSave: function (event) {       // onSave Grid event
      event.onComplete = function () {
            if(event.status =='success'){
                  this.reload();           // Only reloads if data was stored on database
            }
      }
}
```
But event.status is always 'success'. How could I check if the Grid.save() operation was incorrect to avoid Grid reloading?

Thank you.

**Comment by vitmalina** [comment]
Event object is not what server returns. It is object that has related to this event useful information. Look into this object and you will find how to solve you problem. Event.status indicates if ajax request was successful. See event.xhr.responseText for text that your server returned.
