### ISSUE TITLE
click event when delete file from the fields

### ISSUE THREAD

**Issue by wondertalik** [vitmalina/w2ui#1102]
example, w2ui 1.4.3
https://jsfiddle.net/hewranp9/

i deleted one file from the fields and saw two event: click and remove. is it ok or bug?

**Comment by plotnikov-yn** [comment]
up

**Comment by plotnikov-yn** [comment]
up

**Comment by mpf82** [comment]
**This is not a bug.**

if you look at the code, you will see that the click event handler for "enum" and "file" fields does emit both events ("click" followed by "remove"):

            if (['enum', 'file'].indexOf(this.type) != -1) {
                    ...
                    .on('click', function (event) {
                        var target = (event.target.tagName.toUpperCase() == 'LI' ? event.target : $(event.target).parents('LI'));
                        var item   = selected[$(target).attr('index')];
                        if ($(target).hasClass('nomouse')) return;
                        event.stopPropagation();
                        // trigger event
                        var edata = obj.trigger({ phase: 'before', type: 'click', target: obj.el, originalEvent: event.originalEvent, item: item });
                        if (edata.isCancelled === true) return;
                        // default behavior
                        if ($(event.target).hasClass('w2ui-list-remove')) {
                            if ($(obj.el).attr('readonly') || $(obj.el).attr('disabled')) return;
                            // trigger event
                            var edata = obj.trigger({ phase: 'before', type: 'remove', target: obj.el, originalEvent: event.originalEvent, item: item });

**Comment by mrg2001** [comment]
I agree that looks like it is how code is written, but should it send click and remove events. I think it would be more logical to do what issues suggests. I am going to implement it.
