### ISSUE TITLE
Refresh/reload single field of a form

### ISSUE THREAD

**Issue by agphoto** [vitmalina/w2ui#1103]
Hi,
I have  dropdown list that get data from db.
If I change data on db, the dropdown still show old values. 
I would like to do a punctual refresh of the only dropdown field.
Thank you for help.

**Comment by vitmalina** [comment]
it will cache pulled values from the server, you can clear cache on each focus with
```js
$('#field_id')
	.on('focus', function () {
		var fld = $(this).data('w2field');
		if (fld) {
			fld.clearCache();
			fld.request();
		}
	});
```
If you use a form, you can add this in onRefresh event. Also, I think it is only implemented in current master (not 1.4.x, if I am not mistaken)
