### ISSUE TITLE
file upload Error

### ISSUE THREAD

**Issue by birkaf** [vitmalina/w2ui#1107]
Hello,
I use 1.5.x build W2ui.
You can see this error in your test folder file is form.html,
If I try to send "save" request I take error
![err](https://cloud.githubusercontent.com/assets/1826792/11213542/8cbd3ec4-8d4d-11e5-9e23-58f79b9b5e18.jpg)
if i use 1.4.3 library then send POST request

**Comment by birkaf** [comment]
I found an error occurs on the following line:
ajaxOptions.data = String($.param(ajaxOptions.data, false)).replace(/%5B/g, '[').replace(/%5D/g, ']');
The $.param function causes an error

**Comment by vitmalina** [comment]
Good catch. Yes, indeed there was a problem in both Chrome and FF. The reason is because there was a File object in the data. I have removed it before post. Now it works well.
