### ISSUE TITLE
w2ui availability via npm

### ISSUE THREAD

**Issue by kyr0** [vitmalina/w2ui#1109]
Hey :)

...thanks for the great w2ui library!

Could you please do a "npm publish" to publish the library on npm next to bower?
This would be amazing!

The following GIST will make that a no-brainer for you:

    https://gist.github.com/coolaj86/1318304

btw. Just call "npm publish" every once in a while when you want to release a new version. It's pretty easy :)

Thanks and regards,
Aron

**Comment by vitmalina** [comment]
I published 1.4.3 version and pushed 1.5.0 version before that. Though, it is not yet finished and I learned that you cannot reuse version name. So, I will publish when 1.5 becomes stable.

**Comment by LilMinmax** [comment]
@vitmalina just a heads up, uou can publish i.e. 1.5-rc1 and then switch to 1.5.0 when 1.5 is released
