### ISSUE TITLE
[grid] Remote data cannot selectNone

### ISSUE THREAD

**Issue by duccanh0022** [vitmalina/w2ui#1113]
Hi, the first thanks to this plugin :dancer: 
I have a problem, when i use grid with remote data. And I cannot use selectNone function.
Plz help me, thanks u.

![untitled](https://cloud.githubusercontent.com/assets/4942484/11554530/750c29fe-99cb-11e5-971f-773ccf414d42.png)

**Comment by vitmalina** [comment]
does it work from JS console? If you do
```
w2ui.grid.selectNone()
```

**Comment by duccanh0022** [comment]
Hi, this is my JS console
![image](https://cloud.githubusercontent.com/assets/4942484/11649798/67e4d878-9db5-11e5-859c-8c2406ed3246.png)

**Comment by duccanh0022** [comment]
The problem resolved. Thanks= you!
