### ISSUE TITLE
v1.4.3 - Drop List is skipped in the form when press the Tab key

### ISSUE THREAD

**Issue by siuhang** [vitmalina/w2ui#1115]
I have a simple form with 2 textboxs and a drop list.The order like belows:
1.Textbox1
2.DropList
3.Textbox2

When I finish input data in textbox1, then press Tab key, the foucs will jump to textbox2 and skip droplist. I tested v1.4.2 is fine but not work in v1.4.3

**Comment by vitmalina** [comment]
Fixed. I recompiled 1.4.x branch. You can download from dist folder there.
