### ISSUE TITLE
$ not defined

### ISSUE THREAD

**Issue by FelisPhasma** [vitmalina/w2ui#1116]
Hello,
I'm trying to use w2ui in one of my projects. I have included jQuery, and w2ui after that, but I get a reference error. Here is the include code:
```
<script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="lib/w2ui.js"></script>
```
There should be a pretty simple fix, but I've been unable to find one.

**Comment by vitmalina** [comment]
What is exact error?

**Comment by FelisPhasma** [comment]
`w2ui.js:1022`     `Uncaught ReferenceError: $ is not defined`

**Comment by vitmalina** [comment]
Your problem is that jQuery is not properly included. It is impossible for me to guess what is wrong. Please create jsFiddle to demonstrate the problem. Otherwise, I am unable to help you.
