### ISSUE TITLE
Date/time issues

### ISSUE THREAD

**Issue by robjens** [vitmalina/w2ui#1121]
Ok I'm left wondering this last bit, trying to decipher various demos, source code, documentation pieces on how to work non-analog/USA date notation.

I've found the following to be working sufficiently (grid columns)

```javascript
type: 'date', editable: {type: 'date', format: 'dd-mm-yyyy'}
```

As a render function, I use moment to parse the date (wrapped in a convenience column build function since I'll be damned to type it everywhere each date) so it shows 'Wed 31 December 2015` (localized) when in view, and shows `dd-mm-yyyy` in the calendar picker. So far so good.

But inline edit, when I exit the mode, won't update automagically. I've searched for something which enabled it, but seems to do it out of the box for USA silly mm-dd-yyyy malformation and won't for the better dd-mm-yyyy notation. ISO8610 would of course be the right way to deal with dates. But that is besides the point I guess. When I put a handler on the `onChange` event, the changed array is empty. When I close the field, that event triggers. But when I save (or reload) it suddenly shows the correct value

What am I missing here?

**Comment by robjens** [comment]
Ok its not only date/time, list type columns etc all don't show the value which was just changed.

**Comment by vitmalina** [comment]
You can set date format globally in w2utils.settings.date_format in of 1.4.x (in current master it is w2utils.settings.dateFormat), see http://w2ui.com/web/docs/w2utils.settings. Also, you can either use render function for the column (where you can use moments or any other formating lib) or define render: 'date' to format it as default date.

As for error with editable field, please send me a link where you see it.

**Comment by vitmalina** [comment]
I assume it all works. Closing the issue.
