### ISSUE TITLE
How an I change the background color of the current active tab

### ISSUE THREAD

**Issue by bwl21** [vitmalina/w2ui#1122]
It is difficult to recognize which tab is currently active. I would like to change the background color of the active tab. How can I do this?

**Comment by Altair68** [comment]
I didn't try it myself, but i guess you could just change the background color in the css file:
```
.w2ui-form .w2ui-tabs .w2ui-tab.active {
  background-color: #ffffff;
}
```

Just change it to whatever color fits your scheme.

cheers

**Comment by vitmalina** [comment]
@Altair68 - yes, exactly as I would do too. Also, as of 1.5, you can set style of the tab when defining it. This way you can define any tab to have any custom bg without adding it in CSS. If you set it this way, do not forget to call .refresh()

**Comment by bwl21** [comment]
aweseome. Thanks a lot.
