### ISSUE TITLE
Still not friendly with jQuery non-conflict mode

### ISSUE THREAD

**Issue by LiteratimBi** [vitmalina/w2ui#1125]
hi, @vitmalina 
When I use jQuery in non-conflict mode with 'jQuery' alias in simple layout example uncaught error occurs: Cannot read property 'extend' of undefined of w2utils.event.trigger

(function ($) {...})(jQuery); workaround seems to be working in this case.

Ps: Linked to issues #978 && #175.

**Comment by vitmalina** [comment]
Are you sure you use it in current master branch and not in 1.4.x

**Comment by vitmalina** [comment]
You are right, where we other places. All should be fixed now.
