### ISSUE TITLE
In W2ui Grid Infinite scroll doesnt work

### ISSUE THREAD

**Issue by ram08ece** [vitmalina/w2ui#1126]
Dear Vit, In w2ui grid while access the records from a database, for example I m having around 50k to 80k records. While i tried to access this through the w2ui grid, the records doesn't load. But if i used for low records, it works well.. Help this problem Vit

**Comment by chalchis** [comment]
show something or screenshot

**Comment by vitmalina** [comment]
here is an example of infinite scroll http://w2ui.com/web/demos/#!combo/combo-9

**Comment by vitmalina** [comment]
I assume it works...
