### ISSUE TITLE
Dropdown in form doesn't auto-set when using URL?

### ISSUE THREAD

**Issue by elaw01887** [vitmalina/w2ui#1127]
[Attach.txt](https://github.com/vitmalina/w2ui/files/64255/Attach.txt)
I have a dropdown in a form, and am programatically setting data to the form by setting the 'w2ui.formName.record' property.

Edit: I tried pasting code here but it got mangled so code is in attached file.

When I use the code as shown above and the form record's VEND_ID property is set to '01289', when the form is first shown the dropdown displays "Third vendor" as expected.

When I change to feeding the dropdown from a URL by uncommenting the first VEND_ID field above and commenting out the second, it doesn't work... when the form is shown the URL is never called and the dropdown is empty.  Manually typing the first part of the vendor name in the dropdown results in a call to the URL and the vendor being shown in the dropdown.

Is this expected behavior?

**Comment by vitmalina** [comment]
There are two suggestions I can offer. (1) set minLength to 0 for the field, then it will call url to fill out drop down immediately after init.
```
{ field: 'VEND_ID', type: 'list', required: true, options: { openOnFocus: true, url: 'ghVendors.aspx', minLength: 0, placeholder: 'Select...' } },
```
However, if you services returns large data set, it might not be int he first page (page size is 250) and then it will not find the item.

(2) set selected item int the record array with id and text, then your record for the form will have

```js
record: {
VEND_ID: { id: your-id, text: 'text you want to display' }
...
}
```

This can be loaded from the server this way.

This should help. Close this issue if all good.

**Comment by elaw01887** [comment]
Thanks for the response!

I tried the minLength idea but it doesn't seem to work.  It may be because my page is pretty complex... the dropdown is in a form which is rendered to the main panel of a layout control which is in a popup.  The popup is triggered by double-clicking an item in a grid... when that is done I load data from the server, set it to the record property of the form, call refresh() on the form, then open the popup.  During all that, the URL for the list never gets called... that doesn't happen until you set focus to the list and type something.  But even then, the time to render the list is quite long - about 4 seconds for ~650 items.  So I don't think that technique is usable.

I'll try your second suggestion and report back.

**Comment by mpf82** [comment]
@elaw01887 any news? Do you still have an issue with this?

If you do, could you please create a jsfiddle with the latest sources, that demeonstrates your problem?

**Comment by mpf82** [comment]
Closing issue: no response
