### ISSUE TITLE
w2grid simple search operator for text columns

### ISSUE THREAD

**Issue by yaegashi** [vitmalina/w2ui#1128]
In the latest w2ui (1.5.x), w2grid simple search always performs text column searches with 'begins' operator, which is not useful in most cases.  I think 'contains' would be more preferred for text columns.    You can test the behavior in http://jsfiddle.net/rwvjksmx/ (using http://w2ui.com/src/w2ui.min.{css,js}).

It would be very nice if we could specify the simple search operator for each column.

**Comment by vitmalina** [comment]
I am not completely agree that 'contains' better as default. However, I agree that it would be nice to be able to set default. There was already a way to define a default operator, but it was not applying it in simple search. I have extended it to simple search. In fact there are 4 more properties you can set for search (as part of 1.5.x), which are 
```
search.simple - t/f - display or not in simple search drop down
search.hidden - t/f - if search is a hidden search, user cannot change it by it will be sent to the server
search.value - value for the search used in hidden search
search.operator - default operator one of ['is', 'begins', 'contains', 'ends', 'between', 'less', 'more', 'in', 'not in', 'null', 'not null']
```
So, when you define search, you can do
```
searches: [
   { field: 'name', caption: 'Name', operator: 'contains' }
   ...
]

**Comment by yaegashi** [comment]
Great, that's the perfect solution.  Thank you so much! :+1:

**Comment by Adatoza** [comment]
I didn't see "operator" property in search documentation

**Comment by mpf82** [comment]
@Adatoza http://w2ui.com/web/docs/1.5/w2grid.search

>  The search object has the following structure: 

````
search = {
    field    : '',   // search field name
    value    : '',   // field value (array of two values for operators: between, in)
    type     : '',   // type of the field, if not defined search.type for the field will be used
    operator : ''    // search operator, can be 'is', 'between', 'begins with', 'contains', 'ends with'
                     // if not defined it will be selected based on the type
}
````
