### ISSUE TITLE
w2ui date control

### ISSUE THREAD

**Issue by nagasr** [vitmalina/w2ui#1129]
i am using w2ui date control and i need to know how to set the current date to the control with the format 
'dd-mmm-yyyy'

**Comment by vitmalina** [comment]
what is "mmm"? If you want name of the month in text, you should do
```
dd-Mon-yyyy - 3 letters month with first cap
dd-Month-yyyy - full month with first cap
```

**Comment by vitmalina** [comment]
I hope it helped
