### ISSUE TITLE
Editing in the grid

### ISSUE THREAD

**Issue by dariuspranskus** [vitmalina/w2ui#1130]
Hi

I am trying to use the grid in the remote data mode. What I want to achieve is when the user enters edit mode, he may freely edit any field in a row, but when he exists the row, the update is fired to the server. I tried multiple events - onChange, onSelect, but they are firing every time user changes a field and exits it. So it means, that to edit multiple fields in a row it will fire multiple times.

Is there a way to catch, when the user exits a row, check for the changes and then fire the update?

Thanks
Regards
Darius

**Comment by vitmalina** [comment]
Possibly, here is what I think you should do in onEditField handler remember the row user started editing. It should pass needed info in the event object that it sends. If user entered edit mode of another record trigger save. You should be able to get all changes with getChanges() method

I hope it helps. Please note, that issues on github for bugs only, not questions. All questions to stackoverflow.com or w2ui.com comments.
