### ISSUE TITLE
fast scrolling in Buffered Scroll example empty set

### ISSUE THREAD

**Issue by Wyzix33** [vitmalina/w2ui#1131]
Hi, i just started using w2ui and as some of my friends tested it they noticed that if they scroll fast down and while loading scroll up the rows are not showing, to be able to see them you have to scroll down and then slowly  up...
the json is random generated with php, and everything works as long as i slowly scroll, if i scroll fast up while data is generated, everything is gone, white background where rows should be ..., and as i said, if i slowly go down to load more data and then back up i can see the rows.

if i only move the scroll slowly this doesn't happen .
any suggestion?

i got the demo source from 

http://test.localhost/w2ui-master/demos/#!combo/combo-4

and i have this configuration 
[code]
     var config = {
    grid: { 
        name: 'grid',
        url : 'fake-json.php',
        show: { 
            footer    : true,
            toolbar    : true
        },
        columns: [  
            { field: 'id', caption: 'ID', size: '50px', sortable: true, resizable: true },
            { field: 'title', caption: 'First Name', size: '140px', sortable: true, searchable: 'text', resizable: true },
            { field: 'desc', caption: 'Last Name', size: '140px', sortable: true, searchable: 'text', resizable: true },
        ]
    }
}

function refreshGrid(auto) {
    w2ui.grid.autoLoad = auto;
    w2ui.grid.skip(0);  
}

$(function () {
    $('#main').w2grid(config.grid);
});
[/code]
Here is a screenshot, maybe you can understand :) 
![w2ui](https://cloud.githubusercontent.com/assets/13553412/11998203/d0e88092-aa9c-11e5-9251-1e52b84b654e.jpg)

PS same happens on your demo page

http://w2ui.com/web/demos/#!combo/combo-9

if you scroll up fast while data is loading the rows are gone . . not all, but from a point up, see screens
![w2ui1](https://cloud.githubusercontent.com/assets/13553412/11998245/a32163de-aa9e-11e5-917c-f905475f471b.jpg)
![w2ui2](https://cloud.githubusercontent.com/assets/13553412/11998246/a63db96e-aa9e-11e5-93b8-404b64c2acf3.jpg)

**Comment by vitmalina** [comment]
I have just tried in FF and Chrome on OS X and it seems to be fine. I was not able to reproduce regardless how fast I was scrolling. I have tried on current master version.

Please specify what browser you try, OS, and version of w2ui. Thank you.

**Comment by Wyzix33** [comment]
Windows 8.1 Pro
Google chrome Version 47.0.2526.106 m
Firefox 38.0.5
IE 11
All have this behavior, there is a catch, you have to scroll up while new content is loading :) i will try to record my desktop so you can see, here are some screens with IE and chrome too, i am using your demo page located at 
http://w2ui.com/web/demos/#!combo/combo-9
so i guess the latest version of w2ui
![w2ui4](https://cloud.githubusercontent.com/assets/13553412/12002850/39a349ac-ab13-11e5-8f2b-b91c33dc6d50.jpg)
![w2ui3](https://cloud.githubusercontent.com/assets/13553412/12002851/39a5db2c-ab13-11e5-8289-ed4e6a20ccc5.jpg)

on chrome was a little bit harder to reproduce because the scroll was jumping while loading, but the behavior is there, so don't just scroll up and down, keep the scroll down and while it loads move it fast up .. will be back with a recording ASAP

**Comment by Wyzix33** [comment]
OK, i managed to make a video :) i have reproduced this on all 3 browsers i have and i hope you can understand what is going on there... when this bug happens the only way to get rid of it is to refresh or to slowly scroll to bottom and back up

https://youtu.be/qO-nm9VUXYQ

**Comment by Wyzix33** [comment]
Let me know if you need anything else, I'll be on for the next 4 hours.
Thanks

**Comment by Wyzix33** [comment]
It seems that if the table is more complex and the loading is taking more time to finish this is happening more and more...  the only way to get rid of it after it happens is to refresh CTRL + F5, normal refresh leaves chunks of blank space at the top of the table...
I will wait for a reply before adding this to production
Thanks

**Comment by Wyzix33** [comment]
Hi, any updates for this bug?

**Comment by chalchis** [comment]
you need to do on a json file?
or you will use SQL queries ¿?

**Comment by Wyzix33** [comment]
SQL, but i don't think it's relevant, since the loading will be from the server...., i imagine that the bug is because of a timing issue, while an Ajax request is in progress, if you move the scroll, the script triggers another request and the first one is aborted, and maybe there is the error.

**Comment by vitmalina** [comment]
Just a quick update, I tried on windows 10 and I am having hard time replicating the issue. It works for me. I will try to emulate a slow server side response to see what happens.

**Comment by Wyzix33** [comment]
Hi, glad you are still looking into this, for me the OS doesn't make any difference, i tried 3 flavors of linux and windows xp to 8.1, the problem persists, and it seems to happen more often if the table is more complex and the view port is bigger, we don't have a windows 10 PC yet, some drivers issues...
Seems like this bug is directly related with loading time, at least in my tests...

**Comment by mrg2001** [comment]
Did you try with 1.5.x version, that is a current master?

**Comment by Wyzix33** [comment]
One year later and still the bug remains, i tested in latest versions of Chrome, FF and IE.  I made a small video, maybe someone can reproduce and fix...

[Video proof](https://youtu.be/t1Cv1YoPBLI)

Thanks

**Comment by Wyzix33** [comment]
I moved to another scrolling library since this bug was happening too often and data was too important not to be observed when this happened.
