### ISSUE TITLE
[REQ] Divider to ContextMenu

### ISSUE THREAD

**Issue by Mouse** [vitmalina/w2ui#1137]
Vitmalina, 
thank you very much for the great work you do!
I would like to ask you a favor. You will do to the grid (Context Menu [right click]) divider?
I would be very happy.
Thank you in advance.

**Comment by vitmalina** [comment]
Context menu already supports dividers. If you would like to add a divider, you just need to make text: "--"
```
{ 
... 
items: [
   { id: 1, text: 'item 1'}, 
   { text: '--' }, 
   { id: 2, text: 'item 2' }] 
   ...
}
```

**Comment by Mouse** [comment]
Oh, really cool. Thank you. I can somehow create a further submenu in the menu?

**Comment by vitmalina** [comment]
no submenues
