### ISSUE TITLE
Combobox first option autoselection and search error

### ISSUE THREAD

**Issue by geods3** [vitmalina/w2ui#1138]
I have a problem with combo.

When the combo get data (from local or remote data) after search it is not auto pre-select the first line but i have to hit down button to select it. 

And the other problem is that when i have 2 or more cases on the backend select while i am searching if the first case is not muching then even if i keep typing, combo stops searching and making request to data file so i can't catch the other cases on my search. 

This problem i solved that by adding in the code at line 15520 the case { || (search.length > obj.tmp.xhr_search.length)   } as you see in the attached image

![image](https://cloud.githubusercontent.com/assets/6419327/12233132/2baa9e74-b86d-11e5-9a9e-d1b52acb2d74.png)

i don't know if this is the correct method or is another method that works better

**Comment by vitmalina** [comment]
Combo (as well as list and enum) work in the following way with the data retrieved from server:

1. When user types a character, it will wait for 300ms to see if user types another one, etc. And if not then will fire a request with 2 variables: search and max
2. If server returns less than max, then combo assumes that all data with this filter is returned to the client and will not submit any requests again, but filter on the client, except if user removes a character.
3. For combo you do not need to select any item from the drop down, they are just suggestions, you can type any text, for list and enum - you must select an item from drop down (or type exactly the same and then it will auto select), or it will clear input on blur.

I am not sure what is better to preselect an item in the drop down or allow user to hit down key and select on his own. I am still looking into what would be best user experience in this case.

Also, you can set how many max items you want to cache from the server and if you set to 0, then it will make request on each typed character. Also, changing minLength to 0 will allow you to trigger call to the server before user types any data, but when controls initializes

Besides that, I do not see where is bug here and hence I am closing the issue. If you decide to reopen, please provide details with bug description.

**Comment by geods3** [comment]
Hello again,

first of all thanks for your quick answer,

1. I tried to set max to 0 but even if it makes all the time request when i am typing,  that option doesn't return any result to combo...

2. Can you set a variable like cacheMax so if set to true it selects first line and if you set to false to not select anything?
