### ISSUE TITLE
Grid "ajax error" when start a reload while previous reload is not finished

### ISSUE THREAD

**Issue by aetna-softwares** [vitmalina/w2ui#1140]
Hi,

I have a grid with a AJAX url as data source and I experienced this behaviour : 
 - some user action triggers a reload of the table
 - the reload takes some times for some reason (slow network, heavy query, ...)
 - the user triggers a second reload before the first reload completed
 - the first AJAX request is "cancelled" and a popup "ajax error" is displayed to the user (I guess that the first reload call is cancelled because of the second one)
 - the second reload finished correclty but user still got the error message and think something went wrong.

I think that the error should not been displayed in this case as W2UI itself is the origin of the request cancellation (well I guess so...).

I am using version 1.4.1. I don't know if this behaviour changed in version 1.5

**Comment by vitmalina** [comment]
First of all, it is safe for you to upgrade to 1.4.3 as it is fully compatible with 1.4.x branch. Second, all requests are happening with jQuery.ajax and if request is cancelled, it will not trigger it as an error, if, of course, you do not define an error handler. See jQuery.ajaxSetup for more details.

If this still does not solve your problem. Please create a jsFiddle page where you can illustrate the problem. I do use this technique frequently and it is working just fine for me.

**Comment by aetna-softwares** [comment]
Thank for you feedback.

Is it possible to do this elsewhere than in global ajaxSetup ? because I also have other jquery ajax usage in the application that I don't want to affect

**Comment by vitmalina** [comment]
Please refer to jQuery docs. Thanks.
