### ISSUE TITLE
ASP CONTROLS IN POPUP WINDOWS CAN'T USE IN THE CODE BEHIND

### ISSUE THREAD

**Issue by nagasr** [vitmalina/w2ui#1142]
hi..,
i use the following code to use popup in my asp.net application i unable to access the textbox control from codebehind it shows only null value.
 <div id="popup7" class="addPopup">
                                                        <div rel="title">
                                                            <span id="Span7" class="alertheader">Credit Card Info</span>
                                                        </div>
                                                        <div rel="body">
                                                            <table class="PageInnerTable">
                                                                <tr>
                                                                    <td colspan="4">
                                                                        <div id="toolbar7" class="Popuptool">
                                                                        </div>
                                                                    </td>
                                                                </tr>
                                                                <tr>
                                                                    <td class="tdclass">
                                                                        Credit Card#:
                                                                    </td>
                                                                    <td class="tdclass">
                                                                        <asp:TextBox ID="txtAppcntCCNo" runat="server" placeholder="Enter Credit Card No"
                                                                            MaxLength="16" TabIndex="110">
                                                                        </asp:TextBox>
                                                                    </td>
                                                                    <td class="tdclass">
                                                                        Issuing Bank :
                                                                    </td>
                                                                    <td class="tdclass">
                                                                        <asp:TextBox ID="txtAppcntCCIssueBank" runat="server" placeholder="Enter Issuing Bank"
                                                                            MaxLength="30" Width="200px" TabIndex="111" onKeyPress="javascript:makeUpperCase(this.event)">
                                                                        </asp:TextBox>
                                                                    </td>
                                                                </tr>
                                                                <tr>
                                                                    <td class="tdclass">
                                                                        Credit Holder Since:
                                                                    </td>
                                                                    <td class="tdclass">
                                                                        <asp:TextBox ID="txtAppcntCCHolderSince" datetxt="date" runat="server" placeholder="Card Holder Since"
                                                                            TabIndex="112" onblur="return doDateValidation(this)" />
                                                                    </td>
                                                                    <td class="tdclass">
                                                                        Card Type:
                                                                    </td>
                                                                    <td class="tdclass">
                                                                        <asp:DropDownList ID="ddlAppcntCCType" runat="server" Width="200px" TabIndex="113" CssClass="ddl"
                                                                            DataSourceID="XDSCardType" DataTextField="name" DataValueField="name">
                                                                        </asp:DropDownList>
                                                                        <asp:XmlDataSource ID="XDSCardType" runat="server" DataFile="~/App_Data/CardType.xml">
                                                                        </asp:XmlDataSource>
                                                                    </td>
                                                                </tr>
                                                                <tr>
                                                                    <td style="text-align: center" colspan="4">
                                                                        <asp:Button ID="btnAppcntCCAdd" runat="server" class="buttonbg" Height="22px" Text="Add"
                                                                            Width="55px" TabIndex="114" OnClick="btnAppcntCCAdd_Click"  />
                                                                        <asp:Button ID="btnAppcntCCClr" runat="server" CausesValidation="False" class="buttonbg"
                                                                            Height="22px" Text="Cancel" Width="55px" TabIndex="115" UseSubmitBehavior="False"
                                                                            OnClick="btnAppcntCCClr_Click" />
                                                                    </td>
                                                                </tr>
                                                            </table>
                                                        </div>
                                                    </div>

in vb.net page
a=txtAppcntCCNo.Text.Trim
here a shows nothing.
but in page shows value.

**Comment by vitmalina** [comment]
Description of your issue is unreadable. If you do not want to invest a bit of time to explain your point, why should anyone look into it.
