### ISSUE TITLE
The custom field type is missing the "Change" event

### ISSUE THREAD

**Issue by antitim** [vitmalina/w2ui#1144]
Hello.
The custom field type in my form, there is no "Change" event. Therefore, the form when sending does not see the value in this field and tells me "Required field".

https://jsfiddle.net/antitim/yL47eope/

Thank you.

**Comment by vitmalina** [comment]
I recompiled JS, download latest from /dist folder and it will be working. Thanks.

**Comment by antitim** [comment]
Hello @vitmalina . Is there a way to require valid field before submitting the form and prevent the form submission with an invalid field?

**Comment by vitmalina** [comment]
Yes. (1) attach to onValidate event and the form will send you event.errors array with all errors found by the form. (2) If you add your error object to this array, even if it was empty at first, those will be considered errors. (3) form's save fill not proceed if there is an error (array not empty)

You can see the structure of the error object if you catch one that form sends. Simply mark one field as required and see what is in error array when event comes.

**Comment by antitim** [comment]
@vitmalina Thank you.
