### ISSUE TITLE
w2form: unable to reset a numeric field

### ISSUE THREAD

**Issue by mmcfts** [vitmalina/w2ui#1145]
w2ui version 1.4.3
I can't change a numeric field in a form from zero to blank (empty field).

When I do so, no change event is triggered and therefore the value of the field doesn't change, even though on the screen the field gets blanked out. When I save the form, the zero is sent to the server and re-appears on the screen.

The only workaround is to change the zero value to some other number and then empty the field.

Can anyone fix this please?

**Comment by mrg2001** [comment]
Please create a jsFiddle with the problem.

**Comment by mmcfts** [comment]
thanks mrg2001 for picking this up
Go to [](http://w2ui.com/web/demo/form)
fill in the form
put a 0 into the numeric fields
save the form
blank out the numeric fields (cancel the 0)
save the form
.... and woops the 0 is back!
(I attached a screenshot of the demo form here:
![field_error](https://cloud.githubusercontent.com/assets/16334877/15143173/a7976ece-16a8-11e6-9867-6d77bfc29bdb.jpg)

**Comment by mrg2001** [comment]
Easy work around is to clear on your own. For the form above do this

w2ui.form.record.field_int = null;

I have checked. It is not the same in current master branch.

**Comment by mmcfts** [comment]
As I mentioned, when the user blanks out the 0 on the screen, no change event is triggered and the value of the field is still = 0. Therefore there is no way for me to know whether or not the user has tried to blank out the field, the only thing I could do is this (in the save method):

if (w2ui.form.record.field_int == 0)
     w2ui.form.record.field_int = null;

but that is not what I want to do since 0 is a possible choice.

The only workaround for this is to read the field as a normal text field and validate it myself. Version 1.5 still has this issue.
