### ISSUE TITLE
w2layout transitions 

### ISSUE THREAD

**Issue by zimskybo** [vitmalina/w2ui#1146]
When switch layout content very fast，the layout can not  has the animations on the content show.Is that
a bug?

**Comment by mrg2001** [comment]
I do not understand what you mean. Do you mean when you show/hide panel? You can specify if you want it panel show immediately or not, see http://w2ui.com/web/docs/w2layout.show

**Comment by mpf82** [comment]
Closing issue: no response, no reproducer
