### ISSUE TITLE
W2field float silent param on max value

### ISSUE THREAD

**Issue by pelord** [vitmalina/w2ui#1147]
I’m prototyping an offline form plugged on an Access MDB with (Accessdb library http://accessdb.sourceforge.net/). 

I’m looking for an event to control max values. 
At this time, I’ve tested successfully your demo for Inline editing (http://w2ui.com/web/demos/#!grid/grid-21)

I want to understand how to manage alerts / event when the max value is reached. At this time, my goal is to raise an alert, no to set the value to the max value.
I’ve tried  silent setting to false with no success? Any ideas? Is there an issue?

here html:
<div class="w2ui-field w2ui-span4">
    <label>Latitude:</label>
    <div><input id="latitude" value="" onchange="myF_update('latitude','Points_controle','no_point')"></div>
</div>

Here JS:
	var_lat =$('#latitude').w2field('float', { groupSymbol: ' ', precision: 6 ,min: 0, max: 90, silent:false});

Pierre

**Comment by vitmalina** [comment]
Don't define min/max at all, but attach your own events on the control after it is initialized, here is an example
```
$('id').w2gird({
   name: 'grid', 
   ...
   onFieldEdit: function (event) {
      event.done(function () {
         $(event.input).on('keydown', function () { ... } )
      });
   }
});
```
Close the issue if it works.
