### ISSUE TITLE
Uncaught TypeError: Cannot read property 'contains' of undefined

### ISSUE THREAD

**Issue by mpf82** [vitmalina/w2ui#1148]
Hello,

when I use a w2ui layout, set the content of a panel to a w2ui grid and then set the content to a blank string, I get the following error when I click in the empty panel:

> Uncaught TypeError: Cannot read property 'contains' of undefined

I have tracked the problem down to the following lines in function mouseStart():

                    while (tmp) {
                        if (tmp.classList.contains('w2ui-grid')) break;
                        if (tmp.tagName.toUpperCase() == 'TD') tmps = true;
                        if (tmp.tagName.toUpperCase() != 'TR' && tmps == true) {
                            pos.x += tmp.offsetLeft;
                            pos.y += tmp.offsetTop;
                        }
                        tmp = tmp.parentNode;
                    }

suggested fix: check if the properties actually exist before accessing them

                    while (tmp) {
                        if (tmp.classList && tmp.classList.contains('w2ui-grid')) break;
                        if (tmp.tagName && tmp.tagName.toUpperCase() == 'TD') tmps = true;
                        if (tmp.tagName && tmp.tagName.toUpperCase() != 'TR' && tmps == true) {
                            pos.x += tmp.offsetLeft;
                            pos.y += tmp.offsetTop;
                        }
                        tmp = tmp.parentNode;
                    }

pseudo-code to reproduce the problem:

            w2ui["layout"].content( 'main', $().w2grid({ ... }) );
            // it's actually a click event that changes the content, 
            // but a timeout will do just fine to reproduce the error
            setTimeout(function(){
                w2ui["layout"].content( 'main', "" );
            }, 2000);

I think the main problem however is, that the mousedown handler does not get removed from the panel when the content changes.
Any idea why, or how to fix it?

In either case, it's not bad to check for properties before accessing them.

Tested in Chrome 39.0 with w2ui 1.5 (date: 04/01/2016)

**Comment by vitmalina** [comment]
Applied your fix. Create issue #1150 to track event off'ing
