### ISSUE TITLE
Grid search has an endless loop in some cases

### ISSUE THREAD

**Issue by bwl21** [vitmalina/w2ui#1149]
I have some cases, where searching in a grid caused w2ui to hang. I nailed it down to 

```javascript
        function clearMarkedText(index, el) {
            while (el.innerHTML.indexOf('<span class="w2ui-marker">') != -1) {
                el.innerHTML = el.innerHTML.replace(/\<span class=\"w2ui\-marker\"\>(.*)*\<\/span\>/ig, '$1'); // unmark
            }
        }
```

This does not replace the w2ui-marker if the span contains line breaks. The meta character "." matches every character except newline and line terminator.

therefore the while produces an endless loop. I'll prepare a pull request.

**Comment by bwl21** [comment]
I wanted to prepare the pull request, but my application was messed up after I pulled master in my branch.

the patch is

```javascript
        function clearMarkedText(index, el) {
            while (el.innerHTML.indexOf('<span class="w2ui-marker">') != -1) {
                el.innerHTML = el.innerHTML.replace(/\<span class=\"w2ui\-marker\"\>((.|\n|\r)*)\<\/span\>/ig, '$1'); // unmark
            }
        }
```
alternativly

``javascript
        function clearMarkedText(index, el) {
            while (el.innerHTML.indexOf('<span class="w2ui-marker">') != -1) {
                el.innerHTML = el.innerHTML.replace(/\<span class=\"w2ui\-marker\"\>([^<]*)\<\/span\>/ig, '$1'); // unmark
            }
        }
```

**Comment by vitmalina** [comment]
Applied your fix. Thanks for fixing this bug.
