### ISSUE TITLE
List field ignores readonly/disabled property

### ISSUE THREAD

**Issue by mpf82** [vitmalina/w2ui#1153]
When you create a list field and set it to read-only, you can still get the list popup when the field gets the focus (TAB) or when you click in the field and then press arrow up / arrow down key.

![2016-02-03 13_31_07](https://cloud.githubusercontent.com/assets/10152404/12782298/81bd5850-ca7a-11e5-8527-874b24fed682.png)

Code to reproduce the problem:

    <input type="list">
    <input type="list" readonly="readonly">
    <input type="list" disabled="disabled">

    <script type="text/javascript">
    var people = ['George Washington', 'John Adams'];
    $('input[type=list]').w2field('list', { items: people, disabled: true, });
    // $('input[type=list]').prop('readonly', true);
    </script>

It does not matter if readonly/disabled is set on the element or set on run-time.

I managed to track the problem down: the keyUp() handler does not check the properties!

Original code:

        keyUp: function (event) {
            ...
            if (['list', 'combo', 'enum'].indexOf(this.type) != -1) {
                // need to be here for ipad compa
                ...

Suggested fix:

        keyUp: function (event) {
            ...
            if (['list', 'combo', 'enum'].indexOf(this.type) != -1) {
                if ($(obj.el).prop('readonly') || $(obj.el).prop('disabled')) return;
                // need to be here for ipad compa
                ...

**Warning:**
There are other places in the code where you're checking for only readonly **attribute**, when you should probably be checking for both readonly _and_ disabled **properties**:
( For example in keyDown() handler )
I therefore recomment to replace all occurences of 

                if ($(obj.el).attr('readonly')) return;
with

                if ($(obj.el).prop('readonly') || $(obj.el).prop('disabled')) return;

this might be related to issue #244

**Comment by vitmalina** [comment]
Can you please specify what version of the code the problem is. Is it in the current master?

**Comment by mpf82** [comment]
Yes, it's the latest 1.5 version.

**Comment by mpf82** [comment]
While browsng through your site, I found a jsfiddle that you created [here](http://w2ui.com/web/docs/w2form.fields) to demonstrate disabling fields (using version 1.5).

http://jsfiddle.net/rLLwhrbj/1/

You can reproduce the problem in your fiddle by disabling the field and then press arrow up / arrow down while the disabled field has the focus.

**Comment by mpf82** [comment]
added a pull request: https://github.com/vitmalina/w2ui/pull/1188

**Comment by mrg2001** [comment]
Looks like it is fixed

**Comment by mendozada** [comment]
hi, in this example, as can be done to use the tab key to jump from fields.
It's possible?

http://jsfiddle.net/rLLwhrbj/1/

**Comment by mrg2001** [comment]
Fixed. Checkedin. Now jsfiddle works.
