### ISSUE TITLE
dropdown list with combo after selected.

### ISSUE THREAD

**Issue by sud0su** [vitmalina/w2ui#1154]
Sorry for my bad english.
how to make action after choosing one of the options in the combo list. I mean, after onclick in the list of data selection,
I want to make the data appear automatically on the grid next column after I select an option in the combo.
this is my fiddle [http://jsfiddle.net/razinal/11Ladm8z/3/](http://jsfiddle.net/razinal/11Ladm8z/3/)
thanks.. sorry for my bad englis

**Comment by vitmalina** [comment]
Here you go: http://jsfiddle.net/11Ladm8z/5/

Please submit future questions on stackoverflow.com or w2ui.com in comments. These issues are only for bugs
