### ISSUE TITLE
message - options.trigger not a function 

### ISSUE THREAD

**Issue by Snylten** [vitmalina/w2ui#1155]
When trying to close a message (that is autogenerated from a server response when trying to delete a grid row), I get following error in the console: "options.trigger is not a function"

  var msgCount = $(where.box).find('.w2ui-message').length;
        // remove message
        if ($.trim(options.html) == '' && $.trim(options.body) == '' && $.trim(options.buttons) == '') {
            var $msg = $(where.box).find('#w2ui-message'+ (msgCount-1));
            var options = $msg.data('options') || {};
            // before event
            **var edata = options.trigger({ phase: 'before', type: 'close', target: 'self' });**
            if (edata.isCancelled === true) return;
            // default behavior
            $msg.css(w2utils.cssPrefix({

**Comment by vitmalina** [comment]
Can you please create a JS fiddle where problem is reproduced?

**Comment by mpf82** [comment]
This will reproduce the problem with the current 1.5 master:

https://jsfiddle.net/zxcgxkxa/2/
