### ISSUE TITLE
Data range

### ISSUE THREAD

**Issue by ar53n** [vitmalina/w2ui#1158]
Can I create date field with options range, but only for current month?

**Comment by ar53n** [comment]
Sorry, we solve our problem
[jsfiddle.net/r5qpcsw0](url)

**Comment by vitmalina** [comment]
Glad you found a solution. There is start and end date you can pass to w2field and then user cannot pick it. It will also validate it when user types date. See http://w2ui.com/web/docs/form/fields-date
