### ISSUE TITLE
Sub grids weird behavior in 1.5

### ISSUE THREAD

**Issue by mpf82** [vitmalina/w2ui#1160]
I have just tested the [Sub Grids Demo](http://w2ui.com/web/demos/#!grid/grid-7) with the current 1.5 branch (by simply replacing the used CSS and JS).

    
    <link rel="stylesheet" type="text/css" href="https://rawgithub.com/vitmalina/w2ui/master/dist/w2ui.css" />
    <script type="text/javascript" src="https://rawgithub.com/vitmalina/w2ui/master/dist/w2ui.js"></script>

Here's what it should look like (1.4.2):
![2016-02-15 16_47_33-grid_ sub grids _ w2ui](https://cloud.githubusercontent.com/assets/10152404/13053290/ff86df58-d403-11e5-8d42-b91d21f97981.png)

Here's what it currently looks like in 1.5:
![2016-02-15 16_47_45-w2ui demo_ grid-7](https://cloud.githubusercontent.com/assets/10152404/13053297/0d99738a-d404-11e5-9767-f2c6891145c6.png)

Seems the expand-column does not get the correct height, so it does not stay with the associated row.

**Comment by mpf82** [comment]
This might be a duplicate of issue #711

**Comment by mrg2001** [comment]
Sub-grids were rewritten. There were too many problems with current approach and now it is different in 1.5.x, See https://github.com/vitmalina/w2ui/blob/master/demos/examples/grid-7.html

**Comment by mpf82** [comment]
A tree-like grid would not cover our use case.
We need to load entries from a different database table, so our "children" would need their own column(s).

For now I've fixed the issue in our environment by hard coding the height values with CSS when working with sub-grids.

Are there any plans to support sub grids with their own columns in the future (no matter if true grid elements or implemented as tree structure)?

**Comment by mrg2001** [comment]
Yes, indeed it was like that in 1.4 version. I have used in a few real-life projects and I completely dislike the UX of it. It is hard to use and difficult to navigate. I would recommend reconsidering it, possibly doing a sidebar panel or a preview panel. If you absolutely must use it that way, use 1.4 version.
