### ISSUE TITLE
List menu item icon/img broken in 1.5

### ISSUE THREAD

**Issue by mpf82** [vitmalina/w2ui#1161]
http://jsfiddle.net/vt9h7woz/2/

Version: current master 1.5

If you click (and hold down the mouse button) on a menu item with an image, the image gets removed/replaced, which is not a desired behavior.

I tracked the issue down to the following event handler:

`$.fn.w2menuDown = function (event, index) { ... }`

I think the problem is, that you always assume you have an item that can be checked and then the image gets removed because of the added CSS class:

```
.w2ui-icon-check:before {
  content: "\f101";
}
```

Suggested fix: wrap the check handling in a if statement and check if the item is of type "check" or "radio":

            $.fn.w2menuDown = function (event, index) {
                var $el  = $(event.target).parents('tr');
                var tmp  = $el.find('.w2ui-icon');
                if( (options.type == 'check') || (options.type == 'radio') ){
                   var item = options.items[index];
                   item.checked = !item.checked;
                   if (item.checked) {
                       if (options.type == 'radio') {
                           tmp.parents('table').find('.w2ui-icon')
                               .removeClass('w2ui-icon-check')
                               .addClass('w2ui-icon-empty');
                       }
                       tmp.removeClass('w2ui-icon-empty').addClass('w2ui-icon-check');
                   } else if (options.type == 'check') {
                       tmp.removeClass('w2ui-icon-check').addClass('w2ui-icon-empty');
                   }
                }
                // highlight record
                $el.parent().find('tr').removeClass('w2ui-selected');
                $el.addClass('w2ui-selected');
            };

**Comment by mrg2001** [comment]
Implemented your suggestion
