### ISSUE TITLE
Grid toolbar never disables once enabled?

### ISSUE THREAD

**Issue by elaw01887** [vitmalina/w2ui#1162]
I'm using a grid with a toolbar defined as follows:
		toolbar: {
			items: [
				{ type: 'html', html: 'Selected attachment:' },
				{ type: 'button', id: 'btnAttachmentOpen', text: 'Open', hint: 'Open selected attachment', icon: 'fa fa-floppy-o' },
				{ type: 'button', id: 'btnAttachmentRemove', text: 'Remove', hint: 'Remove selected attachment', icon: 'fa fa-trash-o' },
			],
			onClick: toolbarAttachments_onClick
		},

When the grid initially renders, the toolbar buttons are disabled (grayed out).  Once a record is selected in the grid, the toolbar buttons become enabled, which is as expected.

But it seems no matter what I do to the grid, they never get disabled again!

The issue in particular relates to a "delete record" command.  When the user does that, a call is made to the server that deletes the selected record, then I call reload() on the grid to refresh its data from the server.  I expected that to disable the toolbar buttons (as now no record is selected) but it does not.  I've also tried calling refresh(), selectNone(), and stateReset() - none of those disable the toolbar buttons either.

Am I doing something wrong?

**Comment by mpf82** [comment]
It's up to you to enable / disable the buttons.

The way to go is to check the grid's selection ( this.getSelection().length ) in onSelect() / onUnselect() event handlers and enable/disable your buttons accordingly.

**Comment by mrg2001** [comment]
mpf82 is correct, if you create your own buttons, then it is up to you to disable/enable them. You can attach to various events to do so. However, you can enable predefined buttons, see http://w2ui.com/web/docs/w2grid.show, then grid will handle it for you. It would be the same result if you add a custom button with id: "w2ui-delete"
