### ISSUE TITLE
HTTP Headers Support

### ISSUE THREAD

**Issue by daggetlover** [vitmalina/w2ui#1163]
Need to add ability to add HTTP Headers in grid.

**Comment by mrg2001** [comment]
If you submit a pull request, I will merge it. However, please rename .httpHdrData to .headersData

**Comment by daggetlover** [comment]
I have changed the name and uploaded w2grid and w2form. Both are working in my test environment. Pull request has been done.

Thanks.

Chris

**Comment by mrg2001** [comment]
I do not see the pull request.

**Comment by chalchis** [comment]
I do not understand
what you need in the grid?

**Comment by daggetlover** [comment]
w2grid and w2form changes to support adding header data to AJAX requests.

Pull request is now available.

**Comment by mrg2001** [comment]
Can you post link to the pull request. I do not see it.

**Comment by mpf82** [comment]
can be closed, see commit https://github.com/vitmalina/w2ui/commit/3631e2444e8e2dbe428938ee4b1195ebc8adfb9e
