### ISSUE TITLE
Layout: handler to be called _after_ resizing

### ISSUE THREAD

**Issue by Ptival** [vitmalina/w2ui#1165]
Hello,

Sorry if this has been answered already but I could not find it with the search feature.

I am trying to attach an event to be triggered once the layout has been resized and the panels now have their proper size. Or alternatively, I would like to access the "running" size of the resizing currently happening.

As far as I can tell, the onResizing is being called upon starting the resizing, and the associated event.onComplete is being continuously called while the separator is being dragged, but I cannot find a way to attach a handler to the release of the separator, after the resizing has taken place.

Am I overseeing something in the documentation?

**Comment by mpf82** [comment]
You could use this snippet in event.onComplete:

https://gist.github.com/nosp4mSnippets/5846729

It also includes a usage example.

**Comment by Ptival** [comment]
I was trying to avoid a timeout-based solution. How does it guarantee that the elements have been resized?

I feel like there should be a way to hook a callback to the part of the code that performs the resizing upon releasing the draggable.

**Comment by Ptival** [comment]
Ok, nevermind, I figured out I had been attaching my handler to "resizing" rather than "resize", which explains the behaviour I had.
