### ISSUE TITLE
http://w2ui.com/web/demos/#!combo/combo-9 firefox bug.

### ISSUE THREAD

**Issue by tristenator** [vitmalina/w2ui#1166]
that demo ^^^ shows chrome will allow click-drag to select records for as long as the user drags the mouse towards the bottom of the page.

firefox won't allow this behaviour, making it difficult for the user to select a set of records larger than the number of records fitting into the current view.

hope that makes sense and sorry if this has already been reported.

**Comment by mrg2001** [comment]
Unfortunately, there is little that can be done to fix it. Or the solution will be really ugly. Please note that you can also select using click-shift-click or click-ctrl(cmd)-click. Then it should not be a problem.
