### ISSUE TITLE
Customize row height

### ISSUE THREAD

**Issue by davidmpaz** [vitmalina/w2ui#1172]
Hi Vitali,

First of all, thanks a lot for this framework I think your implementation of the grid is awesome. Now the issue:

I have read this #872 and I agree on it, but, is it possible to customize the row height by css and not directly in the style attribute of the "tr" tag?

Is there a way to change this at all by configuration at grid creation time or something alike?

I have look through the code of grid class but did not found anything, maybe I'm just missing it. Please have in mid that I don't want to modify it once is rendered, it would be good for me just to make it different that the 24px Im getting now.

Best regards,
David

**Comment by chalchis** [comment]
yes test style in records

```
$('#myGrid').w2grid({ 
    name   : 'myGrid', 
    columns: [                
        { field: 'fname', caption: 'First Name', size: '30%' },
        { field: 'lname', caption: 'Last Name', size: '30%' },
        { field: 'email', caption: 'Email', size: '40%' },
        { field: 'sdate', caption: 'Start Date', size: '120px' },
    ],
    records: [
        { recid: 1, fname: 'John', lname: 'Doe', email: 'jdoe@gmail.com', sdate: '4/3/2012', "style": "height: 50px" },
        { recid: 2, fname: 'Stuart', lname: 'Motzart', email: 'jdoe@gmail.com', sdate: '4/3/2012' , "style": "height: 50px"}
     
    ]
});
```

**Comment by davidmpaz** [comment]
Hey, thanks!! works like a charm!

**Comment by mrg2001** [comment]
grid.recordHeight is used internally by the grid for calculation records height. It is used in virtual scrolling. I am afraid it might have issues if you do not set it properly. This is also why all rows should be of the same height.

**Comment by davidmpaz** [comment]
I will keep it in mind, thank you for coming around the task even when it was closed.
Best regards
