### ISSUE TITLE
Sort on date column it has problem

### ISSUE THREAD

**Issue by samoilis** [vitmalina/w2ui#1174]
When sorting date column in a grid has a strange behavior

In the following sample the record values come from javascript milliseconds format:

https://jsfiddle.net/samoilis/kfc1n3sL/14/

I've tried the most of the date formats but with no success.

**Comment by mrg2001** [comment]
Please describe what is strange. I looked at it and it looks great (https://jsfiddle.net/kfc1n3sL/15/). In fact, using timestamp is the prefered way to go as then there is no issues with timezone, daylight saving, etc.

**Comment by samoilis** [comment]
Oh, you're right. Confuse it with the older library version.

apologize for any inconvenience
