### ISSUE TITLE
w2field for selected cell

### ISSUE THREAD

**Issue by ar53n** [vitmalina/w2ui#1175]
Can i add w2field('date') for selected cell, not for entire column.
ERROR: w2field could only be applied to INPUT or TEXTAREA. 

Input area show later, but i can't associated for this cell

**Comment by mrg2001** [comment]
You can do this by enabling for the column an input field of type 'text' and then in onEditField event initialize the control with w2field('date'). See http://w2ui.com/web/docs/w2grid.onEditField. I think you will need to attach in onComplete loop and there should be either an id of the input in the event object or reference to it

**Comment by ar53n** [comment]
Just i don't want enable date all for column, but can i enable for record?

**Comment by mrg2001** [comment]
Yes, for one field only, not for the column. For the column you define it as text input, but when onEditField happens, you can specify it for your particular field or event.preventDefault() to disable it.

**Comment by mpf82** [comment]
Closing issue: Solution posted by @mrg2001 should work.
