### ISSUE TITLE
w2 popup responsivenes

### ISSUE THREAD

**Issue by dzona** [vitmalina/w2ui#1176]
Is there a chance to set width and height of popup when maximized to percent instead of pixels? In that way we should have modal repsponsivenes

**Comment by ar53n** [comment]
Maybe for popup onRender event.onComplete  do that document.getElementById('#w2ui-popup').style.width = '100%'

**Comment by dzona** [comment]
@ar53n yes, I did something similar, for ``onMax``

````
onMax : function (event) {
     event.onComplete = function () {
             $('#w2ui-popup').css({
               'top': 0,
               'left': 0,
               'width': '100%',
               'height': '100%'
            });
     };
},
````

but just saying it could be nice feature to be able to set width and height as ``%`` in ``w2popup.resize()``

**Comment by ar53n** [comment]
Sorry but why? When maximized popup resize on full screen?

**Comment by dzona** [comment]
I have customers, that use application by splitting view in two parts. They are transcripting from one application to another, and if I use native maximize feature, size of the popup is not changed when browser size is changed

**Comment by mrg2001** [comment]
If you open a popup and provide really large width/height, it sill still open up to max available width/height. Plus max button will take it max and back. You can read up this thread https://github.com/vitmalina/w2ui/issues/283 that contains some reasons why resize of the window is not implemented.
