### ISSUE TITLE
Documentation quirks

### ISSUE THREAD

**Issue by Ptival** [vitmalina/w2ui#1178]
Hello,

I am in the process of writing a TypeScript definition file for w2ui, and noticed a lot of quirks in the documentation. I will list them in this issue as they arise.

In Grid > Properties:
````
contextMenu - remove(recid, [event])   // remove?

getCellValue - getCellValueL(index, column_index, [summary])   // getCellValueL?

resizeBoxes - requestBoxes()   // is this event a property or should it be a method?

resizeRecords - requestRecords()   // is this event a property or should it be a method?

````

---

In http://w2ui.com/web/docs/w2grid.getSelection

There are oddities: it mentions the second optional parameter, it does not describe the returnIndex

**Comment by mrg2001** [comment]
Good catch. I have fixed them in current master branch /docs folder. It will be uploaded on the website with 1.5 release. I think I am going skip updating them in 1.4.x docs and it is old now.
