### ISSUE TITLE
Are the entry points parameters documented?

### ISSUE THREAD

**Issue by Ptival** [vitmalina/w2ui#1179]
I can't seem to find a place in the documentation where the options one can pass to $(...).w2{layout, grid, ...} are documented.

The examples provided on their respective pages do not seem to exhaustively describe the fields you can pass.

Even looking at the source, I am not sure where to get a clear picture of the fields one may/must pass.

**Comment by mrg2001** [comment]
See 
- http://w2ui.com/web/docs/grid/events
- http://w2ui.com/web/docs/grid/properties
- http://w2ui.com/web/docs/grid/methods

All of them are entry params for the grid. You can find same for the rest of components.

**Comment by Ptival** [comment]
Ah thanks, I didn't realize. Sorry for the noise.

**Comment by mrg2001** [comment]
No prob. Glad to help
