### ISSUE TITLE
Is there any way of getting the name of the grid is already present or not?

### ISSUE THREAD

**Issue by shrabanee** [vitmalina/w2ui#1181]
Hi,

I am new to w2grid. 

I want to create a grid, if the grid name is not present already. I have the name of the grid, that I want to create with.

Is there any way to figure out, whether grid with the name is already present in the view or not.

**Comment by chalchis** [comment]
Why you need to know if this present?
Have you had any problem?

**Comment by shrabanee** [comment]
I am using grid in some tabs. 
On doing first click on each tab I want to generate the grids. But when second time user is clicking on any tab, I don't want to create the grid. To do this, I need to know the grid name which I am trying to create is already present or not.

**Comment by ar53n** [comment]
No just when you click on other tabs you should destroy() grid,

**Comment by bwl21** [comment]
Doesn't w2grid[<yourname>] yield nil if the grid is not yet there?

**Comment by samoilis** [comment]
maybe this will help you
http://w2ui.com/web/docs/w2utils.checkName

**Comment by chalchis** [comment]
shrabanee

I recommend you show some code
remember that you can use render
use tabs mention this scheme can be of more help

```
<!DOCTYPE html>
<html>
<head>
    <title>W2UI Demo: combo-5</title>
    <link rel="stylesheet" type="text/css" href="http://w2ui.com/src/w2ui-1.4.2.min.css" />
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js"></script>
    <script type="text/javascript" src="http://w2ui.com/src/w2ui-1.4.2.min.js"></script>
</head>
<body>

<style>
.tab {
    width: 100%;
    height: 400px;
    border: 1px solid silver;
    border-top: 0px;
    display: none;
    padding: 10px;
    overflow: auto;
}
</style>

<div id="tab-example">
    <div id="tabs" style="width: 100%; height: 29px;"></div>
    <div id="tab1" class="tab">
        First tab.
    </div>
    <div id="tab2" class="tab">
        Second tab, with some HTML in it. :)
    </div>
    <div id="tab3" class="tab">
        What did you expect, of course it is the third tab.
    </div>
</div>

<script type="text/javascript">
var config = {
    tabs: {
        name: 'tabs',
        active: 'tab1',
        tabs: [
            { id: 'tab1', caption: 'Tab 1' },
            { id: 'tab2', caption: 'Tab 2' },
            { id: 'tab3', caption: 'Tab 3' },
        ],
        onClick: function (event) {
            $('#tab-example .tab').hide();
            $('#tab-example #' + event.target).show();
        }
    }
}

$(function () {
    $('#tabs').w2tabs(config.tabs);
    $('#tab1').show();
});
</script>

</body>
</html>
```

**Comment by mrg2001** [comment]
There is a global variable called w2ui. It will contain all objects created (layouts, grids, forms). If it exists there, then grid exists. You can check with the following command:
```
if (w2ui['grid_name'] != null) { ... }
```

**Comment by shrabanee** [comment]
@mrg2001 Okay will try the solution.

**Comment by shrabanee** [comment]
The solution worked @mrg2001 . Thanks.
