### ISSUE TITLE
support multi-level table head off?

### ISSUE THREAD

**Issue by zhump** [vitmalina/w2ui#1182]
Hi,I think it's a excellent ui-widgets !
It can support more than two meter head off?
TreeGrid ajax load node can do?
Summary Records can be fixed at the bottom of it?

for example

![0 hvqzg wn rhy g 0 4 6](https://cloud.githubusercontent.com/assets/7962067/13545515/806bc808-e2c9-11e5-88c3-3751fe879db5.png)

thanks

**Comment by mrg2001** [comment]
Yes, it is supported, 2 levels only. See http://w2ui.com/web/demos/#!grid/grid-13
