### ISSUE TITLE
Enum type in search  grid in 1.5

### ISSUE THREAD

**Issue by pidlo** [vitmalina/w2ui#1183]
At first great job many thanks for you vitmalina!
In 1.4 version this code has no problem and get list of items 600002 ....etc

w2ui.HTVATControlGrid.searches[columnIndex].type = 'enum';
w2ui.HTVATControlGrid.searches[columnIndex].options = {items:[{text:'600002', num_dokl:'600002'},{text:'600003', num_dokl:'600003'},{text:'600004', num_dokl:'600004'}]};

in 1.5 version does not take effect.

**Comment by mpf82** [comment]
Did you check what happens on your server side?

I think the command changed from "get-records" to simply "get" in 1.5.

**Comment by pidlo** [comment]
you cannot use server side. This bug you can see if set only enum items without server side..
if you switch (in both versions 1.4 and 1.5 v ) from enum to list then is all OK but enum take no efect..

**Comment by mrg2001** [comment]
The issue might be if your search fields are already displayed. I just checked, if you do this
```
w2ui.grid.searches[3].options.items.push('other2')
```
And then click on the search button - I can see extra item. However, if search was already open, you do not see new item. It needs to refresh it.

**Comment by mpf82** [comment]
Can you please provide a working Fiddle/Bin/Pen to demonstrate the issue?

**Comment by mpf82** [comment]
Closing issue: no response
