### ISSUE TITLE
w2ui grid: 'add' button causing blank lines when remote data is used

### ISSUE THREAD

**Issue by ricrogz** [vitmalina/w2ui#1184]
Hi,

I am working with remote data, and when I try to add new records to a grid by using the '.add' method, I always get extra blank lines added to the table. I have checked, and I am getting the right 'total' value through my url calls, but '.add' does not properly update its value, causing the blank lines.

This is the code in the '.add' method for the grid:
```javascript
        add: function (record) {
            if (!$.isArray(record)) record = [record];
            var added = 0;
            for (var o in record) {
                if (this.recid && typeof record[o].recid == 'undefined') record[o].recid = record[o][this.recid];
                if (record[o].recid == null || typeof record[o].recid == 'undefined') {
                    console.log('ERROR: Cannot add record without recid. (obj: '+ this.name +')');
                    continue;
                }
                this.records.push(record[o]);
                added++;
            }
            var url = (typeof this.url != 'object' ? this.url : `this.url.get);`
            if (!url) {
                this.total = this.records.length;
                this.localSort();
                this.localSearch();
            }
            this.refresh(); // ??  should it be reload?
            return added;
        },
```

Clearly, 'this.total' is not updated if the data comes from a remote url (`if (!url)` block), producing the 'blank lines' due to the mismatch with the 'this.records.length' value.

**Comment by mrg2001** [comment]
Ideally, .add() should not be used when your data source is remote. The grid might have only a portion of the records and therefore it does not know how many records total. Also another user could add records on the server, which will make total incorrect. If you do decide to use it with remove data source, you will need to update total yourself. Should be quite easy.
