### ISSUE TITLE
spreadsheet old values

### ISSUE THREAD

**Issue by ar53n** [vitmalina/w2ui#1185]
Hello, we have a problem. Our column name  we indicated how date. Now we can't do empty cell, because old_values find with function 

```
parseField: function (obj, field) {
            var val = '';
            try { // need this to make sure no error in fields
                val = obj;
                var tmp = String(field).split('.');//our date [15,07,2016] our values [" ", " ", " "]
                for (var i in tmp) {
                    val = val[tmp[i]];
                }
            } catch (event) {
                val = '';
            }
            return val;
        },
```

After execution function we get old_values = " " and new_values === old values so field dont change

![image](https://cloud.githubusercontent.com/assets/7085102/13665283/b144dbbc-e6bc-11e5-82ac-83811f34d46e.png)

**Comment by mrg2001** [comment]
Can you please create jsFiddle to illustrate the problem.

**Comment by mpf82** [comment]
Closing issue: no response, no reproducer
