### ISSUE TITLE
Get selected element from list with a tabulation

### ISSUE THREAD

**Issue by pelord** [vitmalina/w2ui#1189]
Hi, 

I wonder how to select a choice from a list or combo by tab key on keyboard.
At this time, tab key leave the dropdown list or combo without proceeding to a choice into the dropdown. So user has to
 1- write his choice or move into the dropdown list with arrows
 2- click on his choice or press return to accept the selection.

Is it a real issue, a nice feature to have or simply impossible?

**Comment by mrg2001** [comment]
I think is possible. To start, add an event with jQuery to the input that is used for it, then catch the tab key and cancel it and then add $(this).data('selected', []) your choices.

Please as questions on the forum. Issues are strictly for bugs.
