### ISSUE TITLE
Internal events should be bound to a w2ui namespace

### ISSUE THREAD

**Issue by dhagrow** [vitmalina/w2ui#1192]
See the relevant documentation for jQuery [.on()](https://api.jquery.com/on/) and [.off()](https://api.jquery.com/off/).

An example of how binding to events with no namespace can cause problems: if I bind an event handler for `resize` to the `window` object (`$(window).on('resize')`), and then at any point destroy a grid (`grid.destroy()`), my event handler will also be unbound.

**Comment by dhagrow** [comment]
I see the issue I used as an example has been resolved in a different way in the repo. Event namespaces may still resolve other issues, but as I don't have a ready example I will close this for now.

**Comment by mrg2001** [comment]
Thank you for suggestion, in fact I have adopted such approach into my practice a few years ago. But not everything in w2ui follows it yet. Majority of the events, however, are bound the elements that w2ui generates, which should not create conflicts
