### ISSUE TITLE
Ember support

### ISSUE THREAD

**Issue by secondsano** [vitmalina/w2ui#1193]
Hello, first of all - great product! You made my day!

Question is - is there version of `w2ui` where you use other loops operator instead of `for(var ... in ...)`?

You see, I try to mix `emberjs` with your widgets. There seems to be no problems with that, expect one thing: `emberjs` extends base `Array` class so that `for-in` operator loops through new properties like `lastObject`, `firstObject` etc. I've searched for solution, and it seems like ecma6 conventions suggest to use other loop operators OR use `for-in` with conditions like `.hasOwnProperty`. So i wonder if there any version of your library where you use other loop operators, or, if there's none, can I pull-request to change loop operators so that it would be more safe for extensions like `emberjs`?

**Comment by mrg2001** [comment]
in current master version all for-in loops have been refactored. Latest in dist folder is pretty stable right now. I am working on writing documentation and then will be releasing it.
