### ISSUE TITLE
how to load w2ui correctly in react

### ISSUE THREAD

**Issue by Nicolewxyy** [vitmalina/w2ui#1195]
In my project i used both react and w2ui, i have tried many ways to load w2ui in react. Finally, i make jquery as global available, and use exports loader to set w2ui in the global context: 
  `var w2ui = require('exports?w2ui!../../../node_modules/w2ui/w2ui.min.js')`,  got no error message, but the layout was mixed. Then i load w2ui css, but got a blank layout page , and still no error message. Is there anyone can help me, thanks so much !

**Comment by Nicolewxyy** [comment]
oh,  in fact this solution

**Comment by mrg2001** [comment]
There is already w2ui global variable. It is used to reference all objects that w2ui created. If you redefined it, there might be issues. Besides that, there should be no issue mixing with react.
