### ISSUE TITLE
extend event prototype

### ISSUE THREAD

**Issue by samoilis** [vitmalina/w2ui#1201]
there is a way to extend some grid events without override default prototype?

Looking to find a way to run some actions, always, even when the event is defined (or not) in initialization of grid.

**Comment by mrg2001** [comment]
Once grid initialized, you can do grid.on('*', function...) it will be called on all events. Will this work?

**Comment by samoilis** [comment]
actually, I want to create **global** changes in some events, ie: onRender display always myToolbar in all of grids or mask some form fields of all application forms


if I set the event from **w2obj prototype** (w2obj.grid.prototype.onRender = function (event) {...}) works! 

but when I set onRender at initialization of grid override this global code

**Comment by mrg2001** [comment]
You can do this
```
w2obj.grid.prototype._render = w2obj.grid.prototype.render;
w2obj.grid.prototype.render = function (...) {
   this._render();
   ...
}
```

**Comment by samoilis** [comment]
It works

thank u
