### ISSUE TITLE
[1.4.3, 1.5.x] changing caption of toolbar items does not work

### ISSUE THREAD

**Issue by bwl21** [vitmalina/w2ui#1204]
```Javascript
w2ui['toolbar'].set('sort', { caption: s, icon: 'fa fa-envelope bold' });
w2ui['toolbar].refresh();
```
still does not work on 1.5.x. It was working with 1.3.2

I hacked a workaround with pure js

```Javascript
function set_tbitem_caption(item, caption)
{
$("#tb_layout_top_toolbar_item_"+ item + " .w2ui-tb-caption").html(caption)
// w2ui['toolbar'].set(item, {caption: caption})
// w2ui['toolbar'].refresh();

}
```

see also discussion on http://w2ui.com/web/docs/w2toolbar.set

**Comment by mpf82** [comment]
I'm not sure about 1.4.3, but the following code works for me in 1.5.x

    w2ui['test_grid'].toolbar.set('mybutton-1', { text: "My New Caption" } );

Note that `caption` is supported in the constructor for backwards compatibility, but with `set()` you will have to use `text`instead.

**Comment by bwl21** [comment]
really?

This is the transcript of my console in chrome. You see

the toolbar item "tb_viewe" intially has text: "" and caption: "Auszug"
after I set the text, it has text: "newcaption" but still displays "Auszug".
even  refresh() does not help.

````
w2ui['toolbar'].get('tb_view')
Object {id: "tb_view", type: "menu", text: null, html: "", tooltip: null…}arrow: truecaption: "Auszug"checked: falsecolor: nullcount: nulldisabled: falsegroup: nullhidden: falsehtml: ""icon: "fa fa-shopping-basket"id: "tb_view"img: nullitems: Array[4]onClick: nullonRefresh: nulloverlay: Objectroute: nullselected: nullstyle: nulltext: nulltooltip: nulltransparent: nulltype: "menu"__proto__: Object
w2ui['toolbar'].get('tb_view').caption
"Auszug"
w2ui['toolbar'].set('tb_view', {text: "newcaption"})
true
w2ui['toolbar'].get('tb_view').caption
"Auszug"
w2ui['toolbar'].get('tb_view')
Object {id: "tb_view", type: "menu", text: "newcaption", html: "", tooltip: ""…}
```

**Comment by mpf82** [comment]
<div id="my_toolbar" style="padding: 4px; border: 1px solid silver; border-radius: 3px"></div>
    <script type="text/javascript">
        $(function () {
            $('#my_toolbar').w2toolbar({
                name: 'my_test_toolbar',
                items: [
                    { type: 'button',  id: 'item1',  caption: 'Item 1' }
                ]
            });
        });

        setTimeout(function(){
            var item = w2ui['my_test_toolbar'].get('item1');
            console.log(item.id, "/", item.caption, "/", item.text);
            w2ui['my_test_toolbar'].set('item1', { text: "My New Caption" } );
            console.log(item.id, "/", item.caption, "/", item.text);
        }, 2000);
    </script>

Console output:

    item1 / Item 1 / Item 1
    item1 / Item 1 / My New Caption

And the button changes from "Item 1" to "My New Caption" when the timer is executed.

**Comment by bwl21** [comment]
@mpf82 thank you very much, Mike. I have isolated the case in an extra HTML file in my project (therefore using the same w2ui - files), and it works as you describe.

But when I integrate in my project, it does not work. There must be some conflicting side effect.
I will try to track it down.

**Comment by mrg2001** [comment]
@mpf82 is right about this. In 1.5.x you should use text property instead of caption. But caption will still work when element is initialized. After that you need to user text. I have looked through the lib and saw that sometimes it was used text and sometimes captions. To make it the same throught, I renamed it to text everywhere I could find. However, for backwards compatibility during init mode, it will take caption (if text is not defined) and will use it

**Comment by bwl21** [comment]
I tried to track it down. By whatever reason w2ui['toolbar'] returns an object with the box property null. I stepped through and saw that if box is null, it does not refresh.
