### ISSUE TITLE
Is there way to display error cell

### ISSUE THREAD

**Issue by firstsano** [vitmalina/w2ui#1207]
I've read through docs and I dont see any opportunity to display cell error message. It could be helpful, when server validation fails on property and returns error message. It could be displayed like `combo` popup.
Question is - am I missing something, or there is a way to do it?

**Comment by mpf82** [comment]
If you can identify the cell or the content with a unique ID, you can add either a w2overlay() or a w2tag() to the element:

    $("#grid_test_grid_data_2_3").w2overlay("Must not be empty!", {});

![2016-04-05 16_05_20-nemetris web template - v0 5](https://cloud.githubusercontent.com/assets/10152404/14284537/4970e832-fb48-11e5-932b-4bd8e4609261.png)


    $("#grid_test_grid_data_2_3").w2tag("Must not be empty!", { position: 'bottom' });

![2016-04-05 16_04_06-nemetris web template - v0 5](https://cloud.githubusercontent.com/assets/10152404/14284542/4d672528-fb48-11e5-95c2-becac925c966.png)

**Comment by firstsano** [comment]
Thank you! You saved my day!
So i WAS missing something!

**Comment by chalchis** [comment]
how I can
know the id of the cell?

**Comment by firstsano** [comment]
Well in my case I catch `onSave` event, and I have `event.changes` array of objects, with recid in it.
