### ISSUE TITLE
tabIndex not working correctly with list fields

### ISSUE THREAD

**Issue by enricogatto** [vitmalina/w2ui#1209]
Using w2ui 1.4.3, if I don't specify tabIndex in a form, pressing tab key switchs to all fields except list fields, which are ignored. Version 1.4.2 works well.

Thank you in advance.

**Comment by mrg2001** [comment]
Can you please create a jsFiddle to demonstrate the problem

**Comment by mendozada** [comment]
Hi, Form in a Popup don't work

**Comment by mrg2001** [comment]
Fixed. See latest commits. I regenerated js files too.

**Comment by mendozada** [comment]
its, perfect, thanks
