### ISSUE TITLE
w2grid + tabs initialization

### ISSUE THREAD

**Issue by phase92** [vitmalina/w2ui#1212]
I'm trying to create a page that has 4-5 tabs and each tab has a grid that loads data from a
server.  See the code below for the details..  If I leave off the chunk of code called 'ExtraInit', 
then each grid is initialized but also fully visible on the page right after the page loads  In other
words, the tabs don't appear to be initialized.  If you edit the MakeGrid() function in the example
below so that it is a no-op, I believe you'll see the text for all the tabs displayed until you click on
one of the tabs.

If I add in the 'ExtraInit' section, the tabs do appear to be initialized and the contents of only
the first tab is visible.  However, only the first grid is initialized.  Clicking on tab 2, 3, etc doesn't
show grid 2, 3, etc.  All I see is a blank section.  I need to double check but I think the
server isn't contacted to get data for grids 2, 3, etc.

I'm fairly new to w2ui and so far, I've been very pleased.  In general, everything seems
logical and it's been easy to figure out how to make things work.  I haven't been able to
figure out this particular problem, though.

Maybe there's a different/better way to initialize the tabs and grids?  Also, every now and then,
the page will render but the tabs won't be displayed at all.  It also appears as though the tabs
weren't initialized.  (Each grid takes 1-2 to seconds to load.  A proxy server adds an additional
4-5 seconds.  Maybe there's a timeout that is preventing the tabs from being initialized?  Is there
a good strategy to use to find out?)

Thanks, in advance, for any help you can provide.  And, thanks for providing such a useful
framework.

```
<script>
  function MakeGrid(GridName)
  {
    var config = { ... };
    $(function () { $('#' + GridName).w2grid(config); });
  }
</script>

<div id="TabContainer">
    <div id="TabStrip" style="width: 100%; height: 29px;"></div>
    <div id="tab1" class="tab">
      <p>grid 1</p>
      <div id="grid1"></div><script>MakeGrid('grid1');</script>
    </div>
    <div id="tab2" class="tab">
      <p>grid 2</p>
      <div id="grid2"></div><script>MakeGrid('grid2');</script>
    </div>
    <div id="tab3" class="tab">
      <p>grid 3</p>
      <div id="grid3"></div><script>MakeGrid('grid3');</script>
    </div>
</div>

<script>
  var TabDefn = {
        name: 'tabs',
        active: 'tab1',
        tabs: [
            { id: 'tab1', caption: 'Tab 1' },
            { id: 'tab2', caption: 'Tab 2' },
            { id: 'tab3', caption: 'Tab 3' },
        ],
        onClick: function (event) {
            $('#TabContainer .tab').hide();
            $('#TabContainer #' + event.target).show();
        }
    };

  $(function () {
    $('#TabStrip').w2tabs(TabDefn);
    $('#tab1').show();
  });
  
  /* ExtraInit ... */
  $(function () {
    $('#TabContainer .tab').hide();
    $('#tab1').show();
  });
</script>

```

**Comment by chalchis** [comment]
you can use

//clear grid
w2ui['nom_grid'].clear();

**Comment by chalchis** [comment]
you can use the event click

w2ui.tabs.on('click', function(event) 
{
     event.onComplete = function()
     {
          if (event.target === 'tab1')
          {

         }
     }
});

**Comment by phase92** [comment]
Thanks.  I think I can make this work.  Much appreciated.  And
thanks again for making the library available.

**Comment by TrevorPT** [comment]
(Questions should go in StackExchange but given that you've asked ... )

I'm wondering if it's a timing issue and if your MakeGrid scripts have not been executed when `$(function () {` is hit (the document might be loaded, but that doesn't mean the grids have been fully initialized).  One thing I've found with w2ui is that there are timeouts used throughout that some times messes up order of events (that might not be the case here, but something to watch out for.

see https://learn.jquery.com/using-jquery-core/document-ready/

> $( document ).ready()
>
> Code included inside $( document ).ready() will only run once the page Document Object Model (DOM) is ready for JavaScript code to execute. Code included inside $( window ).load(function() { ... }) will run once the entire page (images or iframes), not just the DOM, is ready.

I would try the MakeGrid calls in `$(function () {` instead of in the HTML and see what happens, or you might want to try using `$( window ).load()`.

Also try forcing a resize of the grid when its tab is shown using `w2ui[ gridID ].resize()`.  This is also necessary if the window has been resized as the hidden tabs will have been rendered at a different size.
