### ISSUE TITLE
Display validation error on field

### ISSUE THREAD

**Issue by firstsano** [vitmalina/w2ui#1213]
Validation on server side, I catch errors and want a method to display errors like build-in w2ui validation errors (message in red box in front of field). How it should be done? Or should I just use overlays?

**Comment by vitmalina** [comment]
You can validate before you submit form. If you find errors in this case you display them with $().w2tag() field. Once you submit to the server and server responds back that there was an error. Depending on the error, you can show in w2alert() or you still can use w2tag() to show what fields was the error. I think for most cases w2alert should work.

**Comment by firstsano** [comment]
I see your point, but the problem is - I don't want to interrupt user's experience by blocking window, so it's like `$().w2tag` is more suitable, but I can't change `$().w2tag` styles (i want it to be red, indicating that there's error), so I use `$().w2overlay`, but it only shows to the top or to the bottom of element. Can I change  `$().w2tag` style or  `$().w2overlay` position?

**Comment by mrg2001** [comment]
$().w2tag() will support all 4 positions. Also, you can add a style to the input itself to show it in red. See http://w2ui.com/web/demos/#!forms/forms-1 and click Save button

Also, please only submit bugs here

**Comment by chalchis** [comment]
sorry I can see
How to apply different positions?
