### ISSUE TITLE
Reset and reload not working with Custom Field 

### ISSUE THREAD

**Issue by Deepam-Singla** [vitmalina/w2ui#1214]
HI Vitali,

i have a form inside popup. which has custom fields. Form has submit and reset buttons. on reset the custom fields are not cleared. also if i close popup nad open again, the inbuilt fields gets reloaded but custom fields are not.  

Thanks in advance

**Comment by mrg2001** [comment]
I see in the demos that Reset button just called form.clear(). I looked up the method and it empties form.record and calls refresh. So, I am not sure what is not working. Can you provide jsFiddle example which illustrates the problem?

**Comment by Deepam-Singla** [comment]
i have custom field type called port in a separate file called customTypes.js. 
[here](https://jsfiddle.net/h7abh4fg/1/) is the code for that.  https://jsfiddle.net/h7abh4fg/1/ . i have a form inside a popup like [this](http://w2ui.com/web/demos/#!forms/forms-8) and i am using custom type there in popup. There when i click on reset it does not reset the custom field. Same goes for when i close the popup and reopen, it reloads the previous values of inbuilt fields not the custom field
now i am using the last release 1.4.3 and i am not allowed to use github release.

**Comment by mrg2001** [comment]
Please create an example where I can see the problem (jsfiddle or your own server). I do not have time troubleshooting custom problems. I am closing it for now. Reopen when you have example.
