### ISSUE TITLE
Grid Summary Records appear as regular records with w2ui version 1.5.x

### ISSUE THREAD

**Issue by ppearson111** [vitmalina/w2ui#1216]
Think I've found a problem with grid summary records... I'm using the w2ui 1.5.x (nightly) files from github and trying to create summary records just causes "regular" rows to be added to the grid.  

This fiddle uses w2ui 1.4.3, you can click the button to add summary records.  Try updating the fiddle to use w2ui 1.5.x versions (both .js and .css files) and notice that summary records are broken.

http://jsfiddle.net/ppearson/sbr39mrb/

-P

**Comment by mrg2001** [comment]
In 1.5.x all custom properties that were in record object were moved intow2ui object. So, instead of
```
records: [
   { field: 1, summary: true }  
]
```
do
```
records: [
   { field: 1, w2ui: { summary: true }}
]
```

moved rec.summary, rec.style, rec.editable -> into rec.w2ui.summary, rec.w2ui.style, rec.w2ui.editable

**Comment by ppearson111** [comment]
Thank you for the quick response!  I updated my test code with this change -- the summary records now appear like they should; however, when I try and an additional summary when I click a button, it seems to overwrite the existing summary records and then only 1 summary row is displayed.  See this fiddle:

http://jsfiddle.net/ppearson/c24L45v4/1/
