### ISSUE TITLE
Enum search and LIKE condition

### ISSUE THREAD

**Issue by pidlo** [vitmalina/w2ui#1222]
Hello, 
I use search in w2ui grid when the column type is enum and list. 
When I want to search something LIKE 48% I must change the column  type to string and then I lose wonderful features which I have in enum or list.
How can I use advantages of both column types ?

**Comment by mrg2001** [comment]
I do not understand your questions. Can you please create jsFiddle to illustrate the problem.

**Comment by mpf82** [comment]
Closing issue: no response
