### ISSUE TITLE
Form Load Does not Connect W2UI Controls

### ISSUE THREAD

**Issue by daggetlover** [vitmalina/w2ui#1224]
With a W2UI form, using load method to load html that has input controls tied to the W2UI form fields. The steps are to render the form, then load the html and then to request the w2ui field data. All gets loaded but the html w2ui controls gets reset to empty controls.

onOpen: function (event) {  
	event.onComplete = function () {
                w2ui['formLOAD'].recid = calledRecId;
                $('#w2ui-popup #formLOAD').w2render('layoutLOAD');
                w2ui.layoutLOAD.content('main', w2ui.formLOAD);
                w2ui['layoutLOAD'].load('main', '/LoadManagement/web/load/view?recid='+calledRecId);
                w2ui.formLOAD.request();
        }
 }

**Comment by mrg2001** [comment]
Here are the steps, 
1. Load HTML with $.get() and save it into a variable
2. Create form and set formHTML to that variable
3. Render form into layout.content('main', w2ui.form_name)

Please submit only bugs here.

**Comment by daggetlover** [comment]
I am sorry but this does not work for drop lists. When the form is complete, the drop lists remain blank even though the data returned is of the json format {id:'key1',text:'key1'}. The form does have the separately load HTML and the form drop lists do work. For some reason the drop lists do not get set to the data record values.

I am pulling my hair out on this one.

Chris

------ Original Message ------

**Comment by mrg2001** [comment]
Please create a jsFiddle to illustrate the problem.

**Comment by daggetlover** [comment]
I have tried that.

I need to reload formHTML and form data at the same time. There is a timing issue. If the formHTML is not loaded (complete not just requested) then the reload of the form data will not connect the form data with the formHTML.

Any suggestions?

Chris



------ Original Message ------

**Comment by mrg2001** [comment]
use callbacks.
