### ISSUE TITLE
Overwrites twitter bootstrap

### ISSUE THREAD

**Issue by CThuleHansen** [vitmalina/w2ui#1227]
Hi.

I am using twitter bootstrap, but I am interested in using some features from w2ui.
However including the css ruins the twitter bootstrap styling.
Example: 
Here is an example with w2ui css included: [With w2uicss](https://jsfiddle.net/we528jw0/1/)
And here is one without: [Without w2ui](https://jsfiddle.net/we528jw0/2/)

Is there any way to fix this?

**Comment by mpf82** [comment]
You should consider using w2ui 1.5, because 1.5 introcuces a w2ui- namepsace for CSS elements.

https://jsfiddle.net/we528jw0/3/

**Comment by CThuleHansen** [comment]
Any knowledge of when this version will be out?

**Comment by mpf82** [comment]
@CThuleHansen There's no official release date yet, but the current 1.5 master branch is pretty stable.

For an official reply about the release date see mrg2001's post in this thread: https://github.com/vitmalina/w2ui/issues/1173

**Comment by CThuleHansen** [comment]
Thank you. Using master branch - works like a charm.
Except a strange shade, but I will create that it a different task.
