### ISSUE TITLE
the position of list field's triangle mark is not correct

### ISSUE THREAD

**Issue by btmanm** [vitmalina/w2ui#1230]
http://jsfiddle.net/syhh6b73/2/

click the toggle button

![image](https://cloud.githubusercontent.com/assets/3347318/15007703/85b8dd82-120d-11e6-80bc-88d587e85fa2.png)

**Comment by mpf82** [comment]
This is already fixed in 1.5

http://jsfiddle.net/syhh6b73/3/

**Comment by mrg2001** [comment]
In 1.4.x instead of resize, call refresh and it will work too. see http://jsfiddle.net/syhh6b73/6/
