### ISSUE TITLE
Proposals for sidebar contextmenu

### ISSUE THREAD

**Issue by CThuleHansen** [vitmalina/w2ui#1232]
**Proposal: Differentiated context menues for different items.**
Specify on node level which contextmenu to use.

**Proposal: Add contextmenu to grouped nodes.**
To solve it I have inserted the contextmenu html: 
I found the html generation to be the problem along with the contextmenu trigger.
Contextmenu:
https://github.com/vitmalina/w2ui/blob/5dae9ab5d4f0265fa20717c1c17bb21841512512/src/w2sidebar.js#L641
I just removed `nd.group ||`

HTML generation:
https://github.com/vitmalina/w2ui/blob/5dae9ab5d4f0265fa20717c1c17bb21841512512/src/w2sidebar.js#L846

I inserted this line: 
`                        '        oncontextmenu="w2ui[\''+ obj.name +'\'].contextMenu(\''+ nd.id +'\', event)"'+ `
so the html for group node now looks like:
```
                    html =
                        '<div class="w2ui-node-group" id="node_'+ nd.id +'"'+
                        '        onclick="w2ui[\''+ obj.name +'\'].toggle(\''+ nd.id +'\')"'+
                        '        onmouseout="jQuery(this).find(\'span:nth-child(1)\').css(\'color\', \'transparent\')" '+
                        '        oncontextmenu="w2ui[\''+ obj.name +'\'].contextMenu(\''+ nd.id +'\', event)"'+ //TODO: MANUALLY INSERTED LINE
                        '        onmouseover="jQuery(this).find(\'span:nth-child(1)\').css(\'color\', \'inherit\')">'+
                        ((nd.groupShowHide && nd.collapsible) ? '<span>'+ (!nd.hidden && nd.expanded ? w2utils.lang('Hide') : w2utils.lang('Show')) +'</span>' : '<span></span>') +
                        (typeof nd.text == 'function' ? nd.text.call(obj, nd) : '<span>'+ nd.text +'</span>') +
                        '</div>'+
                        '<div class="w2ui-node-sub" id="node_'+ nd.id +'_sub" style="'+ nd.style +';'+ (!nd.hidden && nd.expanded ? '' : 'display: none;') +'"></div>';
```

**Comment by mrg2001** [comment]
You already can have different context menu for different sidebar items. If you attach to onContextMenu in the event object there will be id of the item user clicked on and then you can modify menu property to show items that you want.

As for context menu for grouped elements, I am not sure. What about disabled elements, do you think they need context menu too?

**Comment by CThuleHansen** [comment]
Ah yes, obviously.. I use that event already. Thank you.

About disabled elements, I think it should be possible. By default it would make sense that it is turned off, but I do not see any reason for not making it possible to turn it on.

**Comment by mrg2001** [comment]
Fixed, see commit.
