### ISSUE TITLE
All Fields placeholder translation

### ISSUE THREAD

**Issue by dalsword** [vitmalina/w2ui#1236]
Can you also include "All Fields" placeholder within localization? Multisearch input field placeholder does not seem to be affected and remains as "All Fields" still...

Thanks...

**Comment by mrg2001** [comment]
I checked w2grid.js and all instances I see for all fields have
```js
w2utils.lang('All Fields');
```
Please create a jsFiddle with your issue

**Comment by dalsword** [comment]
<!DOCTYPE html>
    <html>

    <head>

    <link rel="stylesheet" type="text/css" href="http://w2ui.com/src/w2ui-1.4.3.min.css" />
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script type="text/javascript" src="http://w2ui.com/src/w2ui-1.4.3.min.js"></script>


    </head>
    <body>
    <div id='w' style='width: 100%; height: 400px;'>
    </div>
    </body>

    <script>
    $(function () {

    w2utils.locale('https://raw.githubusercontent.com/vitmalina/w2ui/master/src/locale/ru-ru.json');
    // creating w2 grid object
    $('#w').w2grid({
    name: 'grid',
    show: {
    toolbar: true,
    footer: true,
    toolbarSave: false,
    toolbarReload: false,
    toolbarColumns: false
    },
    multiSearch: true,

    columns: [
    {
    field: 'recid',
    caption: 'ID',
    size: '30px',
    sortable: true,
    resizable: true
    },
    {
    field: 'goodId',
    caption: 'HAM MADDE ID',
    size: '30%',
    sortable: true,
    resizable: true
    }
    ]

    });
    //w2ui['grid'].refresh();
    });
    </script>
    </html>

THE OUTPUT:

![The output](http://postimg.org/image/fry2va8u9/)
