### ISSUE TITLE
Grid disable checkbox but only if rows has a specific value in a column

### ISSUE THREAD

**Issue by spizzi77** [vitmalina/w2ui#1237]
Hy All,
I have a grid that load in a bootstrap modal after a php call, i have selectColumn true but i want that onLoad if there is a specific value in the row for a specific column only that checkbox of that row must be disabled.
I tried in onLoad and i can recover the id of row the value of the row column but i can't disabled the check box, the logic is that on onload i recover the xhr.responseText i do a jquery loop for each record and inside the loop if the value of the column of that row is PIPPO(EXAMPLE) i must disable the checkbox...But the problem is that the checkbox remain always enabled.Can someone help me?If you want the code i can paste it here....

**Comment by mrg2001** [comment]
Please submit only bugs here. All questions to w2ui.com or stackoverflow. 

The best way would be to attach to onRefresh, and in onComplete loop update DOM with jQuery.
