### ISSUE TITLE
Resizable Popup feature

### ISSUE THREAD

**Issue by Evgsurf** [vitmalina/w2ui#1243]
User can't resize any popups.
Maybe it is ok with conception "Popup is popup", but it is not very good with "Popup is window".
Also it will be very good feature to have several popups at the same time. (Several opened windows)

**Comment by mpf82** [comment]
I doubt that @vitmalina has changed his opinion on multiple popups. See #671 and #283.

Maybe you should look at a different popup component (and render your w2ui form/grid/... there).

Or ask user ratones (  #671 ) how his fork is coming along, maybe he has something that can be pushed to the current master.

Or implement it yourself and create a pull request.

**Comment by mrg2001** [comment]
Agree with @mpf82. If you need another popup, you can still open a browser window.
