### ISSUE TITLE
left click checkboxes in w2ui 1.5.x

### ISSUE THREAD

**Issue by spizzi77** [vitmalina/w2ui#1244]
Hy All, 
I notify that in the last version 1.5.X, in grid, if there are checkboxes, clicking on the record with left click of the mouse it's ok and the checkbox will be checked but clicking on the checkbox(so not the record) with left click the checkbox can't be selected,it's like there is a preventDefault, is it right in this way?
Again my compliments for this usefull library.Good WE

**Comment by mrg2001** [comment]
I do not understand what you mean. Can you please rephrase?

**Comment by spizzi77** [comment]
Hi mrg2001, 
In the grid with checkboxes enabled, if i click with the mouse on the rectangle of the checkboxes, for sure click with the left button of the mouse(the usual click for the checkbox), the checkbox will not selected instead if i click on the record the checkbox will be selected.
I don't use JS fiddle and i don't know how to put in JSFiddle a PHP call so i uploaded an example on my site where i use w2ui 1.5.x nightly...You can see that if you click on the checkbox with the mouse (left click)the checkbox will not selected....I notified that if i put multiSelect true after it works with the left click of the mouse, maybe something is going to conflict.
But if you click with the right button of the mouse over the checkbox it will work, but usually the selection is done with the left click.
Here's the example
Regards

http://fractalcosmo.com/MvcWebLog/paginaDefault.php

**Comment by mrg2001** [comment]
Yes, there was a bug. Will recompile JS a bit later tonight, then you can download
