### ISSUE TITLE
remove searchAll field from grid toolbar issue

### ISSUE THREAD

**Issue by samoilis** [vitmalina/w2ui#1246]
(with last w2ui 5.x)

how to remove searchAll field from grid toolbar

I use show:{searchAll: false} in configuration options but no luck

https://jsfiddle.net/samoilis/ouxje8b3/1/

**Comment by spizzi77** [comment]
http://w2ui.com/web/docs/w2grid.multiSearch

**Comment by mpf82** [comment]
`grid.show.toolbarInput = false`

https://jsfiddle.net/ouxje8b3/3/

**Comment by samoilis** [comment]
@mpf82 works!

Thank you for your answers
