### ISSUE TITLE
Removing the required mark from field

### ISSUE THREAD

**Issue by ZlatyChlapec** [vitmalina/w2ui#1250]
I found [this example](http://jsfiddle.net/rLLwhrbj/1/) somewhere in comments on your website and I tried editing it accordingly to #206 but required mark stays.

[frist try](http://jsfiddle.net/rLLwhrbj/14/)
[second try](http://jsfiddle.net/rLLwhrbj/15/)

Is there any way how to deal with this?

**Comment by mpf82** [comment]
The "marker" mentioned in #206 is a w2tag with the content "Required field" that you can see if you click the Save button in [this demo](http://w2ui.com/web/demos/#!forms/forms-3)

I am assuming you want to get rid of the asterisk ( * ) , which you can not do this way.

**Comment by ZlatyChlapec** [comment]
Oh yes I am sorry. Yes I want to get rid of asterisk. So is there anyway how to do it without refreshing the whole form?

**Comment by mpf82** [comment]
You could handle the adding / removing of the `w2ui-required` CSS class yourself. 

See `$(field.el).parent().parent().addClass('w2ui-required');` in the JS file. I'm not sure which element you need in the JQuery selector.

**Comment by ZlatyChlapec** [comment]
Yes that worked. Thanks. Would be cool if there would be some "cleaner way" via w2ui though.
