### ISSUE TITLE
Unnecessary resize() and refresh() in form.render() ?!?

### ISSUE THREAD

**Issue by mpf82** [vitmalina/w2ui#1251]
In w2form.js (current master) we have this line in the form's render function:

`setTimeout(function () { obj.resize(); obj.refresh(); }, 150); // need timer because resize is on timer` 

I don't think it's really necessary, since we're already doing a resize() 12 lines above the mentioned line, and we're also already doing a request()/refresh() 7 lines above this line, too.

I've removed the line in my local environment and could not see any side effects.

On the contrary, removing this line also removes a possible bug/problem, where the form would try to refresh the fields, even though the form is already destroyed - which occasionally could happen in our application, if the user is browsing through the records really fast (in which case we destroy and re-create the form in fast succession - before the mentioned timer executes - causing a lot of console messages, such as: `ERROR: Cannot associate field "email" with html control. Make sure html control exists with the same name.`).

Before I create a pull request to remove this line, I would like some feedback, as to why it's there in the first place.

If we keep this line, we should somehow prevent the timer from executing if the form is destroyed in the meantime.

**Comment by valq7711** [comment]
You're right - there is something [wrong](https://github.com/vitmalina/w2ui/pull/1238)! If you're sure that `refresh()` is unnecessary  after `request()` I vote for your variant

**Comment by mrg2001** [comment]
submit your pull request, please

**Comment by mpf82** [comment]
PR created: https://github.com/vitmalina/w2ui/pull/1254
