### ISSUE TITLE
Context menu in Firefox is misplaced

### ISSUE THREAD

**Issue by dpmcmlxxvi** [vitmalina/w2ui#1253]
When you right click on a sidebar item in Firefox the location of the menu is far off to the right. 

See an example [here](http://dpmcmlxxvi.github.io/olexp/docs/web/demos.html). On the third layout sidebar, right click on an item and the menu is displaced to the right. The problem does not appear in Chrome or IE.

The issue occurs with v1.4.3. When the latest master is used the problem is replaced by a collapsing sidebar reported in issue [#1252](https://github.com/vitmalina/w2ui/issues/1252). So it is not clear if the problem still exists in the current master and just being masked.

**Comment by vitmalina** [comment]
I fixed #1252. Can you please check. 

As for original issue, it needs to be fixed in 1.4.x branch.

**Comment by dpmcmlxxvi** [comment]
The problem is fixed in the master. Thanks for the update. Closing issue.
