### ISSUE TITLE
SubGrid in w2ui 1.5 expand more that one records not display well

### ISSUE THREAD

**Issue by spizzi77** [vitmalina/w2ui#1255]
Hy All,
Thanks to fix the left click on the checkbox in the grid, btw i work a lot with grid and sub grid and i notified a different behaviour from 1.4 and 1.5.
When i expand 2 records or more(3-4) the sub-grid isn't responsive and aligned with all the rest of the table.
The example in the 1.4.3 that is ok is this... http://w2ui.com/web/demos/#!grid/grid-7
But here you can see what happen if you expand 3-4 records.
Thanks again and good evening.

http://fractalcosmo.com/MvcWebLog/paginaDefault.php

**Comment by mpf82** [comment]
As I understand it, sub-grid support is dropped in 1.5, even though you can get it to work (we're using it in 1.5, though I had to fiddle with the CSS to get it working correctly).

https://github.com/vitmalina/w2ui/issues/1160

**Comment by spizzi77** [comment]
Hy mpf82,
I saw the example, but if i understand well in the future the subgrid could be like the tree grid plugin?
Sincerely this make me really thoughtful to use the 1.4 version, because i used the tree grid plugin like as fancytree, but this really it's not manageable in the server side with a large quantities of data.
I need of grids that can have 2000 records and 1000 2000 records of sub grids...So create the child inside every recid can be very hard to manage the arrays.
We create all server side.
At this point the solution better can be like as JqWidgets manage the sub grid, but really with tree grid is hard in server side...with large quantitaties of sub grids.
I think the actual method of 1.4.3 is good, also to make server ajax call, maybe can be insert in client a function like as the "groupable" in jqWidgetTreeGrid.
Can you say me please as you modified the css to work in 1.5 like as in 1.4?
Regards

**Comment by spizzi77** [comment]
I was re-thinking about this topic now, when i decided to use the w2ui 1.4.3 version it was accepted with entusiasm, because the basic logic is this:
When i load the page the client make ONE php call to the DB and gets the basic data to compose the basic grid, after when i expand a row clicking on the row plus(+) icon i do another call to the DB and i gets the "children", but this what means?
This means that if i have a DB with 500 thousand records and sub-records i don't call the DB to gets all the data in ONE time and create the array-json but the amount of data is generated if the operator need to see determinate records and only in that case.
For example i have a grid with 10 records, so, when i load page i call the DB to get ONLY 10 records, after the operator need to expand one of these 10 records(these records has 1000 sub records-clients, for example, so the DB in total has 10010 records) so the operator expand a row and in that case call the DB and get for example 1000 records in sub grid...In this way the amount of data processing is really minus that call one time the DB and get all the 10 records with respective 1000 sub records, because if we must generate recid and children in server side this mean that i must call the DB to get ALL the 10010 records and after i must create a json in a structure recid{1,name:pippo , children{}}, so the amount of data generated is more that in the version 1.4 and sincerely IMHO is also superfluous because the operator that use the software hardly need to expand all the records.
There are differents problems using the structure of tree grid children, and one of the most important is the amount of data generated from the DB.Because many companies pays in base the amount of data generated.So the better solution is to generated minor data possible and generate it ONLY if necessary.So i think that if the future version will change i must continue to use 1.4.3 version.
Thanks and regards

**Comment by mpf82** [comment]
onExpand : function(event) {
            $('#' + event.box_id).css({ margin: '0px', padding: '0px', width: '100%' }).animate({ height: '300px' }, 0);
        }

This should do the trick. Unfortunately, as you can see, the height is fixed - but you probably could improve the code snippet and calculate the actual height, using the sub-grid's row height and total record count.

Or feel free to fix the grid's behaviour in the current master. I'm sure @vitmalina does not mind that the sub grid remains in 1.5, as long as he does not need to maintain it (it's basically still working, only the expanded height is somewhat broken).

**Comment by spizzi77** [comment]
Hi mpf82,
Thanks this is a good solution, few lines of code to get the right result, it's what i prefer ;)
Can be see here http://fractalcosmo.com/MvcWebLog/paginaDefault.php
Btw it's ok fixed height for me because there is the vertical scroll and if the table has 2000 records in subgrid it's ok put a fixed height.
It's ok, in this way the grid is navigable, btw in the future version i hope remain the compatibility with the old versions, otherwise we can click the records of the basic grid and at the click we can open a modal with the subgrid....At the end we find a solution. :)
I keep the topic open if someone want to comment but for me it's closed.
Thanks again
