### ISSUE TITLE
w2field of type "enum" not working as expected in 1.5

### ISSUE THREAD

**Issue by mpf82** [vitmalina/w2ui#1259]
I've noticed that the enum field in the [demo](http://w2ui.com/web/docs/form/fields-enum) will remove enum items from the drop-down menu that are already in the input.

However, in 1.5 this seems no longer to be working.

Furthermore searching does not work either in 1.5

You can reproduce the issue in this fiddle: https://jsfiddle.net/z0fngmac/2/

The problem still exists if you use `items:  [ { id: 'ENUM_1', text: 'enum item 1' }, { id: 'ENUM_2', text: 'enum item 2' }, { id: 'ENUM_3', text: 'enum item 3' }, ]` instead of `items:  [ 'ENUM_1','ENUM_2','ENUM_3',  ]`

**Comment by mendozada** [comment]
Hi mike, please i need your help to save the date entries and list in mysql. I am a rookie and I tried but can not get to make it work. I could send my code. please ask you to help me or tell me where to look. my mail mendozada@gmail.com

**Comment by mpf82** [comment]
@mendozada I'm assuming you've got the PHP server example running? 
I don't know your date format for the column and I don't know your DB layout, but you should be able to log the data you receive on the server side and then figure out how to transform your w2ui date to a form that fits your database.

As for list items, they might be sent as a JSON object in the form `{ "id": "some id", "text": "some text" }`, again, you should just log what your server receives and then transform the data accordingly.

If you've got a specific programming problem, you should create a question on http://stackoverflow.com/

**Comment by mendozada** [comment]
Hi Mike, thank you very much for your interest and answer. If it is correct I'm using the server / php example. From mysql properly bring the json data and position on the grid.

I pass this link with example files. 
[https://mega.nz/#!8kUnSLiL](url)

The problem is when I want to save.

Of course many many thanks

**Comment by mpf82** [comment]
PR has been merged, closing issue.
