### ISSUE TITLE
w2alert, w2poupup etc. do not show up in an electron app

### ISSUE THREAD

**Issue by bwl21** [vitmalina/w2ui#1265]
I try to wrap my app in http://electron.atom.io/.

I got it running, but w2alert, w2poput etc do not show up.

I could prepare the w2ui demos with electron if you wish.

**Comment by vitmalina** [comment]
If you can please post a sample how I can repeat it. I will look into it.

**Comment by mrg2001** [comment]
If you can please post a sample how I can repeat it. I will look into it.

**Comment by bwl21** [comment]
wtf ... I created an app with w2ui demo and it shows the popups. But my app does not.

So I need to dig into this by myself. I'll post the result here.

If somewone wants to run w2ui with electron. It is important to have the first and the last script tag as follows. See also https://github.com/electron/electron/issues/254 and  http://stackoverflow.com/questions/32621988/electron-jquery-is-not-defined

```html
<pre><!DOCTYPE html>
<html>
<head>
    <title>w2ui Demos</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <script>if (typeof module === 'object') {window.module = module; module = undefined;}</script>

    <link rel="stylesheet" type="text/css" media="screen" href="../dist/w2ui.min.css" id="mainCSS" /> 
    <link rel="stylesheet" type="text/css" media="screen" href="../libs/font-awesome/font-awesome.css" /> 
    <link rel="stylesheet" type="text/css" media="screen" href="index.css"/>
    <script type="text/javascript" src="../libs/jquery/jquery-2.1.4.min.js"></script>
    <script type="text/javascript" src="../dist/w2ui.js"></script>
    <script type="text/javascript" src="code-mirror.js"></script>
    <script type="text/javascript" src="index.js"></script>
    <script>if (window.module) module = window.module;</script> 

</head>
<body>
    <div id="main_layout"></div>
</body>
</html>
</pre>
```

**Comment by bwl21** [comment]
I investigated the difference and I found that I was using jquery-1.11.1.min.js which did work well when I ran the app in Chrome ...

... a bit suspicious

I now try to upgrade to Jquery 3.0.0

**Comment by bwl21** [comment]
I have tried with jquery 3.0.0 and also integrated the migration plugin. It appears to work and the migration plugin does not yield a message.

I propose that the doucumentation makes statements about the prerequisites ...

**Comment by vitmalina** [comment]
Added in readme file

**Comment by mrg2001** [comment]
Added in readme file
