### ISSUE TITLE
Problems with w2field of type 'select' (w2ui 1.5)

### ISSUE THREAD

**Issue by mpf82** [vitmalina/w2ui#1268]
**First issue:**

The field can not be used as stand-alone. This may be related to #1225

It can however be used inside a w2form.

**Second issue:**

Rendering a w2field of type 'select' in a w2form looks really bad in Internet Explorer (tested with IE 11.0.9). 
No issues in Chrome and Firefox.

Both problems can be seen in this fiddle: https://jsfiddle.net/hn9qzs8a/

This is how it looks in IE:

![2016-06-17 14_11_53-edit fiddle - jsfiddle - internet explorer](https://cloud.githubusercontent.com/assets/10152404/16150104/8081db0c-3495-11e6-98c4-4269cda0faf9.png)

This is how it looks in Chrome:

![2016-06-17 14_14_09-edit fiddle - jsfiddle](https://cloud.githubusercontent.com/assets/10152404/16150166/dccd2948-3495-11e6-9246-6606d098628f.png)

**Comment by vitmalina** [comment]
@mpf82, can you please send me your email address to vitamlina@gmail.com

**Comment by mpf82** [comment]
I've sent you an email to the adress on your github profile - the one you just posted seems to have a typo.

Cheers :)

**Comment by mpf82** [comment]
Updated fiddle: https://jsfiddle.net/gjkd0a39/ - fiddle works with w2ui 2.0, issue still exists.

Noone is using IE anymore, so I guess the second issue can be ignored. Select field looks fine in Edge.

**Comment by mpf82** [comment]
Closing this issue, since simply not all field types that are available in a w2form are available as w2field.
