### ISSUE TITLE
perform an action after the list is changed in multi select

### ISSUE THREAD

**Issue by anubhaw2091** [vitmalina/w2ui#1271]
Which part is exactly called when we change the selected list? Either by adding or deleting any items.
I populated the list through my server.

I want to call a function whenever a new item has been selected or deleted.

And how do I get the list of items in the selected list.

I tried getting the selected list by doing `var temp=$('#enum').data('selected');`

**Comment by mrg2001** [comment]
Aren't those questions covered here http://w2ui.com/web/docs/form/fields-enum?

**Comment by anubhaw2091** [comment]
When am trying to get the selected data using the option`onAdd` am not getting the latest value. If there are 3 items selected, am only getting 1st and 2nd. If only 1st item is selected, am getting null value. I even posted a comment over there. 

If I add a simple alert in `onAdd` option, am getting the alert before the item is being added in the list. That's why am asking which option should I select to perform an action after an addition/deletion is done in the list.

Link : http://w2ui.com/web/docs/form/fields-enum#comment-2123771841

**Comment by mrg2001** [comment]
You should check it in onComplete part. See http://w2ui.com/web/docs/utils/events
