### ISSUE TITLE
w2ui Grid "set" method using .extend which does an object merge instead of a replace

### ISSUE THREAD

**Issue by sjmosdef** [vitmalina/w2ui#1276]
I have a fairly complex JSON object representing a row in the grid. In that row object there is a list of objects (we'll call it array) which can change based on the state of the row. If the array length starts out at 3, is updated to 6, and then attempted to be updated back to 3. The grid "set" method will leave all distinct objects in memory because instead of overwriting the object it's using .extend which does an object merge effectively unioning the arrays. This drove me insane for a few hours. Why use .extend instead of just updating the data? Is my object too complex to be "kept in the grid"?

Current:
if (isSummary) {
    $.extend(true, this.summary[ind], record);
} else {
    $.extend(true, this.records[ind], record);
}

Proposed:
if (isSummary) {
    this.summary[ind] = record;
} else {
    this.records[ind] = record;
}

**Comment by mpf82** [comment]
[The documentation](http://w2ui.com/web/docs/w2grid.set) of `w2grid.set` clearly states that the record is extended.

Why don't you just update the record directly and refresh the grid?

    grid.record[index] = new_record;
    grid.refresh();

**Comment by mrg2001** [comment]
@mpf82 is right and gives you a fix. However, I think extend should be used as then I can just update a single field in the record, not entire record.
