### ISSUE TITLE
grid.stateSave(): !localStorage is insufficient to test localStorage capabilities

### ISSUE THREAD

**Issue by vandernorth** [vitmalina/w2ui#1282]
The existence of the localStorage object does not mean that it actually works (http://chrisberkhout.com/blog/localstorage-errors/). 

A setItem or getItem should either be try/catched or prechecked with a script like modernizr (could use this script: https://github.com/Modernizr/Modernizr/blob/master/feature-detects/storage/localstorage.js)

I was facing this error because of a wrongfully configured IE10 workstation (http://stackoverflow.com/questions/13102116/access-denied-for-localstorage-in-ie10)

The grid wouldn't load because the stateSave functions throws an error. Could you either try/catch the whole function body or add some capabilities check on startup?

```javascript
stateSave: function (returnOnly) {
            if (!localStorage) return null;
            var state = {
                columns     : [],
                show        : $.extend({}, this.show),
                last        : {
```

Thanks in advance.

**Comment by vandernorth** [comment]
Counts for all localStorage tests (e.g. in stateReset, stateRestore) but the one in stateSave is more annoying because that's run when initializing.

**Comment by mrg2001** [comment]
I generally try to avoid large try...catch blocks, since it often masks the problems. If  I change to 
```js
if (!localStorage || typeof localStorage.setItem != 'function') return null;
```
Can you test if it works in your use case?

**Comment by vandernorth** [comment]
Then I would suggest a check somewhere in w2utils.  w2utils.hasLocalstorage() or something containing  test like the one Modernizr uses.

Your example will not work because setItem will be a function, only when you call it it will throw an error.

**Comment by mpf82** [comment]
I second a `w2utils.hasLocalstorage` (as boolean). Modernizr has a MIT license, so copying the function to w2utils isn't a problem.
As stated in the linked sources, even if localStorage is available by the browser and even if localStorage.setItem is a function, browser or system settings may still block the successful execution.

My sugestion is to implement a `w2utils.testLocalstorage()` function (returning a boolean), and also a `w2utils.hasLocalstorage` static boolean, that will be initialized with the function's return value, so the test has only to be executed once when w2util loads.
