### ISSUE TITLE
Toolbar Clear Search Event

### ISSUE THREAD

**Issue by anselal** [vitmalina/w2ui#1285]
I see that when I press on the "Clear Search" button, it calls `onclick="var obj = w2ui['images']; obj.searchReset();`
Is there an event for this ? When not, can you add one ?
I want to extend its function. How can I do it ?

**Comment by mpf82** [comment]
`searchReset()` will trigger a `search` event (onSearch) with property `reset: true`.

**Comment by anselal** [comment]
@mpf82 Good to know. And how do I extend the onSearch event instead of overriding it ?
