### ISSUE TITLE
Search type time not considered in section "if there are search fields loop thru them" 

### ISSUE THREAD

**Issue by rcpacheco** [vitmalina/w2ui#1287]
In the search function of the grid, it would be nice to have also a condition for the time fields, like this: 

|| (search.type == 'time' && w2utils.isTime(value))

Thanks a lot

**Comment by mpf82** [comment]
I created a PR: #1290

By the way, it's not hard to create a pull request yourself ;)

**Comment by rcpacheco** [comment]
Thanks a lot. I was not sure if it was out for a reason.
