### ISSUE TITLE
question: layout panel + tabs + form +grid.  Grid sometimes don't show on tab change.

### ISSUE THREAD

**Issue by rcpacheco** [vitmalina/w2ui#1292]
I haye a layout and in its main panel I defined two tabs. The panel has as sole content a div where, after creating the layout, I add the form corresponding the default tab, using the content command. On render I add the grid and add its records. That allows me to display initially.
I added a onClick event to the tabs where, every time a tab is selected its corresponding form is created and since inside each form there is a grid, I also add the grid. Since the grid was not showing, I add it using a setTimeout of 50. I'm tempted to make the time even greater because some times the grid does not display at all. Nertheless I thinks that there may be a simple and nicer way. Thanks a lot

**Comment by mrg2001** [comment]
Please submit only bugs here. All questions to comments on w2ui.com or stackoverflow.com
