### ISSUE TITLE
Error message button does not get the focus.

### ISSUE THREAD

**Issue by rcpacheco** [vitmalina/w2ui#1295]
I have a form to submit new values for a grid. After processing, if there is an error with the new data, the server sends an error message and status error. w2ui properly takes that message and displays it. Nevertheless the message button does not get the focus. Therefore the focus remain in the accept button of the form and if the user hits enter, additional error messages are displayed. The ideal would be to have the error message get the focus and on enter just close. The version used is 1.5 commit 796500f.
A gif of the problem and the debugging session is available at :
![messageerror](https://cloud.githubusercontent.com/assets/845725/16848990/0953d862-49be-11e6-833e-278f8f4a3206.gif)

As you can see, the w2utils.message.call receives the proper box, nevertheless, the onOpen function event does not has that property, therefore is unable trigger the focus change.

**Comment by Connum** [comment]
Can you provide a jsfiddle with this problem?

**Comment by mpf82** [comment]
Problem still exists in current master: http://jsfiddle.net/eaf60w47/

**Comment by mpf82** [comment]
This seems to be fixed in current master: http://jsfiddle.net/dqb489n3/
