### ISSUE TITLE
w2grid editable date column format issue

### ISSUE THREAD

**Issue by ghost** [vitmalina/w2ui#1296]
Created a fiddle for you:
http://jsfiddle.net/bbc79m1z/22/

I have an editable date column in my grid. I would like it to be displayed in "dd.mm.yyyy" format. Whenever the grid is initialized with records, everything looks ok. But when ever I double click and try to change a date to "27.04.2016" from the popup window : 
- The mask is displayed as "m/d/y". I would assume it to be "dd.mm.yyyy".
- I am not able to select "27.04.2016". The cell becomes blank. 

What would be your suggestion to fix the problem?

**Comment by mpf82** [comment]
This seems to be fixed in 1.5

Updated fiddle: http://jsfiddle.net/bbc79m1z/23/

I'd say, this issue can be closed.

**Comment by mpf82** [comment]
Closing issue: seems to be fixed, no response
