### ISSUE TITLE
(1.5) Issue with record.w2ui.class for entire row

### ISSUE THREAD

**Issue by marcoas** [vitmalina/w2ui#1297]
Hi

With nigthly code, this code work fine, for painting entire row :
`foo.records[0].w2ui.style = 'background-color: red !important';`

But this one not... only paint first cell
`foo.records[1].w2ui.class = 'xxxx';`

**Comment by mpf82** [comment]
> But this one not... only paint first cell

That's probably because your first column is `frozen`, right?

Anyway, I fixed it and submitted a PR.

**Comment by marcoas** [comment]
You're right !
