### ISSUE TITLE
(1.5) Form Fields without Label, it's possible ?

### ISSUE THREAD

**Issue by marcoas** [vitmalina/w2ui#1300]
I need to leave blank, the LABEL in some FIELDS

I can do that?

**Comment by mpf82** [comment]
Simply set `caption` to a single space (or a non-breaking space).

`html: { caption: " ", ...}`  or `html: { caption: "&nbsp;", ...}`

**Comment by marcoas** [comment]
I thought there was a special configuration for it

OK, Thanks
