### ISSUE TITLE
Dude: Get Form List Option Selected ID

### ISSUE THREAD

**Issue by marcoas** [vitmalina/w2ui#1301]
Hi

I have this partial form code

    { "field":"campo_email",
      "type":"list",
      "options": { 
        "items": [ 
          { "id":1, "text":"Bar"},
          { "id":2, "text":"Foo"} ] } },

And click in option "FOO"

Then I need get ID from selected option, (for validations)....

**How I can do that?**

    $('#campo_email').val();

return "FOO", But I need it your ID : "2"

Thanks

**Comment by oscarmartins** [comment]
Hi,

Try it: w2ui.form.get('campo_email').options.items[1]

example:

http://jsfiddle.net/bx1z7xxk/

**Comment by mpf82** [comment]
`var id = $("#campo_email").data("selected").id;` (for 1.4 and 1.5)
`var id = $("#campo_email").w2field().get().id;` (for 1.5)

Please use [stackoverflow](http://stackoverflow.com/search?tab=newest&q=w2ui) for questions and tag them with `w2ui`.
Use the github issues for bugs.

**Comment by marcoas** [comment]
Ok. Thank You , but .... A little complex right?
The FIELD could have some internal mechanism to obtain , more simply , that data
