### ISSUE TITLE
grid.url return AJAX error - 403 Forbidden

### ISSUE THREAD

**Issue by mickyva** [vitmalina/w2ui#1302]
![testgridurl](https://cloud.githubusercontent.com/assets/20609034/17076709/7f90bc46-50b9-11e6-9bc4-e1f8b5b3c31b.png)
Occur with every php script in version 1.5 when w2grid.url si setting, w2form.url return no error (work great).
Also version 1.4.3 work great.

This is check  result for w2ui-master/server/php/index.php

**Comment by mendozada** [comment]
Mickyva el users.php es para usar con la version 1.43 , en la version 1.5 cambia la devolucion del CMD, 
fijate en el ejemplo que pusiste abajo a la derecha que el CMD = "get" y dentro del users.php tenes "get-records",  para la version 1.5 tenes que crear un nuevo recolector de datos . 
Yo uso la version 1.43 . Saludos.

**Comment by mickyva** [comment]
Is just a probem about ajax call...
php script called via $.ajax from w2form.url is ok (php script was load, executed and return records) instead php script called via $.ajax from w2grid.url return error (php was not load due to false 403 error.. **attention I use same php script for every two .url**) .
I try to investigate around $.ajax function in w2ui.js without success...

**Comment by mrg2001** [comment]
From the screenshot it is clear that the problem is on the server side. It returns no data. Grid merely shows error that data is incorrect.

**Comment by mickyva** [comment]
yes, no data becouse at script call occurs 403 Forbidden error.
Same script called from W2FORM return data becouse error 403 Forbidden not occur..

**Comment by mrg2001** [comment]
Please note that 403 cannot be an error on the client side, but server side. w2ui is purely client side library.

**Comment by akspnd** [comment]
![c](https://user-images.githubusercontent.com/46956505/51595367-96bc9f00-1f1c-11e9-8a01-d9a580c0782c.jpg)
![d](https://user-images.githubusercontent.com/46956505/51595368-96bc9f00-1f1c-11e9-8f33-e18911869454.jpg)
![e](https://user-images.githubusercontent.com/46956505/51595369-96bc9f00-1f1c-11e9-8278-a14cfab35378.jpg)
![f](https://user-images.githubusercontent.com/46956505/51595370-97553580-1f1c-11e9-86af-4b461f2c117d.jpg)
