### ISSUE TITLE
Add jQuery dependency in description

### ISSUE THREAD

**Issue by englishextra** [vitmalina/w2ui#1304]
So that devs wont get misled

```
no dependencies except jQuery
```
IS a dependency!

**Comment by mrg2001** [comment]
Where do you want me to add it?

**Comment by mpf82** [comment]
englishextra is probably referring to the [readme.md](https://github.com/vitmalina/w2ui/blob/master/readme.md), where it says:

> The library has a small footprint and no dependencies except jQuery (1.8+).

So maybe he wants you to add **Dependencies** as a new heading to the readme?

**Comment by englishextra** [comment]
Just rephrasing this:

```
The library has a small footprint and no dependencies except jQuery (1.8+).
```

to this

```
The library has only jQuery (1.8+) as dependency.
```

In that case it would be less misleading

@mpf82 

I meant GitHub top input discription with link.

@mrg2001 and @vitmalina and other aliases - it's  no longer year 2009. Everything is blatant. The reputation is gained hard and lost easily at once.

**Comment by mpf82** [comment]
> I meant GitHub top input discription with link.

The github front page is created from the readme file.

> @mrg2001 and @vitmalina and @mpf82 and other aliases

This is my one and only github account.

**Comment by englishextra** [comment]
@mpf82 Can you read?

```
I meant GitHub top input discription with link.
```

As for fake account of yours - thats a clear thing.

**Comment by mpf82** [comment]
> As for the fake account of yours - that's a clear thing.

Clear thing? Enlighten me! Maybe we both can have a good laugh at the end =)

**Comment by mrg2001** [comment]
Much ado about nothing :)
