### ISSUE TITLE
render date don't work correctly on 1.5

### ISSUE THREAD

**Issue by natxocc** [vitmalina/w2ui#1305]
If I have date data from mysql like "yyyy-mm-dd", on 1.5, when I try to format to "dd/mm/yyyy" always I have "01/01/1970"
On 1.4.3 works correctly:
fiddle on 1.5
http://jsfiddle.net/natxocc/4rf5kjyp/8/
fiddle on 1.4.3
http://jsfiddle.net/natxocc/bssda0f5/3/

**Comment by mmcfts** [comment]
Hi,
change the definition of the date field to this:
{ field: 'date', caption: 'date', size: '90px', sortable: true, resizable: true, **render: 'date'**, style: 'text-align: right',
                editable: { type: 'date' } 
            }
and your code works as expected in 1.5.

The problem was that you defined to render the date field as :dd/mm/yyyy.

**Comment by mrg2001** [comment]
The best way to work with dates is to use UNIX timestamp (number of seconds or sometimes milliseconds since 1 Jan 1970). Otherwise due to various formatting issues it is a mess. If you supply to a grid an integer in the date field, it will properly format it and render in specified format. Otherwise, it just uses Date() object to convert and depending on user settings it might or might not work correctly because it uses localized settings. However, if it is a unix timestamp, it always works.

**Comment by natxocc** [comment]
ISO standard from mysql is "yyyy-mm-dd", so the problem is 1.5 version don't work correctly to convert data as 1.4 does.
I think that as 1.4 version, 1.5 need to work the same and is not the situation.

If there is any option to convert correctly from mysql standard, could someone show a jsfiddle with 1.5 version?
Thanks for all.

**Comment by mrg2001** [comment]
Open JS console and execute this command, 
```
new Date('1975-05-01')
```
You will see it will return
```
Wed Apr 30 1975 17:00:00 GMT-0700 (PDT)
```

Which mean JS does not follow ISO standard

**Comment by natxocc** [comment]
Thanks for explain it so well.
The problem is I don't know how to read date from mysql as mysal always uses yyyy-mm-dd
In 1.4 version was not problem, but on 1.5 I can't translate yyyy-mm-dd to dd/mm/yyyy

**Comment by natxocc** [comment]
Well, finally I have found a solution using render function to formatDate() during render:
http://jsfiddle.net/natxocc/4rf5kjyp/9/

On 1.4 version this function was implented correctly on render in "getCellHTML" function, when you use default format like "dd/mm/yyyy", "mm/dd/yyyy", "yyyy/mm/dd" or anything else, but on 1.5 this function is removed and I can understand why.

As I said before, the problem is not the original date, but the formatDate use that is not correctly implented on 1.5 on defaults renders on type "date".

**Comment by mrg2001** [comment]
Dates are pain! It is also painful to work with timezones, day-light-saving, etc. So, the best way I found is to work with unix time. It is a number of seconds (sometimes milliseconds) from Jan 1, 1970 in GMT. If you have unix time, it is easy to convert it in any language and db. For example in MySQL you can convert your output to unix time with UNIX_TIMESTAMP function. Similar functions exist in all DBs (and programming languages)

```
SELECT UNIX_TIMESTAMP(STR_TO_DATE('Apr 15 2012 12:00AM', '%M %d %Y %h:%i%p'))
```

in JS you can feed unix time to Date object and it will construct correct date.

```
new Date(123456789)
```

If you feed this to a grid and use render: 'date' or render: 'datetime' it will properly format it.

Good luck!

**Comment by vercoutt** [comment]
Hi! I have found the bug seeing the difference beetween date, datetime and time render.

for date en datetime : w2utils.formatDate(dt, params)   >>>dt is boolean test
for time w2utils.formatDate(value, params)  >>>value is value to convert

...

'date': function (value, params) {
        if (params === '') params = w2utils.settings.dateFormat;
        if (value == null || value === 0 || value === '') return '';
        var dt = w2utils.isDateTime(value, params, true);
        if (dt === false) dt = w2utils.isDate(value, params, true);
        return '<span title="'+ value +'">' + w2utils.formatDate(dt, params) + '</span>';
    },

    'datetime': function (value, params) {
        if (params === '') params = w2utils.settings.datetimeFormat;
        if (value == null || value === 0 || value === '') return '';
        var dt = w2utils.isDateTime(value, params, true);
        if (dt === false) dt = w2utils.isDate(value, params, true);
        return '<span title="'+ value +'">' + w2utils.formatDateTime(dt, params) + '</span>';
    },

    'time': function (value, params) {
        if (params === '') params = w2utils.settings.timeFormat;
        if (params === 'h12') params = 'hh:mi pm';
        if (params === 'h24') params = 'h24:mi';
        if (value == null || value === 0 || value === '') return '';
        var dt = w2utils.isDateTime(value, params, true);
        if (dt === false) dt = w2utils.isDate(value, params, true);
        return '<span title="'+ value +'">' + w2utils.formatTime(value, params) + '</span>';
    },

**Comment by quillaja** [comment]
> Open JS console and execute this command,
> 
> ```
> new Date('1975-05-01')
> ```
> 
> You will see it will return
> 
> ```
> Wed Apr 30 1975 17:00:00 GMT-0700 (PDT)
> ```
> 
> Which mean JS does not follow ISO standard

I think that means it is working correctly. `1975-05-01 00:00:00+00:00` (UTC) is `1975-04-30 17:00:00-07:00` (PDT). Obviously Date() is assuming UTC if no timezone is specified. It also works fine when a timezone is specified: `new Date('2009-09-24T00:00:00-07:00')
` shows `Thu Sep 24 2009 00:00:00 GMT-0700 (Pacific Daylight Time)` as expected.
