### ISSUE TITLE
Date & Time: Blocked days demo does not function as documented

### ISSUE THREAD

**Issue by nexushoratio** [vitmalina/w2ui#1306]
http://w2ui.com/web/demos/#!fields/fields-2

Happens with FF 47, Chrome 52 and Chromium 51.

Example reads:  (12,13,14 of current month are blocked)

But the only date that seems to be blocked is the 14th.

**Comment by mpf82** [comment]
This was just a little issue in the demo, where the year for the 12th and 13th was hardcoded to 2014.

Created PR #1697 to fix this.

Feel free to close the issue.

**Comment by mendozada** [comment]
Hi, I'm trying to make it go, but the blockade of the days does not work for me.

[https://jsfiddle.net/gq3jhLmo/3/](https://jsfiddle.net/gq3jhLmo/3/)

**Comment by mpf82** [comment]
@mendozada w2fields and fields in a w2form do not (always) take the same parameters. For fields in a w2form, most parameters must be encapsulated in an ``options`` property: https://jsfiddle.net/gq3jhLmo/4/

**Comment by mpf82** [comment]
Closing issue: resolved, no further response
