### ISSUE TITLE
Add custom color to w2ui cell

### ISSUE THREAD

**Issue by anubhaw2091** [vitmalina/w2ui#1309]
Well, to add color to a cell in grid is very straight forward with the given documentation. 

If the records are hard coded then we can add the colors like this 

```
records: [
            { recid: 1, fname: 'Jane', lname: 'Doe', email: 'jdoe@gmail.com', sdate: 384052483664, style: {3:'background-color: yellow; color: white;'}}           
        ]
```

But when am loading data from server, I need to add style there only( In my case php). I am trying a lot for correct way to add styles to cells and row, from server, but am not getting the desired result.

Could anyone tell me how to color a cell based on my rule(which is defined in the backend)?

Question on stackoverflow  : [SO Question](http://stackoverflow.com/questions/38696758/add-custom-color-to-w2ui-cell-grid)

**Comment by chalchis** [comment]
actually to fill the grid from the server
You must return a json

An example
```
foreach(........)
{
//Nota: array para mostrar en el grid	
								$datos_horarios[] = array(
											'recid' 		=> $contador,
											'keyhordocent' 	=> $id_hrdocent_segura,//id horario asignado al docente
											'keymatdocent'	=> $id_matdocent_segura,//id de asignacion de materia al docente
											'icon'			=> '<i class="fa fa-clock-o" style="font-size: 18px; color: #9CC834"></i>',//icono
											'numdia'		=> $valHor['hor_numdia'],//numero del día
											'nomdia'		=> $valHor['hor_dia'],//nom del día
											'hrentrada'		=> $valHor['hor_entrada'],//hora de entrada
											'hrsalida'		=> $valHor['hor_salida'],//hora de salida
											'tipofirm'		=> $valHor['hor_firma'],//tipo de firma
											'grupo'			=> $valHor['acad_mat_grado'].$valHor['mat_docent_grupo'],//grado y grupo											
											'descmat'		=> ($alias_materia == 'NDF') ? $valHor['acad_mat_nom'] : $alias_materia.' [alias]',//desc de la materia											
											'fechaplica'	=> ($valHor['hor_aplicar'] === '0000-00-00') ? '' : $valHor['hor_aplicar'],//fecha de aplicacion
											'fechfinaliza'	=> ($valHor['hor_finaliza'] === '0000-00-00') ? '' : $valHor['hor_finaliza'],//fecha de finalizacion
											'nivel'			=> $valHor['acad_niv_abrev'],//siglas nivel
											'plan'			=> $valHor['acad_plan_nom'],//desc plan academico											
											'style'			=> $firma_horario
										);
}
```
return json

```
//formato json predeterminao para los grid de componentes w2ui
						$resultadoJson = array(
											'status_respuesta' 	=> 'true',//$estatus_respuesta,	
											'status'			=> 'success',//parametro del grid									
		                					'mensaje_respuesta' => 'correcto',
											'total' 			=> $total_horas,//parametro del grid																		
											'header' 			=> 'Horas registradas ('.$total_horas.')',//parametro del grid
											'records' 			=> $datos_horarios,//parametro del grid	
											'proceso_respuesta' => $this->input->post('proceso_grid', TRUE),//saber que proceso se realizo
											'records_materias'	=> $datos_materias//lista de materias asignadas al docente									
										);
						
						echo json_encode($resultadoJson);
```

![2016-08-02_10h45_22](https://cloud.githubusercontent.com/assets/2206648/17335098/60b82d6c-589e-11e6-9751-1559f2f5e852.png)

**Comment by anubhaw2091** [comment]
Hi chalchis,

Thanks for the reply.

If i add
```
$a='background-color: #C2F5B4';
.....
$row['style']=$a;
```
The rows get colored. That's fine. But how do I set the cell color?

If I try adding this 

`$a=' 5 :background-color: #C2F5B4';`

to change the color of cell. it doesn't work. 

And how do I change the color of the row as well a cell of that row? For example. 1st row as green color and 3rd cell as red color.

Thanks.

**Comment by chalchis** [comment]
$a='background-color: #C2F5B4';
.....
$row[5]['style']=$a;

Note: you should know the column number in the grid

**Comment by chalchis** [comment]
upss no es true try this

'style' => array('3' => 'background-color: #C2F5B4;')//fila pintada

**Comment by anubhaw2091** [comment]
Thanks chalchis. 
This is working. 

Another question, can I change the color of the row as well as the cell?

1st row=> All green color , but 3rd column of the 1st row => red.

Is it possible?

**Comment by chalchis** [comment]
actually I have not tried
but you may consider an option
paint the row or
paint the desired cells

**Comment by anubhaw2091** [comment]
I tried individually, both are working. But when I try to combine them, it doesn't work.
I'll fiddle with it more.

Thanks again.

**Comment by chalchis** [comment]
greetings, do not forget to close the topic

**Comment by thewithest** [comment]
Hi, i'm currently having the same problem but i can't find any acceptable result, could you please submit your code ?
Thanks!
