### ISSUE TITLE
Column with min size disappears after resize

### ISSUE THREAD

**Issue by elaw01887** [vitmalina/w2ui#1310]
I was working with the grid today and found an interesting issue.  Create a simple grid, and for (at least?) one column specify a "size" (in px or %) and a "min" (in px) that's less than the size (in my test I used "275px" as size and "150px" as min).  Run the page, and using the mouse, resize the column in question to it's minimum size.  Sometimes after you do this the column will disappear, and if it doesn't, click the header of that or any other column to sort it, *then* the column you resized will disappear.

I've tested this in IE11 and Firefox 46 (both on Windows 7) and the problem occurs in both browsers.

You can see an example here: http://www.thelawsplace.com/gridresizebugtest.html

Load the page, resize the "desc" column to the smallest it will go, click any column header to sort and... the "desc" column disappears completely.  If you pop up the "columns" menu it still thinks "desc" is showing, and deselecting/reselecting it does some strange things but doesn't make the column reappear.

Test file attached - just rename from ".txt" to ".html".

[GridResizeBugTest.html.txt](https://github.com/vitmalina/w2ui/files/400536/GridResizeBugTest.html.txt)

**Comment by mpf82** [comment]
I can confirm that this also happens in w2ui 1.5

http://jsfiddle.net/4ht034xu/

**Comment by elaw01887** [comment]
Thanks!  I guess I should have read the docs more closely, it does say the min and max values are "in px".

**Comment by mrg2001** [comment]
Applied suggested change
