### ISSUE TITLE
SelectAll when start grid

### ISSUE THREAD

**Issue by mendozada** [vitmalina/w2ui#1311]
Hi, I get the starting grid with all selected records .

[http://jsfiddle.net/bx1z7xxk/9/](url)

how to do to show me in 2 rows in field Observa

Thank you.

**Comment by mpf82** [comment]
http://jsfiddle.net/bx1z7xxk/10/

**Comment by mendozada** [comment]
hi mike , thanks for your quick response . this example is exactly what I was looking for .
But when I take my program and habilito url: ' users.php ' , it does not work .

it can be?

**Comment by chalchis** [comment]
if you use a URL where the data came
you must use the load event running at the end of the load on the grid

```
//event end load data
        w2ui['name_grid'].on('load', function(target, eventData)
        {
            eventData.onComplete = function()
            {
                  console.log('end load');
             }

       });
```

**Comment by mendozada** [comment]
Gerardo,  Muchas Gracias, me anduvo perfecto , era lo que necesitaba. 
Ahora te consulto, si existe alguna manera de que en el campo observacion puedan hacer 2 o mas renglones.
Desde ya muchas Gracias.  
Diego.

**Comment by mrg2001** [comment]
Height of the record is a constant. It is needed for virtual scroll. I assume this request is closed.
