### ISSUE TITLE
w2uigrid get remote data url return in every case forbidden access

### ISSUE THREAD

**Issue by mickyva** [vitmalina/w2ui#1315]
Every request to remote data via w2grid.url return error 403
This not occur when request is made from w2form.url

**Comment by mpf82** [comment]
The problem is on your side.

I'm using w2ui 1.4 and w2ui 1.5 fine, both with grid.url and form.url (backend: python cherrypy server).

**Suggestions:**

- check your server configuration
- check the url you're accessing and how that url is handled on your server
- check what payload you're sending and what the server receives and how you're handling that payload

related: #1302

**Comment by mickyva** [comment]
Thank for your reply, but i think there is a error on version 1.5 in the way w2ui call ajax for w2grid.url (w2form.url work well! but also w2grid 1.4.3)

In the w2ui-master -> server -> php I have modify users.php with new one with this two rows:

$rows = array( recid => "1", userid =>"1", fname => "John", lname =>"Doe", email => "jdoe@mail.com", login => "jdoe", password =>"12345" );
echo json_encode(array(total => 1, page => 0, records => $rows ));

When execute index.php, i get an error as this:
![w2grid403forbidden](https://cloud.githubusercontent.com/assets/20609034/17651314/aad749f8-6264-11e6-8963-aba71dcb48ab.png)

please note console error... users.php was not executed!!!

interesting is in index.php, when load data with w2form.url and same users.php (after only modify records in record) w2form.url return correct data (and load it in edit form)

for that I think is not a server error, no server configuration error, no url access error and not payload sending or receiving error

Can you help me to resolve issue?

**Comment by mrg2001** [comment]
Why does your server return 403 Forbidden?

**Comment by mickyva** [comment]
And why my server (not my, provide from internet service provider) return error only if i call users.php via w2grid.url and don't return error when i call via w2form.url...
If is server error it must be return error in every case!
I suspect is in a way w2grid call users.php

**Comment by mickyva** [comment]
I reply myself
1.4.3 w2grid default dataType transfered to server is "HTTP", 1.5 w2grid is "HTTPJSON".
I resolve the issue with this setting before grid constructor:

w2utils.settings.dataType = 'HTTP';

**Comment by mendozada** [comment]
mickyva , hi, i try with the last example gone up, and change 

w2utils.settings.dataType = 'HTTP';

but it is useless, even not work for me.

Use the version 1.43 and works perfectly

You have some CRUD running 1.5 ??

Greetings.

**Comment by mickyva** [comment]
I have modify index.php around:

<body>
    <div id="users" style="width: 100%; height: 600px;"></div>
</body>
<script>
w2utils.settings.dataType = 'HTTP'; //default 1.5 is HTTPJSON that is more complex...
w2utils.locale('it-it'); // this one is locale language and setting

$(function () {
    // define and render grid
    $('#users').w2grid({
        name    : 'users',

also i have modify users.php near:

switch ($_REQUEST['cmd']) {

    case 'get':  //'get-records': is for 1.4.3 not for 1.5
        $sql  = "SELECT * FROM users
                 WHERE ~search~ ORDER BY ~sort~";
        $res = $w2grid->getRecords($sql, null, $_REQUEST);
        $w2grid->outputJSON($res);
        break;

after that every work well

I notice that there is other little issue in 1.5 grid...
One that is important is in subgrid... the sign "+", when open subgrid, it become disaligne from next record and this make impossible open other subgrid...

some difference also in column header when there is hidden column...
