### ISSUE TITLE
http://w2ui.com/web/ database connection problem

### ISSUE THREAD

**Issue by dalsword** [vitmalina/w2ui#1316]
There is a warning thrown by PHP:

Warning: pg_connect(): Unable to connect to PostgreSQL server: could not connect to server: Connection refused Is the server running on host "localhost" and accepting TCP/IP connections on port 5432? could not connect to server: Connection refused Is the server running on host "localhost" and accepting TCP/IP connections on port 5432? in /var/www/web20boom/web/libs/phpDB.php on line 50 ERROR: Cannot connect to postgres.

**Comment by mrg2001** [comment]
FIxed
