### ISSUE TITLE
Is there a way to filter the results in grid as you type in the 'search' input without having to press the 'Enter' key?

### ISSUE THREAD

**Issue by javaprog8432** [vitmalina/w2ui#1317]

**Comment by martin-pabst** [comment]
Here's a quick solution with jQuery (div with grid inside has id="libraryBorrowerList"):

`$('#libraryBorrowerList').find('.w2ui-search-all').keyup(function (event) {
                    this.onchange();
                });`

**Comment by javaprog8432** [comment]
I ended up doing something like below because I am using a custom input instead of the toolbar input. What do you think? Works pretty well for me.


```
$('#customer_search').on('input keyup', function () {
        var text = this.value.toLowerCase();        
        w2ui['gridCustomersLeft'].search([{field: 'cust_nm',value: text, operator: 'contains'}]);           
});
```
