### ISSUE TITLE
tabs not working

### ISSUE THREAD

**Issue by ramin786** [vitmalina/w2ui#1319]
I'm trying to write a practice program http://medicalschoolmemoirs.com/ccs/ccs.htm the tabs will not work after I click on other tabs...what could be the problem? 

The tabs will load by itself but after I click on Order Sheet again the grid content disappears

**Comment by mpf82** [comment]
The tabs do exactly what you told them to do:

    $('#myorders').w2tabs({
        name     : 'myorders',
        active     : 'tab1',
        tabs    : [
            { id: 'tab1', caption: 'Order Sheet' },
            { id: 'tab2', caption: 'Progress Notes' },
            { id: 'tab3', caption: 'Vital Signs' },
            { id: 'tab4', caption: 'Lab Reports' },
            { id: 'tab5', caption: 'Imaging' },
            { id: 'tab6', caption: 'Other Tests' },
            { id: 'tab7', caption: 'Treatment Record' }
        ],
        onClick: function (event) {
            $('#ordertabs').html(event.target); // <-- replaces the DIV content
        }
    });

Your grid is inside `#ordertabs`, so once you click on any tab, you remove the grid from the DOM.

**Comment by ramin786** [comment]
So how do i bring back the grids on the assigned tabs?

**Comment by chalchis** [comment]
personally
I like tabs in layout
and within the layout load
grids

version 1.4 w2ui

http://w2ui.com/web/demos/#!layout/layout-8

![tabs_layout](https://cloud.githubusercontent.com/assets/2206648/17880958/9c8c5ce0-68c6-11e6-8780-cf62cbbf63f3.gif)

**Comment by chalchis** [comment]
you can use render to return load
every time you change tab

**Comment by ramin786** [comment]
I got it, it works thanks guys.

What I'm trying to do is create a test simulation where you have a table in the main page under the Tab Order Sheet. Where the user presses the "Order" button on the bottom and in the pop up box in the textarea, the user types in certain lab tests names per line and presses confirm. The lab tests entered per line are then searched in a table list and gives the user the ability to select from a pool of tests and adds it to the table in the main page.

I'm trying to transfer variable chosen in the popup box to be transferred to the main page.

**Comment by mrg2001** [comment]
Based on the last response. I assume tabs are working. Cloging the issue.
