### ISSUE TITLE
Loading formHTML and record data followed by a refresh will not tie the new html to the form fields

### ISSUE THREAD

**Issue by daggetlover** [vitmalina/w2ui#1321]
Loading formHTML and record data followed by a refresh will not tie the new html to the form fields.

```
        w2ui['formLEAD'].formHTML = calledviewHtml;
        w2ui['formLEAD'].record = calledviewJson;
        w2ui['layout'].content('right', calledviewHtml);
        w2ui['formLEAD'].refresh();
```

No console errors but the form record is not loaded.

**Comment by mpf82** [comment]
It looks as if you're only assigning the HTML to your layout, not the form itself.

See http://w2ui.com/web/demos/#!combo/combo-2 for an example where a grid and a form are used as layout content.

If it still does not work, please create a [jsfiddle](http://jsfiddle.net/)

**Comment by mrg2001** [comment]
I assume calledviewHtml is not empty. If it is assigned tot he form, you can render the form into a layout like this
```js
w2ui['layout'].content('right', w2ui['formLEAD']);
``

**Comment by mpf82** [comment]
Closing issue: no response, no reproducer
