### ISSUE TITLE
[Feature Request] Color search type for w2grid

### ISSUE THREAD

**Issue by mpf82** [vitmalina/w2ui#1323]
It would be nice to have a new search type "color" in `w2grid.operators` to be used in [grid.searches](http://w2ui.com/web/docs/w2grid.searches)

That way, there could be a color picker (see color field in [this demo](http://w2ui.com/web/demos/#!fields/fields-1)) in the Search popup (the popup that opens when you click the `Search...` button in [this demo](http://w2ui.com/web/demos/#!grid/grid-3))

Currently, "color" is mapped to "text" in `w2grid.operatorsMap`, but if you use "color" as a type in searches, no field is displayed in the search popup.

**Example:** 

    grid.searches = [
        { "type": "color", "field": "f_color", "caption": "Color" }
    ]
    --> no field at all in the Search popup

**Workaround:**

    grid.searches = [
        { "type": "hex", "field": "f_color", "caption": "Color" }
    ]
    --> works, but a color picker would be awesome instead of a normal text field

**Comment by mrg2001** [comment]
Got it. Please see if it works for you.

**Comment by mpf82** [comment]
Awesome! 

Thanks for the fast implementation, it works (almost) perfectly =)

Minor issue: the last selected color is remembered in the field, however the small "color-preview" DIV has no background color if you close and open the Search popup.

I've attached a screenshot for better understanding:

![2016-08-31 10_13_10-nemetris web template - v0 5](https://cloud.githubusercontent.com/assets/10152404/18121208/c074b38e-6f63-11e6-9e09-3a0879f9d70b.png)

**Comment by mpf82** [comment]
This is broken in the current w2ui sources (not talking about rc1, but the actual /src files).

The color preview is no longer visible (that's already been working in an older w2ui 1.5 build I'm currently using - seems to go broken along the way), and once you click search, the selected HEX value gets replaced with `<div><i style="color: #FEE599;" class="fa fa-fw fa-square"></i>FEE599</div>` once you open the search again.

**Comment by mrg2001** [comment]
I did some updates, please see if it fixes all the issues mentioend

**Comment by mpf82** [comment]
Thanks for the fast response.

What's working:

1. after selecting a color from the "squares", I can see a preview color (fixed `no preview` issue).
2. In the "slider" selection, while changing the slider and/or when moving the mouse above with clicked left mouse button around the "gradient area", the preview updates nicely (fixed `#INFINITYINFINITY-INFINITY` issue)

What's not working:

1. chaging from "square" to "slider" selection still closes both the color picker AND the search popup
2. when opening the search again after successfully searching for a color, the content of the color input still reads `<div><i style="color: #E0DE51;" class="fa fa-fw fa-square"></i>E0DE51</div>` and no preview is shown. **Expected behaviour**: the content reads `E0DE51` and a preview is shown
3. when in "slider" selection, the mouse-up event on the slider or the "gradient area", will immediately close the color picker AND the search dialog, so you have no chance to actually search - because when you open the search again, the color input is empty

**Comment by mpf82** [comment]
The problem still exists in the latest source files.
