### ISSUE TITLE
Nested layouts not lockable

### ISSUE THREAD

**Issue by sonovice** [vitmalina/w2ui#1324]
It is not possible to lock nested layouts with the `w2layout.lock(...)` command.

Demo: http://jsfiddle.net/3qys3wL2/

**Comment by mpf82** [comment]
Seems to be a timing issue. It works if you lock the panel with a `setTimeout()`.

I have also updated your fiddle to use the latest 1.5 sources.

http://jsfiddle.net/3qys3wL2/2/

**Comment by mpf82** [comment]
If your issue is resolved, please close the thread.
