### ISSUE TITLE
Would like to have a field based custom validation

### ISSUE THREAD

**Issue by bwl21** [vitmalina/w2ui#1325]
I would like to implement specific field based validations. I was looking if I could register a regular expression there.

I could do it in the onValidation handler but I could not find, how to report the problems in the same way as w2ui builtin validation does.

**Comment by mrg2001** [comment]
Here is an example how you can report errors back
```js
onValidate: function(event) {
    var date1 = w2utils.isDate(this.record.date1, null, true); // returns JS Date object
    var date2 = w2utils.isDate(this.record.date2, null, true); // returns JS Date object
    if (date1 > date2) {
        event.errors.push({
            field: this.get('date1'),
            error: 'Registration date should be prior to submission date'
        });
    }
```

**Comment by mrg2001** [comment]
I have added it to the docs in 1.5 branch
