### ISSUE TITLE
Scrolling in search view of Grid 

### ISSUE THREAD

**Issue by Mimu1988** [vitmalina/w2ui#1326]
Hello.
There is an display issue with the search types 'list' and 'enum' in the advanced search of the grid. If u have lots of searches defined (i got about 20), so that the displayed search div will get a vertical scrollbar and u scroll inside it then the arrow icon of the dropdownmenu stays in position and does not move. The same is with the type 'enum' there the textbox wil stay on the same position.
![w2ui_issue_type_enum](https://cloud.githubusercontent.com/assets/20539382/18305113/46afceca-74e6-11e6-8e91-3f1490e51f85.png)
![w2ui_issue_type_list](https://cloud.githubusercontent.com/assets/20539382/18305114/46b70460-74e6-11e6-95ec-c0ccc3051769.png)

**Comment by mpf82** [comment]
I could not reproduce this in my local environment, running the latest 1.5 sources.

![2016-09-07 16_51_48-nemetris web template - v0 5](https://cloud.githubusercontent.com/assets/10152404/18316603/8d1c917e-751b-11e6-8d2f-7af6151f07ff.png)

Which version are you using?

Can you create a jsfiddle with the latest sources (you can link them from [here](https://github.com/vitmalina/w2ui/tree/master/dist)) to reproduce the problem?

**Comment by Mimu1988** [comment]
Hello. 

I´m currently using version 1.4.2. 
I will try it with the latest version and will report if i get this issue with version 1.5.

**Comment by Mimu1988** [comment]
Hello.

I now tested it with version 1.5.0 and there the issue doesn´t exist anymore.
Thx
