### ISSUE TITLE
W2grid error on resize after destroy

### ISSUE THREAD

**Issue by JacobMonono** [vitmalina/w2ui#1328]
I have noticed an error which is cumbersome to replicate but easy to spot and fix, so trust me on this. 
Under certain circumstances I have noticed an error originating from the "tmp_resize" function
```
Uncaught TypeError: Cannot read property 'resize' of undefined
```
This uncaught  exception occurs when a w2grid is rendered twice or more, destroyed, and after the window is resized but before the w2grid is recreated. This often does not have any affect since the grid is not rendered, but could interfere with other listeners and clog up the console log. You can see why the error occurs in the section which seemingly tries to prevent this error from occurring.
```
this.tmp_resize = function (event) { w2ui[obj.name].resize(); };
$(window).off('resize', this.tmp_resize).on('resize', this.tmp_resize);
```
This block tries to prevent multiple listeners from being registered. You can see the intent to remove previous listeners first, however since `this.tmp_resize` is already redefined it will silently fail to remove anything.  You could either remove the listener ahead of time, but only if it already exists, or if you are feeling more adventurous you could look at how this is done since I could never figure out why tmp_resize is needed as opposed to using the resize function directly.

**Comment by MarioDelgadoSr** [comment]
This is also a problem with layout. Fiddle reproduction against current master distribution:

http://jsfiddle.net/UberMario/x9thombj/4/

To reproduce, run the fiddle, manually resize the browser and then check console for error messages.

**Comment by vitmalina** [comment]
Fixed in latest commit. jsFiddle works now.

**Comment by MarioDelgadoSr** [comment]
Thanks for quick fix.
