### ISSUE TITLE
Grid with AutoLoad and summary record

### ISSUE THREAD

**Issue by Mimu1988** [vitmalina/w2ui#1331]
Hello.
I´m having an issue with autoLoad and summary records.
If the client makes a request with any searchData i will attach a summary record with the given searchData. 
The first request is ok, but when the user scrolls down so that the next 100 rows will be loaded the grid says "Your remote data source record count has changed, reloading from the first record."
Without the summary record the autoLoad of the grid works without any problem.

I´m using Version 1.5.
Hope you can help.

**Comment by mrg2001** [comment]
The message  "Your remote data source record count has changed, reloading from the first record." will come if subsequent request returned different total then the original request. You might need to check on that. I think summary records should be not included in total. Also, they do not get removed (I think).

You can also return -1 as total. In this case the grid will assume the total number is unknown and will pull as long as server returns something.

Hope it helps.

**Comment by Mimu1988** [comment]
Hey.

Thx for your reply, but i could already solve the problem.
I had the summary records in the records array. I now moved them into the summary array and by this  the problem didn´t occur anymore.

Thx
