### ISSUE TITLE
Event click drop list in tool bar

### ISSUE THREAD

**Issue by mendozada** [vitmalina/w2ui#1333]
hello all, someone could help me with this issue.
I need to run the click event of the list you are in a tolbar
Attached is an example.
[http://jsfiddle.net/kjzyh43k/3/](url)
Greetings.

**Comment by mpf82** [comment]
Implement an onChange event handler on the field directly: http://jsfiddle.net/kjzyh43k/4/

**Comment by mendozada** [comment]
many thanks mike this is exactly needed them.
