### ISSUE TITLE
Column Separator Disappearing at Certain Widths & Zoom Levels on Firefox

### ISSUE THREAD

**Issue by James7xx** [vitmalina/w2ui#1336]
### **Problem:**
- It is possible to make the grid table's column separator disappear when resizing the column on **Mozilla Firefox**.
- Using the 'table cell' element's width as the measurement any multiple of 10 will result in the lines disappearing (This multiple can seem to change depending on the table - this example is for the demo table).
- The 'zoom level' of Firefox must be less than or equal to 90%.

### **Reproduction:**
1.  Make sure to use Firefox for the test.
2.  Find a table with column resize enabled. The default grid demo is suitable for this purpose (http://w2ui.com/web/demos/#!grid/grid-21).
3.  Resize the page size to 90% (CTRL + Minus key).
4.  Drag one of the columns carefully and slowly in order to more easily reproduce and observe the disappearance. If you drag the ID column the smallest size it can go to is 20px; at 22px the column will disappear and again at 32px repeating this pattern.

![dragging_column](https://cloud.githubusercontent.com/assets/11196156/18746005/cd2b16d0-80bc-11e6-9abb-2ea70fc12848.gif)

**Comment by karjac14** [comment]
Tried the link on my Firefox, columns lines were not disappearing. Have you tried with other PC?

**Comment by James7xx** [comment]
Hello Karjac, Sorry for the delay in getting back.

I am pretty certain this is not an issue with the operating system. I have reproduced this issue on the following OS's:
- Windows 10
- Windows Server 2012
- Fedora 21

I have also used different versions of Firefox to make sure that this issue wasn't related to a specific Firefox version all returning the same result.

Could you please make sure that you have followed the reproduction steps and if you have then could you supply some system and browser details so we can narrow this issue down.

**Comment by karjac14** [comment]
After following exactly your procedure, yeah its reproducible in FF. 

But why do you have to re-scale it to 90% (CTRL + Minus key)? If you really have to for some reason. Then maybe this is a work around, add this to your grid css, it might solve your problem. But you will see the that when moving the separator it will still shrink a bit because of the 90% rescale.

````td {
    border: 3px solid gray !important;
} ````


I dont think this is a w2ui bug/issue since you are applying external factor (re-scaling). It shouldn't be in here under issues.

**Comment by James7xx** [comment]
Okay, thanks for your time and support. I will close the issue and raise it with Mozilla.
I had a feeling it would be specific to Firefox but thought i would clarify with the source first.
