### ISSUE TITLE
How to display the grid with the subgrids opened initially

### ISSUE THREAD

**Issue by hanyg** [vitmalina/w2ui#1338]
Hello,

I've been using the subgrid feature of the grid and it works just fine. What I am unable to do is figure out how to render the grid with the subgrid sections shown in the open state initially, versus closed, which is the default.

Thanks,
Hany

**Comment by karjac14** [comment]
run this after creating your grid:

`w2ui['grid'].expand(recid);`

**Comment by mrg2001** [comment]
@karjac14 - thanks for the suggestion. I assume it helped. Closing issue.
