### ISSUE TITLE
Is there a way to rollback record

### ISSUE THREAD

**Issue by firstsano** [vitmalina/w2ui#1342]
I have a local storage. Let's assume user changes one field, I catch it on 'onChange' event and I want to reset these changes. Is there an easy way to do it without regenerating grid with local data?

**Comment by mpf82** [comment]
_The following comment relates to version 1.5:_

You can cancel the `onChange` event by setting `event.isCancelled = true;` - that's it.

---

If you need to rollback "previously" changed fields, keep reading:

All changes are stored in `grid.record.w2ui.changes` until `mergeChanges()` is called (Note: `grid.save()` calls `mergeChanges()`).

Until `mergeChanges()` is executed, `grid.record` still holds the **original** values.

To rollback a change, simply delete the entry from `grid.record.w2ui.changes`, e.g. to delete a specific change

> `delete grid.record.w2ui.changes[field_name];`

or rollback all changes with

> `grid.record.w2ui.changes = {};`

You might still have to call `grid.refresh()` afterwards, so the grid updates the displayed values.

**Comment by firstsano** [comment]
Thank you very much!

**Comment by firstsano** [comment]
Though I'm using 1.4 version I got the idea. So I just map through records
```
let unchangedRecords = grid.records.map((item) => {
  delete item.changes;
  return item
});
grid.records = unchangedRecords;
grid.refresh();
```
