### ISSUE TITLE
OnExpand style css bug :  line column, expand column don't expand like body content

### ISSUE THREAD

**Issue by Kirua88** [vitmalina/w2ui#1343]
Hi

There is a bug on line, expand, checkbox columns when i use onExpand event on masterbranch
It seems css are not update like the body, which expand correctly.

**Comment by karjac14** [comment]
There is a work around.

inside the onExpand event, do some css changes to adjust height.

```
var heightIwant = 60;

$('#grid_gridName_frec_'+ event.recid +'_expanded').css({ margin: '0px', padding: '0px', width: '100%', height: heightIwant + 'px' });
```

**Comment by mrg2001** [comment]
In the example http://w2ui.com/web/demos/#!grid/grid-7 it explains that you need to set width, as it is unknown before you expand.

**Comment by Kirua88** [comment]
@karjac14 thx i will try it
I know, the problem is on what @karjac14 said, content expand but not $('#grid_gridName_frec_'+ event.recid +'_expanded')
