### ISSUE TITLE
Unable to hide grid search toolbar in w2ui version 1.5 

### ISSUE THREAD

**Issue by aswzen** [vitmalina/w2ui#1349]
I try to use w2ui 1.5 nightly but in grid i found a bug that i cant disable toolbarSearch,
already to put `toolbarSearch:false` but the tool still appear in grid toolbar

 ```
show: {
            lineNumbers     : true,
            footer          : true,
            header          : true,
            toolbar         : true,
            toolbarColumns  : false,
            toolbarSearch   : false,
            toolbarReload   : false
        },  
```

**Comment by mrg2001** [comment]
show.toolbarSearch = false; // hides search button on the toolbar
show.toolbarInput = false; // hides search input on the toolbar
show.searchAll = false; // hides "All Fields" option in the search dropdown
