### ISSUE TITLE
w2ui 1.5 button hint is not appear in right position 

### ISSUE THREAD

**Issue by aswzen** [vitmalina/w2ui#1350]
Try to put a button in most/corner side of the screen then when you try to hover it the hint **will appear in bad position and trigger the layout scrollbar**, just see the picture below

![BUG](http://i.imgur.com/d53pc5T.jpg)

**Comment by mpf82** [comment]
You can set the toolbar's tooltip position as an array:

> toolbar.tooltip: ['top', 'bottom', 'left', 'right', 'top']

That way, w2ui will try to position the tooltip in the order listed in the array, so it fits on the visible area in the browser.

![2016-10-09 20_24_06-nemetris web template - v1 1](https://cloud.githubusercontent.com/assets/10152404/19222666/62d0d068-8e5e-11e6-93ee-14636ff27a5d.png)

**Comment by mrg2001** [comment]
I have updated toolbar to have ['top', 'left'], so if top one not positioning right, it will do 'left'
