### ISSUE TITLE
w2ui 1.5 grid scrollIntoView not working in reload callback

### ISSUE THREAD

**Issue by aswzen** [vitmalina/w2ui#1352]
I want the grid scroll to row 20 after the grid itself reloaded.
I try with this command but does not work

```
    w2ui['grid_view'].reload(function(){
        w2ui['grid_view'].scrollIntoView(20);
    });
```

and this one is not working too
,

```
        onLoad: function(){
            w2ui['grid_view'].scrollIntoView(20);
        }
```

but when i try to call scrollToView alone its working.

**Comment by mpf82** [comment]
Have you tried to execute your code in the event's `onComplete` callback?

**Comment by mrg2001** [comment]
I have provided a fix. It should work with .reload() function, but as for onLoad, you will need to put it in onComplete clause.
