### ISSUE TITLE
how to use field upload

### ISSUE THREAD

**Issue by mendozada** [vitmalina/w2ui#1356]
hello, how to upload a pdf file to our server using the file field
I have a form and I want you to save me upload the selected file to a specific folder on my server. I use PHP and MySQL.

Someone could help me or tell me where I could investigate.

thank you very much

**Comment by spizzi77** [comment]
I don't understand well the problem because i don't understand if you want control records on the refresh or control records after a modal or popup opening, btw i try to answer you, to loop every records presents in the grid you will do in the refresh method, supponing that in columns field name a row "intestazione" on the refresh you do:

```javascript
    	onRefresh:function(event){
    		event.onComplete= function(event){
    			//eliminiamo il footer-left del tempo che ci mette a recuperare i dati ma lasciamo il footer right del numero righe
    			$('.w2ui-footer-left').hide();
    			records = this.records;

	    			$(records).each(function(event){

                                       intestazione=this.intestazione,
                                         if (intestazione == 'YOURCONTROL'){
                                               alert('present in table');
                                          }
                                });
}}
```

**Comment by mpf82** [comment]
The content of a file field is sent to your server the basically same way as any other field in your form.

Note that a file field will contain an array of JSON with file related info and the file content encoded in base64.

Maybe this helps you:

http://stackoverflow.com/questions/36388200/how-do-i-save-an-image-file-from-json-string-which-contains-the-image-file

**Comment by mendozada** [comment]
Thank you very much Mike, I could make it work,
Now you wonder how you control the max in Mb and the file type before sending it.

Greetings.
