### ISSUE TITLE
I have 3 million records but it doesn't load these many records. How can I get over this problem

### ISSUE THREAD

**Issue by testaccount280390** [vitmalina/w2ui#1357]

**Comment by mpf82** [comment]
w2ui grid supports lazy loading, so you don't need to pull all 3 million records from your DB at once.

IMHO, there's no real-life use-case where you need to display 3 million records at once to a user - instead let the user filter the records and only display those records that match the user's search criteria.

If you still need to load 3 million records at once, your browser might be the limiting factor, not the framework.

**Comment by testaccount280390** [comment]
I did try the w2grid.limit, but its only for remote data. I have a json file which has all the data in it. Hence I am unable to limit how much data to show

**Comment by testaccount280390** [comment]
Yes you are right. The browser will be a limiting factor no matter what.

**Comment by mrg2001** [comment]
If you add all records to the grid, the grid will only render what is in the current viewpoint. If you scroll, it will rerender the viewpoint.
