### ISSUE TITLE
drag and drop support for two separate grids

### ISSUE THREAD

**Issue by elfwine** [vitmalina/w2ui#1359]
Any way how to implement table(grid)'s row drag to another table(grid)?
I have grid on the left panel and another grid on the main panel. 
I have to drag the selected rows from left panel and drop it to the main panel's grid. 
I tried to use jquery UI drag and drop but every time I drag grid's row, it selecting other rows of the same grid.

I'm using w2ui version 1.4.3.
Any help is much appreciated, 

Thanks,

**Comment by relitodea** [comment]
Do you have a solution here? We are trying to solve the same problem...

**Comment by aadrian** [comment]
Here's an example moving rows from one grid to another, by clicking the rows
http://w2ui.com/web/demos/#!grid/grid-19
That example is not using drag and drop, but it does what you mention is it might be a starting point.

**Comment by elfwine** [comment]
@relitodea 
I modified the code to cater my project's requirement. I have solved this problem but I don't know if it's same with your problem. I'll try to recreate it with simple example and post it here.

**Comment by elfwine** [comment]
@relitodea 
Here's a grid draggable demo. I used the grid demo 19 file and modified the w2ui-1.4.3.js to support draggable row, then declare the draggable function. Also just added an is-dragover style. 
Sorry I couldn't make a fiddler for this as I do not know where to put the modified js.

I hope this one helps. ;)

[GridDraggableDemo.zip](https://github.com/vitmalina/w2ui/files/650639/GridDraggableDemo.zip)

**Comment by aadrian** [comment]
> Sorry I couldn't make a fiddler for this as I do not know where to put the modified js.

Fork the W2UI GitHub repo, commit your changes, and than reference your new URL from the Fiddle.

**Comment by relitodea** [comment]
great solution - thank you for your help.
