### ISSUE TITLE
Click on selected row remove the row selection

### ISSUE THREAD

**Issue by eliavmaman** [vitmalina/w2ui#1362]
Why is that happening?

**Comment by eliavmaman** [comment]
line 2601 : recEl.removeClass('w2ui-selected').removeData('selected');

**Comment by mrg2001** [comment]
This is default and intended behavior. One click on the record selects it, another click on the same record removes selection. Also, click and drag will select multiple records (as well as shift + click, etc). 

You can customize this behavior if you catch onUnselect event and check if record is selected, then cancel this event by calling event.preventDefault(). It should be just a few lines of code.

**Comment by eliavmaman** [comment]
10x will try that

**Comment by eliavmaman** [comment]
well it's works partialy, now after implement
 ```
onUnselect: function(event) {
                       var sel = this.getSelection();
                    if (sel) {
                        event.preventDefault();
                    }
                } 
```

the grid behave as a multi select;
what m i doing wrong?

**Comment by eliavmaman** [comment]
the problem is because the unselect called before the click and with the 
```
event.preventDefault();
```
the grid prevent from any of the selection...
whats funny is that the onSelect event doesnt hold any data of the new selected row.
I'm totally confused

**Comment by mrg2001** [comment]
Here is the code that will required at least one record to be selected
```js
        onClick: function (event) {
            var sel = this.getSelection();
            if (sel.length >= 1 && sel[0] == event.recid) {
                event.preventDefault();
            }
        },
```

**Comment by eliavmaman** [comment]
Hey 
the problem is that unselect happens before the click event.
any idea?

**Comment by elfwine** [comment]
I don't know exactly why unselect called before select/click event.
With mgr2001's code for onClick event, this onUnselect event code worked for me.. I hope it works on you too. ;)

`onUnselect: function(event) {
    if(typeof event.recid == 'undefined') {
        event.stopPropagation();
        event.preventDefault();
        return false;
    }
}
`

**Comment by PeterKainz** [comment]
try

onUnselect: function(event) {
	if ( event.recid != undefined && w2ui['grid'].getSelection().length > 0 ) {
		event.stopPropagation();
		event.preventDefault();
		return false;
	}
}

**Comment by vitmalina** [comment]
@PeterKainz please create js fiddle to illustrate the problem

**Comment by PeterKainz** [comment]
> @PeterKainz <https://github.com/PeterKainz> please create js fiddle to
> illustrate the problem
>
it was not a problem, it was the solution

cheers
peter
