### ISSUE TITLE
w2popup/alert inside w2confirm doesnt show up

### ISSUE THREAD

**Issue by PrimusFighter** [vitmalina/w2ui#1364]
To break the code down and show the issue, I made a short fiddle: https://jsfiddle.net/qfdsbz8d/2/

I first tried with w2popup inside the "btn == 'yes'" request, but it also appears with w2alert.

I also tried to fix this, but didnt came up with a solution. Any other got an idea?

**Comment by mpf82** [comment]
It's case sensitive: https://jsfiddle.net/qfdsbz8d/4/

    $(function () {
        w2confirm('test?', function(btn){
          if(btn == 'Yes') { // <-- Upper case Y
            w2alert('test alert doesnt show up');
          }
        })
    });

**Comment by PrimusFighter** [comment]
God, this is embarrassing! Sorry and thanks ... This works, but my w2popup still won't show up.
I build it with w2popup.load(); the mistake have to be somewhere else.

Sorry and thanks again!

**Comment by mrg2001** [comment]
There is also a new way in 1.5 in the following way
```js
$(function () {
    w2confirm('test?')
        .yes(function() {
             w2alert('Just tested, it works on 1.5');
        })
        .no(function () {
             w2alert('no');
        });;
});
```
