### ISSUE TITLE
w2popup only supports open one window at one page

### ISSUE THREAD

**Issue by chenduansheng** [vitmalina/w2ui#1365]
Hi, is there a way to support open several windows at one html page? (using w2popup.open())
I meeted a problem like this:
I used w2popup.open() and opened a window successfully,  then, I clicked a button in the window in order to use w2popup.open() again to open another window, at this time the last window was disappeared .
is there a way to support open several windows at one html page?
thank you!

**Comment by mpf82** [comment]
Support for multiple popups is not planned.

See #671 and #283, #1243

**Comment by chenduansheng** [comment]
Thanks very much for the quick and useful reply, good luck!
