### ISSUE TITLE
Is there a w2grid property to change the data after the data loaded from the remote service?

### ISSUE THREAD

**Issue by chenduansheng** [vitmalina/w2ui#1368]
Hi, I need some help about the w2grid:  I want to process the data and change the data's value after the data loaded from the remote service. I want to know is there a gird property that can do this?

example : (like this:)

conf: {
		name: 'grid',
                ...
                ...
                ...
                // like this to change the data value
                rowRender: function (rowData)
                {
                    if(rowData.money < 0)
                    {
           	         rowData.money = 0;  
                    }
                    if(rowdata.pay_time == '1970-01-01 08:00:00')
       	            {
           	          rowdata.pay_time = '';
                    }
                    if(rowdata.enable == 1)
       	            {
           	          rowdata.enable = 'yes';
                    }
                }
                ...
                ...
                ...
         }

thanks.

**Comment by mrg2001** [comment]
Please submit bugs here, not question. See http://w2ui.com/web/docs/w2grid.records

**Comment by chenduansheng** [comment]
ok, thanks
could you tell me where is the website or place for submiting question ?

**Comment by mrg2001** [comment]
Either stackoverflow or commens on w2ui.com website

**Comment by chenduansheng** [comment]
ok, thank you
