### ISSUE TITLE
Grid rows become unselectable

### ISSUE THREAD

**Issue by stmansour** [vitmalina/w2ui#1380]
Hi,

First, what a great toolkit!  You've done an awesome job!

I have been using it for about a week now, so sorry if I'm missing something obvious.

Selecting rows in the grid works fine if the grid records are hardcoded in Javascript. However,
when I remove the records and give the grid a url, the rows populate correctly with the server data, but they are no longer selectable. When events like onClick or onDblClick fire, this.getSelection() always returns null.

To see the problem go to:
   http://ec2-54-167-116-168.compute-1.amazonaws.com:8270/html/t0.html .

Try to click or double-click any row. No row is selectable.

I've seen your Infinite Scroll demo in the Combinations page. So, I know the code *should* work. The code below runs under Chrome's debugger and no errors are encountered. Yet, selection doesn't work. So something is wrong.

Here is the source for the client:

	<html>
	<head>
	    <link rel="stylesheet" type="text/css" href="http://w2ui.com/src/w2ui-1.4.2.min.css" />
	    <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js"></script>
	    <script type="text/javascript" src="http://w2ui.com/src/w2ui-1.4.2.min.js"></script>
	</head>
	<body>
	<div id="main" style="position: absolute; top: 0px; left: 0px; bottom: 0px; right: 0px;"></div>
	<script>
	var config = {
	    grid: { 
	        name: 'grid',
	        url : '//ec2-54-167-116-168.compute-1.amazonaws.com:8270/svc/transactants',
	        show: { 
	            footer    : true,
	        },
	        columns: [                
	            { field: 'FirstName', caption: 'First Name', size: '30%', sortable: true, searchable: 'text', resizable: true },
	            { field: 'LastName', caption: 'Last Name', size: '30%', sortable: true, searchable: 'text', resizable: true },
	            { field: 'PrimaryEmail', caption: 'Email', size: '40%%', resizable: true, sortable: true },
	        ]
	    }
	}
	$(function () {
	    $('#main').w2grid(config.grid);
	});
	</script>
	</body>
	</html>

The server data conforms to the documentation as far as I can tell.  Here is a snippet of the server output:

{
    "records": [
        {
            "Address": "309 South Rexford",
            "Address2": "",
            "BID": 1,
            "CellPhone": "123-456-7890",
            "City": "Beverly Hills",
            "CompanyName": "",
            "Country": "USA",
            "FirstName": "Aaron",
            "IsCompany": 0,
            "LastModBy": 0,
            "LastModTime": "2016-10-03T07:00:24Z",
            "LastName": "Read",
            "MiddleName": "",
            "NLID": 1,
            "PostalCode": "90210",
            "PreferredName": "",
            "PrimaryEmail": "aaron@rexford.com",
            "Recid": 0,
            "SecondaryEmail": "",
            "State": "CA",
            "TCID": 1,
            "Website": "",
            "WorkPhone": ""
        },
        ...
        {
            "Address": "311 South Rexford",
            "Address2": "",
            "BID": 1,
            "CellPhone": "123-456-7896b",
            "City": "Beverly Hills",
            "CompanyName": "",
            "Country": "USA",
            "FirstName": "Child2",
            "IsCompany": 0,
            "LastModBy": 0,
            "LastModTime": "2016-10-03T07:00:24Z",
            "LastName": "Mills",
            "MiddleName": "",
            "NLID": 0,
            "PostalCode": "90210",
            "PreferredName": "",
            "PrimaryEmail": "",
            "Recid": 9,
            "SecondaryEmail": "",
            "State": "CA",
            "TCID": 10,
            "Website": "",
            "WorkPhone": ""
        }
    ],
    "status": "success",
    "total": 10
}

You can look at the server output yourself with this command:

curl -H "Accept: application/json" -H "Content-Type: application/json" -X POST -d '{"cmd":"get-records", "limit":100, "offset":0}' http://ec2-54-167-116-168.compute-1.amazonaws.com:8270/svc/transactants | python -m json.tool

BTW -- I tried this command pointed to your server at http://w2ui.com/web/pages/demo/infinite/index.php but its response is:

	{
	    "message": "Command \"\" is not recognized.",
	    "postData": [],
	    "status": "error"
	}

(It would be great if you could publish a curl command to let everyone see exactly what output it produces).

**Comment by mpf82** [comment]
Hi,

I tried to access the URLs you posted, but the server connection always failed.

From the code you posted - especially the records, my guess is that `recid` has to be lower-case (all other record properties don't matter, they just have to match the cases used in your column fields).

Cheers :)

**Comment by stmansour** [comment]
Good catch!  I figured it was something that the server was doing wrong.  I changed it to “recid” and now everything is working.

Thanks so much!

And, again, hats off to you folks on w2ui toolkit.  I love it.

-S

**Comment by mpf82** [comment]
@stmansour Could you please close the issue if it has been resolved?

Cheers =)

**Comment by mpf82** [comment]
Closing issue: no response, most likely resolved
