### ISSUE TITLE
Grid records not showing

### ISSUE THREAD

**Issue by tudorels** [vitmalina/w2ui#1381]
I found the bug in the grid (more details at https://github.com/vitmalina/w2ui/issues/1378). After a lot of tests I found that the problem occurs because the version of jquery being used. Therefore we cannot use jquery 3. x. x with w2ui. The latest version compatible with w2ui is jquery 2.2.4. This incompatibility it should be posted on your site and be accessible to all visitors. 
I was disappointed with the unprofessional answer of your colleague's([mrg2001](https://github.com/mrg2001)) ... who treated with shallowness problem raised by me. 
I think you should pay more attention to communication with users. I hope this post to be useful to other users and to you for w2ui development and compatibility with the latest version of jquery. 
Thank you!

**Comment by mrg2001** [comment]
Fixed in #1378

**Comment by tudorels** [comment]
Thank you! Glad to see it's fixed!

**Comment by Dazorn96** [comment]
Having this issue with jQuery 3.3.1
I resolved launching a refresh manually after table creation.
