### ISSUE TITLE
Grid expand error: For the last row, it can't show the whole content in the  expanded panel

### ISSUE THREAD

**Issue by chenduansheng** [vitmalina/w2ui#1382]
hello,

Here is a bug about the detail grid, need for help.
when i expanded the last row in the grid, a part of the detail content was not showed

see http://test.welcomest.com/ui/w2/bug/expand.html
(if you click the expand button at the 10st row, you can see the problem)

**Comment by mpf82** [comment]
Can you please provide a working Fiddle/Bin/Pen to demonstrate the issue?

I cannot open the URL you've linked.

**Comment by mpf82** [comment]
Closing issue: no response
