### ISSUE TITLE
in 1.5 rc1 grid toolbarSearch always visible

### ISSUE THREAD

**Issue by eltsov-denis** [vitmalina/w2ui#1383]
Try this code in 1.5 rc1
 $('#entry_xc').w2grid({ 
        name: 'entry_xc', 
			       show: { header: true,
			toolbar: true,            
			toolbarAdd: true,
			toolbarSearch: false,
			toolbarReload:false,
			 toolbarColumns:false
        }...
and got search box in a toolbar.

**Comment by mpf82** [comment]
In 1.5 `toolbarSearch` refers to the search **button**.

If you want to get rid of the input file,d you need to use `toolbarInput: false`

Fiddle: https://jsfiddle.net/8kzjo6vs/1/

**Comment by mpf82** [comment]
Please close this issue if my previous post solved your problem.

Cheers :)
