### ISSUE TITLE
in rc1.5 grid.records[i].changes moves to  grid.records[i].w2ui.changes

### ISSUE THREAD

**Issue by eltsov-denis** [vitmalina/w2ui#1384]
is it bug or final version?

**Comment by mpf82** [comment]
This is a permanent change in 1.5

This way, the w2ui specific properties are all under the "namespace" `w2ui` and will not collide with the user's record items.

See also my post here: https://github.com/vitmalina/w2ui/issues/1351#issuecomment-255384351

**Comment by mpf82** [comment]
Please close this issue if my previous post answered your question.

Cheers :)
