### ISSUE TITLE
.style not working in 1.5.rc1

### ISSUE THREAD

**Issue by SouthernSaint** [vitmalina/w2ui#1387]
I have a w2ui grid that successfully renders background-color: red; when sent as JSON data from server using version w2ui-1.4.3.min.js, however when I upgrade to w2ui-1.5.rc1.min.js the same data is not updated in the grid.

**Comment by mpf82** [comment]
`record.style` has moved to `record.w2ui.style`

Please see my comment here: https://github.com/vitmalina/w2ui/issues/1351#issuecomment-255384351

**Comment by mpf82** [comment]
Please close this issue if my previous post solved your problem.

Cheers :)

**Comment by mpf82** [comment]
Closing issue: no response
