### ISSUE TITLE
sortable bug in w2grid

### ISSUE THREAD

**Issue by chenduansheng** [vitmalina/w2ui#1388]
Hi,
the column can't be sorted when using cell-format,
see http://jsfiddle.net/ya9eerb5/7/

**Comment by mrg2001** [comment]
The default behavior is to select entire column. If you want sorting, add this
```js
        onColumnClick: function (event) {
          this.sort(event.field);
          event.preventDefault();
        },
```
see http://jsfiddle.net/ya9eerb5/8/

**Comment by chenduansheng** [comment]
@mrg2001  thanks, good luck
