### ISSUE TITLE
package.json dependencies instead of /libs files

### ISSUE THREAD

**Issue by aadrian** [vitmalina/w2ui#1393]
Please add the dependencies to the ```package.json``` instead of having them in ```/libs``` directory checked in.

Thank you.

**Comment by mpf82** [comment]
w2ui has only jQuery as dependency. Since I already had a PR in progress, I added your suggestion to ``package.json`` (copied from ``w2ui.jquery.json``).

https://github.com/vitmalina/w2ui/pull/1394

let's wait for @mrg2001 or @vitmalina to merge the PR

**Comment by aadrian** [comment]
> w2ui has only jQuery as dependency.

```/libs``` directory also seems to contain FontAwesome and Codemirror. Maybe they're required only for demos? )

**Comment by mpf82** [comment]
I don't know about FontAwesome, since I use it anyway (worst case could be that icons on toolbar buttons might be missing), but I definitely don't use Codemirror in my w2ui projects.

**Comment by mpf82** [comment]
Closing: PR #1394 has been merged
