### ISSUE TITLE
Load data from existing table

### ISSUE THREAD

**Issue by firstsano** [vitmalina/w2ui#1395]
Is there a way to load data (cells and headings) from existing static table, like datatables for example?

**Comment by mpf82** [comment]
If you're asking if there's a built-in way to convert a DOM ``<table>`` to a w2grid, the answer is: no.

You would have to implement such a feature yourself, or maybe add it to the lib: https://github.com/vitmalina/w2ui#contributing

**Comment by firstsano** [comment]
Yes, you got me right. Thank you.
Then I'll implement one
