### ISSUE TITLE
Grid selectAll() and selectNone() methods don't update status

### ISSUE THREAD

**Issue by swarner0807** [vitmalina/w2ui#1397]
When the selectAll() or selectNone() methods are called, either manually or via the selectColumn, the status in the footer continues to show the previous value. This can be seen on this demo [grid](http://w2ui.com/web/demos/#!grid/grid-3).

1. Select 3 of the grid records
2. Notice that the footer will say "3 selected"
3. Click the "Select All" checkbox in the header
4. All of the records will appear selected, yet the footer status will still say "3 selected"
5. Click the "Select All" checkbox in the header again
6. No records will be selected, and the footer will still say 3

**Comment by mpf82** [comment]
Same behaviour if you press ``Ctrl+A`` and ``ESC`` after selecting one/multiple records.

**Comment by migace** [comment]
Here is my proposition to solve problem - issue #1397 
https://github.com/vitmalina/w2ui/pull/1598/files
