### ISSUE TITLE
Grid does not empty when search results from server indicate no matches

### ISSUE THREAD

**Issue by stmansour** [vitmalina/w2ui#1401]
Hi,
Grid is working fine with server searches except when there are no matches.  In the w2ui demos where the data records are embedded in the JS, if the search string produces no matches then the grid empties. That is what I would expect. However, when I do a search against a server and there are 0 results, the grid does not empty.  It retains the contents that it had prior to the search.  Here is the json the server returns when there are no matches:

  {"status":"success","total":0,"records":null}

The JS editor in Chrome indicates the problem 
![image](https://cloud.githubusercontent.com/assets/6549488/20782290/6914e496-b73f-11e6-8801-dcc9977221a6.png)
-- an attempt to read the length on a null value.  I'm hoping you can just check for records being null and do the right thing -- the json above was generated by Go's json encoder; meaning that if you require something different in the json then Go programmers would need to special-case the response for 0 matches.

I made a fix that seems to work.  In w2ui-1.5.rc1.js  I changed this:

5321                             if (data.records.length == this.limit) {
5322                                 this.last.xhr_hasMore = true;
5323                             } else {
5324                                 this.last.xhr_hasMore = false;
5325                                 this.total = this.last.xhr_offset + data.records.length;
5326                             }

to this:

5321                             if (data.records != null && data.records.length == this.limit) {
5322                                 this.last.xhr_hasMore = true;
5323                             } else {
5324                                 this.last.xhr_hasMore = false;
5325                                 this.total = this.last.xhr_offset; 
5326                                 if (data.records != null) this.total = data.records.length;
5327                             }

-Steve

**Comment by mpf82** [comment]
To me it sounds like a bad server-side implementation. Instead of returning ``null`` the server should return an empty array.

Still, nothing wrong with w2grid doing some checks instead of assuming that properties are not null. Maybe even check with ``if(Array.isArray(data.records))``, to make sure records aren't of any other type, even if not null.

**Comment by stmansour** [comment]
I agree that "records": null could be replaced with an empty list -- that would probably keep a lot of code from breaking.  This is just the behavior of Go's json encoder.  I'll mention this to the go community.
