### ISSUE TITLE
Again - remote database and offset problem ...

### ISSUE THREAD

**Issue by Rimokas** [vitmalina/w2ui#1402]
Hi,

downloaded today ( 01 of December  2016 ) sources ... 

In earlier I directed that exist problem with "offset" for remote database . in w2grid sources "offset" is adding as chars, not as integer and became "100100" instead 200 ... After some research I found that in source it must be changed in 2 places : 
- 6654 row , this.last.xhr_offset += parseInt( this.limit ); // add parseInt for this.limit ;
- 6662 row , obj.last.xhr_offset += parseInt( obj.limit ); //  add parseInt for obj.limit ;

Please, correct this lines ... :)

Thanks in advance ... With best regards !

**Comment by mpf82** [comment]
``this.limit`` defaults to 100 (int) and is never re-assigned.

If it's not an integer when the lines you've mentioned are executed, chances are, that you're assigning strings to the property.

**Comment by Rimokas** [comment]
Maybe I'm not understanding something ... but ... seeing though javascript debug I'm seeing that NOW ( I changed locally in mentioned lines ) it sum "offset" value 100, 200, 300 and etc ... Previuosly was "100", then "100100" and appears error about row counting and start to 0 and get first page ... That's fact ...

**Comment by Rimokas** [comment]
You are right - it's mine problem. I'm getting this parm from database . I added parseInt( limit ) to own source and it's working fine with original sources ... Thanks !
