### ISSUE TITLE
Reloading grid will reset current view position

### ISSUE THREAD

**Issue by aswzen** [vitmalina/w2ui#1403]
I try any options, but everytime i reload the table/grid. it will resetting the last view position back to the top (row 0).
Is this a bug?

If not how to get rid of this...if i try to use reload callback then scroll to last position user will see the scrolling animation.

Thank You

**Comment by aswzen** [comment]
any solutions?

**Comment by mrg2001** [comment]
Server reload will set scrollTop to 0. You can remember it before reload and restore after reload. If you want to use scrolIntoView(), use third argument as true, which is instant scroll, w/o animation. 
```js
scrollIntoView: function (ind, column, instant) 
```

will update docs as it comes

**Comment by mrg2001** [comment]
Please note that scollIntoView can also scroll into specific column, not just raw
