### ISSUE TITLE
Grid reloads from first record on last "get" even though record count doesn't change

### ISSUE THREAD

**Issue by stmansour** [vitmalina/w2ui#1404]
By default the grid asks for batches of 100 records at a time. When I scroll past the first 100, it sends a request for the next 100, and so on.  I've tested this capability and it works fine until it gets to the last batch. When the last batch is delivered, it pops up a dialog that says "Your remote data source record count has changed, reloading from the first record."  But the record count did not change.  I put some logging into the server to validate. Here is the output for a test where there were 427 records.  You can see the five requests the grid sent to the server. I list how many records (transactants) were read from the database for each query (stored in the records array), and also the first 50 chars of the response sent back to the grid.  Note that when the last 27 records are sent, total is 427, same as with all the previous replies.  I checked the docs but I didn't see anything about handling the last batch different.  So, I'm assuming there's some sort of logic error in the grid code on the last batch.

grid request:  request={"cmd":"get","selected":[],"limit":100,"offset":0}
Loaded 100 transactants
first 50 chars of response: {"status":"success","total":427,"records":[{"recid

grid request:  request={"cmd":"get","selected":[],"limit":100,"offset":100}
Loaded 100 transactants
first 50 chars of response: {"status":"success","total":427,"records":[{"recid

grid request:  request={"cmd":"get","selected":[],"limit":100,"offset":200}
Loaded 100 transactants
first 50 chars of response: {"status":"success","total":427,"records":[{"recid

grid request:  request={"cmd":"get","selected":[],"limit":100,"offset":300}
Loaded 100 transactants
first 50 chars of response: {"status":"success","total":427,"records":[{"recid

grid request:  request={"cmd":"get","selected":[],"limit":100,"offset":400}
Loaded 27 transactants
first 50 chars of response: {"status":"success","total":427,"records":[{"recid

**Comment by mrg2001** [comment]
no longer an issue, see https://github.com/vitmalina/w2ui/pull/1521
