### ISSUE TITLE
Incorrect grid body refresh when hiding/showing columns

### ISSUE THREAD

**Issue by avber** [vitmalina/w2ui#1418]
IE 11
http://w2ui.com/web/demos/#!grid/grid-3

1. Hide "Start Date" column
2. Show "Start Date" column
   Grid body horizontal scrollbar is shown
3. Hide "Email" column
4. Show "Email" column
   "Start Date" column is not shown correctly

**Comment by mpf82** [comment]
Cannot reproduce. Maybe this has been fixed since you posted the issue.

Can you please confirm if the issue has been resolved?

**Comment by mpf82** [comment]
Closing issue: no response
