### ISSUE TITLE
w2sidebar img option doesn't work

### ISSUE THREAD

**Issue by avber** [vitmalina/w2ui#1426]
IE 11
source code downloaded from github on Dec 14

this.sidebar = this.bodyEl.w2sidebar({
					name: this.id + 'sb',
					img: 'icon-folder',
					nodes: this.nodes
				});

though it works on nodes

{
			text: 'Level 1.1', img: 'icon-folder',
}

**Comment by mrg2001** [comment]
There are 2 properties for sidebar/toolbar: img and icon. Img is for sprites (old way), icon is icon font - user it. Close if this issue is resolved.

**Comment by avber** [comment]
http://jsfiddle.net/dwcdapuc/

icon doesn't work either. I guess sidebar properties are not copied to nodes properly
