### ISSUE TITLE
Grid onDeleted doesn't works

### ISSUE THREAD

**Issue by daniel-alves** [vitmalina/w2ui#1429]
The grid event onDeleted should be called when server responds back after delete request.
does not work Version 1.5.rc1.

**Comment by mrg2001** [comment]
This is not when onDelete is called, see documentation http://w2ui.com/web/docs/1.5/w2grid.onDelete

**Comment by daniel-alves** [comment]
I said **onDeleted** in http://w2ui.com/web/docs/1.5/w2grid.onDeleted not **onDelete**

**Comment by mrg2001** [comment]
onDeleted is decommissioned. Do
```
onDelete: function (event) {
    event(function () {
       // it's after server delete call
   });
}
```
Your link no longer works (deleted 4 days ago)
