### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by forwangtao** [vitmalina/w2ui#1433]

**Comment by aadrian** [comment]
http://w2ui.com/web/blog/8/W2UI-1.3-Released-Goodbye-Pagination-Hello-Infinite-Scroll

**Comment by mrg2001** [comment]
Pagination not supported, infinite scroll is the new "black", see 

http://w2ui.com/web/demos/#!combo/combo-9
https://github.com/vitmalina/w2ui/issues/964
