### ISSUE TITLE
w2utils.formatDateTime fails when using custom format

### ISSUE THREAD

**Issue by avber** [vitmalina/w2ui#1440]
Example from the docs

var a = w2utils.formatDateTime((new Date()), 'mm-dd-yyyy h:m pm');
console.log(a);

fails in IE 11
---------------------
this works
var a = w2utils.formatDateTime((new Date()));
console.log(a);

**Comment by mrg2001** [comment]
Misspell in documentation, should be 
```
var a = w2utils.formatDateTime((new Date()), 'mm-dd-yyyy|h:m pm');
console.log(a);
```

Corrected
