### ISSUE TITLE
Grid event onDeleted dont work

### ISSUE THREAD

**Issue by daniel-alves** [vitmalina/w2ui#1442]
The grid event **onDeleted** dont is called after server request as the documentation says:

http://w2ui.com/web/docs/1.5/w2grid.onDeleted

the onDelete event works fine:

http://w2ui.com/web/docs/1.5/w2grid.onDelete

**Comment by mrg2001** [comment]
I looked up the notes and onDeleted events was removed. Use onDelete and inside it use onComplete clause.
```js
onDelete: function (even) {
   event.onComplete = function () {
       ...
   } 
}
```
