### ISSUE TITLE
Request onKeyDown/onKeyUp on grid edit column

### ISSUE THREAD

**Issue by spizzi77** [vitmalina/w2ui#1443]
Hy All, first of all happy new year to all, i have a question i don't know if this is the right place but i don't know where i can ask it.
When we edit a column in the w2grid object we can insert the type:text alphanumeric etc, there is a way to insert a custom function done in regex function/control on keydown or onkeyup, if i use the onKeydown event it doesn't work, i want to insert a custom regex every time that the user is writing into the edit input and on the blur event, that i can capture with the onChange event, insert a w2alert if the text is false in regex function and for sure make the empty input if the result of regex is false.Any suggests?I tried differents methods but seems that i can't capture the onkeyup at every digits.
Thanks in advantage
Andrea

**Comment by mrg2001** [comment]
There are two events related to this. First, onChange event is triggered when user edits a value in a column and exists edit screen. Second, onEditField is triggered when edit input control is created. You can directly add events to that control and force any regex you'd like. Here is an example
```js
onEditField: function (event) {
   event.done(function () {
      // event.input - is the input
      console.log(event.input);
   });
}
```

**Comment by spizzi77** [comment]
Hy Mrg, thanks for the answer i'll try monday in office and i'll let you know....Regards, Andrea.

**Comment by spizzi77** [comment]
Hy Mrg,
Unfortunately your solution doesn't work, event.done is not recognize for jquery 3.0 and event.input is undefined..BTW i resolved the problem in this way, i need that type of the edit field is ONLY LETTERS and not NUMBERS so in the column i use type="alphanumeric" in this way:

```javascript
{ field: 'note', caption: '<div style="text-align: center;">Nota Recapito<div>',size:'15%', editable: { type: 'alphanumeric',style: 'background-color: #ffcccc' } },
```

but inserting alphanumeric users can write numbers but in this way no special chars so we must controls NUMBERS on the EditField, this field(NOTE) is the fourth column, so on the editField i go to write:

```javascript
        onEditField:function(event){
        	event.onComplete=function(event){
        		id = event.recid;
        		event.preventDefault();
                                //_4 la colonna note è  la quarta colonna così mettiamo _4 e 
                               //gridElencoToDoRec=nome grid
				$('#grid_gridElencoToDoRec_edit_'+id+'_4').keydown(function(event){
					 if (isNaN(event.key) == false){
					 	event.preventDefault();
					 };
				});
        	};
    		$('.w2ui-changed').each(function(event){
			  	$(this).css('color','red');
			});
        },
```

This work perfectly and when the user is writing inside the edit column if he/she is writing a number there is the preventDefault and it's not allowed insert a number.

Regards
Andrea

**Comment by spizzi77** [comment]
Hy again Mrg,
The solution above is working but not allows space so for me is not ok, so this instead is the right solution, keep type : 'text' in the column costruction and on edidField call a function on keypress...This is working and tested for version 1.4.3 i think that also for 1.5 is ok, maybe the name of id of the edit input can be different but i don't think, but the logic and procedure is ok in this way, so:

Defined the fourth column in this way 
```javascript
{ field: 'note', caption: '<div style="text-align: center;">Nota Recapito<div>',size:'15%', editable: { type: 'text',style: 'background-color: #ffcccc' } },
```

And onEditField:
```javascript
        onEditField:function(event){
        	event.onComplete=function(event){
        		id = event.recid;
        		//Il type della colonna note è text ma chiamiamo una funzione personalizzata perchè il text permette tutti i caratteri
				$('#grid_gridElencoToDoRec_edit_'+id+'_4').keypress(function(event){
					 return noNumbers(event);
				});
        	};
    		$('.w2ui-changed').each(function(event){
			  	$(this).css('color','red');
			});
        },

```

And the function noNumbers()
```javascript
function noNumbers(e) {
	//console.log(e);
    var keynum;
    var keychar;
    var numcheck;

    if (window.event)// IE
    {
        keynum = e.keyCode;
    } 
    else if (e.which)// Netscape/Firefox/Opera
    {
        keynum = e.which;
    }
    keychar = String.fromCharCode(keynum);

   //tasti back space - canc - tab
   if ((keynum == 8) || (keynum == 46) || (keynum == 9)){
      return true;
   }
   
    numcheck = /[a-zA-Z\s\ ]/;

    return numcheck.test(keychar);
}
```

**Comment by mpf82** [comment]
> event.done is not recognize for jquery 3.0

Just for clarification, ``event.done`` is a feature of w2ui 1.5 and is independant from the used jQuery version (in w2ui 1.5 you can use ``event.onComplete`` (**but only once**) and have **multiple** ``event.done`` handlers).

For reference see the code of ``w2utils.event.trigger`` to get an idea how and when ``event.onComplete`` and ``event.done`` are executed.

Off Topic: If you want to reduce your code by a few lines, you can use:

    var keynum = e.which || e.keyCode || 0;

**Comment by spizzi77** [comment]
Hy Mike, 
Thanks, i don't use 1.5 for now so i didn't think that .done was implemented there....Thanks for the answer and suggest.Yes noNumbers it's an old function used in all the project, i didn't write it but other people done it...For the moment it's working... ;) Good day.
Andrea
