### ISSUE TITLE
Advanced search button will not show up if searches added after the fact

### ISSUE THREAD

**Issue by nexushoratio** [vitmalina/w2ui#1445]
Reproduction is easy.

Start with the example at http://w2ui.com/web/demos/#!grid/grid-16

Remove the searches field and add it after the grid is rendered.

`w2ui.grid.searches = [....];`

Even with `w2ui.grid.refresh()`, the [Search] button will not show up.

The search input field will have all of the have all of the searches listed, but the button/overlay will simply not be present.

Cheating by using:
`  searches: [{}],`

in the call to w2grid will work around the problem.

**Comment by karjac14** [comment]
adding searches after w2ui grid has rendered works for me. try adding set timeout making sure grid finished rendering

**Comment by mrg2001** [comment]
When initializing the grid, it will determine if to display search button. If not, search button will not be added to the toolbar at all. If you want it to be added, then run this

```js
w2ui.grid.toolbar.items.push($.extend(true, {}, w2ui.grid.buttons['search-go']));
w2ui.grid.render()
```
