### ISSUE TITLE
Form with Tabs and Columns example

### ISSUE THREAD

**Issue by alexey-vasyunin** [vitmalina/w2ui#1449]
Hello!

It's strange mapping with tabs and columns in example http://w2ui.com/web/demos/#!forms/forms-11

![image](https://cloud.githubusercontent.com/assets/5081020/21725349/8249103e-d451-11e6-8187-8650797807b5.png)

**Comment by mpf82** [comment]
It's just the default rendering of groups and group items in a w2ui form - you can also see this in this example: http://w2ui.com/web/demos/#!forms/forms-3

I agree that the default rendering looks odd, especially if the number of fields are varying from column to column. 

If you fiddle with the CSS you can have nicer group headers and/or group boxes.

Here's an example how form columns and form groups look in my project:

![grace_hopper](https://cloud.githubusercontent.com/assets/10152404/21736448/10c27d54-d471-11e6-9776-9b3055142d73.png)

A starting point could be to use:

    .w2ui-column { padding-right: 10px; }

to get some space between the groups: http://jsfiddle.net/9a3zmed3/

**Comment by alexey-vasyunin** [comment]
@mpf82 Thanks for reply. It's seems better with space )

I liked the example from your project
