### ISSUE TITLE
Ajax dataTypes in w2grid and w2form

### ISSUE THREAD

**Issue by thipages** [vitmalina/w2ui#1450]
Hi,

Great library! Congratulation

I need to set dataType of ajaxOptions (in w2grid and w2form) as "json" and not as 'text'. Unless I miss something is it possible to add it in the w2utils.settings object (where unfortunately stands already a dataType property used for ajaxOptions.data : ajax dataType could be set with w2utils.settings.dataType2 temporarily)

Thanks

**Comment by mpf82** [comment]
Overwriting the data type to whatever you need is the way to go.

Example:

    w2utils.settings.dataType = 'JSON';

data types are described here: http://w2ui.com/web/docs/1.5/w2utils.settings

**Comment by thipages** [comment]
please have a look at line 481 in w2form.js
dataType : 'text'

same in w2grid.js

**Comment by thipages** [comment]
As a remembering, is it possible to add a new dataType in the global settings, eg `w2utils.settings.dataType2 `? Thanks.

**Comment by mrg2001** [comment]
According to http://stackoverflow.com/questions/2722750/ajax-datatype, dataType = 'json' or dataType = 'text' would only tall jQuery how to treat data response. Since both w2grid and w2form will check if it is text, it will attempt to parse as JSON. Please note that it can be loose JSON format (w/o making each property in double quotes). 

I fail to see how it makes difference for server side.

**Comment by thipages** [comment]
Hi,
on server, when you output like this : 
` header('Content-Type: application/json; Charset=UTF-8');
  echo json_encode($output);`

you need to put dataType as Json as Ajax side.
Does this help?

**Comment by mrg2001** [comment]
Can you please explain how is it an issue for you. Try changing it in the source code directly and see if it resolves it? I think it will not as setting it to 'json' will not affect request headers.

**Comment by thipages** [comment]
Yes, I change the code from 'text' to 'json' and it works in both w2form and w2grid

```
var ajaxOptions = {
                type     : 'POST',
                url      : url,
                data     : edata.postData,
                headers  : edata.httpHeaders,
                // todo thipages: changed from 'text' to 'json' (27/12/2016)
                dataType : 'json'  // expected data type from server
            };
```

**Comment by thipages** [comment]
So my request is to add it as a parameters in w2utils.settings

**Comment by mrg2001** [comment]
Is there any one to provide an example, jsfiddle if possible. What is your server side language? Sorry for asking too many questions. I want to avoid unnecessary properties.

**Comment by thipages** [comment]
clear. php is my server language. Will try to build a fiddle. Thanks

**Comment by thipages** [comment]
Hi,
I checked again text vs json. It works now. Dont know what happend.
Thanks.
Closed.
