### ISSUE TITLE
Can not retrieve all w2ui Ids

### ISSUE THREAD

**Issue by thipages** [vitmalina/w2ui#1453]
Hi,
I try to retrieve the Ids of global w2ui object. I get an empty array. Any ideas?
Thank you

```
function getW2uiIdList() {
    var idList=[];
    for (var prop in w2ui) {
        if (w2ui.hasOwnProperty(prop)) {
            idList.push(prop);
        }
    }
    return idList;
}
```

**Comment by mrg2001** [comment]
Are you using RequireJS or some CommonJS libs, this commit might have caused it. https://github.com/vitmalina/w2ui/commit/1dd3fd70743e9b4bf72b69c7bf05748d68b5e900.

**Comment by thipages** [comment]
no, nothing else than w2ui lib

**Comment by thipages** [comment]
This was due to a side effect in my code, I will try to explain in a different thread
