### ISSUE TITLE
display context menu when editing grid cell

### ISSUE THREAD

**Issue by chalchis** [vitmalina/w2ui#1455]
How could I display the context menu when the edit mode of a grid cell is activated?

I'm using version 1.4.x

I await your comments

regards

**Comment by mendozada** [comment]
Hola, te consulto si pudiste solucionar el problema de mostrar el submenu cuando la grilla esta activada en Selectype = 'cell'. 
Yo estoy intentando pero aun no pude descubri como hacerlo
[http://jsfiddle.net/y81cyj54/24/](http://jsfiddle.net/y81cyj54/24/)
Podrias verificar en que le estoy errando. 

Gracias. Saludos.

**Comment by mrg2001** [comment]
I have looked into this one before. Here is correct fiddle

http://jsfiddle.net/y81cyj54/28/

**Comment by chalchis** [comment]
thanks
