### ISSUE TITLE
w2field 'list' maxDropWidth

### ISSUE THREAD

**Issue by avber** [vitmalina/w2ui#1460]
Is it the case that if maxDropWidth is not specified, the width of the dropdown should adapt to it's items' width?

There should be no horizontal scrollbar in the demo
http://w2ui.com/web/docs/1.5/form/fields-list

**Comment by mpf82** [comment]
There has been a PR that lets you do what you want:

https://github.com/vitmalina/w2ui/pull/1962

Just play around with ``align``, ``minDropWidth`` and ``maxDropWidth``.

The docs and examples have yet to be updated to reflect these changes.
