### ISSUE TITLE
w2grid refreshbutton-tooltip doesnt hide

### ISSUE THREAD

**Issue by PrimusFighter** [vitmalina/w2ui#1461]
Hi,

when I reload a grid, and removing the cursor from the refreshbutton while the UI is still locked by the refreshmessage, the tooltip of the refresh button doesnt hide.

I solved it with adding this to the gridsettings:
`onReload: function(event)
{
	setTimeout(function () { $().w2tag(); }, 20);
}`

But this is not a general solution. you mind adding this to the library, or got an other general solution for me?!

**Comment by Connum** [comment]
Hi @PrimusFighter,

would you mind providing a jsfiddle that demonstrates this issue? Would make it much easier to implement a general fix without recreating this first.

Kind regards
Connum

**Comment by mrg2001** [comment]
I have seen this issue too. Fixed it, will upload in 10 min.
