### ISSUE TITLE
Check All grid checkbox based on button click

### ISSUE THREAD

**Issue by jackryu** [vitmalina/w2ui#1462]
Hello Team,
I have one grid column type check box, I need check and uncheck all check box based on button click it is possible using any w2ui grid function if possible please suggest this is critical for me.

**Comment by spizzi77** [comment]
Sincerely i don't understand which button click?The button inside the toolbar?

**Comment by jackryu** [comment]
_Yes I am create on button inside the toolbar._

**Comment by thipages** [comment]
This may help : [grid demo](http://w2ui.com/web/demos/#!grid/grid-10)

**Comment by jackryu** [comment]
![need select all checkbox](https://cloud.githubusercontent.com/assets/6933841/23130438/622ebd2a-f7ac-11e6-95b7-629b31a03010.jpg)

**I need this.**

**Comment by jackryu** [comment]
@taipags

**Comment by vitmalina** [comment]
duplicate of https://github.com/vitmalina/w2ui/issues/1526
