### ISSUE TITLE
w2field list doesn't distinguish item ids when id = '' and id = 0

### ISSUE THREAD

**Issue by avber** [vitmalina/w2ui#1466]
comboItems.push({ id: '', text: 'Select' })

comboItems.push({ id: 0, text: 'Select 2' })

they are treated incorrectly after selection

[http://jsfiddle.net/rstv96s0/](http://jsfiddle.net/rstv96s0/)

**Comment by mendozada** [comment]
Hello, the structure of the item object, requires that the ID be a unique key,

[http://w2ui.com/web/docs/1.5/form/fields-list](url)

**Comment by avber** [comment]
IDs ARE unique: '' and 0

**Comment by mpf82** [comment]
I created a PR to fix this issue: https://github.com/vitmalina/w2ui/pull/1477

Reason why it's currently not working: The ``==`` operator in JS compares for ``truthy`` and ``falsy`` instead of exact matches. Fix: use ``===`` operator instead, which is also type-safe.

**Comment by avber** [comment]
@mpf82 
Yeah, I know about  === operator :)

If you have time, could you also create a PR for #1421 ?

Thanks

**Comment by mpf82** [comment]
To be frank, I have no idea how to create a second PR in the github desktop app, while I still have an active/pending PR.

**Comment by mpf82** [comment]
PR has been merged, please close this issue, unless you can still reproduce the problem with the latest sources.
