### ISSUE TITLE
Time spent to set up layouts seems critical

### ISSUE THREAD

**Issue by thipages** [vitmalina/w2ui#1467]
Hi,
Layouts set-up takes time and I remark that I have to delay the application before starting working with elements contained in layouts. Time grows with nested layouts.

A possibility  could be to trigger an event when the layout is ready. eg checking that initial shown panels have valid width and height.

What do you think?

**Comment by mpf82** [comment]
There's already a callback event for layout content: http://w2ui.com/web/docs/1.5/w2layout.onContent

Note that this is a new feature in 1.5

Example:

    $('#admin_layout').w2layout({
        name: 'admin_layout',
        panels: [
            { type: 'top',      content: content,   size: 70,       resizable: false, overflow: 'none' },
            { type: 'left',     content: content,   size: 220,      resizable: false },
            { type: 'main',     content: content,   },
            { type: 'bottom',   content: content,   size: 30,       resizable: false }
        ],
        onContent: function(event) {
            event.onComplete = function(ev){
                // console.log('w2ui layout panel '+ ev.target + ' finished content loading');
                ... your code here
            };
        },
    });

**Comment by thipages** [comment]
ok, thank you.
I miss it
