### ISSUE TITLE
How to add a new field into an existing form

### ISSUE THREAD

**Issue by thipages** [vitmalina/w2ui#1468]
Hi,

This question has been asked serveral times but all answers are not working for me :-(

Here is a simple  [fiddle](http://jsfiddle.net/thipages/nvkmqurs/) based on  [Auto-Generated Templates](http://w2ui.com/web/demos/#!forms/forms-10) demo.

Can you help?
Thank you

**Comment by mpf82** [comment]
Is destroying the form and re-creating it an option?

http://jsfiddle.net/nvkmqurs/5/

**Comment by thipages** [comment]
Yes!
Seems to be radical.
Thank you.
