### ISSUE TITLE
Add Row Total in Summary Section

### ISSUE THREAD

**Issue by jackryu** [vitmalina/w2ui#1470]
Hello - 

I need to total sum on selected row in summary section if it is possible.

**Comment by jackryu** [comment]
**No this is not helpful for me because  this is based on static coding but i need total my grid rows based, I am trying to create code with reference this demo but it is not working please share any code sample**    

reference
http://www.filetolink.com/af4c5ac950

**Comment by mrg2001** [comment]
You should use summary records. See http://w2ui.com/web/docs/1.5/w2grid.summary. You will been to calculate total on your own.
