### ISSUE TITLE
change the header color of the grid and colors the buttons

### ISSUE THREAD

**Issue by mendozada** [vitmalina/w2ui#1473]
Hi, is there a possibility to change the header color of the grid and colors the buttons without modifying the w2ui.css?

**Comment by mpf82** [comment]
Sure, simply overwrite the CSS classes anywhere else, e.g. your own CSS file (loaded after the w2ui CSS), or an inline style tag.

To enforce your changes, add ``!important`` to your CSS rule.

Example: http://jsfiddle.net/y53dm2hq/

**Comment by mendozada** [comment]
Hi mike, how are you? My idea is that you can change the class to each button to assign different colors, in an earlier version existed button.w2ui-btn-blue / button.w2ui-btn-red ....

How can I call them in a popup 

In example you passed me as I can to make each button have a different color

You understand me?

Thank

**Comment by mpf82** [comment]
I'm fine, thanks.

In 1.5 the form actions can be an object with a custom CSS class and/or a custom CSS style.

There's an example in the disqus comments on this page: http://w2ui.com/web/docs/1.5/w2form.actions

> action: { caption: 'Limpiar', style: '', class: '', onClick: function () {} }

**Comment by mendozada** [comment]
Perfect, that's what I need, thank you very much.
I share my code.

[http://jsfiddle.net/y53dm2hq/1/](url)

Greetings.
