### ISSUE TITLE
datetime search not working

### ISSUE THREAD

**Issue by MrDefacto** [vitmalina/w2ui#1475]
Hi,

It looks that search for datetime format is not working. 'date' is ok, but not 'datetime'.

searches:
{ field: 'f', caption: 'Last', type: 'datetime' }

datetime in td cell is in format 'm/d/yyyy hh:mi pm' for example: '1/19/2017 1:00 am'. I'm using 'after' in multisearch and it's not showing anything after clicking search button.

Any clues?

**Comment by mendozada** [comment]
Hello, please show us how you load the grid, what is your backend.
I use php + mysql

From mysql I use the sql with date_format ()

regards

**Comment by PolisImdat** [comment]
I have same problem here. Here is my code.
`$.ajax({
        type: 'GET',
        url: url,
        success: function (response, textStatus, xhr) {
            records = response;
            $('#grid').w2grid({
                name: 'grid',
                header: 'SampleTable',
                reorderColumns: true,
                recid: 'id',
                show: {
                    header: true,
                    toolbar: true,
                    footer: true,
                    lineNumbers: false,
                    toolbarAdd: false,
                    toolbarDelete: false,
                    toolbarSave: false,
                    toolbarEdit: false,
                    selectColumn: true
                },
                toolbar: {
                    items: [],
                    onClick: function (event) {}
                },
                searches: [
                    { field: 'no', caption: "No", type: 'text', operator: 'contains' },
                    { field: 'userName', caption: "Kullanıcı Adı", type: 'text', operator: 'contains' },
                    { field: 'date', caption: "Tarih", type: 'datetime', render: 'dd.mm|h24:mm:00' },
                ],
                columns: [
                    {
                        field: '',
                        caption: '',
                        size: '23px',
                        sortable: true,
                        info: {
                            render: function (rec) {
                                let user = rec.user;
                                let bubble = "<table>";
                                bubble += "<tr><td>Id : </td><td>" + rec.id + "</td></tr>";
                                bubble += "<tr><td>Sahibi : </td><td>" + user.userName + " - " + user.powerName + "</td></tr>";
                                bubble += "<tr><td>Ip : </td><td>" + rec.ip.ip + "</td></tr>";
                                bubble += "<tr><td>Ülke : </td><td>" + rec.ip.country + "</td></tr>";
                                bubble += "<tr><td>Şehir : </td><td>" + rec.ip.city + "</td></tr>";
                                bubble += "<tr><td>Isp : </td><td>" + rec.ip.isp + "</td></tr>";
                                bubble += "<tr><td>Bölge : </td><td>" + rec.ip.regionName + "</td></tr>";
                                bubble += "<tr><td>Detail : </td><td>" + rec.detail + "</td></tr>";
                                bubble += "</table>";
                                return bubble;
                            }
                        }
                    },
                    {
                        field: 'no',
                        caption: 'No',
                        size: '40px',
                        sortable: true
                    },
                    {
                        field: 'userName',
                        caption: 'Kullanıcı Adı',
                        size: '86px',
                        sortable: true
                    },
                    {
                        field: 'name',
                        caption: 'İsim',
                        size: '66px',
                        sortable: true
                    },
                    
                    {
                        field: 'status',
                        caption: 'Durum',
                        size: '80px',
                        sortable: true
                    },
                    {
                        field: 'isPayed',
                        caption: 'Ödendi',
                        size: '59px',
                        sortable: true
                    },
                    {
                        field: 'isCalculated',
                        caption: 'H. Kesildi',
                        size: '68px',
                        sortable: true
                    },
                    {
                        field: 'date',
                        caption: 'Tarih',
                        size: '124px',
                        sortable: true,
                        render: 'datetime:dd.mm|h24:mm:00'
                    },
                    {
                        field: 'id',
                        caption: 'İşlemler',
                        size: '124px',
                        sortable: true,
                        render: function (rec) {
                            let html = '<a class="Detail" id="' + rec.id + '">Detay</a>';
                            return html;
                        }
                    }
                ],
                records: records,
                onReload: function (event) {
                    getTable();
                }
            });
        },
        error: function (response) {
            console.log(response);
        }
    });`

**Comment by mpf82** [comment]
Can you please provide a Fiddle/Bin/Pen to demonstrate the issue?

**Comment by mpf82** [comment]
Closing issue: no response
