### ISSUE TITLE
sort event direction

### ISSUE THREAD

**Issue by MrDefacto** [vitmalina/w2ui#1478]
Hi,

There is no way to get direction of selected sort. Object returned gives null in direction field. Simple handler:
```
w2ui.masternodes.on('sort', function(event) {
    console.log(event);
});
```

And output:
![screen shot 2017-01-19 at 11 42 26](https://cloud.githubusercontent.com/assets/21372372/22103801/da417688-de3c-11e6-999e-544353827e0d.png)

Is there any other way to get user sort selection? For example to resort grid after row is modified?

**Comment by mpf82** [comment]
You can get the latest sorting from ``grid.sortData``: http://w2ui.com/web/docs/1.5/w2grid.sortData

It should be relatively easy to return the current sorting in the sort event, thus I suggest you leave the issue open.

**Comment by MrDefacto** [comment]
@mpf82 great! Thx again :-) i can use this.

**Comment by MrDefacto** [comment]
still... this was workaround... not good builtin solution :-(

**Comment by mpf82** [comment]
@MrDefacto I will look into adapting the event to properly pass the direction (instead of ``null``)

**Comment by MrDefacto** [comment]
Thank You :-)
