### ISSUE TITLE
updating summary total records

### ISSUE THREAD

**Issue by MrDefacto** [vitmalina/w2ui#1480]
Hi,

Is there a cleaner way to update only total number of records? Not .refresh - which is too much. I just need refresh total after adding/removing record in table.

I'm refreshing total by doing this:

```
var footer = document.getElementsByClassName("w2ui-footer-right")[0]
var spl = footer.innerHTML.split(" ");
footer.innerHTML = spl[0] + " " + spl[1] + " " + w2ui.grid.total.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",");
```

Maybe there is a better solution?

**Comment by mrg2001** [comment]
Nope. Using jQuery will be easier.

**Comment by MrDefacto** [comment]
in what way if I may ask?
