### ISSUE TITLE
search matches only start of string: feature or bug?

### ISSUE THREAD

**Issue by susdu** [vitmalina/w2ui#1481]
If I look for 'AB' I will find 'ABCD'
but searching for 'BC' won't find it. Any idea
how to make it search the entire string?

Edit: I just noticed that advanced search can search based on 'contains'
how can I make this default behavior in basic search?

**Comment by susdu** [comment]
found the place and changed it.

**Comment by mrg2001** [comment]
add operator: 'contains' in your search field
