### ISSUE TITLE
Combobox in toolbar

### ISSUE THREAD

**Issue by zexxar** [vitmalina/w2ui#1483]
Hello,

I have a question regarding the use of a combobox in a toolbar. I really would like to have a combobox in my toolbar just like it is in this grid example [http://jsfiddle.net/8dkdoc4p/5/](url). But it seems, at least to me, that you can't use a combobox in the toolbar at the moment. Is that correct ?

If so, will this be added for 1.5 or is there any alternative solution, that offers the same functionality and can be used in a toolbar ?

Thanks and regards
zexxar

**Comment by mpf82** [comment]
Native toolbar support for all w2field types has already been requested, but is currently not implemented.

See this for a workaround: http://stackoverflow.com/questions/36045032/is-it-possible-to-have-a-date-input-in-a-w2ui-toolbar

See also this issue: https://github.com/vitmalina/w2ui/issues/886

Another option would be to use a toolbar menu and change the menu caption based on the selected menu entry.

**Comment by zexxar** [comment]
Thanks for the quick reply :) 

Then I will try using that workaround for now.

**Comment by mpf82** [comment]
Closing this issue as a duplicate in favor of #886
