### ISSUE TITLE
Tabs with Grid is collapsing every time tab selected

### ISSUE THREAD

**Issue by eliavmaman** [vitmalina/w2ui#1484]
@vitmalina hey friend,
We use your grid alot and we are very stesfied.
I use bootstrap tab or even just plain show/hide functionality, every time tab selected the grid is start from
the left-top corner and collapse to fill the container , the whole thing  take about 2 sec.
![image](https://cloud.githubusercontent.com/assets/6911449/22241224/27abec80-e227-11e6-8813-f7585b306887.png)

this is what happend

the html
```
<div wgrid="columns.bind:columns;
                     records.bind:records;
                     callback.bind:rowClicked;
                     scope.bind:$this;
                     name.bind:gridName;"
                     style="width: 100%;">
</div>
```

the js

```
 setGridColumns() {
        
        this.columns = [
             { field: 'recid', caption: '', hidden: true },
             { field: 'TourPosition', caption: 'Tour Position' ,size: '20%',sortable: true},
             { field: 'PlayerUserName', caption: 'Player user name', size: '20%', sortable: true},
             { field: 'Prize', caption: 'Prize($)', size: '20%', sortable: true,render: 'float:2'},
             { field: 'Team', caption: 'TeamName', size: '20%', sortable: true},
             { field: 'TeamPrize', caption: 'Team prize', size: '20%', sortable: true,render: 'float:2'},
             { field: 'RMStatus', caption: 'RM Status', size: '20%', sortable: true},
             { field: 'AccountStatus', caption: 'Account Status', size: '20%', sortable: true},
             { field: 'RegistrationCountry', caption: 'Registration country', size: '120px', sortable: true}
        ];    
    }

  if (w2ui[this.name]) {
                // w2ui[this.name].clear();
                w2ui[this.name].records = newVal;
                w2ui[this.name].refresh();
            } else {
                this.grid = $(this.element).w2grid({
                    name: this.name || ('grid' + Math.random() * 100),
                    show: {
                        toolbar: this.toolbar || false,
                        footer: this.footer || false,
                        markSearch: this.markSearch || false
                    },
                    multiSelect: false,
                    multiSearch: true,
                    columns: this.columns,
                    records: this.records,
                    reorderColumns: true,
                    sortData: this.sortData
                });
                w2ui[this.name].refresh();
            }
```

can u please help

**Comment by eliavmaman** [comment]
any help friends?

**Comment by daniel-alves** [comment]
w2ui.grid.refresh(); when you click on the tab i do that and works fine.

**Comment by carlosgblos** [comment]
Don't need refresh, just a resize. This happens because it was invisible when you set the grid height

**Comment by mrg2001** [comment]
@carlosgblos - sounds like a most likely what it happens. You should not render grid into div that is not visible. The grid takes dimensions from the div it is rendered in. The best would be to render grid after yo show the div. 

Please close this issue if this is the case.

**Comment by eliavmaman** [comment]
Hey guys i created a  [fiddle](http://jsfiddle.net/x145gn99/)  that describe my problem.
what you need to do is :
1. click on the button to hide the grid.
2. resize the grid container (manually,just drug the borders a bit).
3. click the button a gain to display the grid.

play with that a bit you should see that the grid stack and shrink.

Any idea to solve that please?

**Comment by mrg2001** [comment]
Here is the fix for it http://jsfiddle.net/x145gn99/1/
