### ISSUE TITLE
jQuery 3

### ISSUE THREAD

**Issue by smru** [vitmalina/w2ui#1487]
The Working Example at http://w2ui.com/web/get-started does not work when using jquery 3.1.1.
This is due to a breaking change in jQuery 3. See https://jquery.com/upgrade-guide/3.0/ and search for: "Return values on empty sets are undefined". This causes records.height() to return undefined instead of null. Now the Math.floor() function returns NaN instead of 0.

Also, parseJSON is deprecated in jQuery 3. Please use JSON.parse() instead of $.parseJSON().

**Comment by mpf82** [comment]
This has already been adressed and already been fixed.

Related issues:  #1378 and #1381

This fiddle uses the ``Working Example`` code you're mentioning with JQuery 3.1.1 - looks good to me:

http://jsfiddle.net/octsyvga/1/

If it's still not working for you, please create a fiddle to demonstrate your issue.

**Comment by smru** [comment]
I used w2ui-1.5rc1 instead of the latest build. Everything is working now. Thanks.
