### ISSUE TITLE
w2field list scroll issue in IE 11

### ISSUE THREAD

**Issue by avber** [vitmalina/w2ui#1489]
http://jsfiddle.net/q58gmumL/

Only mouse can be used to scroll dropdown list.
If you click on the scrollbar, dropdown list is hidden.

This doesn't happen in FF.

P.S.
http://w2ui.com/web/demos/#!forms/forms-2
doesn't work on jsfiddle.net

http://jsfiddle.net/bjj1qa15/

**Comment by Connum** [comment]
I fixed the scrollbar issue in IE11 (pull #1497 currently pending).
