### ISSUE TITLE
Only suggestion, not issue :)

### ISSUE THREAD

**Issue by Rimokas** [vitmalina/w2ui#1490]
Hi,
I want you to suggest to renew font-awesome ... At this time it have a new fonts, but in w2ui-master\libs\font-awesome I'm not finding them . Can be it renewed time by time ? :) 
Thanks in advance ...

**Comment by Connum** [comment]
I have implemented this in pending pull #1495

**Comment by Rimokas** [comment]
Thanks ! :)

**Comment by Connum** [comment]
by the way: font-awesome is not integrated into w2ui, so the font-awesome files in the libs are only used for the documentation/test/demo pages. So even without my update, nothing prevents you from using the latest font-awesome version in your projects using w2ui! ;-)

**Comment by mrg2001** [comment]
@Connum is right. There are a few icons in w2ui as its own font. It is included as data url in css.

**Comment by mrg2001** [comment]
See https://github.com/vitmalina/w2ui/pull/1495
