### ISSUE TITLE
Toolbars large icons

### ISSUE THREAD

**Issue by thipages** [vitmalina/w2ui#1491]
Hi,
I try to put larger icons from Font awesome in a toolbar, but does not work.
Here is a [code Pen](http://codepen.io/thipages/pen/EZbzyj)

Any ideas? Thank you

Note :  I used codePen since I can not work properly with Fiddle

**Comment by mrg2001** [comment]
You also need to change CSS for large icons, here is an example 
```
.w2ui-toolbar table.w2ui-button .w2ui-tb-caption {
  font-size: 20px;
  padding: 8px 14px 0px 10px;
}

.w2ui-toolbar table.w2ui-button .w2ui-tb-image>span {
  font-size: 25px
}
```

**Comment by thipages** [comment]
Thank you
I have updated code Pen
