### ISSUE TITLE
Inline editting/Add/Remove for w2ui url based grid

### ISSUE THREAD

**Issue by r7iba** [vitmalina/w2ui#1492]
Hi Vitmalina,
First of all, I wanted to thank for this wonderfull library and congratulate you for this huge work and effort !
I'm Rihab, a python dev and I'm now working on a project in which I wated to use the w2ui library.
I started by showing and sorting grids using url method but now I'm facing a problem becuse I can't find a way to add/remove/inline edit records when using url method to load the grid?
I wish you could help me to find the right way to do so.
Looking forward to seeing your answer.
Best regard,
Rihab.

**Comment by mpf82** [comment]
There are 2 python server implementations right here: https://github.com/vitmalina/w2ui/tree/master/server/python

They both handle get / save / delete requests.

Note: they are not yet updated to work with w2ui 1.5 - See [this issue](https://github.com/vitmalina/w2ui/issues/1351) for hints on how 1.4 and 1.5 differ.

About inline editing: you need to keep in mind that you don't get a single record, but an array of records.

If your ``url`` is pointing to a JSON file you still need to write the backend to handle saving/updating the records.

If you are stuck and have a specific programming question, you should visit stackoverflow instead.

**Comment by r7iba** [comment]
Hi mpf82 !
Thank's a lot for your answer.
I'll see the python server ssolutions you suggested to me.
For my url returns an ' application/json' content-type which is the result of an SQL request for a data base  using flask API RESTful.
I'm really new in this field and if I got a stack I will go to stackoverflow as I always did.
Thank a lot again for your answer.
Best reagrds.
Rihab.
