### ISSUE TITLE
Minor regex fix for isEmail check

### ISSUE THREAD

**Issue by stmansour** [vitmalina/w2ui#1493]
Hi - the check did not allow email names with dashes. This is a valid character for the name (started receiving a bunch of them, that's when we found the issue). 

I changed this:
    var email = /^[a-zA-Z0-9._%-+]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}$/;
to this
    var email = /^[-a-zA-Z0-9._%-+]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}$/;

Now it works for email addresses like ys-k37@outlook.com.  This is a very quick fix.  But I can do a pull request if that helps.

-S

**Comment by Supme** [comment]
and domain, for example "@dmbasis.agency", have more then 4 litters
and domain "@тюменев.рф"...

**Comment by Supme** [comment]
Best way convert domain to punycode and after validate this
