### ISSUE TITLE
Grid filter error in v1.5 and v1.4

### ISSUE THREAD

**Issue by daniel-alves** [vitmalina/w2ui#1494]
Im testing filters on w2ui grid when i type the search field is submited the logic OR and operator 'begins', the previous version v1.4 submits 'contains' and that is right because i need to filter by 'contains' and not 'begins'.

Another point in v1.5 is when i select a filter field of type float then is submited operator 'begins' and should be 'is' because in SQL cant filter 'begins' in float fields. 
In v1.4 is submited 'contains' when select a float field to filter and shoud be 'is' too by the same reason.

My sugestion is to remove lists or submit only type text when submiting with logic OR , and not submit operators wich not is possible to do SQL search with the type of the filter.

**Comment by mpf82** [comment]
You can set the search behaviour yourself: ``grid.textSearch``

I don't get your second point - in my test grid (w2ui 1.5), if I use the "quick search", it will submit the correct search operator for each field, based on the default operator for the field type. So even if strings are searched with "begins" or "contains", numeric fields are serched with "is".

Example: 

> **'search'**: [{'value': '123', 'type': 'int', 'field': 'f_int', 'operator': 'is'}, {'value': '123', 'type': 'text', 'field': 'f_char', 'operator': 'begins'}, {'value': '123', 'type': 'text', 'field': 'f_varchar', 'operator': 'begins'}, {'value': '123', 'type': 'text', 'field': 'f_clob', 'operator': 'begins'}, {'value': 0, 'type': 'datetime', 'field': 'f_unix_time', 'operator': 'is'}, {'value': 19700101, 'type': 'date', 'field': 'f_datumn', 'operator': 'is'}, {'value': '19700101010000', 'type': 'datetime', 'field': 'f_datuz', 'operator': 'is'}, {'value': '123', 'type': 'enum', 'field': 'f_enum', 'operator': 'is'}, {'value': '123', 'type': 'list', 'field': 'f_list', 'operator': 'is'}, {'value': '123', 'type': 'color', 'field': 'f_color', 'operator': 'is'}, {'value': '123', 'type': 'list', 'field': 'f_check', 'operator': 'is'}], 
> '**searchLogic**': 'OR', 
> '**cmd**': 'get'

**Comment by daniel-alves** [comment]
Thx for help this works: `grid.textSearch: 'contains' `

I'll check the second point I tested now again and also did not happen maybe happen under some specific circumstance if I can reproduce I notice.
