### ISSUE TITLE
clean up the issues section

### ISSUE THREAD

**Issue by Connum** [vitmalina/w2ui#1502]
Hi vitmalina and whoever else has the rights to do this: Would it be possible to close any issues that have already been fixed / declared as not fixable in order to clear up the issues list?
We're at over 200 now and it's really difficult to find out what issue to address next... I would like to help fixing, but I'm a bit overwhelmed... :-)

**Comment by mrg2001** [comment]
Got it. Merging and closing now what I can. Thanks for you help.
