### ISSUE TITLE
Tree-View: Child record bugs

### ISSUE THREAD

**Issue by DigitalFlow** [vitmalina/w2ui#1505]
Hey everyone,

First up, thanks for this awesome library, I use it a lot.

I recently adapted to the 1.5 RC and the tree like grid is really awesome.
However I found two bugs with child records:
- When doing changes to child records and collapsing their parent record again, the save button will be disabled if there were only changes in now hidden child records.
- Probably related to the first one: When iterating through all records in a grid by using the grid's records property, child records are only returned, if they are currently expanded. I think they should always be returned.

I created a [fiddle](http://jsfiddle.net/p5pyhd04/) where you can test the issue.
Just expand a parent record, edit some column in a child row. The save button will get enabled.
Once the parent is collapsed again, the Save Button will get disabled, although the changes are still in the child record.

Thanks for reading this.

Kind Regards
Florian

**Comment by Connum** [comment]
Hi DigitalFlow,

I just added a pull request that addresses this problem. When checking for changes, children will now be checked recursively.

If you want to get all records including the children, you'll have to iterate over the records property manually and see whether a record is not expanded but has something in its .w2ui.children array.

All the best
Connum

**Comment by DigitalFlow** [comment]
Hey Connum,

Awesome, thanks for your PR!
When retrieving all records including children, we must pay special attention to the children, since they will show up as plain record, but also as child of a record, so we should not add them twice.
I'll either get all records using a dictionary for uniqueness or try expanding all parents first before walking the records array.

Again, thanks for your help!

Kind Regards,
Florian

**Comment by Connum** [comment]
Yes, that's exactly the problem I stumpled upon while trying to fix this. :-) We could also add a .getAllRecords() method that will return a one-dimensional array holding all records, regardless of parent/children relationship. This could then also be used inside the .getChanges() method instead of calling it recursively (like I now did for the fix). But this is something that I would like to discuss before implementing it, and first the fix should be integrated I guess.

Kind regards
Connum

**Comment by DigitalFlow** [comment]
Hey Connum,

Sounds like a good idea to me :+1: 
Should I leave this issue open for discussion?

Kind Regards,
Florian

**Comment by Connum** [comment]
I'd suggest to keep this open and wait for Feedback from @mpf82 or @vitmalina!

**Comment by mpf82** [comment]
@Connum : I'm only a contributor (I guess you get the same status once your PRs are merged), the only ones who can really decide what gets added to the library are @vitmalina and @mrg2001

**Comment by Connum** [comment]
Sorry, mixed you up with marg2001, whom I wanted to mention. :)

**Comment by mrg2001** [comment]
Merged mentioned PR
