### ISSUE TITLE
Search is not working for https

### ISSUE THREAD

**Issue by sj11** [vitmalina/w2ui#1507]
Hi @vitmalina,
Thanks for the awesome library.I am using it from the past 2 years.I wrote the code  for searching the data in a  table from json file.I used the server side scripting to fetch the search value.It was working fine in url with http.However when i deployed the same code with https it is no working.Please help me on this.

**Comment by Connum** [comment]
Hi there,

can you please provide a link to an example implementation? Are there any errors in the console?

**Comment by mpf82** [comment]
Sounds like a problem with your backend. 
I can switch from http to https just fine (running CherryPy, but I doubt the server matters).

My grid url is relative - maybe you've got the scheme hardcoded to _http_ in the url?

As @Connum said, you should check your console and also your browser's network tab - then compare the request and response (headers and payload) for http and https.

**Comment by mrg2001** [comment]
I also fail to see how https can be a problem in UI.
