### ISSUE TITLE
About the current version

### ISSUE THREAD

**Issue by pierpaolocira** [vitmalina/w2ui#1509]
Hi and congratulation for this library.

I would like to use the 1.5 version (for new features it introduces), but it seems not to still be a stable release.
Do you have any plan about releasting a stable 1.5?

What is currently missing for that?

Thanks

**Comment by pierpaolocira** [comment]
I'm asking this because it finally seems to solve the #978 and #1125

**Comment by mrg2001** [comment]
1.5 is considered stable. The final release delay is due to incomplete documentation. It would be safe to use 1.5rc1
