### ISSUE TITLE
Tree-like grid and more usable to view expanded children records

### ISSUE THREAD

**Issue by alexey-vasyunin** [vitmalina/w2ui#1511]
Hello!

It is more willing than the problem.

It convert my grids from from 1.4 to 1.5 and from grid/subgrids to tree-like grid. It's more handy to use tree-like grid. But there is one thing was lost in tree. Grid/subgrids are more informative bacause have wide border. For example:

![image](https://cloud.githubusercontent.com/assets/5081020/22827682/8ce5ba70-efb2-11e6-89ff-b232173a363c.png)

 Every subgrid separated from previous with border and background grid row. Also, every nesting level  has own left indent with background.

Here I have w2grid v1.5

![image](https://cloud.githubusercontent.com/assets/5081020/22827780/fd85a1dc-efb2-11e6-9ebd-2083c8f4ba42.png)

And it's harder to see levels in my opinion.
Mayby somebody have any css style to fix this?

**Comment by mrg2001** [comment]
Alexey, please submits bugs only here. All other items please to stackoverflow or w2ui.com comments
