### ISSUE TITLE
Small errror in locale ru-ru

### ISSUE THREAD

**Issue by alexey-vasyunin** [vitmalina/w2ui#1512]
Hello!

There are a small error in locale file ru-ru.json
Line 83 - last string translate:

> "Yesterday": "Вчера",

Remove last comma, pls. Chrome can't load locale file with it. "ERROR: Cannot load locale /w2ui/src/locale/1.5/ru-ru.json"

thanx

**Comment by mrg2001** [comment]
Fixed
