### ISSUE TITLE
Projects that use w2ui: wxFormBuilder does not seem to use w2ui

### ISSUE THREAD

**Issue by user1713952** [vitmalina/w2ui#1522]
I have looked through the source code of wxFormBuilder on [github](https://github.com/wxFormBuilder/wxFormBuilder) and searched for w2ui but found nothing. Did I overlook something?
The interface that wxFormBuilder has is actually close to what I need so I was really interested in looking into their code..

**Comment by edomato** [comment]
Hi, wxFormBuilder is a tool for wxWidgets and has nothing to do with w2ui.

**Comment by mrg2001** [comment]
Unrelated
