### ISSUE TITLE
Need Select All Check Box in Grid Header -

### ISSUE THREAD

**Issue by jackryu** [vitmalina/w2ui#1526]
**Hello Team,
I need select all check box in w2 UI grid column header like row selection checkbox - this is very urgent for me please help -**

reference snapshot attached - 
![need select all checkbox](https://cloud.githubusercontent.com/assets/6933841/23130315/fff732d6-f7ab-11e6-8488-d8c66ba89f3a.jpg)

**Comment by mrg2001** [comment]
You can add checkbox in caption property when you define column.
```
columns: [
   { fileld: "field", caption: 'Call Maker <input type="checkbox" style="float: right;..." onclic="w2ui.grid.callMarkerSelectAll(this)">' }
   ...
]
```

**Comment by jackryu** [comment]
@mrg2001 - Thanks for quick reply - checkbox added but this is not working if I am click on check box this is not checked data is sort.

**_Requirements..._** 
If I check box is checked then all check box is selected and editing mode is enable.
If I check box is unchecked then all check box is deselected and editing mode is enable.

Please help I am working on this problem for last week I am found one solution but this is complicated and its hard to manage......

**Comment by mrg2001** [comment]
@jackryu I just pointed you to a solution, I did not provide a complete example. Here is the summary again.

1. You add a checkbox to a column and in onClick of that checkbox you call a custom function you defined on the grid
2. You create custom function on the grid which when called will loop through records and set state of checkbox as checked.
3. refresh grid

Create a jsFiddle and do as much as you can. I will help you finish. Attach jsFiddle link here.

**Comment by jackryu** [comment]
@mrg2001 - Thanks for support I will try....
