### ISSUE TITLE
grid search "x" disappears after refresh.

### ISSUE THREAD

**Issue by tristenator** [vitmalina/w2ui#1527]
after searching and the results are shown a little "x" appears at the right of the search input for clearing the search. if a refresh of the grid occurs whilst search results are shown then the little "x" disappears and the user can't clear the current search.

the workaround is to type a new search, hit enter, and then the little "x" appears again, at least until the next refresh occurs.

no biggie, just a minor annoyance!

**Comment by mpf82** [comment]
I can not reproduce your issue. What I tried:

1) Open http://w2ui.com/web/demos/#!grid/grid-15
2) Search something
3) in the browser console enter ``w2ui.grid.refresh();``

Result: The little ``x`` is still there.

Can you create a fiddle?

**Comment by tristenator** [comment]
i beg your pardon - it was indeed a caching issue after upgrading to this new rc1, i'll close it out.
