### ISSUE TITLE
Date format in grid

### ISSUE THREAD

**Issue by carlhussey** [vitmalina/w2ui#1532]
Our dates are: 14 Jun 2016.

I have the column definitions set up as follows:

{ name: 'field_date', type: 'date', options: { format: 'DD Mon YYYY' }}

As it stands, the column is still out of order when I try and sort on that column.

Are there any ways to use custom date formats like this?

**Comment by vitmalina** [comment]
In order for dates to be sortable properly and be formatted, it would be best if you would create record data in this column in unix timestamp format. You can create JS date object form unix time in the following way
```
new Date(unix_time)
```
You can convert JS date object into unix time:
```
(new Date()).getTime()
```
If data is in this format - it will be sortable. Also, you can define render function as date, when defining columns
```
columns: [
{ field: 'field_date', caption: 'date', size: '90px', render: 'date' }
...
]
```
see http://w2ui.com/web/docs/1.5/w2utils.formatters for other formatters.

Alternatively, you can pass the date in "yyyy-mm-dd", then it will be sortable too. Or as JS Date objects. I personally like unix time as it is the easiest to work with as it takes care of timezones and easy to compare, add, subtract dates. Search fields will work too

**Comment by asvinze** [comment]
I am passing unix timestamp to the grid and the date is displaying well. However if I want the it to be displayed always in UTC irrespective of the user's local timezone, Can I send the timezone information to the datetime formatter alongwith the unix timestamp?
