### ISSUE TITLE
Error in the height of first row

### ISSUE THREAD

**Issue by mendozada** [vitmalina/w2ui#1539]
Hi, I have a problem when I search the grid that shrinks the size of the first row.

Here I show you
[https://drive.google.com/file/d/0BzizXydiA888UGxvYVYyZVNDZ1U/view?usp=sharing](https://drive.google.com/file/d/0BzizXydiA888UGxvYVYyZVNDZ1U/view?usp=sharing)

I set recordHeight : 70,

I created a jsfiddle but it works perfectly here [http://jsfiddle.net/y81cyj54/1/](http://jsfiddle.net/y81cyj54/1/)

I do not understand that it can happen since the json generated from php is similar to the one used here.

I appreciate any help

Diego.

**Comment by mrg2001** [comment]
When search is applied it would highlight result. There might be a bug in highlight function when there are certain tags. Try set grid.markSearch = false and see if it helps. There is a plugin $.w2marker() that does the highlighting.

**Comment by mendozada** [comment]
Hello, thank you very much for the help.
The problem appears when you freeze the column, (look at this example when you look for John X)
[http://jsfiddle.net/y81cyj54/2/](http://jsfiddle.net/y81cyj54/2/)
Getting the Frozen , it's perfect.

Thank you so much . :+1:
