### ISSUE TITLE
Searching HTML String

### ISSUE THREAD

**Issue by carlhussey** [vitmalina/w2ui#1542]
I have a few data points in my grid source which are HTML strings. Specifically, links such as `<a href="http://site.com/bob">Bob's Personal Website</a>`. 

When I try to do a search for Bob, it is not finding the row where the keyword is within the HTML.

If I searched for the whole HTML string though, it finds it just fine.

Is there a setting I can notify the column of the HTML content so it handles the searches differently? I don't really have a way to modify the data source so hopefully a function like this exists.

**Comment by mpf82** [comment]
change grid's textSearch property to ``contains``.

     grid.textSearch = 'contains';

or within the contructor:

    var grid = $('#grid').w2grid({ 
        ...
        textSearch: 'contains'
        ...
        });

**Comment by carlhussey** [comment]
Sweet! Thanks so much.

**Comment by mpf82** [comment]
You're welcome. Updated docs should be up soon: https://github.com/vitmalina/w2ui/pull/1544
