### ISSUE TITLE
How can I catch w2ui-search-advanced's action?

### ISSUE THREAD

**Issue by vt167098** [vitmalina/w2ui#1545]
Hi,

In grid toolbar's search form, then input data to form field.

Can I catch input action or trigger onchange event? 

How can I do?

Thks

**Comment by spizzi77** [comment]
For sure,
In the refresh event...like this, where nameGrid is the name of your grid

```javascript
        onRefresh : function(event){
			event.onComplete = function(event){
				$('#grid_'+nameGrid+'_search_all').on('change',function(event){
					w2alert('Onchange');
                                        event.stopImmediatePropagation();
				});
                       }            
          } 
```

**Comment by mpf82** [comment]
@vt167098 Is your question answered? Can this issue be closed?

**Comment by mpf82** [comment]
Closing issue: no response
