### ISSUE TITLE
grid toolbar search icon fixed on toolbar overflow

### ISSUE THREAD

**Issue by ratones** [vitmalina/w2ui#1547]
When toolbar overflow on a grid toolbar, if you scroll to the left, the search icon of the search box stays fixed, overlapping other buttons
see screenshot
![capture](https://cloud.githubusercontent.com/assets/1935273/23821997/e76f9688-064a-11e7-90a4-4658382e4be8.PNG)

**Comment by mpf82** [comment]
Hi,

this should have been fixed with this PR: https://github.com/vitmalina/w2ui/pull/1394

Which version are you using? Can you create a jsfiddle to demonstrate the issue?

Cheers :)

**Comment by ratones** [comment]
Sorry, my bad. Using an older version from another project.
Confirm  it is fixed an close!
Nice work, btw
