### ISSUE TITLE
Combobox lookup view 

### ISSUE THREAD

**Issue by Rimokas** [vitmalina/w2ui#1550]
Hello,

This isn't issue, but I don't know where to ask about problem ... so, exuse, I'm writing here . Please direct , where I can to write about small problems ...

Mine problem is a WIDTH of combo box lookup . Now I have about 2 weeks old sources from gitHub . All is working fine ... Here I found an old post of combobox in jsFidle : http://jsfiddle.net/8dkdoc4p/5/ . It use 1.4.2 version . You can see that combobox width it can be wider than column . Picture : 

![problem1](https://cloud.githubusercontent.com/assets/12154604/24008204/a4155d36-0a79-11e7-9fb7-196bd449c7c6.png)

Now I have a combobox in own aplication . And here I'm using Id + name as combobox "text". But ComboBox width is related to width of column. Ilustrate : 

![problem_ilustr2](https://cloud.githubusercontent.com/assets/12154604/24008602/c075d00e-0a7a-11e7-8149-6e3c53fc2980.png)

So user must to do a very width column , to see what is in lookup : 

![problem_ilustr3](https://cloud.githubusercontent.com/assets/12154604/24008651/e0fe78a8-0a7a-11e7-9bef-78acf704e61c.png)

Can this be done as in 1.4.2 version, then combobox is wider than column ? Or maybe I something missed ? 

Thanks in advance ...

**Comment by Rimokas** [comment]
Hi,

I forgot to say that mine combobox data is from server/remote ...

**Comment by natxocc** [comment]
Yes, I can confirm the same problem, with or without remote/server data.

**Comment by natxocc** [comment]
Is it possible to repair this bug?
Thanks in advance!!

**Comment by mrg2001** [comment]
Fixed in latest, but you still will need to pass align: 'left' when defining editable column, 

```js
            { field: 'combo', caption: 'combo1', size: '50%', sortable: true, resizable: true, editable: { align: 'left', type: 'combo', items: people } },
```

**Comment by natxocc** [comment]
Great!!!
Thanks!!

**Comment by Rimokas** [comment]
Hi,

Downloaded today ( 04 day ) zip of recompiled JS (I'm seeing that it's 6 days old ). Can't confirm that problem is out. The same view . Here it's mine description of combobox field ( copied from debugger ) : 

caption:"Prekės ID"
editable:Object
align:"left"
minLength:0
openOnFocus:true
postData:Object
showAll:true
type:"combo"
url:"phpf/dmas.php"
__proto__:Object
field:"preke"
hidden:false
hideable:true
resizable:true
size:"106px"
sortable:true
length:0
__proto__:Array(0)

Thanks in advance for any help ...

**Comment by Rimokas** [comment]
Oh, sorry, excuse me. I don't noticed that fix at this moment is only for source ... Yes! :) It's working fine now. Thanks you. Will wait for recompilation ...
