### ISSUE TITLE
Set object is not update all records

### ISSUE THREAD

**Issue by jackryu** [vitmalina/w2ui#1552]
Hello -

I am trying to update all records using "w2ui['grid'].set({ fname: 'none' });" function but this is update only first page record not all records... please help.

![error snap](https://cloud.githubusercontent.com/assets/6933841/24212804/8c40cce0-0f56-11e7-8bee-be107fe26a39.JPG)

**Comment by mrg2001** [comment]
grid.set(recid, obj) - it takes first argument as recid. There is no mass update of records. The easies way would be to loop through grid.records array, update what you need and call grid.refresh()

**Comment by mpf82** [comment]
Uhm, actually, in the [docs](http://w2ui.com/web/docs/1.5/w2grid.set) it says:

> Or you can update one parameter in all records:
> ``w2ui['grid'].set({ fname: 'none' });``

Judging from the code:

        set: function (recid, record, noRefresh) { // does not delete existing, but overrides on top of it
            if ((typeof recid == 'object') && (recid !== null)) {
                noRefresh = record;
                record    = recid;
                recid     = null;
            }
            // update all records
            if (recid == null) {
                for (var i = 0; i < this.records.length; i++) {
                    $.extend(true, this.records[i], record); // recid is the whole record
                }
                if (noRefresh !== true) this.refresh();
            }

it *should* work.

I currently don't have time to test it, though.

**Comment by jackryu** [comment]
thanks - @mpf82 
**Its work - but records status is not update to modified.** 

after this code - i am gating all 

> var updatedRows=w2ui['gridIABU'].changes;


_**this red mark**_
![image](https://cloud.githubusercontent.com/assets/6933841/24305208/2e56e5b4-10e2-11e7-8fdf-4ea2c78197e4.png)

but this is showing blank.... 

**all record selected but red mark identifier is not showing on records**
