### ISSUE TITLE
Last column disappear after reordering columns, when column header's caption contains html 

### ISSUE THREAD

**Issue by PCS-Ismail** [vitmalina/w2ui#1553]
Hello there,
If the column header's caption (w2ui-col-header) contains html, for example: caption: '\<div\>Email\</div\>' (I escaped it on purpose here for the issue, but as you will see below in jsfiddle, it's just a normal html div). 
and if we try to reorder that column, then the last column of the grid disappear.

Using w2ui-1.5.rc1

JsFiddle: http://jsfiddle.net/vx0do63h/

**Comment by mrg2001** [comment]
Can you please create jsFiddle with the problem.

**Comment by PCS-Ismail** [comment]
Sorry about that, there you go http://jsfiddle.net/vx0do63h/

**Comment by carlosgblos** [comment]
Hi dear, 
any news on this issue ? I'm having the same!
