### ISSUE TITLE
Grid - click on selected row remove selection background in multi-select mode

### ISSUE THREAD

**Issue by eliavmaman** [vitmalina/w2ui#1558]
Hey, We use w2ui grid on single selection mode, we wanted to keep the selected row when clicking on the row multiple times.
that what worked for me 
```
  onUnselect: function (e) {
                var sel = this.getSelection();
                if (sel.length >= 1 && sel[0] == e.recid) {
                    var recEl = $('#grid_' + this.name + '_rec_' + w2utils.escapeId(e.recid));
                    if (recEl.length != 0) {
                        recEl[0].style.cssText = 'height: ' + this.recordHeight + 'px; ' + recEl.attr('custom_style');
                    }
                    e.preventDefault();
                }
            },
```

But the problem is with multiselect mode,
ithe ```e.recid``` always return the last record **and not the new clicked one**.

**Comment by mrg2001** [comment]
Can you please create jsFiddle

**Comment by mpf82** [comment]
@mrg2001 This issue can probably be closed due to inactivity.

**Comment by mpf82** [comment]
Closing issue: no response, no reproducer
