### ISSUE TITLE
Filling form remotely

### ISSUE THREAD

**Issue by mendozada** [vitmalina/w2ui#1559]
Hello, I'm having a problem filling out a form
I have a layout, on the right a grid and on the main I have a form
The idea is that when clicking on the grid I fill up with remote data form, but I can not do it, someone could help me ???

I tried

`onClick:
            function(event){
               var form = w2ui.form;
                var record = this.get(event.recid);
                $.ajax({ type   : 'GET',
                        url     : 'consultas/Persona_Det.php',
                        data    : {Id : record.recid},
                        success : function (resultado) {
                              form.record = resultado;
                              form.refresh()
                            }
                      });
},
`

and my PHP scripts return JSON 

`
{"recid":"2","Legajo":"2","ApeNom":"SOLANA, JUAN CARLOS ","TipoDoc":"D.N.I.","NroDoc":"12049530","Cuil":"20-12155330-4","Tel":"388854314849 8887796","Celular":null,"FechaNac":"-423349200000","IdCat":"12","CodPostal":"2900","Domicilio":"CHACABUCO 532","Barrio":"","Nacionalidad":"ARGENTINA","Foto":"","activo":"0","adelanto":"1","Observaciones":".","categoria":"Oficial Multiple","Localidad":" San Nicol\u00e1s","Provincia":"Buenos Aires","IdConvenio":"5","convenio":"Luz y Fuerza"}
`

Also try

w2ui['form'].url = 'consultas/Persona_Det.php';
w2ui['form'].reload();

But I can not get the form filled out and do not throw any mistakes

[jsfiddle.net](http://jsfiddle.net/y81cyj54/10/)

Thank.

**Comment by mkaim** [comment]
1. Your JSON key names don't matches to form input names. Your current form expects data like this:
`{
  recid: "2",
  fname: "Doe",
  lname: "John",
  email: "john@gmail.com",
  sdate: "01/03/2012",
  office: "something",
  state: "something"
}`

2. Make sure that `resultado` is a JSON object, not a string - add `dataType : "application/json"` argument to `$.ajax()` method and try your first solution again.

Don't even try your second solution - that's not the way it works.

**Comment by mendozada** [comment]
Mkaim, Perfect, i add dataType: 'Json' and is working
Thanks.
