### ISSUE TITLE
Improve Copy/Pasting system in Grid

### ISSUE THREAD

**Issue by remmel** [vitmalina/w2ui#1560]
Hello,

Currently when copying it copies the text displayed not the record value.

Problems:

- when using a render "eg render: 'float:2'" and if the value is 2.123, the value copied will be 2.12
- when using a list eg record.people:{id:1,text:John}, the value "John" will be copied

Eg: http://jsfiddle.net/remmel/7ogzLh72/ when copying the first line:
![w2ui grid](http://i.imgur.com/tblqC2P.png)

- I get :    "1	1.00	John	"
- I'm expecting :     "1	1.001	1	true"

Here are the different solutions :

1. Copy/paste the id and stores {id:1,text:John} in record.people / record.w2ui.changes.people

- When copying get id (if record.field is object, get id).

- When using the autocompletion, it already puts id&text

- When pasting
  - looks for the text in editable.items. If not make an ajax call to the one specified with the text; cache it or not in editable.items
  or
  - copies only the id and when rendering look for the text if not already in editable.items

2. Copy/paste the id  and stores in record.name the id only. When render will look for id in items. (+) simpler /  (-) a lot of ajax call when the list is coming for db
3. Copy/paste the id/text "encoded" Eg: {id:1,text:John} will be copied "1|John" => Nice to have the label when coping in excel
4. Copy/paste the id/text as 2 columns, may need to display the 2 columns to be able to copy/paste in the same doc

Which solution seems to be the best ?

To be more concrete, when copy pasting into Excel how do the data will be copied ?
![Excel solutions](https://i.imgur.com/0et0XbG.png)
https://docs.google.com/spreadsheets/d/1HiU6Rl5oSZcN-G3i51ApjRgOV_BehrKmYVbIzRxSwX8/edit?usp=sharing

http://w2ui.com/web/docs/1.5/w2grid.copy

**Comment by mrg2001** [comment]
Since the pull request is merged, I am closing this issue.
