### ISSUE TITLE
Remote  data Source & Infinity Scroll Using ASMX Service.

### ISSUE THREAD

**Issue by IAmAbhishekTomar** [vitmalina/w2ui#1561]
**Query :** _I need to load data & Infinity Scroll from remote location  and apply CRUD operation using ASMX services any one can help.._

**_## My Reference Code_** 

_ASMX Services Code_

  
```
 [WebMethod(Description = "Get Rule Details")]
    [ScriptMethod(ResponseFormat = ResponseFormat.Json, UseHttpGet = true)]
    [WebGet(ResponseFormat = WebMessageFormat.Json)]
    public string nwGetRules()
    {
        try
        {
            Cubics.ApplicationLayer.RootRules _RootRules = new RootRules();
            return JsonConvert.SerializeObject(_RootRules.GetRuleDetails(), Formatting.Indented, new JsonSerializerSettings
            {
                ReferenceLoopHandling = ReferenceLoopHandling.Ignore
            });
        }
        catch (FaultException ex)
        {
            string msg = ex.Message.ToString();
            throw new FaultException(msg);
        }
    }
```

**_JSON Object Fromat_**

`[ { "RuleID": 1, "RuleName": "085 Block 2.0", "RuleDescription": "Block All 085 Inventory data.", "RuleLogic": "ABC", "RuleJSON": "XYZ", "IsPublic": false, "IsOnAir": false, "COMMENT": null, "status": "success", "total": 12 } ]`

_**JavaScript Code for Bind W2UiGrid**_ 

```

$(document).ready(function () {
    var config = config_grid.grid_RuleDetails;
    console.log('grid objects',config);
    $('#gvRuleDetails').w2grid(config);
    w2ui['gvRuleDetails'].load('../WebService.asmx/nwGetRules');
    //w2ui.gvRuleDetails.autoLoad = auto;
    //w2ui.gvRuleDetails.skip(0);
});


var config_grid = {
    grid_RuleDetails: {
        name: 'gvRuleDetails',
        load: '../WebService.asmx/nwGetRules',  // url:'../WebService.asmx/nwGetRules'
        recid:'RuleID',
        show: {
            footer: true,
            toolbar: true
        },
        columns: [
            { field: 'RuleID', caption: 'ID', size: '50px', sortable: true, resizable: true },
            { field: 'RuleName', caption: 'Name', size: '140px', sortable: true, searchable: 'text', resizable: true },
            { field: 'RuleDescription', caption: 'Description', size: '140px', sortable: true, searchable: 'text', resizable: true },
            { field: 'RuleLogic', caption: 'Logic', size: '100%', resizable: true, sortable: true },
            { field: 'IsPublic', caption: 'IsPublic', size: '200px', resizable: true, sortable: true },
            { field: 'IsOnAir', caption: 'IsOnAir', size: '200px', resizable: true, sortable: true },
            { field: 'CreatedBy', caption: 'Created By', size: '200px', resizable: true, sortable: true },
            { field: 'CreatedOn', caption: 'Created On', size: '200px', resizable: true, sortable: true },
            { field: 'ModifiedBy', caption: 'Modified By', size: '200px', resizable: true, sortable: true },
            { field: 'ModifiedOn', caption: 'Modified On', size: '200px', resizable: true, sortable: true },
        ]
    }
};

```

_I will Use load and URL both object._

**Comment by mpf82** [comment]
Since this is not a w2ui issue, it would probably be better to post this on StackOverflow.

Just two heads-up comments up front: 

1) you should provide a ``limit`` on your grid and handle that limit on the server side for infinite scrolling to work.

2) It seems your JSON is mixing the response header and the record(s). You should look at the expected data structure described here: http://w2ui.com/web/docs/1.5/grid/overview#data-structures

**Comment by jackryu** [comment]
thanks fro Quick reply.... @mpf82 

> My this issue  #1552 still pending. Please see if you have a time.

**Comment by jackryu** [comment]
No file in net folder  in existing server examples - https://github.com/vitmalina/w2ui/tree/master/server

**Comment by jackryu** [comment]
Hello,

I am create may type of solution but above problem is not resolve.

Please provide any help or reference.

How to implement Infinity Scroll  in w2ui grid using ASMX services.

**please any one can help me .**

stackoverflow link :
https://stackoverflow.com/questions/43235555/w2ui-grid-remote-data-source-infinity-scroll-using-asmx-service
