### ISSUE TITLE
sidebar icon and img not working

### ISSUE THREAD

**Issue by iwzoo** [vitmalina/w2ui#1563]
`            function getNodeHTML(nd) {
                var html = '';
                var img  = nd.img;
                if (img == null) img = this.img;
                var icon = nd.icon;
                if (icon == null) icon = this.icon;
`

these to lines in function getNodeHTML()  should be obj.img and obj.icon, otherwise the global icon and img will not work

**Comment by mrg2001** [comment]
It is either or. Icon has higher preference. If both defined, icon will be displayed. Icons come from iconfont, images from sprites. Both are defined with use of css classes. I know this works for sure as it is a fundamental issue and works in all my projects. Provide more details if you have problem and/or create a jsFiddle that shows it.

**Comment by iwzoo** [comment]
@mrg2001 thanks for the reply. 
it seems not working, please check http://jsfiddle.net/ekgpLrhw/2/
I set the global 'img' and removed individual  'img' value of "Level 1" and it's leaves. There is no image appearing anymore.

**Comment by mrg2001** [comment]
Oh! You mean when global is defined. Yes, it was not working. Fixed.

**Comment by mrg2001** [comment]
Will compile later today
