### ISSUE TITLE
How do I put a grid inside a form

### ISSUE THREAD

**Issue by mendozada** [vitmalina/w2ui#1564]
Hi, how do I put a grid inside a form, 
I need to put a grid of details, I set the example
[http://jsfiddle.net](http://jsfiddle.net/y81cyj54/13/)
i set in FORMHTML : `'<div id="gridDet" style="width: 100%; height: 100px;"></div>'`

Thanks

**Comment by mpf82** [comment]
I did it by creating a new field type:

    $().w2field('addType', 'nem_form_grid', function(options) {
        var obj = this;
        var $el = $(this.el);
        var subgrid_name = obj.el.name + '_nem_form_grid';
        // hide the actual field element
        $el.hide();
        // create grid container only once!
        var $grid_el = $("#" + subgrid_name);
        if($grid_el.length){return; }
        $el.after('<div id="'+ subgrid_name +'" class="nem_form_grid"></div>');
        var subgrid_params = { ... };
        // build w2grid
        var subgrid = w2ui_get_grid_content(subgrid_params);
        if(subgrid){
            // render w2grid
            subgrid.render($grid_el);
        }
    });

and in the w2ui form (using auto templates) I use a field of this type:

    {
        name    : 'f_subgrid',
        type    : 'nem_form_grid',
        required: false,
        html    : { caption: ' ', attr: '', text: '', span: 0, page: 5 },
        options : { tablename_form: tablename, tablename_grid: "mdemployeetab", searchData: [ { field: 'empid', operator: 'is', value: 'f_list_int' } ] }
    },

This is what it looks like in my project:

![webtemplate_form_grid](https://cloud.githubusercontent.com/assets/10152404/24960246/7b2d9038-1f95-11e7-8c32-93e1cbb549ae.png)

It might not work out of the box in your project (e.g. ``w2ui_get_grid_content()`` is a method that returns a w2grid object based on given params), but you should get the basic idea.

Ofc this is just **one** way to do it, maybe others have a better idea.

Cheers =)

**Comment by mendozada** [comment]
Hi, mike I'm trying to make your example walk but I'm not making it work, you could tell me if the parameters are well loaded inside Sub_grids
[http://jsfiddle.net/y81cyj54/16/](http://jsfiddle.net/y81cyj54/16/)
