### ISSUE TITLE
On Bubble Click Event For Grid

### ISSUE THREAD

**Issue by jackryu** [vitmalina/w2ui#1565]
Hello Team,

Any existing event like OnBubble Click for Grid info field.

![eventforthis](https://cloud.githubusercontent.com/assets/6933841/24962702/4c0256c0-1fba-11e7-907e-67c64cc6c9a3.JPG)

**Comment by mpf82** [comment]
There's no such event, but you could override ``grid.showBubble()``.

**Comment by jackryu** [comment]
OK, but its good!! for development if "Bubble" support a event without rendering - i will try to add this feature in Grid.  i am working on it.

**Thanks for support. @mpf82** 

Please  close this issue issue **************
