### ISSUE TITLE
Wrong behavior with add method in grid using url

### ISSUE THREAD

**Issue by edomato** [vitmalina/w2ui#1568]
I have a grid in a project that load records using an url.

To save requests to the server, when I add elements to the grid (from a w2ui form), it add the new record as expected, but the problem is that the behavior of selecting the new added record is not working properly because the w2ui-selected class is not added to it like it does to others records already in the grid.

The only way to solve this problem is to "reload" the grid but it could be expensive if you have to do that a lot and with lots of records as a response.

You can test it on http://w2ui.com/web/demos/#!grid/grid-1 by running:

w2ui.grid.add({ "recid": 10, "fname": "Test", "lname": "Tester", "email": "test_tester@example.com", "sdate": "4/3/2017" })

on the console. Then, try to select the new added record and see the difference by selecting any other record.

The rest on the new added record works perfectly fine excepts for this issue.

Thanks in advance.

**Comment by mrg2001** [comment]
You need to increment total as well, run this
``js
w2ui.grid.total++;
w2ui.grid.add({ "recid": 10, "fname": "Test", "lname": "Tester", "email": "test_tester@example.com", "sdate": "4/3/2017" })
```

The reason it does not auto increment total because you have remote data source, which means total and the number records in the grid can be different. For local data source, it does increment total. In case of remote, the total is the number of records in DB, so it would know if it needs to request more.

**Comment by edomato** [comment]
Great, it worked perfectly.

Thanks for the response and I think that it should be clarified on the documentation maybe :-)
