### ISSUE TITLE
coloring only a part of the cell in the grid

### ISSUE THREAD

**Issue by susdu** [vitmalina/w2ui#1570]
is it possible using the w2ui[style] notation?
Let's say I want to make a 50:50 black/white cell

**Comment by mpf82** [comment]
This is not a w2ui issue, but the general answer is: Yes, it should be possible by creating a CSS gradient with 4 steps: black-black-white-white

    background: linear-gradient(to right, rgba(255,255,255,1) 0%, rgba(255,255,255,1) 50%, rgba(0,0,0,1) 51%, rgba(0,0,0,1) 100%);

**Comment by susdu** [comment]
Hi mpf82, I knew about CSS, I though there was maybe a different approach, thanks.

**Comment by mrg2001** [comment]
Added this for the records 
```
w2ui.grid.records[4].w2ui.style = { 
    fname: 'background: linear-gradient(to right, #1e5799 0%,#207cca 5%,#2989d8 50%,#e5e5e5 100%)' 
};
```
worked beautifully
