### ISSUE TITLE
height option in w2menu doesn't work

### ISSUE THREAD

**Issue by wondertalik** [vitmalina/w2ui#1572]
```
    function showMenu(type) {
        $('#some-input').w2menu({
            type: type,
            openAbove: window.above,
            align: window.align,
            width: 50,
            height: 50,
//            tmp: {
//                contentHeight: 50,
//                contentWidth: 150
//            },
            items: [
                { id: 1, text: 'Item 1', icon: 'fa-star' },
                { id: 2, text: 'Item 2    ', icon: 'fa-star-empty' },
                { id: 3, text: 'Item 3    ', icon: 'fa-camera' },
                { id: 4, text: 'Item 3    ', icon: 'fa-camera' },
                { id: 5, text: 'Item 3    ', icon: 'fa-camera' },
                { id: 6, text: 'Item 3    ', icon: 'fa-camera' },
                { id: 7, text: 'Item 3    ', icon: 'fa-camera' },
                { id: 8, text: 'Item 3    ', icon: 'fa-camera' },
                { id: 9, text: 'Item 3    ', icon: 'fa-camera' },
                { id: 10, text: 'Item 3    ', icon: 'fa-camera' },
                { id: 11, text: 'Item 3    ', icon: 'fa-camera' },
                { text: '--' },
                { id: 12, text: 'Item 4    ', icon: 'fa-table' }
            ]
        });
    }
```
I want to use height option for menu and scroll content inside menu. But it does'nt work. I can scrolling content only if height of the content bigger that height of the browser window. I try to use tmp option and have the same situation. Screen in atach

![menu overlay no scroll](https://cloud.githubusercontent.com/assets/1611064/25171066/e1107436-24ec-11e7-9693-6e8c77af75e7.png)
![menu overlay scroll](https://cloud.githubusercontent.com/assets/1611064/25171067/e1144c32-24ec-11e7-9c90-bb8c75d1edbc.png)
```
   { id: 1, text: 'Item 1', icon: 'fa-star' },
                { id: 2, text: 'Item 2    ', icon: 'fa-star-empty' },
```
Another problem is in text option.  What is it 'B B B' in  Item 2? I copy&paste from demo this line
![screenshot3](https://cloud.githubusercontent.com/assets/1611064/25171325/c68dcf5e-24ed-11e7-8f12-c501f594d177.png)

**Comment by mrg2001** [comment]
Please note that height is dynamic. Setting height to 50 and when content is 100 will extend popup to 100. However, setting height to 100 and if content is 50, will have height of 100. Also, there is a property called maxHeight (and maxWidth), it might be more useful in this case.
