### ISSUE TITLE
Grid select doesn't work

### ISSUE THREAD

**Issue by wondertalik** [vitmalina/w2ui#1577]
```
$('#grid').w2grid({
    name: 'grid',
    show: {
       lineNumbers: false,
                    toolbar: true,
                    toolbarReload: false,
                    toolbarColumns: false,
                    columnHeaders: true,
                    selectColumn: true
    },
     multiSelect: true,
    columns: [
        {
            "field": "FechaAlbaran",
            "caption": "Mes",
            "size": 50,
            "sortable": true,
            "resizable": true
        }
    ]
    ,
    records: [
       	{FechaAlbaran: 1, recid: 1},
        	{FechaAlbaran: 2, recid: 2},
       ],
 onSelect: function(event) {
                    event.onComplete = function () {
                        var rowIndexSelection =  this.getSelection()
                        
                        console.log(rowIndexSelection);
                    }
                },
                onUnselect: function(event) {
                    event.onComplete = function () {
                        var rowIndexSelection =  this.getSelection()
                        
                        console.log(rowIndexSelection);
                    }
                }
});
//w2ui['grid'].select(1, 2);
d = [1, 2]
w2ui['grid'].select(d.join(","))
```
The rows in the grid don't select. I can't run select in this way w2ui['grid'].select(d.join(","))?

**Comment by mpf82** [comment]
Your first select operation (``w2ui['grid'].select(1, 2)``) should work just fine.

My question to your qiuestion: Why **should** ``w2ui['grid'].select([1, 2].join(","))`` work?

The docs on Array.join say that the result is a string.

https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Array/join

So the result of ``[1, 2].join(",")`` is ``'1,2'`` (even if you can't see the quotes when you log it to the console).

The docs on grid.select() say: ``select(recid1, recid2, ...)``.

Now, if you pass your string ``'1,2'`` to the function, the grid will look for a record with the recid ``1,2``.

What you probably want is to convert your array to a parameter list. To achieve this you have 2 options: 

    w2ui['grid'].select.apply(w2ui['grid'], [1, 2]);

or

    w2ui['grid'].select(...[1, 2]); // requires the browser to support ECMA 6


Cheers, Mike

**Comment by wondertalik** [comment]
My mistake, after read about select i thought that i can use parameter as string. That's why i wrote this issue.

**Comment by mrg2001** [comment]
Please close the issue if it is resolved.

**Comment by wondertalik** [comment]
done!
