### ISSUE TITLE
Need to hit refresh for w2ui table to render inside bootstrap modal

### ISSUE THREAD

**Issue by rsaungc** [vitmalina/w2ui#1579]
I tried to load w2ui grid into a bootstrap modal and having issue with complete rendering.   It only rendered partial column.   Need to hit refresh button from w2ui tool bar in order to get complete table.  I already included "#w2ui[div_name].reload();"  within my js and still didn't load completely.  Appreciate any help.

![w2ui_modal_issue](https://cloud.githubusercontent.com/assets/10384065/25309957/6dbc64e6-278e-11e7-85fc-70a306e6780c.PNG)

**Comment by mrg2001** [comment]
You need to render the grid only after div element is inserted into HTML and properly sized. The grid will pick up the size from the div. If not, call grid.resize() when it is ready.

**Comment by rsaungc** [comment]
I did insert the div element into HTML before grid is rendered.  It only happen if I tried to render the w2ui grid within bootstrap modal.  If I render outside of modal, it display correctly.  I also included resize, refresh and reload functions and it still didn't render correctly inside modal.

 w2ui[grid].resize();
w2ui[grid].refresh();
w2ui[grid.reload();

**Comment by mrg2001** [comment]
add it to setTimeout(..., 0), it will add to the end of JS event loop

**Comment by rsaungc** [comment]
That works!  Thanks for your help mrg2001!

**Comment by rsaungc** [comment]
Hi mrg2001.  That method resolved for Bootstrap Modal.  Now, I am having issue with Bootstrap tabs.  Tried to print w2ui  table for each tab and only table from the first tab show correctly.  For other tabs, I need to hit refresh button from w2ui tool bar in order to get complete table.  I already tried all above methods and still don't work.  Please let me know if there any other way to resolve this.  Thanks again!

(https://cloud.githubusercontent.com/assets/10384065/25309957/6dbc64e6-278e-11e7-85fc-70a306e6780c.PNG)
