### ISSUE TITLE
Information function w2utils.locale in async false is deprecated 

### ISSUE THREAD

**Issue by spizzi77** [vitmalina/w2ui#1581]
Hy All,
I notified that uploading the json file for the language in html/javascript with locale in this way, for example the italian language ot others:

`w2utils.locale('js/it-it.json');`

It's causing a warning in the console browser 

**Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help http://xhr.spec.whatwg.org/**

To avoid this waring in line 1482 in the function locale of the w2utils object comment the async:false.

**Comment by mkaim** [comment]
It's really a bad idea to remove/comment `async:false` option. `w2utils.locale` must work synchronously to make sure that all w2ui widgets created just after calling this method will use newly loaded locale file.

**Comment by spizzi77** [comment]
I'm agree with you, but the problem it's the async : false must be used on the work threads and not on the main threads, in the future this feature will be removed, so i suggest to take attention to this and find another solution.

**Synchronous XMLHttpRequest outside of workers is in the process of being removed from the web platform as it has detrimental effects to the end user's experience. (This is a long process that takes many years.) Developers must not pass false for the async argument when the JavaScript global environment is a document environment. User agents are strongly encouraged to warn about such usage in developer tools and may experiment with throwing an InvalidAccessError exception when it occurs.**

**Comment by mrg2001** [comment]
Removed async, added callBack param if needed
