### ISSUE TITLE
bug: hex validator doesn't recognize 0x format

### ISSUE THREAD

**Issue by susdu** [vitmalina/w2ui#1584]
0xFFF is widely used hexademical format:

```
    function isHex (val) {
        var re = /^[a-fA-F0-9]+$/;
        return re.test(val);
    }
```
should be:

```
    function isHex (val) {
        var re = /^(0x)?[0-9a-fA-F]+$/;
        return re.test(val);
    }
```

**Comment by mpf82** [comment]
I would argue that this is **not** a bug. 

Hexadecimal values consist - per definition - only of the digits 0-9 and the characters a-f (repectively A-F).

The ``0x`` is only a prefix specific to certain compilers/programming languages (mostly C-based languages), while Delphi uses the ``$`` prefix and Smalltalk uses the ``16r`` prefix. 

And please note that the ``0x`` only indicates that the following characters represent a hex value - while the prefix itself is not hex at all.

You can read more about it here: https://en.wikipedia.org/wiki/Hexadecimal#Written_representation

**Comment by susdu** [comment]
While you are syntactically right, this is still a UI library. And as a UI library,
it has to interact with input from the outside world (human, webpage, etc.) 
where differentiating hex numbers from regular numbers in print is almost always accompanied by `0x`
