### ISSUE TITLE
[FEATURE REQUEST] How to Create Stacked Popover with tab

### ISSUE THREAD

**Issue by muthu32** [vitmalina/w2ui#1586]
I am just impressed with stacked popover (Not dialog) in Openui5. Is there any way to implement stacked popup in w2ui.
Demo Page: https://openui5.hana.ondemand.com/explored.html#/sample/sap.m.sample.MessagePopover/preview

**Comment by mrg2001** [comment]
Once popover is opened, you can update html inside it through $().html(). I do not think there should be any problems with it. I occasiannaly use it to display w2form in it. You can put tabs, or anything else in it. See demos (not directly related) http://w2ui.com/web/demos/#!utils/utils-5
