### ISSUE TITLE
[Feature Request] Windows

### ISSUE THREAD

**Issue by plungedtoilet** [vitmalina/w2ui#1587]
A window-like container. Like in Windows OS, or the popup-- but it doesn't close when clicked out of.  Even though you could just attach to an element, and move the element, and hide the element, it would be a cool feature if you could create it using w2ui.

![concept](https://cloud.githubusercontent.com/assets/19500789/25568315/9a88f812-2dc5-11e7-9507-3d5e40863a49.png)

**Comment by mrg2001** [comment]
Please see discussion here https://github.com/vitmalina/w2ui/issues/283
