### ISSUE TITLE
Grid - the problem of horizontal scrolling.

### ISSUE THREAD

**Issue by AnatolyAG** [vitmalina/w2ui#1589]
I have more than 40 fields, when the grid is empty, the scroll is slow, and resets, you can only click.
If the table is filled, it works more or less smoothly.

**Comment by mpf82** [comment]
Which browser are you using?

This might be a duplicate of https://github.com/vitmalina/w2ui/issues/1231

**Comment by AnatolyAG** [comment]
chrome, yes duplicate
I'm sorry I did not see, although I did a search for the problem
