### ISSUE TITLE
in inline edit demo for the empty cell enabled save button

### ISSUE THREAD

**Issue by wondertalik** [vitmalina/w2ui#1591]
http://w2ui.com/web/demos/#!grid/grid-21

in inline edit demo when i press to empty cell and don't change any in one the save button enabled, is it ok?

**Comment by mpf82** [comment]
That happens because ``record.text`` actually changes from ``undefined`` to an empty string ``""``.

If all records would have ``text`` defined as an empty string this would not happen.

Cheers =)

**Comment by wondertalik** [comment]
Thanks for the reply =)
