### ISSUE TITLE
Unable to render 2 w2ui tables in a same page.

### ISSUE THREAD

**Issue by rsaungc** [vitmalina/w2ui#1592]
I tried to print two w2ui tables side by side in two different <div> and unable to print. Only one table will display.   Both table has own div ID, 'name' and all are unique.   I use rand number for table name.

DIV name TABLE_LEFT and table name is 96899
DIV name TABLE_RIGHT and table name is 2503

<ERROR>
ERROR: The parameter "name" is not unique. There are other objects already created with the same name (obj: 2503).
</ERROR>

- Both table names are clearly different
- (obj: 2503) is only created once.  Error message said it already created.

Thanks in advance for any help!

**Comment by mpf82** [comment]
The global ``w2ui`` object holds a reference to all w2ui objects, not just grids. 

Maybe you have already created a w2toolbar/w2sidebar/... with the same name. You can check with ``w2ui['2503']`` (or whatever your random ID during the error is) what w2ui object already exists with this name.

If this does not help, please create a fiddle to demonstrate your problem.

Cheers =)

**Comment by rsaungc** [comment]
Thanks mpf82.  Problem is resolved.  I moved rand generator inside of "$(function ()" and its now working.
