### ISSUE TITLE
Tabindex for lists not working in 1.5.rc1

### ISSUE THREAD

**Issue by nihem** [vitmalina/w2ui#1593]
Since i updated from 1.4.3 to 1.5.rc1 the tabindex for lists are not working anymore. All fields of the type list are skipped.

**Comment by mrg2001** [comment]
Please create a jsfiddle. You can link these 2 files
```js
w2ui.com/src/w2ui.min.js
w2ui.com/src/w2ui.min.css
```

**Comment by nihem** [comment]
Solved the problem. I had to change the type of the input fields to text for initializing. Thanks
