### ISSUE TITLE
How to make "grouping grid"

### ISSUE THREAD

**Issue by gboulanger13** [vitmalina/w2ui#1596]
Hello,

I want to know how to make a "grouping grid" like this exemple : http://examples.sencha.com/gxt/4.0.2/#ExamplePlace:groupinggrid.

I tried to do some stuffs with tree-like grid but it's not want i want.

**Comment by mpf82** [comment]
You can have nested grids by adding a new grid in the ``onExpand`` callback.

Here's a demo: http://w2ui.com/web/demos/#!grid/grid-3

Though the demo only demonstrates how to a a DIV, you can easily adapt the code to add a w2grid instead.

**Comment by gboulanger13** [comment]
I'll see this, thank you for reply.
