### ISSUE TITLE
grid sorting  not workink

### ISSUE THREAD

**Issue by eliavmaman** [vitmalina/w2ui#1599]
Im trying to use the sortData property of the grid like this:
```this.sortData=[{field: 'Date', direction: 'desc'}];```

the column code : 
```
           {
                field: 'Date',
                caption: 'Date',
                size: '15%',
                sortable: true,
                render: function (record, index, column_index) {
                    return moment(record.Date).format('MM/DD/YYYY HH:mm:ss');
                }
            },
```
**this is only happened when the grid first load, when i sort again (manually click on the column) its works fine** 
see attached :)
![image](https://cloud.githubusercontent.com/assets/6911449/26034205/cafa6664-38c1-11e7-9d3f-b5c582aa5240.png)
it's looks like the sorting is quite a mess.. any idea please?

**Comment by eliavmaman** [comment]
any one please?

**Comment by mrg2001** [comment]
Date column should have data in sortable format. It is either unix timestamp (int number represending date), or yyyy-mm-dd string. Please create jsFiddle where you problem is illustrated.

**Comment by mpf82** [comment]
@mrg2001 This issue can probably be closed due to inactivity.

**Comment by mpf82** [comment]
Closing issue: no response, no reproducer
