### ISSUE TITLE
Grid open calendar to set Date located at 1970

### ISSUE THREAD

**Issue by carlosgblos** [vitmalina/w2ui#1601]
Hi,  I'm using the library (congratulations by the way, so good...), and on the new version when changing an editable date field, the calendar always opens at 1970. 
There's anyway to make it open on "today" date ?
Please check jsfiddle. 
http://jsfiddle.net/410z8msk/2/

Thanks so much
Carlos Guilherme

**Comment by mendozada** [comment]
Hi Carlos , please see [jsfiddle.net](http://jsfiddle.net/410z8msk/6/)
Saludos.
Diego

**Comment by mrg2001** [comment]
@mendozada  thanks for the workaround. I looked into the code and found fixed it so that current date would be used when default date is not specified.
