### ISSUE TITLE
Right-click menu in grid

### ISSUE THREAD

**Issue by mendozada** [vitmalina/w2ui#1603]
Is it possible to display a menu by right-clicking on a cell in the grid ???

Thanks

**Comment by mrg2001** [comment]
http://w2ui.com/web/docs/1.5/w2grid.onContextMenu 

You can attach menu using w2menu

**Comment by mendozada** [comment]
ERROR: to display menu at mouse location, pass options.pageX and options.pageY.
[http://jsfiddle.net/y81cyj54/25/](http://jsfiddle.net/y81cyj54/25/)

**Comment by mrg2001** [comment]
http://jsfiddle.net/y81cyj54/28/

Also better documentation is http://w2ui.com/web/docs/1.5/w2grid.menu
