### ISSUE TITLE
css related list bug (FF)

### ISSUE THREAD

**Issue by rolfn** [vitmalina/w2ui#1609]
* **I'm submitting a ...**
[ x] bug report

* **What is the current behavior?**

In the following example the first list with 32 entries don't show its content. The other list (31 entries) is ok.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a screenshots**.
```html
<!DOCTYPE html>
<html>
<head>
  <title>XY</title>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <link rel="stylesheet" type="text/css" href="http://w2ui.com//src/w2ui-1.5.rc1.min.css" />
  <script type="text/javascript" src="http://w2ui.com/web/js/jquery-2.1.1.min.js"></script>
  <script type="text/javascript" src="http://w2ui.com/src/w2ui-1.5.rc1.min.js"></script>
</head>
<script type='text/javascript'>
  $(document).ready(function() {
    var fields = [
      { name: 'LIST_1', type: 'list', required: true, 
        options: { items: ['x', 'x', 'x', 'x', 'x', 'x', 'x', 'x', 'x', 'x', 
                           'x', 'x', 'x', 'x', 'x', 'x', 'x', 'x', 'x', 'x', 
                           'x', 'x', 'x', 'x', 'x', 'x', 'x', 'x', 'x', 'x', 
                           'x', 'x' 
      ] } },
      { name: 'LIST_2', type: 'list', required: true, 
        options: { items: ['y', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 
                           'y', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 
                           'y', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 
                           'y' 
      ] } },
    ];  
    $('#XY').w2form({
      name: 'XY',
      fields : fields
    }); 
  });
</script>
<style type='text/css'>
.foo {
  width:400px;
  height:300px;
  top:50%;
  left:50%;  
  //top: 50vh;
  //left:50vw;
  position:absolute;
  margin:-150px 0 0 -200px;
  background-color:lightgreen;
}
</style>  
<body style="background-color:lightblue;">
  
<div class="foo" id="XY">
  <div class="w2ui-page page-0" >
    <div class="w2ui-field"d>
      <input name="LIST_1" type="list" />
    </div>
    <div class="w2ui-field">
      <input name="LIST_2" type="list" />
    </div>
  </div>
</div> 

</body>
</html>
```
I see the bug with w2ui 1.5rc1 in Firefox 53.0 (Linux). The bug  disappear if I decrease the number of entries to 31 or less. The bug  also disappear if I use the lines with viewport units in the style tag.

**Comment by mrg2001** [comment]
Please create jsFiddle with the bug

**Comment by rolfn** [comment]
I tried it. The result seems not to work: https://jsfiddle.net/Ln6jx2c2/ I get errors: "You're loading resources over HTTP not HTTPS, your fiddle will not work.". Maybe you can correct it. Thanks.

**Comment by mpf82** [comment]
You should not mix HTTP and HTTPS.

I have updated your fiddle: https://jsfiddle.net/Ln6jx2c2/1/

Note: I also linked the latest sources from master instead of the rc1 sources.

Cheers =)

**Comment by mpf82** [comment]
Seems to be fixed: https://jsfiddle.net/sjtg7mnb/

I'm cloing this issue for now, feel fre to re-open if you can provide a fiddle, showing that the problem still exists.
