### ISSUE TITLE
font-awesome Issue.

### ISSUE THREAD

**Issue by jackryu** [vitmalina/w2ui#1610]
Hello - My Project Showing below mention issue in  console.

![image](https://cloud.githubusercontent.com/assets/6933841/26552480/f22536b2-44a4-11e7-8776-bfbf2cdda6e4.png)

But every thing is working fine.

**Project Reference structure.**

Project/plugins/vendor/W2UI

![image](https://cloud.githubusercontent.com/assets/6933841/26552526/23b2b286-44a5-11e7-8471-e0b6324601d2.png)

**Add Font Reference using CDN**

`  <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet"/> `

**Please help how to resolve this issue.**

**Comment by mpf82** [comment]
1) w2ui does **not** require font-awesome
2) w2ui will by default **not** use font-awesome icons

The issue is most likely on your side.

**Comment by mpf82** [comment]
@mrg2001 This issue can probably be closed due to inactivity. And it's not really a w2ui issue in the first place.
