### ISSUE TITLE
Click and other events of content loaded inside panels are not working

### ISSUE THREAD

**Issue by yunidbauza** [vitmalina/w2ui#1612]
I'm using 1.5-rc1.
Attaching an event handler to an element inside a panel won't trigger the action:
```html
<script>
$(function() {
         $('#layout').w2layout({
                name: 'mainArea',
                panels: [
                    { type: 'left', size: 200, resizable: true, style: panels, content: 'left' },
                    { type: 'main', style: main, content: 'main' }
                ]
            });

   //UPDATE
     $().w2layout({
                name: 'innerArea',
                panels: [
                    { type: 'main', style: '', content: 'main' }
                ]
            });
            
     w2ui['mainArea'].content('main', w2ui['innerArea']);
     w2ui['innerArea'].content('main', $("#list-panel").html());
//UPDATE

     $("#mylist li a").click(function() {
          alert( "Handler for .click() called." );
     });
})
</script>
<div id="layout"></div>
<div id="list-panel" style="visibility: hidden" >
        <ul id="mylist" class="list-group">
            <li><a href="#" onclick="alert('This one will work')"><span>Adele</span></a></li>
            <li><a href="#"><span>Bella</span></a></li>
            <li><a href="#"><span>Carl</span></a></li>
        </ul>
</div>
```
Clicking on the items **Bella** or **Carl** will never trigger the alert. 
The interesting thing is that if I remove the w2ui layout then everything works.
```html
<script>
$(function() {
     $("#mylist li a").click(function() {
          alert( "Handler for .click() called." );
     });
})
</script>
<div id="list-panel" >
        <ul id="mylist" class="list-group">
            <li><a href="#" onclick="alert('This one will work')"><span>Adele</span></a></li>
            <li><a href="#"><span>Bella</span></a></li>
            <li><a href="#"><span>Carl</span></a></li>
        </ul>
</div>
```

I noticed that the same happens when I try to add bootstrap components or any other content inside a panel. The click, change and other events on those components are never triggered.

Any idea why?

**Comment by chalchis** [comment]
`
<script>
$(function() 
{
var contend = '<div id="list-panel" style="visibility: hidden" >'
        +'<ul id="mylist" class="list-group">'
            +'<li><a href="#" onclick="alert('This one will work')"><span>Adele</span></a></li>'
            +'<li><a href="#"><span>Bella</span></a></li>'
            +'<li><a href="#"><span>Carl</span></a></li>'
        +'</ul>'
+'</div>';

         $('#layout').w2layout({
                name: 'mainArea',
                panels: [
                    { type: 'left', size: 200, resizable: true, style: panels, content: 'left' },
                    { type: 'main', style: main, content: 'main' }
                ]
            });
     w2ui['mainArea'].content('main', contend );

     $("#mylist li a").click(function() {
          alert( "Handler for .click() called." );
     });
})
</script>
<div id="layout"></div>

`

**Comment by yunidbauza** [comment]
Hi @chalchis 
Your solution is not quite different to what I already have, without mentioning that does not work either.

The problem seems to be that moving/copying the content from one place to another loses the bindings. An event delegation implementation in the **onContent** event of the layout object might solve the issue. 

```html
<script>
$(function() {
         $('#layout').w2layout({
                name: 'mainArea',
                panels: [
                    { type: 'left', size: 200, resizable: true, style: panels, content: 'left' },
                    { type: 'main', style: main, content: 'main' }
                ],
                onContent: function(event) {
                     var $my_content = $(event.content);
                     //implement the binding here
                }
            });
     w2ui['mainArea'].content('main', $("#list-panel").html());
})
</script>
<div id="layout"></div>
<div id="list-panel" style="visibility: hidden" >
        <ul id="mylist" class="list-group">
            <li><a href="#" onclick="alert('This one will work')"><span>Adele</span></a></li>
            <li><a href="#"><span>Bella</span></a></li>
            <li><a href="#"><span>Carl</span></a></li>
        </ul>
</div>
```
But I still cannot make it work...
Any suggestions?

**Comment by mpf82** [comment]
I created a fiddle (please provide one yourself the next time) based on the code you posted, but everything seems to work fine:

https://jsfiddle.net/qokbups4/

All 3 links will trigger the alert.

Tested in FF 53 and Chrome 58

If it's still not working for you, please provide a fiddle where your problem can be reproduced.

Cheers =)

**Comment by yunidbauza** [comment]
Hi @mpf82 

Actually, by trying to simplify my example, I forgot the most important detail.
Yes, the previous case works, however, when using **nested layout** is not.

I created a JSfiddle when you can see it.
https://jsfiddle.net/yunidbauza/qokbups4/5/

I also update the initial issue

**Comment by mpf82** [comment]
There are at least two ways to successfully attach the click event handler:

1) in the onContent event handler (though you need to delay it with a setTimeout, even if it's for 0 milliseconds, to be sure the html is part of the DOM)

           onContent: function(event) {
             event.done(function() {
               setTimeout(function() {
                 $("#mylist li a").click(function() {
                   alert("Handler for .click() called (1)");
                 });
               }, 0);
             });
           }

2) globally on a parent element (this works for any dynamically created content)

         $(document).on("click", "#mylist li a", function() {
           alert( "Handler for .click() called (2)" );
         });

You can find both implementations in this fiddle: https://jsfiddle.net/qokbups4/6/

Please close the issue if this works for you.

Cheers =)

**Comment by mrg2001** [comment]
You can also attach in onRefresh event. Here is that jsFiddle https://jsfiddle.net/qokbups4/7/

**Comment by yunidbauza** [comment]
Yes, all examples work well.
