### ISSUE TITLE
Search is not working

### ISSUE THREAD

**Issue by meteoric93** [vitmalina/w2ui#1614]
I created w2ui grid with below columns type.
I have linked field. So I can search with this field.
how can I solve this problem?
[columns: [                
				{ field: 'recid', caption: 'ID', size: '50px', sortable: true, resizable: true },
				{ field: 'check', caption: 'check', size: '60px', sortable: true, resizable: true, style: 'text-align: center',
					editable:{type: 'checkbox', style:'text-align: center'}
				},
				**{ field: 'text', caption: 'Full Name', size: '120px', sortable: true, resizable: true, 
				 	render: function (record, index, column_index) {
						var html = '<a href="auto-segments-add.php">'+ record.fname + '</a>';
						return html;
					}
				},**
				{ field: 'text', caption: 'Title', size: '80px', sortable: true, resizable: true, },
				{ field: 'text', caption: 'Company', size: '80px', sortable: true, resizable: true},
				{ field: 'text', caption: 'Email Address', size: '80px', sortable: true, resizable: true },
				{ field: 'text', caption: 'Account Type', size: '80px', sortable: true, resizable: true, },
				{ field: 'text', caption: 'Referrer', size: '90px', sortable: true, resizable: true, style: 'text-align: right',},
				{ field: 'date', caption: 'Date Added', size: '70px', sortable: true, resizable: true, render: 'date' },
				{ field: 'text', caption: 'Added By', size: '50%', sortable: true, resizable: true, },
				{ field: 'text', caption: 'Last Contacted', size: '50%', sortable: true, resizable: true, },
				{ field: 'text', caption: 'Last Contacted By', size: '100px', sortable: true, resizable: true, },
				{ field: 'date', caption: 'Follow-up date', size: '100px', sortable: true, resizable: true, render: 'date' },
				{ field: 'text', caption: 'Follow-up By', size: '100px', sortable: true, resizable: true, },
				{ field: 'date', caption: 'Date Updated', size: '100px', sortable: true, resizable: true, render: 'date' },
				{ field: 'text', caption: 'Updated By', size: '100px', sortable: true, resizable: true, }
			],](url)

**Comment by mrg2001** [comment]
Please create jsFiddle with the problem.

**Comment by mpf82** [comment]
@mrg2001 This issue can probably be closed due to inactivity.

**Comment by mpf82** [comment]
Closing issue: no response, no reproducer
