### ISSUE TITLE
adding a new item to a grid with remote data with more than 150 rows

### ISSUE THREAD

**Issue by colin44** [vitmalina/w2ui#1617]
I'm submitting a ...
[ x] bug report

What is the current behavior?
If you add the 151th or more row of data to a grid from a remote data source the display is not shown correctly and you can't edit any fields.

If the current behavior is a bug, please provide the steps to reproduce and if possible a screenshots

Data is loaded via a URL
        url    : 'test9.php',

method for adding a new row via a button on the tools bar

            onClick: function (event) {
                if (event.target == 'add') {
                    var g = w2ui.racegrid.records.length+1;
                    w2ui.racegrid.add({ recid: g });                   
                }

What is the expected behavior?

the row is added and the editable fields are visible and selectable

Other information

It must be something to do with vs_start
as you can work around the issue by
                if (event.target == 'add') {
                    var g = w2ui.racegrid.records.length+1;
                    w2ui.racegrid.vs_start = g;      // allows the new record to show correctly using remote data
                    w2ui.racegrid.add({ recid: g });                   
                }

**Comment by mpf82** [comment]
Can you please provide a Fiddle/Bin/Pen to demonstrate the issue?

**Comment by mpf82** [comment]
Closing issue: no response
