### ISSUE TITLE
Grid advanced search and sorting features doesn't work

### ISSUE THREAD

**Issue by anushabachu** [vitmalina/w2ui#1623]
I am using W2UI 1.5.rc1, and implemented a grid with data coming from a json file. The "Search", "Advanced Search" and "Column Sorting" features doesn't work on my grid.

I have gone through the demos that import data from external json file like this one http://w2ui.com/web/demos/#!grid/grid-3 , even here the "Advanced Search" and "Search" features doesn't work. So, I suspect this to be an issue in the library. Can you guys please fix this or let me know the correct way to implement this

**Comment by mpf82** [comment]
From the [docs](http://w2ui.com/web/docs/1.5/w2grid.url):

> If the .url property is defined, then every time the grid needs to refresh, search, or sort records, they will be pulled from the .url. If grid needs to save the records, new changes will be submitted to this .url as well.

That means, the search request is sent to the url (and youshould be able to see this behaviour in the network tab of your browser).

Ideally, your url points to a function on your server that can handle get/set/delete and not just to a json file.

To make the search work you could remove the url (set ``grid.url = null``) once your data is loaded to make the grid think it's running in local mode, or you can load your remote data with ``grid.load(url)`` **instead** of setting ``grid.url`` (as suggested in the docs).

Cheers =)

**Comment by anushabachu** [comment]
It worked!! Thanks a lot :)
