### ISSUE TITLE
How can I set selectColumn style ?

### ISSUE THREAD

**Issue by sayyes566** [vitmalina/w2ui#1625]
* **I'm submitting a ...**
[ ] bug report
[* ] feature request
[ ] question about the decisions made in the repository

* **What is the current behavior?**
I want to custom style of each column, but I don't know how to set checkbox's cell  as the same style.
Please help me, thanks
[live demo](https://codepen.io/kristen1111/pen/xrdaBj)

**Comment by mpf82** [comment]
1) This is **not** a feature request, but a support question (asking for help with your code)
2) You should ask support question on the w2ui disqus forum or and stackoverflow
3) To save you some time, I will answer anyway

``w2grid`` has a property ``recordHeight`` as described in the docs: http://w2ui.com/web/docs/1.5/w2grid.recordHeight

If you want to align the items of your records within the grid cells you can use ``w2ui.style`` or ``w2ui.class`` in the record (this is new in 1.5).

Fiddle: http://jsfiddle.net/ej0ywncy/

Please close the issue if this answers your question.
Or close the issue anyway and ask in either the disqus forum or on stackoverflow.

Cheers =)

**Comment by sayyes566** [comment]
@_@", sorry! I walked the wrong place. Thanks for your help!
