### ISSUE TITLE
getSelection() returns empty selection within a double click event

### ISSUE THREAD

**Issue by Sososlik** [vitmalina/w2ui#1627]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **What is the current behavior?**
The getSelection() returns that there is no selection when you double click a currently selected row.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a screenshots**.
I made this Fiddle to test it: https://jsfiddle.net/6go7556p/
When you double click any row an alert message will show the selection.
1) double click any unselected row and it works OK. 
2) select (one click) any row and later double click that selected row. The selection will show empty :(

* **What is the expected behavior?**
The getSelection() should return the selected row.

* **What is the motivation / use case for changing the behavior?**
I'm trying to implement this: when user double clicks a row then I will show a "view/edit form" for that record.

* **Link to jsFiddle that demonstrates the problem:**
https://jsfiddle.net/6go7556p/

* **Other information**

**Comment by mpf82** [comment]
All events have a "start" and a "finish".

When the event starts, the event handler is triggered - when the event finishes, ``event.onComplete`` and ``event.done`` are executed, if you assign them.

At the end of the onDblClick event, the selection is correct, both when you double click an unselected and a selected record.

Updated fiddle: https://jsfiddle.net/6go7556p/1/

Cheers =)

**Comment by Sososlik** [comment]
I see... Thank you very much!  I will study better the documentation :)
