### ISSUE TITLE
First record hidden

### ISSUE THREAD

**Issue by hamri** [vitmalina/w2ui#1633]
* **I'm submitting a ...**
[ ] bug report

* **What is the current behavior?**
After setting the columns dynamically in a parser function, the first record does not appear.

The parser function content:
parser: function (responseText) {
                var data = $.parseJSON(responseText);
                w2ui.grid.columns = data.columns;     
                w2ui.grid.refresh();
                return data;
}
Even if i set the total property, the problem still occurring.
Thanks

**Comment by mpf82** [comment]
Can you create a jsfiddle to demonstrate the problem?
