### ISSUE TITLE
Grid doesn't have function get the filtered data

### ISSUE THREAD

**Issue by eliavmaman** [vitmalina/w2ui#1635]
Hey,
After apply grid search by field, there is no function that retrieve the filtered data .

Any idea?

**Comment by mpf82** [comment]
See https://github.com/vitmalina/w2ui/issues/1604 and https://github.com/vitmalina/w2ui/issues/1428

**Comment by eliavmaman** [comment]
@mpf82  Thanks, 
That's Exactly What i needed.
