### ISSUE TITLE
Delete confirmation dialog causes form submit

### ISSUE THREAD

**Issue by Sososlik** [vitmalina/w2ui#1644]
* **I'm submitting a ...**
[x ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **What is the current behavior?**
The grid is inside a form.
When delete confirmation dialog appears and users clicks on either of the buttons, the parent form is submitted.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a screenshots**.
Open the jsfiddle, select any row, click on the delete button, answer 'No' to the dialog, and form will be submitted.

* **What is the expected behavior?**
The grid should not submit the form.

* **What is the motivation / use case for changing the behavior?**
?

* **Link to jsFiddle that demonstrates the problem:**
https://jsfiddle.net/6go7556p/3/

* **Other information**

**Comment by pidlo** [comment]
HI sosolik 
Example from w2ui works fine with delete 
http://w2ui.com/web/demos/#!grid/grid-17
There is link to js fiddle too.

I create js fiddle from http://jsfiddle.net/api/post/jquery/2.1/
copy and paste your code add external resources and example is ok.

I see redirect in your example in jsfidde   
http://fiddle.jshell.net
see in inspector 
If you try your code on your localhost i would be fine,

**Comment by Sososlik** [comment]
Hi @pidlo I'm not sure if I understand what are you trying to say.
The linked example http://w2ui.com/web/demos/#!grid/grid-17 works fine with delete, but is not in a form tag. The problem appears only when the grid is contained in a form.
The jsfiddle you linked is empty.
I copyied the linked demo code in a local html file. And surrounded the <div> with a <form> and there is the same problem, when I click delete, then NO, and form is submitted...
I attached a local file demotrating the problem.

[test.zip](https://github.com/vitmalina/w2ui/files/1185013/test.zip)

**Comment by pidlo** [comment]
Hi @Sosolik 
so you can do something like bellow ...
Why you must have w2ui grid inside form tag?

onsubmit function always return false and on the top onsubmit function you can do anything.

<form action="notexists.test" onsubmit="/*code for your form*/return false;">
<div id="grid" style="width: 100%; height: 400px;"></div>
</form>

**Comment by Sososlik** [comment]
The example code that I posted is reduced to minimum complexity for easy understand. The real code is a complex form that have many controls inside, and one of them is this grid for adding/creating/relating child items of an entity.
And at the end there is a button for submitting the entire form. So I cannot just cancel the submit because I use it for actually submitting the form. The problem is the grid causing the submit in a wrong place.
A temporary workaround I did is override the onDelete event, and use a custom confirmation dialog for deleting and problem gone away. But I think it should be fixed, no? Or at least state the limitation on the docs.

**Comment by pidlo** [comment]
I mean that 
if you have in your form some button no type submit..
Then on click action add some value for input type hidden and then call form.submit function
inside this can you check if the value is filled if not then you click w2ui button and then return false in submit function.

Or as you write can override onDelete event.
I for my project with w2ui crud action do the same because i use it for serverside actions and serverside validation and send messages from server into form etc..
