### ISSUE TITLE
There is a pattern in which the header of the grid is not displayed

### ISSUE THREAD

**Issue by FreemenWeb** [vitmalina/w2ui#1646]
* **I'm submitting a ...**
[X ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **What is the current behavior?**
Even if property 'header' is set to True, the header is not displayed.
Between 4674 and 4675 lines, should you add the following sources?

`$.extend(this.show,` `this.last.state.show);`

* **Link to jsFiddle that demonstrates the problem:**
https://github.com/vitmalina/w2ui/blob/master/src/w2grid.js

* **Other information**

**Comment by mpf82** [comment]
grid header shows as expected: http://w2ui.com/web/demos/#!grid/grid-3

Can you please provide a Fiddle/Bin/Pen to demonstrate the issue?

**Comment by mpf82** [comment]
Closing issue: no response
