### ISSUE TITLE
How do I copy the content of the grid？

### ISSUE THREAD

**Issue by Mingscript** [vitmalina/w2ui#1648]
The contents of the Grid are not selected for replication. How should I manipulate the contents of a single td like the text on the HTML ?

**Comment by pidlo** [comment]
Hi @Mingscript 
you can copy content from grid use ALT key with seleced method (mouse or keyboard).
I hope that i help you.

**Comment by okinadok** [comment]
do vitmalina died ?

**Comment by mpf82** [comment]
> The contents of the Grid are not selected for replication.

As @pidlo mentioned, you can hold the ALT key to select text. There's also a new column feature to add a "copy to clipboard" icon to all cells of a column.

> How should I manipulate the contents of a single td

Use inline editing mode of the grid. Example: http://w2ui.com/web/demos/#!grid/grid-21

Closing issue as resolved.
