### ISSUE TITLE
Add option focus_to_no

### ISSUE THREAD

**Issue by aetna-softwares** [vitmalina/w2ui#1655]
* **I'm submitting a ...**
[ ] bug report
[X] feature request
[ ] question about the decisions made in the repository

* **What is the current behavior?**
The w2confirm give focus to Yes button

* **What is the expected behavior?**
Have an option to give focus to No button

* **What is the motivation / use case for changing the behavior?**
User have the habit to discard message as quick as possible without reading them. For some dangerous action, I whish to have focus to "No" button to make sure that someone that did not read the warning and press enter don't perform the action.
The default behaviour should remain the focus on "Yes"

* **Other information**
I made a pull request for the modification : 
https://github.com/vitmalina/w2ui/pull/1654

**Comment by mpf82** [comment]
Since the PR has been merged, this issue can probably be closed.
