### ISSUE TITLE
Grid reload() not working

### ISSUE THREAD

**Issue by SHIJINGLI0206** [vitmalina/w2ui#1661]
Hi, 
Any one can help about w2ui grid reload issue?

I have two w2ui grid, parent grid and child grid. both grid data are from json file at server site.

now i click one row in parent grid and update child json file at server site then display the searched data in child grid. i do this using parent grid onComplete() function. 

however, i use w2ui.child_grid.reload() to update child grid data. but nothing happen. i check child json file and find it is updated.

So how can i update child grid data after i click one row in parent grid?

Thank you so much.

**Comment by mpf82** [comment]
Can you please provide a Fiddle/Bin/Pen to demonstrate the issue?

**Comment by mpf82** [comment]
Closing issue: no response
