### ISSUE TITLE
Grid with fixed columns may have different cell height in fixed and scrollable parts

### ISSUE THREAD

**Issue by AlexanderNickolsky** [vitmalina/w2ui#1666]
FF, Chromium, IE

If cell contents has different height, the cells will also have different height.
![bug_ff 2017-08-31](https://user-images.githubusercontent.com/22120142/29935491-98922cea-8e87-11e7-8dc1-6d5f58a8b9f5.png)

overflow:hidden in table and inner div does not help, the cell height will be set according to contents,
not specified height. The only solution I found on StackOverflow is the following:

set position: relative in td
set position: absolute; left:0;top:0 in div

It works!

**Comment by mpf82** [comment]
Can you please create a jsfiddle to demonstrate the problem?
And maybe add a fiddle that includes your fix, so someone can create a Pull Request?

Or consider to create a Pull Request yourself.

**Comment by mpf82** [comment]
Closing issue: no response
