### ISSUE TITLE
Running IE locally, json fails

### ISSUE THREAD

**Issue by squadjot** [vitmalina/w2ui#1667]
This might seem like a odd request, but would it be possible to get w2ui to work in IE10+ when loading json in a document that runs in locally. (ie. from your harddrive)

I'm trying to use w2ui in HTA's and until now everything works, except loading json which will trigger error message (line 5277)

**Comment by squadjot** [comment]
I realized i just have to avoid using the xhr , and read the data with FileScriptObject and then use the **add** method
`w2ui['grid'].add(JSON.parse(data).records);`

Problem solved

**Comment by mpf82** [comment]
If your problem is solved, please close the issue, thanks :)
