### ISSUE TITLE
Small problem with grids in tabs and layout html

### ISSUE THREAD

**Issue by Rimokas** [vitmalina/w2ui#1670]
Hello,

Can't understand this is a BUG ot not ... Ok, description of problem .

Created tabs with grids . In first tab master grid, in second slaves . All is working very fine . 
Now in the last (4-ty)  tab rendered layout - here 'main' is for grid and 'right' for images of products . 
All is working OK .

The first picture : 
![image](https://user-images.githubusercontent.com/12154604/30223499-c8f64694-94d3-11e7-9ca6-f2d0a0c3e7a5.png)
As you can see in picture in the main tab, exist empty line . Now I'm going to the last tab wit layout : 
![image](https://user-images.githubusercontent.com/12154604/30223604-45fee4b6-94d4-11e7-8243-75581fc601ef.png)
Now if I'm returning to first, main, tab, I'm seeing that empty line dissapear ... 
![image](https://user-images.githubusercontent.com/12154604/30223697-9c3c200a-94d4-11e7-8790-ac9e8ddb4009.png)

And that it's related with layout and pictures . Here it's mine source pieces  - 
selection of main grid : 

            w2ui[ tab_grd[ 0 ] ].on( 'select', function( event ) 
            {
               w2ui[ 'model_layout' ].html( 'right', '' ); // clear images in the 4-ty grid in layout 
               event.onComplete = function()
               {
                  ... some values ...                  
                  mod_buv = mod_rec;
               }
            });

selection of 4-ty grid : 

            w2ui[ tab_grd[ 3 ] ].on( 'select', function( event ) 
            {
               w2ui[ 'model_layout' ].html( 'right', '' );
               event.onComplete = function()
               {
                  var rec = w2ui[ tab_grd[ 3 ] ].get( event.recid );
                  if ( rec.dok_tip == 'img' && rec.kelias.length > 0 ) // if in database type "img" and exist 
                  {
                     w2ui[ 'model_layout' ].html( 'right', "<img src='" + rec.kelias + "' class='swipebox' style='position: relative;'>" );
                  }
               }
            });
           
If I disable this line - 

w2ui[ 'model_layout' ].html( 'right', "  img src='" + rec.kelias + "' class='swipebox' style='position: relative; '"  ); - ( removed <>  ) 

 then first empty line don't dissapear . All is working OK. 

But at this time I did this in such design and view of images in the 4-ty tab ( layout ) it's neddful . This small problem of dissapering of first line - unpleasant . Here I shown with empty line, but this can be in the second page and then 1-st line in the grid will dissapear ... How to avoid that ? 

I know that I must to do a sample to jsfidle, but how to do with images in layout in jsfidle - don't know. Excuse ... :)

Any suggestion ? Thanks in advance ...

**Comment by mpf82** [comment]
You could use [Lorempixel](http://lorempixel.com/) as images in your fiddle. That way you can even easily control the size of the placeholder image.

**Comment by Rimokas** [comment]
Thanks, I'll know at second time .. 

Any ideas how to avoid desribed problem ?
