### ISSUE TITLE
Can not use autocomplete with multiselected when render it on w2popup

### ISSUE THREAD

**Issue by dalmatele** [vitmalina/w2ui#1672]
I have a code like this:
`Combo.prototype.addNewWindow = function(){
    this.destroyW2uiObject(w2ui.add_new_layout);
    var self = this;
    $().w2layout({
        name: "add_new_layout",
        padding: 0,
        panels:[
            {
                type: "main",
                size: "600",
                content: "<div id='add_new_main'></div>"
            }
        ]
    });
    w2popup.close();
    w2popup.open({
        title: "Create new combo",
        body: "<div id='add_new_popup' style='width: 100%; height: 100%;'></div>",
        modal: false,
        width: 600,
        height: 350,
        showClose: true,
        onOpen: function(event){
            event.onComplete = function(event){
                $("#w2ui-popup #add_new_popup").w2render("add_new_layout");
                var html = new Array();
                html.push("<div class='row' style='margin-top:5px;'>");
                    html.push("<div class='col-md-3'>Combo name:</div>");
                    html.push("<div class='col-md-9'><input id='combo-name' style='width: 100%;'/></div>");
                html.push("</div>");
                html.push("<div class='row' style='margin-top:5px;'>");
                    html.push("<div class='col-md-3'>Combo code:</div>");
                    html.push("<div class='col-md-9'><input id='combo-code' style='width: 100%;'/></div>");
                html.push("</div>");
                html.push("<div class='row' style='margin-top:5px;'>");
                    html.push("<div class='col-md-3'>Combo price:</div>");
                    html.push("<div class='col-md-9'><input id='combo-price' style='width: 100%;'/></div>");
                html.push("</div>");
                html.push("<div class='row' style='margin-top:5px;'>");
                    html.push("<div class='col-md-3'>Valid date:</div>");
                    html.push("<div class='col-md-3'><input id='combo-valid-date' style='width: 100%;'/></div>");
                    html.push("<div class='col-md-3'>Exprired date:</div>");
                    html.push("<div class='col-md-3'><input id='combo-expire-date' style='width: 100%;'/></div>");
                html.push("</div>");
                html.push("<div class='row' style='margin-top:5px;'>");
                    html.push("<div class='col-md-3'>Courses:</div>");
                    html.push("<div class='col-md-9'><input id='courses-lst' style='width: 100%;'></div>");
                html.push("</div>");
                html.push("<div class='row' style='margin-top:5px;'>");
                    html.push("<div class='col-md-2 col-md-offset-7'><button type='button' id='save-btn' class='btn btn-primary'>Save</button></div>");
                    html.push("<div class='col-md-2' style='margin-left: 40px;'><button type='button' id='cancel-btn' class='btn btn-primary'>Cancel</button></div>");
                html.push("</div>");
                $("#add_new_main").append(html.join(""));
                $("#cancel-btn").click(function(){
                    w2popup.close();
                });
                $("#courses-lst").w2field("enum",
                    {
                        items: self.courses,
                        openOnFocus: true //must have
                    }
                );
            };
        }
    });
};`

and self.courses is a source for list.
With this, I can use multi selected field but can not use autocomplete function of this util. When I type something, it reports that input.val() is not undefined.
This error happen in 1.4 version.
Can you recheck that?

**Comment by mpf82** [comment]
Can you please provide a Fiddle/Bin/Pen to demonstrate the issue?

**Comment by mpf82** [comment]
Closing issue: no response
