### ISSUE TITLE
Enabling toolbar button

### ISSUE THREAD

**Issue by aditya1122** [vitmalina/w2ui#1674]
I was trying to enable the toolbarSave button when button the button is not enabling.

    this.toolbar.enable('w2ui-save');

**Comment by mpf82** [comment]
Can you create a fiddle to demonstrate your problem?
The code you posted is looking good, IMHO.

Here's a working example: http://jsfiddle.net/szgtdvw9/

Please close this issue if your problem has been resolved.

Cheers =)

**Comment by mpf82** [comment]
Closing issue: no response
