### ISSUE TITLE
Bottom panel overlaps left/main/right panels

### ISSUE THREAD

**Issue by nightrider77** [vitmalina/w2ui#1677]
I'm submitting a bug report / feature request.

Let's imagine I want to devide user's interface to 3 adjustable parts.

```
var pstyle = 'height:300px; border:1px solid #dfdfdf; padding:5px;';
$().w2layout({
    name: 'doc_panel',
    padding: 4,
    panels: [
      { type: 'left', size: '49.8%', resizable: true, style: pstyle, content: 'left' },
      { type: 'main', size: '49.8%', resizable: true, style: pstyle, content: 'main' },
      { type: 'bottom', size: '99.6%', resizable: true, style: pstyle, content: 'bottom' },
    ]
});
```

This example results in overlapping left and main panels by bottom: left and main panels have 0px height and bottom panel has 0px top indention.

**Comment by mpf82** [comment]
Well, what is your *expected* behavior?
If you tell the bottom panel to have a height of 99.6%, that leaves little rom for the left and main panel.
Bottom always has a width of 100%.

Maybe you should look into ``minSize`` instead.

E.g. if you want the bottom panel to be **100px or less** (of the 400px of the container) you could use this code:

```
$(function () {
   var pstyle = 'border:1px solid #dfdfdf; padding:5px;';
$("#layout").w2layout({
    name: 'doc_panel',
    padding: 4,
    panels: [
      { type: 'left', size: '49.8%', minSize: 300, resizable: true, style: pstyle, content: 'left' },
      { type: 'main', size: '49.8%', minSize: 300, resizable: true, style: pstyle, content: 'main' },
      { type: 'bottom', size: '100px', resizable: true, style: pstyle, content: 'bottom' },
    ]
});
});
```

fiddle: http://jsfiddle.net/11wybhbv/

**Comment by mpf82** [comment]
Closing issue: no response
