### ISSUE TITLE
jquery3 - tabs + layout + grid

### ISSUE THREAD

**Issue by STiAT** [vitmalina/w2ui#1678]
* **I'm submitting a ...**
[x] bug report

* **What is the current behavior?**
Using jquery-3.2.1, grids are not re-rendered when OnClick on a tab sets a new grid to be shown using w2ui.layout.html.

Example:
```
onClick: function (event)
{
    switch(event.target)
    {
        case "fields":
            w2ui.layout.html('main', w2ui.efieldsgrid);
            break;
        case "details":
            w2ui.layout.html('main', w2ui.edetailsgrid);
            break;
        case "journal":
            w2ui.layout.html('main', w2ui.journalgrid);
            break;
    }
}
```

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a screenshots**.
In jquery3, the grid somehow shows, it even knows the number of rows, but it does not render the information into the grid / the actual data / records are not shown.

Works perfectly fine with jquery-2.2.4.

* **What is the expected behavior?**
The records to be shown

**Comment by mpf82** [comment]
Can you please provide a Fiddle/Bin/Pen to demonstrate the issue?

**Comment by STiAT** [comment]
Will try to reproduce with a current version and provide the requested information next week, I ain't at my home setup at the moment.

**Comment by mpf82** [comment]
Closing issue: no response
