### ISSUE TITLE
problem with inactive list

### ISSUE THREAD

**Issue by julienparagon** [vitmalina/w2ui#1679]
Hi,

I use drop down list and I encounter problems.

My list is empty and I can not type anything.
I used the same code as on the website (http://w2ui.com/web/demos/#!fields/fields-3) but the list remains empty and inactive.

![list](https://user-images.githubusercontent.com/32343253/30937122-2ac38b46-a3d6-11e7-8d1d-342ff1ff9131.png)

I tried with IE11, Google Chrome and Edge but the problem is the same.
I use version 1.5 rc1 of w2ui

Could you tell me what is going on?

Thank you

**Comment by mpf82** [comment]
Can you please create a jsfiddle to reproduce your problem?

Or can you tell us if you managed to solve the problem on your own, so that this issue can be closed?

**Comment by mpf82** [comment]
Closing issue: no response, no reproducer
