### ISSUE TITLE
Consuming ASP.NET Web Services with w2ui Grid

### ISSUE THREAD

**Issue by umbundu** [vitmalina/w2ui#1683]
First, thank you for such beautiful design!
I am trying to use the grid control to consume a simple web service using (ASMX) asp.net but keep getting a message saying that the json is invalid, even though it meets the requirements in the docs!
Do you have any examples using asp.net?
Thanks,
Everardo

**Comment by aadrian** [comment]
@umbundu take a look at https://github.com/vitmalina/w2ui/tree/master/server

The PHP implementation seems more complete.

**Comment by umbundu** [comment]
I did, there is nothing there for .net. thanks

**Comment by aadrian** [comment]
@umbundu as you can see from that page, only the PHP implementation is declared "complete". So you will have to use it as a "specification" and do the same for ASP.  

Someone else tried to do it for .NET https://github.com/gulitskiy/w2ui.net but it's also not ready either.

**Comment by umbundu** [comment]
thank you!

**Comment by mpf82** [comment]
Closing as resolved.
