### ISSUE TITLE
Toolbar - Break with id in sub menu

### ISSUE THREAD

**Issue by Mimu1988** [vitmalina/w2ui#1685]
* **I'm submitting a ...**
[x ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **What is the current behavior?**
If you have a break with an id set inside an sub menu of the toolbar the break won´t be displayed correct.
It shows the text of the break id.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a screenshots**.
![image](https://user-images.githubusercontent.com/20539382/31402512-7e893508-adf6-11e7-9a06-5e2f2bb9f16f.png)

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Link to jsFiddle that demonstrates the problem:**
@https://jsfiddle.net/so3dq3so/

* **Other information**

**Comment by mpf82** [comment]
Created a PR: #1695

**Comment by mpf82** [comment]
Closing as resolved: https://jsfiddle.net/ghmfbd43/
