### ISSUE TITLE
tabindex problem when two forms in same page

### ISSUE THREAD

**Issue by nproto** [vitmalina/w2ui#1686]
* **I'm submitting a ...**
[] bug report
[x] feature request
[ ] question about the decisions made in the repository

* **What is the current behavior?**
When there are two forms autogenerated in the same page the focus from the first field of the first form jumps to first field of the second form, then it comes back to the second of the first form and then again to the second of the second form and so on.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a screenshots**.

* **What is the expected behavior?**
The focus  should stay in the same form until all field is exhausted.

* **What is the motivation / use case for changing the behavior?**
There many cases where two forms are present in the same page

* **Link to jsFiddle that demonstrates the problem:**

* **Other information**
The problem occurs because the tabindex numbering of the fields  starts from 1 in each form. So there are two fields with tabindex 1, two with tabindex 2 and so on.
A solution could be to allow the setting of tabindex in the field options or even set the starting number of the autoincrement used for the tabindex, in the form options.

**Comment by nproto** [comment]
I noticed that I can set the tabindex through the attr  option. When I set for example 
{ field: 'ff', type: 'test', html: { caption: 'ff', attr:'tabindex=102' } } it works fine.

**Comment by mpf82** [comment]
I created a PR #1708, that will not completely solve this issue, but you can now assign a value to ``w2form.tabindexBase``, so you do not need to assign a tabindex to every field manually.

**Comment by nproto** [comment]
This will solve the issue. Thank you.

**Comment by vitmalina** [comment]
PR merged
