### ISSUE TITLE
[1.5.rc1] Upload a single file with max=1

### ISSUE THREAD

**Issue by virusav** [vitmalina/w2ui#1688]
To select many files, and is discharged only one, although in the tooltip see the list of all selected files.
More logical would be (src\w2fields.js):
```
@@ -2318,11 +2318,12 @@
                         '</div>';
             }
             if (obj.type == 'file') {
                 html =  '<div class="w2ui-field-helper w2ui-list" style="'+ margin + '; box-sizing: border-box">'+
                         '   <div style="position: absolute; left: 0px; right: 0px; top: 0px; bottom: 0px;">'+
-                        '       <input class="file-input" type="file" style="width: 100%; height: 100%; opacity: 0;" name="attachment" multiple tabindex="-1"' + ($(obj.el).prop('readonly') ? ' readonly="readonly"': '') + ($(obj.el).prop('disabled') ? ' disabled="disabled"': '') + ($(obj.el).attr('accept') ? ' accept="'+ $(obj.el).attr('accept') +'"': '') + '/>'+
+                        '       <input class="file-input" type="file" style="width: 100%; height: 100%; opacity: 0;" name="attachment"'+
+                        (obj.options.max != 1 ? ' multiple' : '') + ' tabindex="-1"' + ($(obj.el).prop('readonly') ? ' readonly="readonly"': '') + ($(obj.el).prop('disabled') ? ' disabled="disabled"': '') + ($(obj.el).attr('accept') ? ' accept="'+ $(obj.el).attr('accept') +'"': '') + '/>'+
                         '   </div>'+
                         '    <div style="position: absolute; padding: 0px; margin: 0px; display: inline-block" class="w2ui-multi-items">'+
                         '        <ul><li style="padding-left: 0px; padding-right: 0px" class="nomouse"></li></ul>'+
                         '    </div>'+
                         '</div>';


```

**Comment by mpf82** [comment]
How do you even select multiple files if you set max to 1?

The line ``if (options.max !== 0 && cnt >= options.max) {`` should prevent this.

And in what tooltip do you see a list of files? The w2ui tooltip shows only the info of the clicked item.

Removing the ``multiple`` does not affect the behaviour of a w2ui file field, as far as I can see - neither in the browser nor does it have an influence on how the data is sent to the server (if you're working with a server backend).

Can you elaborate your concern and maybe create a fiddle to demonstrate your problem?

**Comment by virusav** [comment]
If you need to upload only one file, it is not necessary to give the possibility to select multiple files.

**Comment by virusav** [comment]
I enclose screenshots:
![step_1](https://user-images.githubusercontent.com/323130/32363633-5aec321a-c081-11e7-8ce3-f92c9cfca974.gif)
![step_2](https://user-images.githubusercontent.com/323130/32363634-5b0c154e-c081-11e7-9d05-050cd3f6f090.gif)
![step_3](https://user-images.githubusercontent.com/323130/32363635-5b2c94b8-c081-11e7-99a7-961b0ea57411.gif)

max=1

The current version:
step_1 - we choose multiple files
step_2 - in the end selects only one file, but the tooltip shows the names of all selected files

With the proposed edit:
step_3 - we can choose only one file

**Comment by mpf82** [comment]
Thanks for your detailed explanation, now I understand what this is about.

This issue is adressed in PR #1706

Feel free to close the issue, or leave it open until the PR has been merged.

Cheers =)

**Comment by mpf82** [comment]
Closing issue: related PR has been merged
