### ISSUE TITLE
Search with "not in" will act as "in" in 1.5rc1

### ISSUE THREAD

**Issue by dominiquebeauchamp** [vitmalina/w2ui#1689]
* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **What is the current behavior?**
I use multiSearch and a field with enum/items and I provide a list. When I select the items in the enum, the "in" works correctly, i.e. it keeps only the records that match the selected items in the enum. But when I select "not in", it behaves exactly like the "in" rather than keeping the records that don't match the selected items.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a screenshots**.

Original list or records

![bug_nosearch](https://user-images.githubusercontent.com/32841732/31614428-697931e2-b254-11e7-9bcc-216b4d2712b6.PNG)

Searched list with "in": expected behavior

![bug_in](https://user-images.githubusercontent.com/32841732/31614473-8b2c5c6a-b254-11e7-9b1a-61eaffcc3be2.PNG)

Searched list with "not in": inverted behavior. I expected to get the "MyTest_2" as they are "not in" the selected set in the box.

![bug_notin](https://user-images.githubusercontent.com/32841732/31614534-b2be9d38-b254-11e7-83aa-d647202bd4ed.PNG)

The filtered records must be those that don't match the searched items in the enum because we ask for "not in" the items...

w2ui 1.5rc1
jQuery 2.2.4
Chrome 52.0.2... (not the last one, I'm working in a private/isolated network.)

**Comment by vipersss** [comment]
fixed it in commit https://github.com/vitmalina/w2ui/commit/13a277a0f8ab04f3f5ff9941dab0e5f7f6b58226

**Comment by mpf82** [comment]
Closing issue, related PR #1742 has been merged
