### ISSUE TITLE
Problem with rendering different date formats in Grid

### ISSUE THREAD

**Issue by yodes69** [vitmalina/w2ui#1707]
* **I'm submitting a ...** bug report

When using render in the grid column for a date to a format such as date:yyyy-mm-dd it returns 1969-12-31 for any date.  The problem is with w2utils.formatters for dates.  It uses the same date format for checking to see if it is a valid date as it does to format the date.  So if yyyy-mm-dd is passed into params, it uses that to see if it is a valid date and fails.

I have created a work around that seems to work, but makes some assumptions.  I load the settings default date format all the time into a variable.  I than pass this new variable into both the isDateTime and isDate function.  I still pass params into formatDate.

I was not sure exactly what the settings default date format is used for?  I assumed that it represents how the user prefers to represent dates.  I was also using this as the default format that is returned from sql queries, which in my case also fixed the problem of mysql returning dates in the yyyy-mm-dd fromat.  I am also able to fix the mysql issue by using mysql function date_format on my dates.

Last issue I have with formatting dates is the .replace(/yyyy/g year), .replace(/yyy/g, year), and .replace(/yy/g,  year > 2000 ? 100 + parseInt(String(year).substr(2)) : String(year).substr(2)).
I was wondering why there are two format for four digit year(yyyy and yyy)?   Seems like yyy would represent what  yy does and yy would have been a two digit year?

Let me know if these fixes make sense or if I am way off base.

Thanks!
John

**Comment by quillaja** [comment]
I just tried removing a call to `isDate()` on line 5582 (this is a copy of 1.5 rc1 I downloaded maybe a few months ago).
from
```javascript
val = w2utils.formatDate(w2utils.isDate(val, edit.format, true), edit.format);
```
to
```javascript
val = w2utils.formatDate(val, edit.format);
```

If `isDate()` returns false (which it is always doing for me since my "date" values are full RFC3339 date-time strings (eg `2006-01-02T15:04:05Z07:00`)), then `formatDate()` gets a boolean which results in an empty string being returned. That empty string is then evaluated to 0 or some other invalid `Date`, hence the shown date as `1969-12-31`.

**Comment by vitmalina** [comment]
There was a recent bug fix in isDate. Can you see if with this fix it is working for your user case. You can download form here: 
```
https://raw.githubusercontent.com/vitmalina/w2ui/master/dist/w2ui.js
https://raw.githubusercontent.com/vitmalina/w2ui/master/dist/w2ui.css
```

Also, if you want grid to render dates, you can write your provide your own renderer. See w2utils.formatters <http://w2ui.com/web/docs/1.5/w2utils.formatters> or you can just provide a function for render.

**Comment by quillaja** [comment]
Sorry, I hope my comment above wasn't too critical sounding. I appreciate all the work you've done on this project.

I tried modifying a number of the functions to parse and format date/time, but each time I just found some other way it would break or send data back to my server in the wrong format. In the end, I found it much easier to change my server to use the `yyyy-mm-dd hh:mm:ss` format that it seems w2ui is expecting. I should have experimented more with w2ui before posting to github. Sorry.

As an added bonus, this format is actually more readable in database and will make it easier for me to output CSV files nicely formatted for human interaction (as opposed to ISO8601/RFC3339 which is less human friendly).

**Comment by vitmalina** [comment]
Got it. Thanks for the note. In my experience, the best way to work with dates is to pass Unix Timestamp. All languages support it, and there is no confusion with time zone. I use it with the grid this way and never have problems. In the grid, it just renders in the format you specify.
