### ISSUE TITLE
opposite of "w2utils.escapeId"

### ISSUE THREAD

**Issue by rolfn** [vitmalina/w2ui#1715]
* **I'm submitting a ...**
[ ] bug report
[ x] feature request
[ ] question about the decisions made in the repository

Sometimes it would be helpful to have the inverse function to "w2utils.escapeId" (--> "unescapeId"). I use path-like names which must be escaped in normal usage but un-escaped if the path should use otherwise. I defined by myself the following:
```
function unescapeId(id) {
  return String(id).replace(/\\/g, '');
}
``` 
Thanks in advance.

**Comment by mpf82** [comment]
Closing as implemented: #2105
