### ISSUE TITLE
[1.5.rc1] grid.reload getSelection()

### ISSUE THREAD

**Issue by virusav** [vitmalina/w2ui#1716]
grid with url

If you highlight an item, and then reload the grid, then the allocation will remain in place, but to the selected item is not obtained.

```
grid.select
grid.getSelection()[0] = X
grid.reload
grid.getSelection()[0] = undefined
```

Is this a bug?
Whether in this case to use grid.last.sel_recid?

**Comment by mpf82** [comment]
Can you create a fiddle to reproduce the issue?

I tried, but before and after the reload everything is fine: http://jsfiddle.net/5Lxqyaxu/

**Comment by mpf82** [comment]
Closing issue: no response, no reproducer
