### ISSUE TITLE
[1.5.rc1] grid.expand fixedBody=false

### ISSUE THREAD

**Issue by virusav** [vitmalina/w2ui#1717]
If in grid when opening to insert another grid (fixedBody=false), then the height of the element event.fbox_id is calculated incorrectly, ie less records.length*H, where H is the height of the line grid.

**Comment by mpf82** [comment]
Can you please provide a Fiddle/Bin/Pen to demonstrate the issue?

**Comment by mpf82** [comment]
Closing issue: no response
