### ISSUE TITLE
Field TabIndex incorrect after enum field refresh

### ISSUE THREAD

**Issue by Mimu1988** [vitmalina/w2ui#1730]
* **I'm submitting a ...**
[x ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **What is the current behavior?**
The TabIndex of a field type enum isn´t correct after the field was refreshed.

 

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a screenshots**.

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Link to jsFiddle that demonstrates the problem:**

* **Other information**
Problem is tabIndex at function "addMulti"  is being checked as number but it is a string.
So the check against -1 will always return true.

**Comment by mpf82** [comment]
Closing issue: fixed
