### ISSUE TITLE
users.php doesn't return DATA from mysql database

### ISSUE THREAD

**Issue by majidwafi** [vitmalina/w2ui#1735]
I have a basic problem for more than 2 weeks, my page users.php doesn't return data, could you help me please, I am blocked.

here is the message posted on the users.php page :

<br />
<font size = '1'> <class table = 'xdebug-error xe-notice' dir = 'ltr' border = '1' cellspacing = '0' cellpadding = '1'>
<tr> <th align = 'left' bgcolor = '# f57900' colspan = "5"> <span style = 'background-color: # cc0000; color: # fce94f; font-size: x-large; '> (!) </ span> Notice: Undefined index: cmd in C: \ wamp \ www wafi \ w2ui-master \ server \ php \ users.php on line <i> 9 </ i> </ th> </ tr>
<tr> <th align = 'left' bgcolor = '# e9b96e' colspan = '5'> Call Stack </ th> </ tr>
<tr> <th align = 'center' bgcolor = '# eeeeec'> # </ th> <th align = 'left' bgcolor = '# eeeeec'> Time </ th> <th align = 'left' bgcolor = '#eeeeec'> Memory </ th> <th align = 'left' bgcolor = '# eeeeec'> Function </ th> <th align = 'left' bgcolor = '# eeeeec'> Location </ th> </ tr>
<tr> <td bgcolor = '# eeeeec' align = 'center'> 1 </ td> <td bgcolor = '# eeeeec' align = 'center'> 0.0020 </ td> <td bgcolor = '# eeeeec' align = 'right'> 135504 </ td> <td bgcolor = '# eeeeec'> {main} () </ td> <td title = 'C: \ wamp \ www \ wafi \ w2ui-master \ server \ php \ users.php 'bgcolor =' # eeeeec '> ... \ users.php <b>: </ b> 0 </ td> </ tr>
</ Table> </ font>
<br />
<font size = '1'> <class table = 'xdebug-error xe-notice' dir = 'ltr' border = '1' cellspacing = '0' cellpadding = '1'>
<tr> <th align = 'left' bgcolor = '# f57900' colspan = "5"> <span style = 'background-color: # cc0000; color: # fce94f; font-size: x-large; '> (!) </ span> Notice: Undefined index: cmd in C: \ w \ www \ wafi \ w2ui-master \ server \ php \ users.php on line <i> 42 </ i> </ th> </ tr>
<tr> <th align = 'left' bgcolor = '# e9b96e' colspan = '5'> Call Stack </ th> </ tr>
<tr> <th align = 'center' bgcolor = '# eeeeec'> # </ th> <th align = 'left' bgcolor = '# eeeeec'> Time </ th> <th align = 'left' bgcolor = '#eeeeec'> Memory </ th> <th align = 'left' bgcolor = '# eeeeec'> Function </ th> <th align = 'left' bgcolor = '# eeeeec'> Location </ th> </ tr>
<tr> <td bgcolor = '# eeeeec' align = 'center'> 1 </ td> <td bgcolor = '# eeeeec' align = 'center'> 0.0020 </ td> <td bgcolor = '# eeeeec' align = 'right'> 135504 </ td> <td bgcolor = '# eeeeec'> {main} () </ td> <td title = 'C: \ wamp \ www \ wafi \ w2ui-master \ server \ php \ users.php 'bgcolor =' # eeeeec '> ... \ users.php <b>: </ b> 0 </ td> </ tr>
</ Table> </ font>
{"status": "error", "message": "Command \" is not recognized. "," postData ": []}

below the php code:

<?Php

require ("w2db.php"); 
require ("w2lib.php");

$db = new dbConnection ("mysql"); 
$db-> connect ("localhost", "root", "", "test", "3306");

switch ($_REQUEST ['cmd']) {

case 'get':
    if (array_key_exists('recid', $_REQUEST)){  // if true , then is a 'get-record' only one record with recid
        $sql = "SELECT userid, fname, lname, email, login, password
                FROM users
                WHERE userid = ".$_REQUEST['recid'];
        $res = $w2grid->getRecord($sql);
    }
    else{        
        $sql  = "SELECT * FROM users       
                 WHERE ~search~ ORDER BY ~sort~";
        $res = $w2grid->getRecords($sql, null, $_REQUEST);
    }  
     $w2grid->outputJSON($res);
    break;

case 'delete':
    $res = $w2grid->deleteRecords("users", "userid", $_REQUEST);
    $w2grid->outputJSON($res);
    break;

//case 'get-record':
//    break;

case 'save':
    $res = $w2grid->saveRecord('users', 'userid', $_REQUEST);
    $w2grid->outputJSON($res);
    break;

default:
    $res = Array();
    $res['status']  = 'error';
    $res['message'] = 'Command "'.$_REQUEST['cmd'].'" is not recognized.';
    $res['postData']= $_REQUEST;
    $w2grid->outputJSON($res);
    break;

    }

thank you in advance for your valuable help

**Comment by majidwafi** [comment]
Hello,

need some help please, it's really urgent!!!

**Comment by majidwafi** [comment]
help please, im stuck !!

**Comment by majidwafi** [comment]
i have this error msg

Notice: Undefined index: cmd


{"status":"error","message":"Command \"\" is not recognized.","postData":[]}

thank you in advance for your help

**Comment by mpf82** [comment]
grid no longer sends "cmd", it's now called "action" and it's only set for "save" and "delete", no longer for "get".

Releated issues: 1997, 1869 and 1837

Docs have been updated: http://w2ui.com/web/docs/1.5/grid

Closing issue as resolved.
