### ISSUE TITLE
I want to be able to select multiple when w2form's filedType is checkbox.

### ISSUE THREAD

**Issue by hinoko58** [vitmalina/w2ui#1744]
Even if multiple checkboxes are placed, it seems that there is only one return value with w2form.record [fieldname]. Can I make multiple settings possible?
The value to be acquired should be in the form of [1, 2, 3]

Thank you.

**Comment by mpf82** [comment]
I sounds that what you want is an ``enum`` field.

Check out this demo: http://w2ui.com/web/demos/#!fields/fields-4

**Comment by mpf82** [comment]
Closing issue: no response
