### ISSUE TITLE
showClose property on popup d'ont appear

### ISSUE THREAD

**Issue by hervest** [vitmalina/w2ui#1755]
popup showclose button and ShowMax button don't appear, i change css file and w2ui from 1.4 to 1.5 file but nothing. is the any issue?

**Comment by hervest** [comment]
i try another css file wui1.4.css and it's appear but after three test, showmax et showclose button desapear again

**Comment by mpf82** [comment]
Can you please provide a Fiddle/Bin/Pen to demonstrate the issue?

**Comment by mpf82** [comment]
showClose and showMax are working fine in the demo: http://w2ui.com/web/demos/#/popup/1

Closing issue: cannot reproduce; no response
