### ISSUE TITLE
Filling form content onRender does not work.

### ISSUE THREAD

**Issue by tomaso909** [vitmalina/w2ui#1757]
I want to fill the textarea of a form with content when the form is created. I am trying to do it with an onRender event but the field is undefined so its 'value' property cannot be changed:

Fiddle: http://jsfiddle.net/tomaso909/fgfLwbsu/3/

**Comment by mpf82** [comment]
You can use w2form.record:

```
$(function () {
    $('#form').w2form({ 
        name  : 'form',
        fields: [
            { field: 'comments',   type: 'textarea'}
        ],
        record: {
        	"comments": "Hello World!"
        }
    });
});
```

Updated fiddle: http://jsfiddle.net/fgfLwbsu/5/

**Comment by tomaso909** [comment]
I cant believe I missed that. Thank you.
Sorry for asking this kind of questions here but I never get an answer on w2ui.com.

**Comment by mpf82** [comment]
No problem. I don't use Disqus, but I and other w2ui users are also active on StackOverflow, so you might want to ask over there. 

Of course bugs and feature request should still be posted here.

It's been suggested o get rid of Disqus and add the solved Disqus issue to the FAQ: https://github.com/vitmalina/w2ui/issues/1546 but Vitali didn't reply yet, but as you said, the Disqus issues get rarely answered.

Cheers =)
