### ISSUE TITLE
Fixed width of select column

### ISSUE THREAD

**Issue by optior** [vitmalina/w2ui#1763]
In my usecase for w2ui grid I've stumbled over the fixed width of the select column set to 26px. In my case I needed a bigger value, so I changed it in the source. Is there any way to detect the width of the select column? I think a fixed value isn't the best solution.

**Comment by mpf82** [comment]
> Is there any way to detect the width of the select column?

You can get the width (including borders) with `$(".w2ui-head.w2ui-col-select").outerWidth();`

Closing issue: resolved.

As you said, you can override it in your CSS.

If you think that the width of the select column should be an option that you can modify, please open a new Feature Request issue and explain the use case.
