### ISSUE TITLE
If a column is created dynamically there is no tooltip

### ISSUE THREAD

**Issue by boumboum** [vitmalina/w2ui#1764]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

If I create the columns dynamically via addColumn there is no any tooltype appearing if I hover the mouse over the cell, except above the first (frozen) column which is a string (the other columns are rendered as 'int'.)

W2ui 1.5

**Comment by mpf82** [comment]
Can you please provide a Fiddle/Bin/Pen to demonstrate the issue?

**Comment by mpf82** [comment]
Grid cells of the added column have a tooltip, just like the other ones: http://jsfiddle.net/m19wuhfL/

Closing issue: cannot reproduce; no response
