### ISSUE TITLE
form onSubmit 

### ISSUE THREAD

**Issue by awadhesh4772** [vitmalina/w2ui#1765]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[] question about the decisions made in the repository

* **What is the current behavior?**
Unable to send additional parameters form onSubmit event. my example code below
    **onSubmit: function(event){
    	w2ui['form']['postData'] = {param1 : 'value1'};
    }**

When click on Save button first time, postdata not available on remote server.. but when click again save button.. then post data available. below is example of fist click and second click. 
**1st Click : {"cmd":"save","recid":0,"name":"form","record":{"first_name":"John"}}
2nd Click : {"cmd":"save","recid":0,"name":"form","param1":"value1","record":{"first_name":"John"}}**

Is this right way to post data on click save button?

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a screenshots**.

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Link to jsFiddle that demonstrates the problem:**

* **Other information**

**Comment by mpf82** [comment]
> Is this right way to post data on click save button?

No, at this point you're not supposed to edit the form's postData, instead modify the event:

```
onSubmit: function(event){
    event.postData.param1 = 'value1';
}
```

As you already saw, modifying the form will only change the postData for the next call of the event.

So this is not a bug, but the intended (though badly documented) behavior.

Cheers =)

**Comment by awadhesh4772** [comment]
Thank you very much Mike!!
It is working perfect as you advised. 
Cheers!
