### ISSUE TITLE
File Upload Example

### ISSUE THREAD

**Issue by awadhesh4772** [vitmalina/w2ui#1766]
* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[X] question about the decisions made in the repository

Hi, Can any provide an example of upload big file. e.g. 2mb to 10mb.. 

* **What is the current behavior?**
The situation is, when I am uploading small file (below 1mb), file content generated quickly sent along with form data. But when file is big size, form Save request completed before form-data with content generated. I debug in chrome browser and noticed that form-data loaded after some time, though Form Save request has complete, hence request is null at server side. 

my example code is 
$('#main').w2form({
	name : 'form',
	url : 'saveForm',
	fields : [ {name : 'upload',type : 'file'} ],
	actions : {
		save : function(event) {			
			this.save();
		}
	}
});

I believe there will be some way to handle it, but I don't know.. Please help with quick example. 

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a screenshots**.

* **What is the expected behavior?**
Submit form-data with upload file content on Form Save click.

* *f*What is the motivation / use case for changing the behavior?**

* **Link to jsFiddle that demonstrates the problem:**

* **Other information**

**Comment by mendozada** [comment]
Hi, i use this 

`                { field: 'archivo',  type: 'file', required: true, html: { caption: 'Archivo:' ,  attr: 'style="width: 300px"' },  options:{ max : 1, maxSize : 10500000 ,
                      onAdd:function(event){

                          event.onComplete = function(){
                                  console.log('esta Completo' + event)
                          };
                          if (event['file']['size'] > 10500000 ) {
                            w2alert('Archivo supera el tamaño permitido de 10mb.')
                          }
                          console.log(event)
                      },
                    }
                },`

and server side with PHP
`
  $direc = '../myFolder/'. $_REQUEST['record']['archivo'][0]['name'];
  $base64string = $_REQUEST['record']['archivo'][0]['content'];
  file_put_contents( $direc, base64_decode($base64string));
`
I hope it is useful, greetings

**Comment by mayurivaibhav** [comment]
It's still not working

**Comment by vitmalina** [comment]
@mayurivaibhav  Your comment is not very informative
