### ISSUE TITLE
w2grid right click on render function

### ISSUE THREAD

**Issue by LitMB** [vitmalina/w2ui#1772]
Greetings,
i have a simple w2grid without menu or oncontextmenu custom code.
but only a column with a render function like 

` render: function (record, index, col_index) { return '<div><a href="http://www.google.com" >CLICK ME</a></div>'; }`

I noticed that left mouse click on "CLICK ME" works as expected for a hyperlink, but right click doesn't show standard browser context menu.

How could be possible fix it? 
Thanks

**Comment by mpf82** [comment]
Simply implement an empty context menu handler and you will get the default browser right click menu for the whole grid.

```
$(function () {
    $('#grid').w2grid({ 
        name: 'grid', 
        columns: [                
            { field: 'fname', caption: 'First Name', size: '30%' },
            { field: 'lname', caption: 'Last Name', size: '30%' },
            { field: 'email', caption: 'Email', size: '40%',  render: function (record, index, col_index) { return '<div><a href="http://www.google.com" >CLICK ME</a></div>'; } },
            { field: 'sdate', caption: 'Start Date', size: '120px' }
        ],
    "records": [
        { "recid": 1, "fname": "John", "lname": "Doe", "email": "jdoe@gmail.com", "sdate": "4/3/2012" },
        { "recid": 2, "fname": "Stuart", "lname": "Motzart", "email": "jdoe@gmail.com", "sdate": "4/3/2012" },
        { "recid": 3, "fname": "Jin", "lname": "Franson", "email": "jdoe@gmail.com", "sdate": "4/3/2012" },
        { "recid": 4, "fname": "Susan", "lname": "Ottie", "email": "jdoe@gmail.com", "sdate": "4/3/2012" },
        { "recid": 5, "fname": "Kelly", "lname": "Silver", "email": "jdoe@gmail.com", "sdate": "4/3/2012" },
        { "recid": 6, "fname": "Francis", "lname": "Gatos", "email": "jdoe@gmail.com", "sdate": "4/3/2012" },
    ],
    contextMenu: function() {}
    });    
});
```

Fiddle: http://jsfiddle.net/ct3vhLh2/

If you need it "more fancy" (e.g. only for specific cells / columns) you will have to check the values of the context menu handler (parameters: ``(recid, column, event)``) and return or call ``event.preventDefault();`` accordingly.

Cheers =)

**Comment by mpf82** [comment]
You're welcome. Please close the issue if it has been solved.
