### ISSUE TITLE
[Feature] Responsive Tabs

### ISSUE THREAD

**Issue by ellisgl** [vitmalina/w2ui#1773]
As a developer, I would like have responsive tabs, where icons to scroll (arrows) will show up when there is an overflow.

**Comment by mpf82** [comment]
Already implemented in 1.5

http://w2ui.com/web/demos/#!tabs/tabs-7

Cheers =)

**Comment by mpf82** [comment]
Please close the issue if it has been solved.

Otherwise please elaborate on your feature request.

**Comment by qPrutp** [comment]
In our project we are using 1.4.2 version. I would like have responsive tabs, where icons to scroll (arrows) will show up when there is an overflow.
http://w2ui.com/web/demos/#!tabs/tabs-7
is not work ... is possible it?
