### ISSUE TITLE
JSON (") quote issue!!!

### ISSUE THREAD

**Issue by ImAbhishekTomar** [vitmalina/w2ui#1781]
Can you please help.

This is my object created by c# code based on SQL data.
{
  "RowId": 4533,
  "PriorityID": 11,
  "Priority_Description": "Exceeded PG WD 11+ where Clock has not stopped",
  "PrioritySort": 13000,
  "Include": false,
  "UnitID": 82,
  "Unit": "PI",
  "AuditDate": "/Date(1493700221290)/",
  "AuditUser": "MS\\jdean9",
  "RuleStartDate": "/Date(1527828900000)/",
  "RuleEndDate": "/Date(1528869600000)/",
  **"w2ui": "{\"style\": \"background-color:#FFC7CE;color:#9C0006\"}",**
  "IsExpire": false,
  "CreatedBy": null,
  "CreatedOn": null,
  "ModifiedBy": null,
  "ModifiedOn": null,
  "recid": 4533,
  "RuleStartDate_": null,
  "RuleEndDate_": null
}

in this object w2ui property is bind in side (") quote.
If i will remove this quote then, this is showing error in my sql query.
how to resolve this issue?

**SQL Query** 

SELECT 
		A.UID as RowId,A.PriorityID,B.Priority_Description,
		A.PrioritySort,
		CAST(IIF(A.[Include]=0,0,1) as bit) as [Include],A.UnitID,C.Unit,
		A.AuditDate,A.AuditUser,
		A.RuleStartDate,
		A.RuleEndDate,
		**IIF(IsExpire=0, '{"style": "background-color:#FFC7CE;color:#9C0006"}' ,null) as w2ui,**
		A.IsExpire,
		A.CreatedBy,
		A.CreatedOn,
		A.ModifiedBy,
		A.ModifiedOn
	FROM 
	[dbo].[T_CPSMasterInventory_Priority_By_Unit] A
	INNER JOIN [dbo].[T_CPSMasterInventory_Priority] B
	ON A.PriorityID=B.PriorityID
	INNER JOIN [dbo].[T_UNIT_ID] C
	ON C.UNITID=A.UnitID	
	AND C.Unit='PI'

**Comment by jackryu** [comment]
Issue resolved.
https://github.com/vitmalina/w2ui/compare/master...jackryu:patch-1?expand=1

**Comment by jackryu** [comment]
Sorry... This solution is not working please help.

**Comment by jackryu** [comment]
my solution is not working, can you please help on this issue #1781

**Comment by Sososlik** [comment]
have you tried escaping the quote? in your sql:
IIF(IsExpire=0, '{\"style\": \"background-color:#FFC7CE;color:#9C0006\"}' ,null) as w2ui,

**Comment by ImAbhishekTomar** [comment]
@KirillBorunov okay I will try.... thanks for comment.

**Comment by mpf82** [comment]
> This is my object created by [...]

Well, your code is not valid JSON.

It is out of the scpe of the w2ui project to write your C# backend code.

Closing issue: not a w2ui issue
