### ISSUE TITLE
deselect checkbox when i double click grid 

### ISSUE THREAD

**Issue by dineshsp** [vitmalina/w2ui#1782]
![image](https://user-images.githubusercontent.com/30404133/41650465-b9243818-749b-11e8-9593-edbc115aedb5.png)

**Comment by dineshsp** [comment]
Help me plz quick

**Comment by mpf82** [comment]
It's not clear what you're trying to do. Is this a bug report? A question?

Can you please provide a Fiddle/Bin/Pen to demonstrate the issue?

**Comment by mpf82** [comment]
Closing issue: no response
