### ISSUE TITLE
Dash ("-") not appearing inside a dropdown menu in the auto complete

### ISSUE THREAD

**Issue by bmakan** [vitmalina/w2ui#1788]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **What is the current behavior?**
When the auto complete list contains a dash, it will not render in the autocomplete list.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a screenshots**.
Can't make screenshot. The dropdown disappears when I click Print Screen button.
Check the fiddle. Type "-" inside the input field. "- " will show but "-" will not.

* **What is the expected behavior?**
"-" should be an option to select inside the dropdown.

* **What is the motivation / use case for changing the behavior?**
"-" is the value we use in our app for a value that's not set yet.

* **Link to jsFiddle that demonstrates the problem:**
http://jsfiddle.net/vpLmtkdg/

* **Other information**

**Comment by mpf82** [comment]
"_It's not a bug, it's a feature_" ™

Any number of consecutive dashes (``-``) will be rendered as a horizontal line.

See function ``getMenuHTML()``, especially this check:

    if (mitem.type !== 'break' && txt != null && txt !== '' && !(/^-+$/.test(txt))) {

You could override this function or use a different string as placeholder.

**Comment by bmakan** [comment]
Good to know. Thanks.

For completeness, I added it as "- " (dash, space) and then I trim the spaces before using the value further in the app. It's a bit dirty but it works well for me.
