### ISSUE TITLE
Date picker and select2 not initialize in w2ui grid on invisible column

### ISSUE THREAD

**Issue by avisodiya** [vitmalina/w2ui#1790]
I have dynamic columns in w2grid column, In such column we have add date picker and select2. Date picker and select2 initialize in visible column but not initialize when horizontal scrolling. And when i horizontal scrolling to last column my all initialize datepicker and selct2 not working. Please help me.

https://i.imgur.com/eRGY7kX.png

@vitmalina

**Comment by mpf82** [comment]
Can you please provide a Fiddle/Bin/Pen to demonstrate the issue?

**Comment by mpf82** [comment]
Closing issue: no response
