### ISSUE TITLE
Is there a way to force column to sort as digit?

### ISSUE THREAD

**Issue by rsaungc** [vitmalina/w2ui#1792]
* **I'm submitting a ...**
[x] bug report
[x ] feature request
[ ] question about the decisions made in the repository

* **What is the current behavior?**

Column won't sort as digit if it has a link.  In following example, 20 will be placed under '111'.  The order should be 11, 20, 111.

<a href="?q=20">20</a>
<a href="?q=11">11</a>
<a href="?q=111">111</a>

Is there a way to sort a column as digits?

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a screenshots**.

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Link to jsFiddle that demonstrates the problem:**

* **Other information**

**Comment by mpf82** [comment]
Natural sort has already been requested: https://github.com/vitmalina/w2ui/issues/1476

And is already implemented: https://github.com/vitmalina/w2ui/pull/1504

You will need to use the sources though, as it's not yet in dist: https://github.com/vitmalina/w2ui/tree/master/src

**Comment by mpf82** [comment]
Closing this issue as resolved, because columns can now have a sortMode ``natural``, see docs: http://w2ui.com/web/docs/1.5/w2grid.columns
