### ISSUE TITLE
enum selected not working  (jsfiddle)

### ISSUE THREAD

**Issue by macingili** [vitmalina/w2ui#1801]
why this code not working
https://jsfiddle.net/macingili/kuhr98ye/5/
```
 $(function () {
			$('#form').w2form({
			name     : 'form',
			 fields: [
				{ name: 'field_enum', type: 'enum', required: true,
            options: {
                items: [ 
                    { id:0, text:'Adams, John' }, 
                    { id:1, text:'Johnson, Peter' }, 
                    { id:2, text:'Lewis, Frank' }, 
                    { id:3, text:'Cruz, Steve' }, 
                    { id:4, text:'Donnun, Nick' }
                ],
                selected: [
                    { id:1, text:'Johnson, Peter' }  //not working
                ]  
            }
        }
    ]
})
	 
```
	 });

**Comment by alan8373** [comment]
Is 'selected' supposed to be an array? Or just a single item?

**Comment by mpf82** [comment]
You should pre-fill form fields with ``form.record``.

https://jsfiddle.net/kuhr98ye/7/

    $('#form').w2form({
			name     : 'form',
			//url      : 'server/post',
			fields: [
				{ name: 'field_enum', type: 'enum', required: true,
            options: {
                items: [ 
                    { id:0, text:'Adams, John' }, 
                    { id:1, text:'Johnson, Peter' }, 
                    { id:2, text:'Lewis, Frank' }, 
                    { id:3, text:'Cruz, Steve' }, 
                    { id:4, text:'Donnun, Nick' }
                ]
            }
        }
    ],
    record: {
    	field_enum: [{ id:1, text:'Johnson, Peter' }]
    }
    })

**Comment by mpf82** [comment]
Closing issue as resolved
