### ISSUE TITLE
datetime component

### ISSUE THREAD

**Issue by devzonetrack** [vitmalina/w2ui#1802]
Any plan to add datetime picker component?

**Comment by mpf82** [comment]
w2ui 1.5 already has a datetime picker. 

There's even an online demo: http://w2ui.com/web/demos/#!fields/fields-2

**Comment by horninblack** [comment]
It has some inconvinience when year displayed in 2-digit mode. For example, 2009 is displayed as 109.

**Comment by mpf82** [comment]
@horninblack might have been related to https://github.com/vitmalina/w2ui/issues/1941 - can you test with the latest sources?

If it's still not working, can you please create a fiddle / pen? 

Maybe even create a new issue, as the original issue (asking for a datetime picker in general) can probably be closed and a bug in the datetime picker is something different.

**Comment by vitmalina** [comment]
Issue is over 2 years old, since no JS fiddle, I am closing it. Reopen if you add a jsfiddle that illustrate the bug.
