### ISSUE TITLE
w2ui 1.5 tabIndex is not working for list and multi select

### ISSUE THREAD

**Issue by Kolaani** [vitmalina/w2ui#1803]
Hi there,

TabIndex is not working for list and multi select in version **1.5**. Following is the link to w2ui's own form demo. [http://w2ui.com/web/demos/#!forms/forms-2](http://w2ui.com/web/demos/#!forms/forms-2). As you can see from date field the focus is shifting to texarea skipping both list and multi select fields.

Is there any solution to this?

**Comment by mpf82** [comment]
I cannot reproduce this issue in the current demos: http://w2ui.com/web/demos/#!forms/forms/3

Maybe it has been fixed already?

Can you please confirm?

**Comment by mpf82** [comment]
Updated link to demo: http://w2ui.com/web/demos/#/form/3

Closing issue: cannot reproduce; no response

**Comment by yodes69** [comment]
I have not had chance to test, but you can leave closed.  I will create new issue if have too.
