### ISSUE TITLE
You must add pagination

### ISSUE THREAD

**Issue by DungeoN33** [vitmalina/w2ui#1809]
I have 20.000 records. I can't every time go to server and bind data. One time I get all data and than pagination, filter or everything process in client side. Each request requires extra server cost. This is unnecessary. Once you get the data from the database, you do all the calculations on the client side. No queries are thrown into the database for each search. Infinite Scrool is not as good as you think. Who pulls 20,000 records down one by one? Pagination is very important some systems. I was so glad I found you. Because I had a client who wanted a flexigrid. I thought I had the alternative, even more powerful. But I don't have paging, so I have to throw everything away.

**Comment by mirannda** [comment]
Use offse and limit on your select, see https://github.com/vitmalina/w2ui/tree/master/server/php

**Comment by advh67** [comment]
I use SQL on server language to LIMIT my number of records. My tables may have 1 million records/results, but I fetch, let's say, only 500. Sorting and search for my users uses a full table scope, but watching 500 at once is more than enough for them.

**Comment by vitmalina** [comment]
Respectfully, but I think you do not understand what infinite scroll is. It does not mean all records are pulled from the server at once, but they are pulled as you scroll. By default grid requests 100 records at a time. Set autoLoad to false and see what happens. If your server sends them all, then it is a server side problem. You should not send them all.
