### ISSUE TITLE
How to change w2grid column header background color ?

### ISSUE THREAD

**Issue by Rimokas** [vitmalina/w2ui#1810]
Hi, 

I found this how to change color for all columns in w2grid : https://github.com/vitmalina/w2ui/issues/1473 

But I want to change columns header background separatelly for conditions. I'm doing timecards table and want that according rest or work day of month can be another color ... 

`
            days = rsp.days // array of days with types of day ( W- work, R - rest, H - holiday ) 
            if ( Object.keys( days ).length > 0 )
            { 
               /*  - here I look at w2grid column elements 

               #grid_work_tab_columns
               <td id="grid_work_tab_column_6" col="6" 
               class="w2ui-head  w2ui-reorder-cols-head " 
               onmouseover="w2ui['work_tab'].columnTooltipShow('6', event);" 
               onmouseout="w2ui['work_tab'].columnTooltipHide('6', event);" 
               oncontextmenu="w2ui['work_tab'].contextMenu(null, 6, event);" 
               onclick="w2ui['work_tab'].columnClick('d1', event);" 
               ondblclick="w2ui['work_tab'].columnDblClick('d1', event);" 
               style="width: 57px;">
                  <div class="w2ui-resizer" name="6" style="height: 25px; margin-left: 52.3693px;"></div>    
                     <div class="w2ui-col-header  ">
                        <div class=""></div>D1    
                     </div>
               </td>   
               */   
               
               for ( var u in days )
               {
                  var col_id = 'd' + days[ u ].day // cols of days in w2grid are "d1", "d2" ... 
                  var dat_tp = days[ u ].type
                  var clr = ( dat_tp == 'W' ? '#aed7ff' : ( dat_tp == 'R' ? '#ceffce' : '#ffbbbb' ) )
                  var col = findElement( w2ui[ tab_grd[ 0 ] ].columns, "field", col_id )
                  if ( col != -1 )
                  {
                     var idf = "#grid_work_tab_column_" + col.toString()
                     //$( idf ).css( 'background-color', clr + ' !important' )
                     debugger
                     var elm2 = $( idf ).children( 'div.w2ui-col-header' )
                     elm2.css( 'background-color', clr + ' !important' )
                     //css( "background-color", clr );
                     //var c1 = ''
                     //w2ui[ tab_grd[ 0 ] ].columns[ u ].caption = c1
                  }
               }
            }

`

Sorry, but mine solutions isn't working ... :( 

I can do background colors for rows - I know that ... But at this time I want to do in column header, with rows will be another solution ... 

Any help ? Thanks in advance ...

**Comment by Rimokas** [comment]
Sorry ... 

After onLoad event it colorize as I want . But ... scrooling horizontally it reset to default columns headers colors ... 

How to solve that ?

**Comment by mpf82** [comment]
Answered here: https://stackoverflow.com/questions/54459663/how-to-change-w2ui-grid-column-header-background-colors

Option 1: http://jsfiddle.net/dt3yv2q4/2/

Option 2: http://jsfiddle.net/0Lkrb19w/

Feel free to close the questioin.

**Comment by Rimokas** [comment]
Many thanks, Mike ...
