### ISSUE TITLE
[BUG] Selection-border is not scrolling in fixedbody mode 1.5 RC1

### ISSUE THREAD

**Issue by kkrseges** [vitmalina/w2ui#1818]
Hi.

First of all, thank you for an awesome tool.

I am using your tool with the options fixedbody:true and selectType: cell.

After making a selection and then scrolling, the selection area does not scoll out of the viewport, but stays in the visible area.

The screendump illustrates the problem. The blue area is what is being selected, but the 'w2ui-selection' is positioned wrongly. 

![2019-03-25_09-06-54](https://user-images.githubusercontent.com/48905672/54904107-d2082980-4edd-11e9-9ec1-c1da04d81273.png)

**Comment by mpf82** [comment]
possibly related to #1890 

though this issue is older, but the other one has a fiddle.
