### ISSUE TITLE
radio with Grid

### ISSUE THREAD

**Issue by Scnck** [vitmalina/w2ui#1820]
is it possible to create a radio button with label within a grid cell; if so what is the correct syntax? Thank you

**Comment by MD00414** [comment]
Fiddle: http://jsfiddle.net/UberMario/7vfztx2d/24/

![Capture](https://user-images.githubusercontent.com/38018368/58293826-2a9c5b80-7d95-11e9-8faa-ed0164727967.PNG)

**Comment by mpf82** [comment]
Closing issue: no response
