### ISSUE TITLE
Tabs in Firefox

### ISSUE THREAD

**Issue by beza2000** [vitmalina/w2ui#1825]
* **I'm submitting a ...**
[X] bug report
[ ] feature request
[X] question about the decisions made in the repository

* **What is the current behavior?**
All standard examples with Tabs (http://w2ui.com/web/demos/#!tabs/tabs-1) in Firefox 60.3 look strange. It's hard to know which Tab is active.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a screenshots**.
In my Firefox
![21](https://user-images.githubusercontent.com/5364251/56966936-d244b600-6b68-11e9-8da0-322445f33835.png)

* **What is the expected behavior?**
In my Chrome
![22](https://user-images.githubusercontent.com/5364251/56966966-e4265900-6b68-11e9-97ad-b9f4ad11eb28.png)

**Comment by mpf82** [comment]
Seems to be fixed in the current master. Can you please confirm?

**Comment by beza2000** [comment]
Yes, I confirm it. Thanks.
