### ISSUE TITLE
onRender/event.onComplete is not the very last fired when a grid is initialized

### ISSUE THREAD

**Issue by MD00414** [vitmalina/w2ui#1828]
A slightly modified version of the 'Spreadsheet Like Grid' example illustrates a behavior with the onRender/event.onComplete event;  it is not the last event fired for the grid initialization.

Original example: http://w2ui.com/web/demos/#!combo/combo-3

Fiddle version modified to illustrate issue:  http://jsfiddle.net/UberMario/nwy1egL8/12/

The use case is to have a grid initially rendered with a column pre-selected; as can be illustrated by manually invoking the 'w2ui.grid.columnClick("c")' in the debug console for both the original example and the modified fiddle.

The columnClick can be placed inside the onResize event handler, as a workaround for the fiddle modified example, but not in the use case scenario.  The use case scenario alters the grid in such a way that the resize event goes into an endless loop.

Side note: Logic for the 'w2ui.grid.refreshRow' in the original example is placed inside the onRender event to eliminate errors it was throwing within Chrome complaining the w2ui.grid object was not yet instantiated.

**Comment by mpf82** [comment]
This seems to be fixed in the current master. Can you please confirm?

Related: #1942

**Comment by mpf82** [comment]
Closing issue: no response
