### ISSUE TITLE
Single cell colorizing not working as expected

### ISSUE THREAD

**Issue by g40** [vitmalina/w2ui#1829]
* **I'm submitting a ...**
[X] very big thank you for this fantastic toolkit. Superb.
[x ] bug report
[x] feature request
[ ] question about the decisions made in the repository

* **What is the current behavior?**

Not working as expected. 

Coloring a single cell using a `render()` function does not style the whole height of the row, simply the `div` it contains. Based on http://w2ui.com/web/demos/#!grid/grid-23

```
// the problem here is that it is not the TD that gets styled but the internal div ... 
// A complete HTML/JS example is listed below
render: function (record, index, column_index) {
    var html = '<div style="background-color:#7F7F7F;">'+ record.email + '</div>';
    return html;
} 
```

The second possible solution is suggested on here: https://stackoverflow.com/questions/38696758/add-custom-color-to-w2ui-cell-grid
```
// suggests the `1:` means style is applied to column 1 only?
w2ui: { style: "1: background-color:red; color:blue;" },
```

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a screenshots**.

![w2ui-cell-color](https://user-images.githubusercontent.com/812250/58374629-4b9db180-7f39-11e9-985f-8048a5be7d62.jpg)

The .JS used to generate the screen shot:

```<!DOCTYPE html>
<html>
<head>
    <title>W2UI Demo: grid-1</title>
    <script src=http://ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js></script>
    <script type=text/javascript src="http://rawgit.com/vitmalina/w2ui/master/dist/w2ui.min.js"></script>
    <link rel="stylesheet" type="text/css" href="http://rawgit.com/vitmalina/w2ui/master/dist/w2ui.min.css" />
</head>
<body>

<div id="grid" style="width: 50%; height: 350px;"></div>

<script type="text/javascript">
$(function () {
    $('#grid').w2grid({ 
        name: 'grid', 
        method: 'GET', // need this to avoid 412 error on Safari
        columns: [                
            { field: 'fname', text: 'First Name', size: '30%' },
            { field: 'lname', text: 'Last Name', size: '30%' },
            { field: 'email', text: 'Email', size: '40%',
                // based on http://w2ui.com/web/demos/#!grid/grid-23
                // the problem here is that it is not the TD that gets styled
                // but the internal div ... 
                render: function (record, index, column_index) {
                    var html = '<div style="background-color:#7F7F7F;">'+ record.email + '</div>';
                    return html;
                } 
            },
            { field: 'sdate', text: 'Start Date', size: '120px' }
        ],
        records: [
        { recid: 1, 
            // default styling for reference
            fname: "John", lname: "Doe", email: "jdoe@gmail.com", sdate: "4/3/2012"
        },
        { recid: 2, 
            // based on http://w2ui.com/web/demos/#!grid/grid-2
            // this works. entire row is blue text on red
            w2ui: { style: "background-color:red; color:blue;" },
            // https://stackoverflow.com/questions/38696758/add-custom-color-to-w2ui-cell-grid
            // suggests the `1:` means style is applied to column 1 only?
            // w2ui: { style: "1: background-color:red; color:blue;" },
            fname: "John", lname: "Two", email: "j2@gmail.com", sdate: "4/3/2012"
        },
        ]
    });    
});
</script>
</body>
</html>
```

* **What is the expected behavior?**

Ideally the cell would be colored on its own as specified.

**Comment by mpf82** [comment]
Hi,

that's not what I wrote in my SO answer.

Compare ``style: {3: 'background-color: yellow; color: white;'}`` to ``style: "1: background-color:red; color:blue;"``.

You will see that the first is an object, while the second is a string. 

Can you please try the first option? If it's not working, please create a fiddle.

Cheers =)

**Comment by g40** [comment]
Hello @mpf82 

Thank you. Indeed, but as far as I understand it, this styling now has to be attached via the w2ui key. Incidentally, neither form works. I am getting an example into CodePen. I will update shortly.

**Comment by mpf82** [comment]
Thanks for creating a codepen.

Indeed, w2ui 1.5 requires the style to be encapsulated in a ``w2ui`` property.

But the style itself must also be an object as I wrote.

``w2ui: {style: {1: 'background-color: yellow; color: black;'} },``

Codepen: https://codepen.io/anon/pen/rgKXMp

I don't see an example of coloring a single cell in the ShieldUI example you posted.

If you want to color all cells of a column, you could implement ``column.render``

You could also create a PR to support column.style and/or column.class - should be easy to implemet in ``w2grid.getCellHTML()``.

**Comment by g40** [comment]
@mpf82, that looks much more promising. thank you. Let me check this out for a bit. I think that any PR would start with the w2ui documentation.

**Comment by g40** [comment]
@mpf82 Thanks again. Please have a look at https://codepen.io/G40/pen/WBKZRM. It attempts to set multiple cell colors but how to do this is not at all obvious.

**Comment by g40** [comment]
@mpf82 One more question. How does one set multiple styles in a row? Please see https://codepen.io/G40/pen/WBKZRM for what I thought would work ...

**Comment by sturan2** [comment]
Hi @g40, you can try the following code:

w2ui: {style: {0: 'background-color: yellow; color: black;',1: 'background-color: grey; color: black;'}

https://codepen.io/anon/pen/EzpRWz

**Comment by g40** [comment]
@sturan2 Thanks! That'll work. @mpf82 Would you like a PR for one of the grid demos?

**Comment by mpf82** [comment]
Sure, documentation and additional demos are always welcome =)

Hopefully @vitmalina and @mrg2001 find the time to look through the active PRs.

By the way, feel free to close this issue if your initial question has been answered.
