### ISSUE TITLE
How to format header and column width in Export to Excel.

### ISSUE THREAD

**Issue by sunilsingh115** [vitmalina/w2ui#1831]
How to format header and column width in Export to Excel.

**Comment by mpf82** [comment]
What "Export to Excel" are you referring to? AFAIK, w2ui has no such functionality.

**Comment by sunilsingh115** [comment]
So there is no way to set width of column of excel export?

**Comment by vitmalina** [comment]
Usually by "Export to Excel" people mean export to CSV file and then it can be opened in excel. Well, CSV is a text format and does not support column width. Plus, this is something a developer need to implement. You can get data by accessing grid.records array, then it is all up to you. In additional, you can copy/paste to excel. This is done by selecting records, clicking ctrl+c and then going to excel and clicking ctrl+v. This will work with grid, but still, it is text format, it will not pass column width. 

As it is not a bug, I am closing this issue
