### ISSUE TITLE
 WYSIWYG HTML editor on popup form

### ISSUE THREAD

**Issue by juhaszzs** [vitmalina/w2ui#1832]
I would like to use a popup form as grid editor. There are some text input and a textarea on the form. It is working

I would like to convert textarea to HTML editor but is not working.

I tried several HTML WYSIWYG editor (jqte, Froala etc.).  My problem is how can I use it with w2ui?

It is not rendering on w2ui form.

**Comment by mpf82** [comment]
Can you please provide a Fiddle/Bin/Pen to demonstrate the issue?

**Comment by mpf82** [comment]
Closing issue: no response
