### ISSUE TITLE
Duplicate request to remote datasource when search is enabled

### ISSUE THREAD

**Issue by H-Lo** [vitmalina/w2ui#1840]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **What is the current behavior?**
When I define a grid that has an URL to the remote server as a data source and if I turn on search on original toolbar - 2 requests are issued to the server upon grid initialization. If I cut out URL definition and add the same later, only one request is made.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a screenshots**.
To reproduce this behaviour one has to define grid including remote URL and toolbar and search. More will be available on JS fiddle URL provided below.

* **What is the expected behavior?**
Expected behaviour is to issue one request to the server no matter search 

* **What is the motivation / use case for changing the behavior?**
Want to have search and remote datasource at the same time.

* **Link to jsFiddle that demonstrates the problem:**
https://jsfiddle.net/28reypsw/

* **Other information**

**Comment by nvcodemonkey** [comment]
This could be work around:
Around line 8981: following line can be replaced:
FROM ` } else {'+`
TO `} else if (val!=\'\' ) {'+`

**Comment by mpf82** [comment]
I've created a fiddle based on your fiddle, but I cannot reproduce the issue: http://jsfiddle.net/vLe9q4km/

Maybe it has been fixed already. Can you please confirm?

**Comment by mpf82** [comment]
Closing issue: cannot reproduce; no response
