### ISSUE TITLE
w2grid.request() uses wrong URLs for save and delete commands

### ISSUE THREAD

**Issue by Vaidot** [vitmalina/w2ui#1842]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **What is the current behavior?**
On grid with remote data source methods w2grid.save() and w2grid.delete() makes request to w2grid.url.get URL.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a screenshots**.
Try to save changes or delete record on grid with remote data source.

* **What is the expected behavior?**
request() should use w2grid.url.save and w2grid.url.remove URLs respectively.

* **Other information**
I think problem appeared because https://github.com/vitmalina/w2ui/commit/5f7e5986e9327ebbc8075f126fc62acb2901e475#diff-8b4d4a6961edfba8a65c282e9645abb3L2376 removed params.cmd, but not changed
```
if (params.cmd == 'save' && typeof edata.url == 'object')   url = edata.url.save;
if (params.cmd == 'delete' && typeof edata.url == 'object') url = edata.url.remove;
```
or
```
if (params.cmd == 'save')   ajaxOptions.type = 'PUT';  // so far it is always update
if (params.cmd == 'delete') ajaxOptions.type = 'DELETE';
```
or any other place where params.cmd is used in request().

**Comment by mpf82** [comment]
Related: https://github.com/vitmalina/w2ui/issues/1837

**Comment by Vaidot** [comment]
Got corrected by https://github.com/vitmalina/w2ui/commit/670c31e80facb0e2a18db6140fe29f55a8732344 and https://github.com/vitmalina/w2ui/commit/384f163b5378059fd5d32ba08a986def37a559d2
