### ISSUE TITLE
stripTags function doesn't work with attribute containing HTML

### ISSUE THREAD

**Issue by kudlav** [vitmalina/w2ui#1847]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **What is the current behavior?**
Input:
`<span data-toggle="tooltip" data-html="true" title="fuu (<b>BAR</b>) is based on fuu.">FUU</span>`
Output:
`BAR) is based on fuu.">FUU`

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a screenshots**.
Set column caption with that input.
Open _Show/Hide column_ dialog.

* **What is the expected behavior?**
Expected output:
`FUU`

* **Link to regex101 that demonstrates the problem:**
https://regex101.com/r/8JDty4/1

It's caused by function stripTags, using this regex pattern:
`String(html).replace(/(<([^>]+)>)/ig, "");`

**Comment by kudlav** [comment]
Correct regex is:
` String(html).replace(/<\/?[\w\s]*>|<.+[\W]>/ig, "");`

source: [https://digitalfortress.tech/tricks/top-15-commonly-used-regex/](https://digitalfortress.tech/tricks/top-15-commonly-used-regex/)

**Comment by mpf82** [comment]
Closing issue: PR #1848 has been merged
