### ISSUE TITLE
w2ui-resizer has harcoded height

### ISSUE THREAD

**Issue by kudlav** [vitmalina/w2ui#1849]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **What is the current behavior?**
Element w2ui-resizer has harcoded it's height to 25px. This causing problem when using multiline `<br>` header.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a screenshots**.
/src/w2grid.js Line 8374
`"height"         : td.height(),`

This column caption breaks it:
`System<br>Perfomance<br>Overall`

* **What is the expected behavior?**
Compute height from parent height:
`"height"         : td.height(),`

**Comment by mpf82** [comment]
Closing issue: PR #1850 has been merged
