### ISSUE TITLE
Android keyboard keeping showing when select grid row

### ISSUE THREAD

**Issue by wumingwuan** [vitmalina/w2ui#1851]
* **I'm submitting a ...**
[] bug report
[ ] feature request
[x] question about the decisions made in the repository

* **What is the current behavior?**

In v1.5rc1 : android keyboard keeping showing when select row.
In v1.4 : keyboard won't show up when select row.

use android chrome browser:
v1.4:       http://w2ui.com/web/demo/grid  
V1.5rc1:  http://w2ui.com/web/demos/#!grid

temporary fix:
search 
<textarea id="grid_'+this.name+'_focus" class="w2ui-grid-focus-input"   
and add html readonly  property.

**Comment by mpf82** [comment]
Can you please check if adding this CSS fixes the issue?

https://github.com/vitmalina/w2ui/issues/1812#issuecomment-492989254

**Comment by wumingwuan** [comment]
> Can you please check if adding this CSS fixes the issue?
> 
> [#1812 (comment)](https://github.com/vitmalina/w2ui/issues/1812#issuecomment-492989254)

Yes , adding the css also works.
textarea.w2ui-grid-focus-input {
    width: 0px !important;
    position: absolute !important;
    top: 0 !important;
    right: 0 !important;
    height: 0px !important;
    border: 0px !important;
    margin: 0px !important;
    padding: 0px !important;
    width: 0px !important;
    z-index: -1 !important;
    opacity: 0 !important;
}
