### ISSUE TITLE
context menu in different grids

### ISSUE THREAD

**Issue by mendozada** [vitmalina/w2ui#1873]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

The problem is when, within the same layout we have 2 or more grids and each one has a different context menu, the context menus are mixed or not displayed

here you see the menu on the grid
[http://jsfiddle.net/y81cyj54/28/](http://jsfiddle.net/y81cyj54/28/)

Now on it, for example, place a grid with another menu, and if they are fixed, the contact menu appears only in the gridDet, but mixing the items of the two grids.
[http://jsfiddle.net/1xmt6hbc/](http://jsfiddle.net/1xmt6hbc/)

I hope it can be solved. Thank you and excellent work.

**Comment by mpf82** [comment]
I cannot reproduce this issue: http://jsfiddle.net/9j8y1z7k/

I've created a new fiddle based on your fiddle, because you were referencing the form, that no longer existed in your second example, causing an error in the click handler.

Can you confirm that the issue no longer exists?

**Comment by mendozada** [comment]
hi, mpf82 ,  
This problem has already been solved with the update of w2ui.js.

Thanks for your interest.

I leave the link to share. [https://jsfiddle.net/n4et1kp6/](https://jsfiddle.net/n4et1kp6/)
