### ISSUE TITLE
Dates passed to grid in format yyyy-MM-ddTHH:mm:ss are not recognised correctly

### ISSUE THREAD

**Issue by Vaidot** [vitmalina/w2ui#1878]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **What is the current behaviour?**
Dates passed to grid in format yyyy-MM-ddTHH:mm:ss (for example "2020-01-29T18:09:56") are not recognised as dates and in grid written as zero dates (1970-01-01).

* **Other information**
This worked correctly before the commit https://github.com/vitmalina/w2ui/commit/4c58c4baaa7d88cf5e398854590c7d0889057f4a#diff-6ce300965d88ab4e70ced0cd752e9cd8. It is named "Fix date file format". What exactly it fixes?

**Comment by vitmalina** [comment]
Can you specify (1) how you define column in the grid (2) what is the data record where it does not parse correctly. I tried to parse
```js
w2utils.formatDateTime('2020-01-29T18:09:56')
```
and it returned me proper date, which is 
```
1/29/2020 6:09 pm
```
* From my experience, the easiest way is to use unix timestamp

**Comment by Vaidot** [comment]
Example:
```
$("#grid").w2grid({
    name: "grid",
    columns: [
        { "field": "Number", "text": "Number" },
        { "field": "Date", "text": "Date", "render": "date" },
        { "field": "DateTime", "text": "DateTime", "render": "datetime"}
    ],
    records: [
        {"recid": 0, "Number":"00001", "Date":"2018-12-08T00:00:00", "DateTime":"2020-01-30T12:08:42.953"},
        {"recid": 1, "Number":"00002", "Date":"2018-12-31T00:00:00", "DateTime":"2020-01-26T16:31:56.821"}
    ]
});
```
Problem is not with w2utils.formatDateTime(), but with w2utils.isDateTime(), part that used to recognise that value is a datetime string is removed so function returns false.

**Comment by Vaidot** [comment]
I somehow not noticed explanation of change in https://github.com/vitmalina/w2ui/pull/1860.
Then how about add to `w2utils.isDateTime()` this code instead:
```
if (String(val).indexOf(' ') < 0 && String(val).indexOf('T') >= 0 && String(new Date(val)) != 'Invalid Date') {
    if (retDate !== true) return true;
    return new Date(val);
}
```
This should only work for standard ISO 8601 dates in format `yyyy-MM-ddTHH:mm:ss`, so problem of returning wrong date should not occur.
