### ISSUE TITLE
can't reselect a row after reload, is this a bug?

### ISSUE THREAD

**Issue by namewhat** [vitmalina/w2ui#1879]
when i reload the data source, that recid is changed to 'undefined', and i can not select a row again
`w2ui.grid.records
(3) […]
​
0: {…}
​​
checked: false
​​
downloaded: false
​​
fname: "res3.xlsx"
​​
nbrs: 6
​​
recid: undefined
​​
sdate: "2/6/2020"
​​
<prototype>: Object { … }
​
1: Object { fname: "res2.xlsx", nbrs: 6, sdate: "2/6/2020", … }
​
2: Object { fname: "res.xlsx", nbrs: 6, sdate: "2/6/2020", … }

​
length: 3
​
<prototype>: Array []`

**Comment by chalchis** [comment]
any screen shoot?

**Comment by vitmalina** [comment]
recid should be sent by the server. However, there is `grid.recid` property that just specifies which field in the data use as recid. The description in this issue is not enough to find out the reason. I am closing this bug unless you can provide a sample code that demonstrates the issue.
