### ISSUE TITLE
double request when delete rows for grid, how to fix it?

### ISSUE THREAD

**Issue by namewhat** [vitmalina/w2ui#1880]
when the 'url' is set of a grid, then I trigger the delete event, requesting sent twice. I just want request one, how to fix it?

**Comment by mdavis1960** [comment]
I can't reproduce this.  How are you triggering the delete event?

**Comment by vitmalina** [comment]
I cannot reproduce it eaither

**Comment by namewhat** [comment]
> 
> 
> I can't reproduce this. How are you triggering the delete event?
some action like this `document.getElementById('file').click()`, after tragger it,I found that the log of back-end show two request message about it, whatever the event is "onAdd","onRequest" or "onDelete"

**Comment by mpf82** [comment]
Can you please provide a Fiddle/Bin/Pen to demonstrate the issue?

**Comment by mpf82** [comment]
Closing issue: cannot reproduce; no reproducer provided
