### ISSUE TITLE
When the grid initialized, it posts two api calls and aborts the first of the two calls

### ISSUE THREAD

**Issue by mdavis1960** [vitmalina/w2ui#1883]
Every time I load or refresh my w2grid, as the toolbar initializes, the initAllField() function calls el.change() when field == 'all' inside .  The call to el.change triggers a second api call which aborts the first one.  So my grid loads fine but an abort message is triggered.

**Comment by vitmalina** [comment]
I try to call `.initAllField('all')` and it does not trigger reload of the grid. Nor does it when reload/refresh/render calls it. Can you create a jsFiddle to illustrate the problem?

**Comment by mdavis1960** [comment]
I am running the latest code as of yesterday.  Here is the change I have been playing with to fix this @ line 2365 of w2grid.js:
`                if (value !== null || this.last.search !== '') {
                    el.change();    // only fire change if search criteria is changing
                }
`
Trying to understand the potential consequences of this change.  This will also likely fix #1885.

**Comment by mdavis1960** [comment]
Might be related to #1903, my grid is also inside a layout

**Comment by vitmalina** [comment]
Request gets cancelled if it is not finished, when another one is made. So, if you call grid.reload() twice in a row, first ajax will execute and then will get cancelled. Just before second one is triggered.

It is done to avoid situations where there is one request is sent, then second request is sent with, say, different search criteria and then second one comes back first and first one later on. In this case the data in the grid will be wrong (w/o correct search). This is why cancel is implemented.

Generaly, in my projects I have no issue with 2 requests, but sometimes I see this problem too. It is not a mission critical issue, but is is annoying. The key is not to render the grid twice, which will call reload twice. If you have to render grid multiple times, then I would recommend clearning grid.url property before render and set it once you are ready for data to be reload.
