### ISSUE TITLE
Grid add records trouble

### ISSUE THREAD

**Issue by atitoff** [vitmalina/w2ui#1886]
* **I'm submitting a ...**
[ ] feature request

A w2ui grid is a great tool. Used in many projects.
In the new project, all exchange on websockets.
How do I send requests to my function, which will give answers.

I receive request variables normally
```js
onRequest: function (event) {
    data = event.postData;
    event.preventDefault();
}
```
How do I send them to the table?

```js
grid.add([
    {recid: 1, fname: 'John', lname: 'doe', email: 'vitali@gmail.com', sdate: '1/3/2012'},
    {recid: 2, fname: 'Stuart', lname: 'Motzart', email: 'jdoe@gmail.com', sdate: '2/4/2012'}
])
```
doesn’t work correctly, an empty line is inserted

![pic](https://i111.fastpic.ru/big/2020/0309/25/691be278569363f25a9390e67580bd25.png)

http://jsfiddle.net/z4nr9ke7/1/

**Comment by mdavis1960** [comment]
Have your tried adding them one at a time?  The grid.remove only works one
at time, it fails when I call it with more than one.

**Comment by vitmalina** [comment]
is `grid.url` defined? If your loading data manual, it should not be set. If it is set, it might trigger infinite scroll, and hence the issue. Seeing onReuqeust in your come, makes me thing, it is defined. Use `grid.load()` to load data one time or just do not set `grid.url` at all.

**Comment by atitoff** [comment]
![pic](https://i111.fastpic.ru/big/2020/0311/8e/b2dde6535bb6327bcc45c7e7648d968e.png)  

What events of the w2ui.grid call the load() method?

**Comment by vitmalina** [comment]
@atitoff In the original issue, you need to add `grid.total = 2` after you add records. Then all will be good. Total is used for lazy loading, therefore it needed. I have checked, current version does not have this problem. In the example you use 1.4, which will work with the fix I mentioned.

@mdavis1960 as for you can do `.remove(recid1, recid2, recid3)`

**Comment by vitmalina** [comment]
@atitoff for your web socket idea, you can use something like this
```
$(function () {
    $('#grid').w2grid({
        name: 'grid',
        header: 'List of Names1',
        url: 'http://w2ui.com/web/pages/demo/infinite/index.php',
        recid: 'userid',

        onRequest(event) {
            getRecords(event.url, event.postData)
            event.preventDefault()
        },
        columns: [
            { field: 'userid', text: 'ID', size: '80px', sortable: true, searchable: 'int', hidden: true },
            { field: 'fname', text: 'hex', size: '180px', sortable: true, resizable: true, editable: { type: 'hex' } },
            { field: 'lname', text: 'color', size: '180px', sortable: true, resizable: true, editable: { type: 'color' } },
            { field: 'email', text: 'date', size: '100%', sortable: true, resizable: true, editable: { type: 'text' } }
        ]
    });

    function getRecords(url, post) {
        $.ajax({
            url,
            method: 'GET',
            data: { request: JSON.stringify(post) }
        })
        .done((data) => {
            var grid = w2ui.grid
            grid.last.xhr_offset = post.offset
            if (grid.last.xhr_offset === 0) grid.records = []
            if (data.total > grid.records.length) {
                grid.last.xhr_hasMore = true
            } else {
                grid.last.xhr_hasMore = false
            }
            grid.last.pull_more    = false;
            grid.last.pull_refresh = true;
            grid.total = data.total
            grid.records = grid.records.concat(data.records)
            grid.refresh()
        })
    }
});
```
