### ISSUE TITLE
Grid with SelectYpe = cell and copy and paste

### ISSUE THREAD

**Issue by ponyEdp** [vitmalina/w2ui#1891]
Good morning
If I have a grid with selectType = cell and I want copy and paste a cell.
It will not work if I copy one cell and I want to past in multiple cells.
The cell is paste only in the first cell of the selected cells.
May you fix the problem ?
Do you want a JsFiddle example or I must post here the program code ?
Thanks 
Regards
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/55495773/76736394-01efb300-6767-11ea-9e1a-88f664bfd2c9.gif)

**Comment by vitmalina** [comment]
It is not a bug. if you want a behavior where one cell is copied into many, you need to use onPaste event and implement it yourself.
