### ISSUE TITLE
Using Library with Kotlin Ktor / Kvision

### ISSUE THREAD

**Issue by mittpatel** [vitmalina/w2ui#1901]
Hi There,

is there good way can this library integrated with Kotlin Ktor or Kvision Frameworks ? 

Regards,
Mit

**Comment by sada-narayanappa** [comment]
HI 
Thank you for an excellent library. I was wondering, if you have an example of adding menu items to side bar. I see an example of adding menu items at the end. But I was looking for something like lazy loading - here is a specific example. Suppose if I use to show all database tables and lazily load columns until user clicks the table name on the menu item. when clicked I like to add column names to that node.

**Comment by vitmalina** [comment]
It is a question, not a bug
