### ISSUE TITLE
Form url, the form not show data

### ISSUE THREAD

**Issue by ponyEdp** [vitmalina/w2ui#1902]
* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[X ] question about the decisions made in the repository

Good morning
I'm loading data in a form using the command url. No error are detect but the form not show the data.
Here is my code.
May you help, please.
Thanks
Best regards

`<div id="form" style="width: 95%; margin: 0 auto;"></div>`

`<script language="javascript">`
`    $(function () {`
`        $('#form').w2form({`
`            name: 'form',`
`            recid: 1, `
`            url: {`
`                get: '/{MyPony/GetBPANs',`
`                //save: '/{culture}/MyPony/SaveBPANs'`
`            },`
`            fields: [`
`                { field: 'recid', type: 'text', required: true, disabled: true, html: { caption: 'ID', page: 0 } },`
`                { field: 'Email', type: 'text', required: true, disabled: true, html: { page: 0 } },`
`                {`
`                    field: 'Nature', type: 'select', required: true,`
`                    options: { items: ['ddd', 'eee'] },`
`                    html: { caption: 'qqq', page: 0 }`
`                },`
`                { field: 'Vat', type: 'text', required: true, html: { caption: 'Vat', page: 0 } },`
`                { field: 'Newsletter', type: 'checkbox', required: false, html: { page: 0 } },`
`            ],`
`            tabs: [`
`                { id: 'tab1', caption: 'aaa' },`
`                { id: 'tab2', caption: 'bbb' },`
`                { id: 'tab3', caption: 'ccc' }`
`            ],`
`            actions: {`
`                "Pulisci": function () {`
`                    this.clear();`
`                },`
`                "Salva": function () {`
`                    var obj = this;`
`                    this.save({}, function (data) {`
`                        if (data.status == 'error') {`
`                            console.log('ERROR: ' + data.message);`
`                            return;`
`                        }`
`                    });`
`                }`
`            }`
`        });`
`        w2ui['form'].refresh();`
`    });`
`</script>`

The server respond with this json
`{ "status": "success", "record": {"recid": 1000, "Email": "pippo@pluto.net", "Newsletter": true, "Nature": "D", "Vat": "0123456789" }}

**Comment by mpf82** [comment]
I've created a fiddle based on your code, but for obvious reasons, I cannot access your URL: http://jsfiddle.net/971z8tqe/

> The server respond with this json
{ "status": "success", "record": {"recid": 1000, "Email": "pippo@pluto.net", "Newsletter": true, "Nature": "D", "Vat": "0123456789" }}

Well, that looks good. Is that what you're seeing in your browser's dev console? 

Did you make sure your server sends the content type header as expected by w2ui? The default is ``HTTPJSON``.

If your server sends JSON (``Content-Type: application/json``), you may want to set ``w2utils.settings.dataType = 'JSON'`` in your code.

**Comment by mpf82** [comment]
Closing issue: cannot reproduce; no response
