### ISSUE TITLE
grid load inside layout

### ISSUE THREAD

**Issue by chalchis** [vitmalina/w2ui#1903]
* **I'm submitting a ...**
[* ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

hi i am trying to load a grid inside a panel of a layout.
It works fine, but I notice that the grid calls the server more than 1 time

I am using version 1.4

![w2ui](https://user-images.githubusercontent.com/2206648/81866449-d7d32b00-9534-11ea-8bf6-642ffa71644a.gif)

![code](https://user-images.githubusercontent.com/2206648/81866726-3a2c2b80-9535-11ea-814e-8d5fb7d2507a.png)

* **What is the current behavior?**

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a screenshots**.

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Link to jsFiddle that demonstrates the problem:**

* **Other information**

**Comment by mdavis1960** [comment]
very likely related to #1883 where I reported a similar issue and my grid is also inside a layout.

**Comment by vitmalina** [comment]
I explained in #1883 why it might be happening. I would recommend trying to figure out why it calls reload twice. Put a debugger in onLoad event and see call stack who calls it. It should shed some light.
