### ISSUE TITLE
Custom Search

### ISSUE THREAD

**Issue by gslsouza** [vitmalina/w2ui#191]
Is it possible to have a custom search on local data?
Capture the onSearch event and return an array of recid?

I thought I could do that setting all record.hidden to false and only the records that would return from my search with true and than calling refresh(). But, record.hidden will be removed on version 1.3.

**Comment by ricardo-r2ac** [comment]
Hi,
I am using this way to customize my filter and it works well. The problem is when I need to **sort** any column in the grid after filter,  the grid is getting empty.
Any suggestion ?
