### ISSUE TITLE
W2grid select of records isn't working with Shift from 1-st record

### ISSUE THREAD

**Issue by Rimokas** [vitmalina/w2ui#1910]
I'm submitting a ...
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

This isn't working in popup with grid. I'm loading array in popup and grid and then I want to select some records for other manipulations.
 - first step - check first record , ok;
 - second step - check the 4 or 9 record holding "Shift" key - no any reaction ...;

If it try from 2-nd record to other - it's working, but isn't working from 1-st record ...

I debugged and found that the reason is in w2grid from 3384 row : 

               for (var i = start; i <= end; i++) {
                    if (this.searchData.length > 0 && !url && $.inArray(i, this.last.searchIds) == -1) continue;
                    if (this.selectType == 'row') {
                        sel_add.push(this.records[i].recid);
                    } else {
                        for (var sc = 0; sc < selectColumns.length; sc++) {
                            sel_add.push({ recid: this.records[i].recid, column: selectColumns[sc] });
                        }
                    }
                    //sel.push(this.records[i].recid);
                }
                this.select.apply(this, sel_add);

the problem - selectColumns array is empty. 

At this time I added some rows higher : 

                if ( selectColumns.length == 0 && this.selectType == 'cell' )
                   for (var c = 0; c < obj.columns.length; c++) selectColumns.push(c);

Can't understand why this selectColumns became empty if it try to check from first record ...
My grid is cell selectType, multiselect, with selectColumn.

About 2 weeks ago it was working until I renewed from github ... 

With best regards !

**Comment by mpf82** [comment]
Cannot reproduce.

I tried with this fiddle: http://jsfiddle.net/fnzxu962/

```
grid: {
        name: 'grid',
        selectType: 'cell',
        multiSelect : true,
        show: {
            footer: true,
            lineNumbers: true,
            selectColumn    : true,
        },
        .....
```

Maybe it has already been fixed?

Please create a fiddle to demonstrate your problem or close this issue if the problem no longer exists.

**Comment by Rimokas** [comment]
Hi!

This problem exist then exist hidden columns ... 
I found that and forgot to write here. Excuse.

So then in the grid to hide one or some columns, then selection with Shift isn't working. After showing all columns - all is working ...

**Comment by mpf82** [comment]
Here's the same fiddle, with every second column (B, D, ...) hidden: http://jsfiddle.net/jon0utkh/

I still cannot reproduce the problem.

Please modify the fiddle as you see fit to reproduce the issue and then post the link here.

**Comment by Rimokas** [comment]
Sorry, Mike,

I can't reproduce simple sample of this product. I can to repeat, that with hidden columns w2grid in popup - isn't working shift key for selection . I debugged with w2grid.js source and found, maybe, that maybe problem is here ... 

Not hidding columns it's working...
Thanks for your efforts. Good luck ..
