### ISSUE TITLE
W2Grid Added Blank Space when resize my layout.

### ISSUE THREAD

**Issue by ImAbhishekTomar** [vitmalina/w2ui#1911]
Hello,

When i close my right navbar the grid add blank space.

**HTML**
  ```
.w2ui-grid-x {
        width: 100% !important;
        overflow: hidden;
        min-height: -moz-calc(100vh - 93px); /* Firefox */
        min-height: -webkit-calc(100vh - 93px); /* Chrome, Safari */
        min-height: calc(100vh - 93px); /* IE9+ and future browsers */
    }

<div id="divGrid">
    <div id="main" class="w2ui-grid-x">
    </div>
</div>
```
**Normal View**

![normal-view](https://user-images.githubusercontent.com/6933841/84833665-6f083280-b04d-11ea-923e-ea3b26433600.JPG)

**Issue when i have close right navbar**

![Space](https://user-images.githubusercontent.com/6933841/84833668-70d1f600-b04d-11ea-9ebb-4aab9eb038e6.JPG)

**Comment by AlexVDem** [comment]
Just select "Restore Default State"

![image](https://user-images.githubusercontent.com/16631351/85200336-3d1df700-b2ff-11ea-9679-4a31f911fed3.png)

**Comment by vitmalina** [comment]
Can you please create example on jsfiddle or similar and post a link here.

**Comment by mpf82** [comment]
Closing issue: no response, reproducer missing
