### ISSUE TITLE
w2grid - server/php example doesn't work on PHP7

### ISSUE THREAD

**Issue by AlexVDem** [vitmalina/w2ui#1912]
w2grid - server/php example doesn't work on PHP7
Hi, guys. First of all I'd like to thanks for this nice plugin. But I can't use it on my server. I don't know this is a PHP7 version issue, or total issue with new version w2ui.
I noticed, that we have differences between 1.5 and previous versions, new url: {} construction use in different ways and new default AJAX type change in 1.5. And therefore I getting error (Command "" is not recognized) on default users.php, and I can't get data array.
That issue was described in one bug report https://github.com/vitmalina/w2ui/issues/1508
I've changed my code that way:
- put w2utils.settings.dataType = 'JSON'; in index.php to declare new data format.
- put url: {get: 'users.php', save: 'users.php', remove: 'users.php'},
- put $_REQUEST = json_decode(file_get_contents('php://input'), true); in users.php to decode JSON string from w2grid for users.php and detect 'get' command from {cmd: "get", selected: [], limit: 3, offset: 0}

That way I've resolved half a problem, and now I receive array looks like: 

---Array ( [0] => Array ( [0] => 18 ) ) ---Array ( [0] => Array ( [0] => 1 [1] => Name1 [2] => Lastname1 [3] => demo@team4work.net [4] => Name1 [5] => 1234567 ) [1] => Array ( [0] => 2 [1] => Name2 [2] => Lastname2 [3] => demo@team4work.net [4] => Name2 [5] => 11223 ) [2] => Array ( [0] => 3 [1] => Name3 [2] => Lastname3 [3] => demo@team4work.net [4] => Name3 [5] => 11223 ) )

But as result I got error 500 (Internal Server Error) and "AJAX error. See console for more details." The problem is that I can't get JSON string for w2grid. 

Apache2 php log give me that error report:
[Fri Jun 19 09:00:40.622863 2020] [php7:notice] [pid 11700] [client ] PHP Notice:  Trying to get property of non-object in /var/www/html/test/w2/server/php/w2lib.php on line 111, referer: /w2/server/php/
[Fri Jun 19 09:00:40.623268 2020] [php7:notice] [pid 11700] [client ] PHP Notice:  Trying to get property of non-object in /var/www/html/test/w2/server/php/w2lib.php on line 127, referer: /w2/server/php/
[Fri Jun 19 09:00:40.623293 2020] [php7:notice] [pid 11700] [client ] PHP Notice:  Trying to get property of non-object in /var/www/html/test/w2/server/php/w2lib.php on line 129, referer: /w2/server/php/
[Fri Jun 19 09:00:40.623302 2020] [php7:notice] [pid 11700] [client ] PHP Notice:  Trying to get property of non-object in /var/www/html/test/w2/server/php/w2lib.php on line 130, referer: /w2/server/php/
[Fri Jun 19 09:00:40.623308 2020] [php7:warn] [pid 11700] [client ] PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/test/w2/server/php/w2lib.php on line 130, referer: /w2/server/php/
[Fri Jun 19 09:00:40.623500 2020] [php7:error] [pid 11700] [client ] PHP Fatal error:  Uncaught Error: Call to a member function moveNext() on array in /var/www/html/test/w2/server/php/w2lib.php:135\nStack trace:\n#0 /var/www/html/test/w2/server/php/users.php(24): w2grid_class->getRecords('SELECT * FROM u...', 'SELECT count(1)...', Array)\n#1 {main}\n  thrown in /var/www/html/test/w2/server/php/w2lib.php on line 135, referer: /w2/server/php/

Maybe this is PHP7 difference, maybe not, khow knows? But, anyway, I suppose to pay attention to this issue, because  w2lib.php doing something wrong I can't understand why. And we can't use this useful plugin to manipulate SQL data.
Do you have any idea, what's wrong with that code? I will appreciate for help. Thanks.

**Comment by vitmalina** [comment]
The example is just for demo purposes. It is super simple. @AlexVDem would you be willing to fix it and submit a PR with the fix?

**Comment by AlexVDem** [comment]
> The example is just for demo purposes. It is super simple. @AlexVDem would you be willing to fix it and submit a PR with the fix?

I've changed code finally, and it's work fine for me. I've checked get records, sorting, add/edit and searching. I need some more time to test it.

**Comment by vitmalina** [comment]
Got it. Thank you.

**Comment by AlexVDem** [comment]
Ok, I finally tested my code, and I don's see errors anymore. You can check it out on my SQL server by [mysqllink](http://test.team4work.net/w2/server/php/) (only for test, I will remove it after couple days).
My code in attached file. I know, it ugly, but it works. :) I've put comments in code ('//NEW! ...' means new code, other code commented by '// ' if don't need it.
I tested it only PHP7 and MariaDB (MySQL - clone).
[4Git.zip](https://github.com/vitmalina/w2ui/files/4812629/4Git.zip)

**Comment by vitmalina** [comment]
please submit a pull request.

**Comment by mpf82** [comment]
Closing issue: no response
