### ISSUE TITLE
w2grid.select issue?

### ISSUE THREAD

**Issue by AlexVDem** [vitmalina/w2ui#1913]
I'd like to render table with pre-selected records, and I can't do it.
Let's say we are going to make table with pre-selected records with recid = 1,2,4. 
I put that code in 
```
$('#users').w2grid({
//some code
onRender: function(event) {
           console.log("rendered2");
            w2ui.users.select(1,2,4);          
} });
```
and I always get error:
```
rendered2
-----
Uncaught TypeError: Cannot read property 'select' of undefined
    at w2grid.onRender (resp_select.php:80)
    at w2grid.trigger (w2ui-1.5.rc1.min.js:3)
    at w2grid.render (w2ui-1.5.rc1.min.js:6)
    at r.fn.init.$.fn.w2grid (w2ui-1.5.rc1.min.js:3)
    at HTMLDocument.<anonymous> (resp_select.php:31)
    at j (jquery-3.1.1.min.js:2)
    at k (jquery-3.1.1.min.js:2)   
```
BUT! If I put the same code in: ` <button class="w2ui-btn" onclick="w2ui.users.select(1,2,4);">Select a Records</button>`
and push 'Select a Records' button, I've see selected records 1,2,4 and all works fine. But I need selection after loading.
This is a bug or feature? Thanks.

**Comment by mpf82** [comment]
It's the order in which the code is executed. ``render`` is called before the new grid is registered with the global ``w2ui`` object, you can see that it in the grid constructor: https://github.com/vitmalina/w2ui/blob/master/src/w2grid.js#L279

But why reference the grid via the global ``w2ui`` object when you can simply use ``this``?

**Comment by vitmalina** [comment]
thy this
```js
$('#users').w2grid({
/ /some code
onRender: function(event) {
  event.done(function () { 
    console.log("rendered2");
    w2ui.users.select(1,2,4);          
  }
}
});
```

**Comment by AlexVDem** [comment]
> try this
> 
> ```js
> $('#users').w2grid({
> / /some code
> onRender: function(event) {
>   event.done(function () { 
>     console.log("rendered2");
>     w2ui.users.select(1,2,4);          
>   }
> }
> });
> ```

Soryy, but 
jquery-3.1.1.min.js:2 Uncaught TypeError: Cannot read property 'select' of undefined
    at w2grid.<anonymous> (resp_select.php:81)
    at w2grid.trigger (w2ui-1.5.rc1.min.js:3)
    at w2grid.render (w2ui-1.5.rc1.min.js:6)
    at r.fn.init.$.fn.w2grid (w2ui-1.5.rc1.min.js:3)
    at HTMLDocument.<anonymous> (resp_select.php:31)
    at j (jquery-3.1.1.min.js:2)
    at k (jquery-3.1.1.min.js:2)
(anonymous) @ resp_select.php:81
trigger @ w2ui-1.5.rc1.min.js:3
render @ w2ui-1.5.rc1.min.js:6
$.fn.w2grid @ w2ui-1.5.rc1.min.js:3
(anonymous) @ resp_select.php:31
j @ jquery-3.1.1.min.js:2
k @ jquery-3.1.1.min.js:2
setTimeout (async)
r.readyException @ jquery-3.1.1.min.js:2
(anonymous) @ jquery-3.1.1.min.js:2
j @ jquery-3.1.1.min.js:2
k @ jquery-3.1.1.min.js:2
setTimeout (async)
(anonymous) @ jquery-3.1.1.min.js:2
i @ jquery-3.1.1.min.js:2
fireWith @ jquery-3.1.1.min.js:2
fire @ jquery-3.1.1.min.js:2
i @ jquery-3.1.1.min.js:2
fireWith @ jquery-3.1.1.min.js:2
k @ jquery-3.1.1.min.js:2
setTimeout (async)
(anonymous) @ jquery-3.1.1.min.js:2
i @ jquery-3.1.1.min.js:2
fireWith @ jquery-3.1.1.min.js:2
fire @ jquery-3.1.1.min.js:2
i @ jquery-3.1.1.min.js:2
fireWith @ jquery-3.1.1.min.js:2
ready @ jquery-3.1.1.min.js:2
R @ jquery-3.1.1.min.js:3
[Violation] Forced reflow while executing JavaScript took 31ms
resp_select.php:1 Uncaught TypeError: Cannot read property 'columnTooltipShow' of undefined
    at HTMLTableCellElement.onmouseover (resp_select.php:1)
onmouseover @ resp_select.php:1
resp_select.php:1 Uncaught TypeError: Cannot read property 'columnTooltipHide' of undefined
    at HTMLTableCellElement.onmouseout (resp_select.php:1)

**Comment by AlexVDem** [comment]
> It's the order in which the code is executed. `render` is called before the new grid is registered with the global `w2ui` object, you can see that it in the grid constructor: https://github.com/vitmalina/w2ui/blob/master/src/w2grid.js#L279
> 
> But why reference the grid via the global `w2ui` object when you can simply use `this` in the event handlers?

Probably you right, I just follow the manual.

**Comment by vitmalina** [comment]
Please create jsFiddle, I cannot repeat it.

**Comment by AlexVDem** [comment]
> Please create jsFiddle, I cannot repeat it.

Sorry, I can't use jsFiddle in this case, because my data on my SQL server.
I found temporary solution:
```
function preSelect() {
    console.log("rendered2");
    w2ui.users.select(1,2,4);
};
setTimeout(preSelect, 300);
```
All other methods to call w2ui.users.select(); don't work or give errors. I still in quest of good solution.

**Comment by vitmalina** [comment]
it does not work because it is a string. 
Without a repeatable example, I am afraid, but there is no way to fix it. Closing the isuse.

**Comment by AlexVDem** [comment]
Oh, yes, now I see, I need number of strings, not one string. I've resolved it by:
`function preSelect() {    
    sel = selected.split(",");    
    var i;
    for (i = 0; i < sel.length; ++i) {w2ui.users.select(sel[i]);}
};
setTimeout(preSelect, 500);`
