### ISSUE TITLE
missing index variable "i" to auto-generate "recid" on fetch records

### ISSUE THREAD

**Issue by markusruth** [vitmalina/w2ui#1914]
## Short description
missing index variable "i" in forEach() loop at line 6135 of w2ui.js in function requestComplete():
 
code in #master branch is:
  ```
... 
               }
                if (Array.isArray(data.records)) {
                    // make sure each record has recid
                    data.records.forEach(function (rec) {
                        if (obj.recid) {
                            rec.recid = rec[obj.recid];
                        }
                        if (rec.recid == null) {
                            rec.recid = 'recid-' + i;
                        }
                    })
                }
```
to fix add "i" parameter in forEach():
 ```
... 
               }
                if (Array.isArray(data.records)) {
                    // make sure each record has recid
                    data.records.forEach(function (rec, i) {
                        if (obj.recid) {
                            rec.recid = rec[obj.recid];
                        }
                        if (rec.recid == null) {
                            rec.recid = 'recid-' + i;
                        }
                    })
                }
```
## What is current behavior
if recid not provided by API response, automatic generation fails because index variable "i" is missing

## What is desired behaviour
have "i" as index

## Link to jsfidle/codepan with sample code
not needed - too simple fix

## Steps to reproduce or sample 
create a grid and fetch data from API without recid column.

**Comment by markusruth** [comment]
bug is already fixed in the sources - just need to run "grunt".

**Comment by vitmalina** [comment]
recompiled js and css, updated files are in /dist folder
