### ISSUE TITLE
Closing Tabs

### ISSUE THREAD

**Issue by yodes69** [vitmalina/w2ui#1916]
## Short description
When I close all my Tabs, I check the tabs array to see if it is empty or the length is 0.  I am doing this on the onClose event and inside the onComplete function.  It doesn't seem to update the tabs array until after it exits this event.  Is this a bug, or is this how it is suppose to work?  If so, is there another way to check if all the tabs are closed?

## What is current behavior
...

## What is desired behaviour
Update the tabs array before onComplete function is executed.

## Link to jsfidle/codepan with sample code
...

## Steps to reproduce or sample 
...

**Comment by mpf82** [comment]
I cannot reproduce the issue, seems to be working as expected: http://jsfiddle.net/f2m7t0u5/

Maybe this has been fixed in the current master.

Please close this issue if it has been resolved, otherwise please provide a fiddle to demonstrate the problem.

**Comment by yodes69** [comment]
I will check if the current master has fixed this issue.

Thanks

**Comment by mpf82** [comment]
Closing issue: no response
