### ISSUE TITLE
How to remove Record ID from w2ui grid footer?

### ISSUE THREAD

**Issue by AlexVDem** [vitmalina/w2ui#1917]
This is not a bug, just clarification of functionality and (probably) of documentation.
I'd like to remove Record ID from w2ui grid footer. How it possible to do? I got code like that:

```
$('#users').w2grid({
    name    : 'users',
    //limit     : 50,        
    header  : 'List of Respondents',
    url: {
        //get: 'respondents/users.php',            
        save: 'respondents/users.php',
        remove: 'respondents/users.php'
    },
    show: {
        header        : true,
        toolbar       : true,
        footer        : true,
        toolbarAdd    : true,
        toolbarDelete : true
    },        
    columns: [
        { field: 'resp_first_name', caption: 'First Name', size: '100px', searchable: true, sortable: true },
        { field: 'resp_last_name', caption: 'Last Name', size: '100px', searchable: true, sortable: true },            
        { field: 'resp_company', caption: 'Company', size: '150px', searchable: true, sortable: true },
        { field: 'resp_department', caption: 'Department', size: '150px', searchable: true, sortable: true }
        { field: 'resp_phone', caption: 'Phone', size: '100px', searchable: true, sortable: true }
    ],
    onAdd: function (event) {
        editUser(0);
    },
    onDblClick: function (event) {
        url = w2ui['users'].get(event.recid).resp_hashlink;
        console.log(url);
        editUser(event.recid, url);
    }
});
```
This code works fine, but I need to remove 'Record ID' badge in footer on grid bottom. I don't want to remove footer, just Record ID. I don't find the way of it in Doc. Thanks.

**Comment by mpf82** [comment]
There are at least two options:

1) Hide the HTML element with CSS: 

```
.w2ui-footer-left {
    display: none !important;
}
```
Note: this will also prevent the "x selected" status message if you select records.

2) Override `grid.status` and handle the "msg" parameter as you see fit

grid.status() is the method that updates the ``.w2ui-footer-left`` element.

Implementation: https://github.com/vitmalina/w2ui/blob/master/src/w2grid.js#L7716

---

Please close the issue if your question has been answered.

**Comment by mpf82** [comment]
Closing issue: no response
