### ISSUE TITLE
infinite scroll is not working

### ISSUE THREAD

**Issue by preetamjakhmola** [vitmalina/w2ui#1921]
working with w2ui grid unable to implement pagination for my grid. please must add pagination. Also infinite scroll is not working. 
http://w2ui.com/web/demos/#!combo/combo-9  <=  This page is not working with the given example
w2ui.com/web/pages/demo/infinite/index.php   <= php api is not working giving error.

**Comment by Rimokas** [comment]
I'm confirming the problem with infinite scrolling.

And problem ALWAYS is in limit and offset ranges. Can you, please, add in w2grid.js parseInt function for offset, total, limit and and xhr_offset values ?

Today ( 19-09-2020 ) downloaded zip from github :
line7171 : 
                    this.last.xhr_offset += this.limit;
in the  second request inf.scrolling I'm seeing in php request - limit: 200, offset : 200200 and etc ... 
                    this.last.xhr_offset += parseInt(this.limit); - is working fine ...
Here it's one place - maybe exist in other place the same problem ...

I must allways to fix this error manually for myself, after renewing w2ui ... 
I alreday writed about that problem - but no any feedback .. 

Thanks in advance ...

**Comment by soysaltan** [comment]
This is the implementation of infinite scrolling via Laravel 6
```php
 public function getNodes(Request $request)
    {
        $data = [];
        $parameters = json_decode($request->query('request'));
        $result = AssetNodeModel::query()->skip($parameters->offset)->take($parameters->limit)->get();

        foreach ($result as $node) {
            $data[] = [
                'nodeId' => $node->nodeid,
                'nodeLabel' => $node->nodelabel,
                'nodeLocation' => $node->location,
                'nodeCreateTime' => $node->nodecreatetime
            ];
        }

        return [
            'total' => AssetNodeModel::count(),
            'records' => $data
        ];
    }
```


Also this is the ui side of the project when you render the w2ui grdi : 
```javascript
  $('#dg').w2grid({
                    name: 'dg',
                    .......
                    recid: 'nodeId',
                    header: 'Asset List',
                    autoload: false,
                    limit: 50,`
                   .......
```

**Comment by mpf82** [comment]
> please must add pagination

Pagination had been implemented in a previous version of w2ui, but has been superseded by infinite scroll and will not come back.

> Also infinite scroll is not working.

The demo has been fixed and there are also some (outdated) server examples you can look at, to see how it could be implemented on the server side.

> Can you, please, add in w2grid.js parseInt function for offset, total, limit and and xhr_offset values ?

Those are already supposed to be integers. Can you provide a fiddle to show in which case those values are not integers?

> I alreday writed about that problem - but no any feedback ..

Can you please link that issue?

**Comment by mpf82** [comment]
Closing issue: no response
