### ISSUE TITLE
[BUG] form.getChanges() does not detect changes to int/float fields

### ISSUE THREAD

**Issue by mpf82** [vitmalina/w2ui#1922]
## Short description
form.getChanges() does not detect changes to int/float fields if the value has been changed via arrows or up/down keys.

## What is current behavior
create a form with an int field with arrows, change the value with arrows or up/down keys, check the return value of form.getChanges(), see that there are no changes.

Only if the input field has been changed directly, the changes are detected correctly.

I think this has to do with **``form.original``** not being set on ``change`` but only on ``input`` event, thus ``form.original`` is still ``null`` if the field has been changed via arrows/keys.

## What is desired behaviour
Detect changes via arrow or keys correctly. This has been working in 1.5rc1, but now it's broken.

## Link to jsfidle/codepan with sample code
http://jsfiddle.net/9zkwhmLc/

## Steps to reproduce or sample 

```
$(function () {
    $('#form').w2form({ 
        name   : 'form',
        header : 'Auto-Generated Form',
        fields : [
            { field: 'f_int', type: 'int', options: { arrows: true } },
        ],
        actions: {
            'Changes?': function (event) {
                console.log(w2ui.form.getChanges())
                w2alert( JSON.stringify(w2ui.form.getChanges()) );
            }
        }
    });
});
```

---

Update: I just notice, the same is true for color fields, if the value has been changed via CTRL+KEYS instead of direct input. There might be even more field types affected, where the value of the field changes, but the ``input`` event is not triggered. Maybe filling ``form.original`` should be moved to the ``change`` event instead?

**Comment by mpf82** [comment]
Here's my temporary work-around for this issue:

            // Override the w2form function getChanges because of a missing typecheck in 1.5.0 w2ui.js
            w2obj.form.prototype.getChanges = function getChanges() {
                // MPF: temporary fix for https://github.com/vitmalina/w2ui/issues/1922 might be to set this.original, if it's null ?!?
                if ( this.original === null ) {
                    this.original = this.record;
                }
                // console.log( "getChanges: ", this.original, this.record );
                var diff = {};
                if ( this.original != null && typeof this.original === 'object' && !$.isEmptyObject( this.record ) ) {
                    diff = doDiff( this.record, this.original, {} );
                }
                return diff;

                // eslint-disable-next-line require-jsdoc
                function doDiff( record, original, result ) {
                    // eslint-disable-next-line no-restricted-syntax
                    for ( var i in record ) {
                        if ( typeof record[i] === "object" ) {
                            result[i] = doDiff( record[i], original[i] || {}, {} );
                            if ( !result[i] || ( $.isEmptyObject( result[i] ) && $.isEmptyObject( original[i] ) ) ) delete result[i];
                        }
                        else if ( record[i] !== original[i] ) { // MPF: we really need the !== (e.g. for float / int)
                            result[i] = record[i];
                        }
                    }
                    return result;
                }
            };

This also includes a strict check in ``if ( record[i] !== original[i] )`` insted of ``if ( record[i] != original[i] )``

Reason: 

``""==0.0`` is ``true`` (e.g. an empty field changing to 0.0)

while

``""===0.0`` is ``false``

and we want to detect this change, as it matters for our application.

I think, this should make it to the w2ui standard, afterall ``""`` **is not the same as** ``0.0``

**Comment by vitmalina** [comment]
Fixed by also sending `input` event on change with key up/down, etc. Related bug fixed too. 

I evaluated condition you mentioned `if ( record[i] !== original[i] )` however, it creates an issue when original value was "1" for int field for example, it will create change record. However, I have added a condition to catch if user emptied field.
