### ISSUE TITLE
Request : Scroll overflowed tab into view

### ISSUE THREAD

**Issue by squadjot** [vitmalina/w2ui#1928]
It could be nice if "Set a tab active" **w2ui.tabs.click('tab3');** would scroll the tab into view ( if it was in overflowed part )

**Comment by mpf82** [comment]
Not *exactly* what you wanted, but I've added ``scrollIntoView`` with a callback:

     w2ui.tabs.scrollIntoView('tab7', null, function(id, tab) { console.log(event); w2ui.tabs.click( id ) })

That way, you can scroll to the tab and then click it.

Or you can click it first, then scroll it into view, that's up to you.

PR pending, implementation still subject to change

**Comment by mpf82** [comment]
Closing issue: PR merged

**Comment by squadjot** [comment]
Nice, thanks!
