### ISSUE TITLE
Can't find any way to play audio on grid fields

### ISSUE THREAD

**Issue by sadzas** [vitmalina/w2ui#1931]
I'm trying to reproduce audio using grid. The idea is bring location of the audio and play it with a button or something. Is there any way to do it?

Thanks in advance.

**Comment by mpf82** [comment]
You can write your own column formatter that creates a button in your grid cell.

It is up to you to provide a click handler for your button(s).

**Comment by vitmalina** [comment]
Not a bug report. Please ask questions at forums
