### ISSUE TITLE
Checkbox in columns

### ISSUE THREAD

**Issue by xeroxstar** [vitmalina/w2ui#1932]
Hello, 
I have columns with checkbox in it something like this:
```
columns :[
   text : '<input type="checkbox">'
]
```

I have around 30 columns in my grid and when I scroll to the left or right all my checkbox's are re-rendering again and if check box was checked, it lose its state and become again unchecked. Here is an example:

![grid](https://user-images.githubusercontent.com/6754584/104048617-62d5f500-5198-11eb-89b8-3365634fcebf.gif)

Is there way to fix it? Thanks

**Comment by vitmalina** [comment]
There has been a fix provided. Now you can define in this way
```
columns :[
  {... text : function (column) { return '<input type="checkbox">' } ...}
...
]
```
This should allow you to preset checkbox when needed.
