### ISSUE TITLE
Popup open animation is quirky in Firefox

### ISSUE THREAD

**Issue by ECrosland** [vitmalina/w2ui#1934]
**Short description**
Very often when opening a w2ui popup window in Firefox, I observe one of two undesirable behaviors. Either the popup simply appears, without either the scale-up or fade-in transition apparently having run, or else, more commonly and more obtrusively, the scale-up transition appears to run at the wrong moment. What I mean is that the dialog seems to appear at full size, then the initial `transform: scale(0.8)` seems to be applied, and then the transition back up to full size seems to run.

**What is current behavior**
I may not have got the sequence precisely right in my description above, but the visually observable effect is that the dialog goes from full size, to smaller size, and then back to full size in quick succession, while it is in the process of opening. It's very evident, and very clearly not what's intended.

I have been testing in Chrome and in Firefox. I've never noticed this behavior in Chrome, but I almost always (though not absolutely consistently) notice it in Firefox. I am running Firefox 84.0.2 on 64-bit Windows.

**What is desired behavior**
The opacity and transform CSS transitions should run smoothly and in a coordinated way to give an appealing "appear" animation to the dialog.

**Additional notes**
Digging into the w2ui source code and experimenting, I happened to discover that if I increase the timeout interval, as specified on line 238 in w2popup.js, from 1ms to 100ms, I no longer observe the anomalous effect in Firefox.

This is the delay that's applied before setting the opacity and the scale factor back to 1 and starting the CSS transition on these two properties. That it appears to be a timing issue leads me to wonder if there is internally a delay in Firefox's applying the initial `scale(0.8)` transform (see line 198), such that it applies this after initially flashing the dialog on screen at full size.

**Comment by ECrosland** [comment]
FYI, a colleague reported observing this behavior in an earlier version of Chrome also. However, it doesn't seem to happen in the most up-to-date version of this browser.


Absent a fix, I will probably work around the oddness by suppressing the part of the popup animation that relies on the scale transform. This will leave me with a popup that simply fades in and out, which looks fine to me.

`#w2ui-popup {
    transform: none !important;
}`

**Comment by mpf82** [comment]
Closing issue: PR #1935 has been merged
