### ISSUE TITLE
Please clarify the status of w2ui v1.5-rc1 and v1.5-latest

### ISSUE THREAD

**Issue by ECrosland** [vitmalina/w2ui#1936]
**Describe the problem your feature will solve.**
The Download link on the [w2ui homepage](http://w2ui.com/web/home) has us download w2ui-1.5.rc1, which appears at this point to be several years out of date.

Moreover, the [getting started](http://w2ui.com/web/get-started) page seems not entirely clear on whether or why a new project should prefer the latest compiled build of the library available from GitHub, or the rc1 build that is available for download from the w2ui site. The **Download** section of this document initially directs us to get the latest version from GitHub, but it also includes a button to download rc1. For its part, the **Working Example** section on this page is using rc1.

My team has been using w2ui for a couple years now (thanks!). We started using 1.5rc1 because this is what the website puts in the forefront. However, it seems that all the bugfixes are going to the other build available on GitHub, and haven't been pushed to what's available for download directly from the w2ui site in some time.

I recently decided to move a project from 1.5rc1 to the latest 1.5 build. In doing so, I encountered a few breaking changes--nothing too difficult to address, but a bit of a hiccup nonetheless. I mention this here because it seems that, given the breaking changes, perhaps rc1 shouldn't be put forward for use in new projects any longer, as it will make upgrading to new versions more complicated.

**Describe the solution you'd like**
Maybe consider building a release of 1.5 from the latest source code available in GitHub and promoting this by making it available for download from the w2ui homepage, replacing the rc1 build that is available there now.

If you're not ready to do this, maybe add a little clarification to the getting started page as to the status of development and when we can expect rc1 to be replaced with something more up-to-date.

**Comment by elaw01887** [comment]
I completely agree!

I've been using 1.5 RC1 for a while, but today downloaded what I assume is the 1.5 release version from W2UI.com.  Lots of things have changed and the grid "get" no longer seems to work (I'll open a separate issue about that).  So some clarification on status would be nice.

**Comment by vitmalina** [comment]
@ECrosland @elaw01887 - thanks for pointing out issues.

The download links on the website have been updated. It will download 1.5 version now everywhere. 
- updated getting started page
- posted latest w2ui to npm, so `npm -i w2ui` will install correct last version

All 1.5.x version should be 99% compatible with each other. Major development stopped on 1.5 branch and work on 2.0 has began. 1.5 will still get critical bug fixes. It has been moved to `w2ui-1.5` branch

@elaw01887, I will look at your `.get()` issue. but api of 1.5.x should be nearly compatible within 1.5.x. Or it should be easy to fix it.
