### ISSUE TITLE
Feature Request: Bring back the old w2field checkbox style as an option

### ISSUE THREAD

**Issue by mpf82** [vitmalina/w2ui#1947]
Old checkbox style (label to the left, just like all other fields):

![check_old](https://user-images.githubusercontent.com/10152404/107662995-27dd4a80-6c8b-11eb-8684-4f6cb2869830.png)

New checkbox style (label to the right, not consistent with other fields):

![check_new](https://user-images.githubusercontent.com/10152404/107663058-3c214780-6c8b-11eb-9ed4-8ea345f413b8.png)

Currently there's no way to manipulate this behaviour, as it is hard coded for type "checkbox" in ``generateHTML()``.

It would be nice if you could provide an option to show the label on the left, like it used to be.

**Comment by mpf82** [comment]
By reading the source again and again, I figured it out that ``checkbox`` supports both ``label`` and ``text``.

``text`` is used on the left side (which is the property ``label`` for every other field) and ``label`` is used on the right side (which is inconsistent wich radio items, that use ``item.text`` on the right side).

So, to avoid going nuts and changing all our forms, I've hooked into the w2form constructor and I am changing the w2form options before the form is created by iterating all fields and if the field is of type ``checkbox`` I am using ``label`` as ``text``.

    options.fields.forEach( ( field ) => {
        if ( !field.html ) {
            field.html = {};
        }
        if ( field.type === 'checkbox' ) {
            field.html.text  = field.html.label;
            field.html.label = '&nbsp;'; // we need to set something, otherwise ``field.name`` will be used!
        }
    } );


I am leaving the issue open, though in my book it's "fixed", but maybe we can talk about the inconsistency I've mentioned.

**Comment by vitmalina** [comment]
Mike you are correct. Text and label are switched for the single checkbox. It was suggested by ux people that it is more logical to have label for the checkbox on the right. It is also the case that you can click on the label and it checks the checkbox. However, when label on the left, it seems illogical to click it to check checkbox. Therefore it was switched for checkbox. 

In some of my projects, I did search/replace in the project and it seemed to resolve the issue quickly. Also, there is a way to do list of checkboxes. I think it is called `checks`. Demos for the form have been updated, possibly you can find there something new http://w2ui.com/web/demos/#!forms/forms/10

**Comment by vitmalina** [comment]
It is is ok with you, I would close this issue.
