### ISSUE TITLE
'flatButton' for Sidebar nested in layout not resizing

### ISSUE THREAD

**Issue by Digicrat** [vitmalina/w2ui#1952]
The sidebar collapse button doesn't seem to work correctly when nested in a layout.  It looks like the sidebar itself collapses, but the layout doesn't resize to match.  I've tried a few variations, including explicitly calling sizeTo or refresh on the parent layout in an 'onFlat' handler without any success.

See http://jsfiddle.net/qa52nvyu/ -- all I did here was to take the existing Combo-1 demo and added "flatButton: true" for the sidebar (line 40).

(Note: If I'm missing something simple here, I'd suggest updating one of the existing combo demos to include this case).

**Comment by mpf82** [comment]
That's not a bug. The layout never adapts its size to the content. If you want the layout panels to change their size, you have to actively set it: 

http://jsfiddle.net/783hkcgz/

Relevant parts:

    layout: {
        panels: [
            { type: 'left', size: 200, resizable: true, minSize: 35 }, // <- make sure size and minSize are set correctly
            { type: 'main', minSize: 550, overflow: 'hidden' }
        ]
    },
    sidebar: {
        name: 'sidebar',
        flatButton: true,
        onFlat: function (event) {
            w2ui.layout.sizeTo('left', (event.goFlat ? 35 : 200), true); // <- set to panel's minSize / size
        },
    }

>  I've tried a few variations, including explicitly calling sizeTo or refresh on the parent layout in an 'onFlat' handler without any success.

Your demo unfortunately did not inlcude any ``sizeTo`` or ``onFlat``.
