### ISSUE TITLE
[BUG] Double clicking empty row in editable grid causes error

### ISSUE THREAD

**Issue by mpf82** [vitmalina/w2ui#1953]
**Short description**
Double clicking anywhere on an empty row will cause a JS error in the dblClick event handler.

Line: ``if (this.show.expandColumn || (rec.w2ui && Array.isArray(rec.w2ui.children))) this.toggle(recid);``

**Link to jsfidle/codepan with sample code**

http://jsfiddle.net/23w7eo0s/

Just double click somewhere in the empty rows below row 9.

The full error in my browser is:

```
w2ui.js:7549 Uncaught TypeError: Cannot read property 'w2ui' of undefined
    at w2grid.dblClick (w2ui.js:7549)
    at w2grid.click (w2ui.js:6862)
    at HTMLTableRowElement.<anonymous> (w2ui.js:8293)
    at HTMLDivElement.dispatch (jquery-2.1.3.js:4430)
    at HTMLDivElement.elemData.handle (jquery-2.1.3.js:4116)
dblClick @ w2ui.js:7549
click @ w2ui.js:6862
(anonymous) @ w2ui.js:8293
dispatch @ jquery-2.1.3.js:4430
elemData.handle @ jquery-2.1.3.js:4116
```

**Comment by mansurdegirmenci** [comment]
Is it necessary to create a Recordid column? This is the reason why the error happens.

![image](https://user-images.githubusercontent.com/38755096/108990352-c912ca80-76a7-11eb-83ba-b69007dbdf73.png)
