### ISSUE TITLE
'List' edit control's overlay in wrong spot when grid has horizontal scroll

### ISSUE THREAD

**Issue by sbowers-cgi** [vitmalina/w2ui#1956]
**Short description**
On a grid without horizontal scrolling, if I use the 'list' edit control for a column and make that column editable, the overlay shows below the cell and fills the width of the column (as expected). However, if there are enough columns in the grid for horizontal scrolling and the grid is scrolled away from the left-most position, making a 'list' column editable places the overlay

**What is current behavior**
As mentioned above

**What is desired behavior**
Desired behavior is when painting the overlay to take the horizontal scroll position into account so overlay remains within the width of the 'list' column.

**Link to jsfidle/codepan with sample code**
...

**Steps to reproduce or sample** 
Create a grid with enough columns to have horizontal scroll.
Place a 'list' edit control on a column that requires scrolling to get to.
Make one of the cells in that column editable.  Overlay will not be under the column.

**Comment by mpf82** [comment]
This might be a duplicate of issue #1789

Can you please check the issue and my jsfiddle and confirm whether your post is a duplicate?

 https://github.com/vitmalina/w2ui/issues/1789#issuecomment-780559678

**Comment by sbowers-cgi** [comment]
This is indeed a duplicate of issue #1789. I will close.
