### ISSUE TITLE
Question: how to add parameter in save request method 

### ISSUE THREAD

**Issue by mansurdegirmenci** [vitmalina/w2ui#1961]
![Adsız](https://user-images.githubusercontent.com/38755096/109148554-79033900-7777-11eb-9ed1-8ba582524874.png)

I don't want to use Recid. Or I don't want to set a recid value.

**Comment by vitmalina** [comment]
http://w2ui.com/web/docs/1.5/w2grid.postData

**Comment by mansurdegirmenci** [comment]
![image](https://user-images.githubusercontent.com/38755096/110211680-ca62a500-7ea8-11eb-959e-966ca84fd6af.png)

**my solution**
