### ISSUE TITLE
w2grid.mergeChanges() error if set [recid] in construction (not use default value)

### ISSUE THREAD

**Issue by vinhpt2** [vitmalina/w2ui#1965]
$(adiv).w2grid({
		...
		recid: "NOT_DEFAULT_VALUE",
                ...
	});
w2grid.mergeChanges() -> Cannot read property 'w2ui' of null at w2grid.mergeChanges (w2ui.min.js:formatted:4210)

**Comment by vitmalina** [comment]
see #2007 as it is the same
