### ISSUE TITLE
When show multi w2form the tabindex of field is not correct

### ISSUE THREAD

**Issue by vinhpt2** [vitmalina/w2ui#1966]
When show multi w2form the tabindex of field is not correct. It jump from one form to other form.
It can, please not set tabindex of field in form as default. Let tabindex is an optional configuration in contruction.

**Comment by mpf82** [comment]
Did you try to set ``tabindexBase`` on one of the forms?

**Comment by mpf82** [comment]
Related: #1686

**Comment by mpf82** [comment]
Closing issue: no reply
