### ISSUE TITLE
[BUG]  Blank line dblClick  error in inline editing grid

### ISSUE THREAD

**Issue by mansurdegirmenci** [vitmalina/w2ui#1971]
http://w2ui.com/web/demos/#!grid/grid-21

![image](https://user-images.githubusercontent.com/38755096/110232927-f37b4800-7f31-11eb-8bd9-87a55eb93317.png)

![image](https://user-images.githubusercontent.com/38755096/110233021-65539180-7f32-11eb-87a0-7492d73c40d5.png)

**Comment by mpf82** [comment]
Duplicate: https://github.com/vitmalina/w2ui/issues/1953

And already fixed: https://github.com/vitmalina/w2ui/commit/97a3bae20aa03a5d708f07ce6b092132549fbe6a
