### ISSUE TITLE
[Question] how can i do cell background color with "render function"

### ISSUE THREAD

**Issue by mansurdegirmenci** [vitmalina/w2ui#1974]
my render function
![image](https://user-images.githubusercontent.com/38755096/110985300-5b3ff180-837d-11eb-83c4-69c205f591bb.png)

Error 1:

![image](https://user-images.githubusercontent.com/38755096/110985515-96422500-837d-11eb-9527-db8286abd5e9.png)

Error 2:

![image](https://user-images.githubusercontent.com/38755096/110986322-9393ff80-837e-11eb-8bc4-3e529300af8e.png)

**Comment by vitmalina** [comment]
```
render(rec) {
   return '<div style="background-color: red">Some Text</div>'
}
```
