### ISSUE TITLE
 [BUG] w2utils.settings.dataType = 'RESTFULLJSON' 

### ISSUE THREAD

**Issue by mansurdegirmenci** [vitmalina/w2ui#1980]
mysettings:
![image](https://user-images.githubusercontent.com/38755096/111918569-c0d76080-8a96-11eb-8a94-cc352a23e39e.png)

mysearch:
![image](https://user-images.githubusercontent.com/38755096/111918459-342ca280-8a96-11eb-88f7-05b4a0823c6a.png)

url not json:
![image](https://user-images.githubusercontent.com/38755096/111918478-4b6b9000-8a96-11eb-8832-e35b14fae4fb.png)

myfield
![image](https://user-images.githubusercontent.com/38755096/111918512-7950d480-8a96-11eb-91a3-f203575184c3.png)

**Comment by mansurdegirmenci** [comment]
url is not json and not encode.

**Comment by vinhpt2** [comment]
please w2utils.settings.dataType="RESTFULL"

The return is JSON or not depend on the server side not client side.

**Comment by mansurdegirmenci** [comment]
no no, my setting data type restfulljson but request not json.

**Comment by vitmalina** [comment]
In drop down definition, you can use `onLoad` function and transform the data you receive from the server to the data it expects. See http://w2ui.com/web/docs/1.5/form/fields-list

`w2utils.settings.dataType` - defines how data is encoded when sent to the server, mostly it related to the grid. The return data is always JSON and there is no confirg for it.

see http://w2ui.com/web/docs/1.5/w2utils.settings

**Comment by vitmalina** [comment]
You can also attach to `onRequest` event and trnsform request to the way your server understands it.
