### ISSUE TITLE
About drawing on canvas inside w2layout

### ISSUE THREAD

**Issue by petrov-ab** [vitmalina/w2ui#1986]
Hi all!
i decided to use draw2d ( https://github.com/freegroup/draw2d ) inside w2layout. But I found that outside w2layout draw2d work good, but inside not work. How this can be fixed?
html code attached

[index_test.zip](https://github.com/vitmalina/w2ui/files/6221357/index_test.zip)

**Comment by vitmalina** [comment]
Can you please create JS fiddle to illustrate the problem.

**Comment by petrov-ab** [comment]
Yes, i did it
see https://jsfiddle.net/petrov_ab/xp4165j8/1/

**Comment by mpf82** [comment]
That's not a bug. on ``DOMContentLoaded`` the div with ID ``gfx_holder2`` does not exist in the DOM. You have to delay the execution of that code until the layout has loaded the panel's content. 

See: http://w2ui.com/web/docs/1.5/w2layout.onContent

For demonstration purposes, I've used a timeout to show you that it can work: https://jsfiddle.net/n9zsa4mt/

Next time, please reduce your fiddle to the **minimum** code necessary to demeontrate the issue. The fiddle you've created takes forever to load and contains a lot of code that's irrelevant to the issue.

**Comment by petrov-ab** [comment]
thank you very much for your answer
