### ISSUE TITLE
Grid Col Reorder disabled?

### ISSUE THREAD

**Issue by TauerOne** [vitmalina/w2ui#1996]
**Short description**
Column reordering is not working in the current 1.5 branch.  Has this been disabled on purpose or is it broken?

**What is current behavior**
Nothing happens when you click on a column header and drag it.

**What is desired behavior**
You should be able to drag a column to a new location in the grid.

**Link to jsfidle/codepan with sample code**
You can see it in the grid column re-order page.  http://w2ui.com/web/demos/#!grid/grid-25

**Steps to reproduce or sample** 
Click on a column heading and drag it.  Nothing happens.

**Comment by bswarts** [comment]
This seems like an important feature that has not been working for a few months now.  I'm new to w2ui and just evaluating it for use in my own projects. Am I missing something or like this issue indicates, the reorder column feature does not work?

**Comment by mpf82** [comment]
Closing as fixed
