### ISSUE TITLE
Textarea in editable grid

### ISSUE THREAD

**Issue by mendozada** [vitmalina/w2ui#2003]
Hello 
Is there a possibility to add a textarea in an editable column within the grid?

can the input be changed to a textarea?

greetings and thanks

**Comment by vitmalina** [comment]
You can use editable div, and that would be contenteditable="true" for the div.
```
columns: [ 
   { ... editable: { type: 'div' } }
]
```
you can also attach to `onEditField` (and `onChange`) events and replace input with textarea. Theoretically it should work, but I do not like textareas there as it suppose to be just a single line of text and textareas are multiline. 

contentEditable is different, it allows to do syntax highlight for example. I implemented it once.
