### ISSUE TITLE
w2ui gird mergeChanges() when grid.recid set to different field 

### ISSUE THREAD

**Issue by alocalsewerhistorian** [vitmalina/w2ui#2007]
**Short description** 
mergeChanges function fails when grid.recid set to different field in w2ui 2.0.x (nightly)(4/21/2021)

**What is current behavior**
calling "mergeChanges" after onChange event in grid with inline editing and with recid set to different field ('id' in this case)
get errors:
ERROR: Cannot merge.  Cannot set property 'id' of null TypeError: Cannot set property 'id' of null
    at w2grid.mergeChanges (w2ui.js:6348)
    at <anonymous>:1:17
w2ui.js:6353 Uncaught TypeError: Cannot read property 'w2ui' of null
    at w2grid.mergeChanges (w2ui.js:6353)
    at <anonymous>:1:17
seems to be due to change in "getChanges" causing "mergeChanges" to not find record based on recid field...?

v1.5: getChanges:line 5874-6:
                    if (rec.w2ui.changes != null) {
                        changes.push($.extend(true, { recid: rec.recid }, rec.w2ui.changes));
                    }
v2.0: getChanges: line 6322:
                    if (rec.w2ui.changes != null) {
                        var obj = {}
                        obj[this.recid || 'recid'] = rec.recid
                        changes.push($.extend(true, obj, rec.w2ui.changes));
                    }
v2.0:mergeChanges: line 6340                var record = this.get(changes[c].recid);

**What is desired behaviour**
mergeChange() updates grid recordset.

it works when I changed line :
// changed 
//                var record = this.get(changes[c].recid);
                var record = this.get(changes[c][this.recid || 'recid']);

...

**Steps to reproduce or sample** 
1. grid.recid:"id"
2. inline editing
3. call grid.mergeChanges()

...

**Comment by alocalsewerhistorian** [comment]
I just realized this is duplicate of issue #1965

**Comment by vitmalina** [comment]
Fixed in both branches `master` and `w2ui-1.5`. Good Catch. Eventually, there will be 1.5.4 but before that you can compiled version from 1.5 branch on your own.
