### ISSUE TITLE
maximized:true  It doesn't work

### ISSUE THREAD

**Issue by Dra-CuLa** [vitmalina/w2ui#2009]
The first way（It doesn't work）：
w2popup.open({
    title   : 'Popup'
    ,maximized : true
});
The second way（It doesn't work）：
w2popup.open({
    title   : 'Popup'
    ,onOpen  : function (event) {
        event.onComplete = function () {
            w2popup.max();
        };
    }
});

**Comment by mpf82** [comment]
Closing as fixed, PR pending.

Also introducing a new option: ``w2popup.options.openMaximized``
