### ISSUE TITLE
Need "Apply changes" function for w2grid and w2form!

### ISSUE THREAD

**Issue by vinhpt2** [vitmalina/w2ui#2017]
Now there is no way to apply changes for w2grid and w2form.
"Apply changes" mean save all changes in w2grid.records/w2form.record and clear current changes

**Comment by mpf82** [comment]
I'm not sure what you're trying to tell us.

w2grid.save does exactly that - it saves the current changes and then merges then, so they no longer show up as changes.

Changing fields in a w2form sets w2form.record directly, thus the comparison in getChanges happens agains w2form.original.
w2form.original is also reset if saving the form was successful.

So, in both cases w2grid.save and w2form.save will apply/save/merge/reset the changes.

Please elaborate on the issue.

**Comment by vinhpt2** [comment]
The w2grid.save and w2form.save will submit data to server. In case I do not what summit data so I can not use .save method

**Comment by mpf82** [comment]
You can try

    grid.mergeChanges();
    form.original = null;

This should tell the grid/form that there are currently no changes.

w2form does not need a "mergeChanges" method, because changes are done on form.record directly.

**Comment by mpf82** [comment]
Closing issue: no response

If you think this issue should be reopened, please elaborate on how ``grid.mergeChanges();`` and/or ``form.original = null;`` are not getting the job done.
