### ISSUE TITLE
Form layouts: natural flow

### ISSUE THREAD

**Issue by LucaGabi** [vitmalina/w2ui#2018]
**Describe the problem your feature will solve.**
Can forms be other then vertical forms ?
Request: allow the fields of a form to flow in natural html manner, the layout is then at the application level

**This a great library. The responsive UI is not always a solution for large business apps.**
I'd consider donation if you can provide details.

**Comment by vinhpt2** [comment]
It is better if form have more than 1 layout
flow layout
grid layout....

**Comment by vitmalina** [comment]
I am not sure what you mean by "other than vertical forms"? I think that greatest strength of w2form is ability to have auto generated layouts. It is super useful and you can have group fields, place groups next to each other, have multi page form, etc. See http://w2ui.com/web/demos/#/form/10,

However, you can use custom layout (not auto generated), See http://w2ui.com/web/demos/#/form/1, then form will just find to fields you provide. Hence, any layout is possible.
