### ISSUE TITLE
[BUG] Grid scrolling problem after search

### ISSUE THREAD

**Issue by mansurdegirmenci** [vitmalina/w2ui#2043]
![Animation10](https://user-images.githubusercontent.com/38755096/120396217-db537300-c33e-11eb-9ea7-0e9457cb2123.gif)

**Comment by mpf82** [comment]
This should be fixed in the currenty master's sources (no dist yet): https://github.com/vitmalina/w2ui/pull/2046

**Comment by mpf82** [comment]
Closing this issue since PR #2046 has been merged. Please re-open with a fiddle if needed.
