### ISSUE TITLE
[Bug] w2field overlay renders into w2toolbar overlay

### ISSUE THREAD

**Issue by mpf82** [vitmalina/w2ui#2048]
http://jsfiddle.net/fg03y8wu/1/

My guess: maybe this is because of ``keepOpen`` in ``w2menu``?

![w2ui_issue_2048](https://user-images.githubusercontent.com/10152404/121330772-99b26180-c916-11eb-9c23-bd4d5056e50d.gif)

Code:

```
$(function() {
  $('#form').w2form({
    name: 'form',
    fields: [{
      field: 'field1',
      type: 'list',
      required: true,
      html: {
        label: 'Last Name',
        span: 8,
        attr: ''
      }
    }, ],
    toolbar: {
      items: [{
        type: 'menu',
        id: 'item1',
        text: 'Menu',
        items: [{
            text: 'Item 1',
          },
        ]
      }, ]
    }
  });
});

```

**Comment by mpf82** [comment]
Somehow, after the recent changes in master, the fiddle in the original post no longer works with JQuery 3.2, so here's an updated fiddle, using the latest JQuery : http://jsfiddle.net/rnbs2z3t/

**Comment by vitmalina** [comment]
I checked JS fiddle, it works fine now.
