### ISSUE TITLE
[BUG] w2grid in advanced search 

### ISSUE THREAD

**Issue by mansurdegirmenci** [vitmalina/w2ui#2051]
no dropdownlist

https://jsfiddle.net/mansurdegrmenci/ewrtLcjm/4/

![resim](https://user-images.githubusercontent.com/38755096/121602635-46442e80-ca50-11eb-9e1b-cbc18ec9d292.png)

**Comment by mansurdegirmenci** [comment]
![Animation](https://user-images.githubusercontent.com/38755096/121603945-53621d00-ca52-11eb-96a5-b53318128723.gif)

**Comment by mpf82** [comment]
ACK.

list fields (outside of forms) are broken in the current master's dist.

Another example: http://jsfiddle.net/596yqpk0/ based on http://w2ui.com/web/demos/#/fields/3

**Comment by mansurdegirmenci** [comment]
"backspace" in dropdownlist does not work.

![Animation](https://user-images.githubusercontent.com/38755096/121702952-fe1e1e00-cada-11eb-8c06-6c022c41f93c.gif)

**Comment by mansurdegirmenci** [comment]
> "backspace" in dropdownlist does not work.
> 
> ![Animation](https://user-images.githubusercontent.com/38755096/121702952-fe1e1e00-cada-11eb-8c06-6c022c41f93c.gif)

Backspace does not work for w2list in firefox browser.

**Comment by mpf82** [comment]
This seems to be fixed.
At least your fiddle https://jsfiddle.net/mansurdegrmenci/ewrtLcjm/4/ and my fiddle http://jsfiddle.net/596yqpk0/  are now working correctly.

Can you please conform?

**Comment by mansurdegirmenci** [comment]
> This seems to be fixed.
> At least your fiddle https://jsfiddle.net/mansurdegrmenci/ewrtLcjm/4/ and my fiddle http://jsfiddle.net/596yqpk0/ are now working correctly.
> 
> Can you please conform?

thank you. no error appears. "backspace" still doesn't work :)

**Comment by mpf82** [comment]
I can reprocude backspace not working in inline editing of lists.

I've created a new issue for this: #2095

I will close this issue, as the original issue has been fixed.
