### ISSUE TITLE
Question or request regarding "flat sidebar"

### ISSUE THREAD

**Issue by mansurdegirmenci** [vitmalina/w2ui#2052]
http://w2ui.com/web/demos/#/combo/11

How can I make the "flat sidebar" like this when launching the app? I want it to be hidden at the beginning.

![resim](https://user-images.githubusercontent.com/38755096/121608225-2b76b780-ca5a-11eb-9845-df103bd69393.png)

This is not good.
![resim](https://user-images.githubusercontent.com/38755096/121608418-93c59900-ca5a-11eb-9f78-f0a43b268e12.png)

**Comment by vitmalina** [comment]
http://w2ui.com/web/docs/1.5/w2sidebar.flat
