### ISSUE TITLE
w2grid + tab

### ISSUE THREAD

**Issue by olyagordienko1** [vitmalina/w2ui#2063]
Ошибка "Cannot read property 'apply' of undefined" при наведении курсора мыши на вкладку

Google Chrome (91.0.4472.106)
![1](https://user-images.githubusercontent.com/86226974/122736485-493deb00-d2aa-11eb-9f37-10ed8a38458b.png)

Mozilla Firefox (52.9.0)
![2](https://user-images.githubusercontent.com/86226974/122736743-899d6900-d2aa-11eb-81ba-c18e2c0a9689.png)

https://jsfiddle.net/olyagordienko1/8pyt07rm/5/

**Comment by telewak** [comment]
same issue here.... otherwise great tool!

**Comment by mpf82** [comment]
Updated fiddle: https://jsfiddle.net/ysgzdoe8/

@vitmalina Surely we could wrap the default handler in ``if(subject[method])`` - but I'm not familiar with the overall logic in this case.

![2021-09-14 12_42_22-w2utils js - w2ui - Visual Studio Code](https://user-images.githubusercontent.com/10152404/133243764-4682d408-242f-45ed-aca6-1a572278c2ad.png)

**Comment by olyagordienko1** [comment]
![3](https://user-images.githubusercontent.com/86226974/134476043-cf7f8cdc-3daa-4b4f-86c8-d052e90587b8.png)
Не вызываются события onClick и onClose
https://jsfiddle.net/olyagordienko1/7f1nprj4/7/

**Comment by vitmalina** [comment]
Recompiled JS and CSS and checked, JS Fiddle works fine now. The problem was in the grid, it have too broad `bindEvent`. I have fixed related possible issues in tabs and toolbar too.
