### ISSUE TITLE
Dragging of columns and lists in search fields no longer work (v. 2.0)

### ISSUE THREAD

**Issue by gespo14** [vitmalina/w2ui#2069]
Hi, I report that on version 2.0 the dragging of columns and the lists in search fields no longer work.

**Comment by mpf82** [comment]
Closing this as a duplicate of https://github.com/vitmalina/w2ui/issues/1996 and https://github.com/vitmalina/w2ui/issues/2051

Both issues are now fixed.

Please re-open with a fiddle, if needed.
