### ISSUE TITLE
w2field get / set to retrive the actual value

### ISSUE THREAD

**Issue by LucaGabi** [vitmalina/w2ui#2072]
**Describe the problem your feature will solve.**
For w2field there is no way to actually get / set underlaying value (i.e 44%  would be 0.44).
There is a clear difference between the rendered value and actual value.

**Describe the solution you'd like**
w2field need a set / get function to return the actual value not the rendered value.

**Comment by mpf82** [comment]
That's already possible using ``$(selector).w2field().set()`` and ``$(selector).w2field().get()`` - in combination with ``clean()``.

General demo:  http://w2ui.com/web/demos/#/fields/7

Specific demo: http://jsfiddle.net/zp7w90vg/

Code:

```
$('#test1').w2field('percent', {});
setTimeout( () => {
	$('#test2').val( $('#test1').w2field().clean( $('#test1').w2field().get() ) );
}, 2000);
```

But maybe an optional ``clean`` parameter for ``get`` would be more intuitive.

Or maybe ``clean`` w/o parameters could use the result of ``get()`` as value.

@vitmalina what do you think?

**Comment by LucaGabi** [comment]
:) I also found that
Thanks great lib!

![tm web](https://user-images.githubusercontent.com/37976898/125822529-fb9d5bde-3502-4202-a491-bfa69314bb8b.gif)

**Comment by LucaGabi** [comment]
is there any way to get the date object from w2field ?

**Comment by mpf82** [comment]
> is there any way to get the date object from w2field ?

You can use ``w2utils.isDate( 'your_date_string', null, true );`` to convert a string to a JS ``Date`` object using the current ``w2utils.settings.dateFormat``.

If you have a specific date format, pass it as the second argument.

Docs: http://w2ui.com/web/docs/1.5/w2utils.isDate

**Comment by vitmalina** [comment]
It looks like this issue is resolved.
