### ISSUE TITLE
[Feature Request] Adding row delete method in w2grid

### ISSUE THREAD

**Issue by mansurdegirmenci** [vitmalina/w2ui#2076]
I'm using web socket and when one person deletes the record, I want it to be deleted for everyone. 
I don't want the grid to be reloaded. 

because this method only sends http delete request. then it reloads to the grid.
![image](https://user-images.githubusercontent.com/38755096/126724616-0f3209be-dd0a-467c-a8fb-7648a1679ecb.png)

If there is a method that I do not know, can you share with me? how can i delete only single line without reloading.
![image](https://user-images.githubusercontent.com/38755096/126724759-90ea9a87-4112-4cfb-88f8-dadb4f85eb86.png)

how can i use this method
```
remove() {
        let removed = 0
        for (let a = 0; a < arguments.length; a++) {
            for (let r = this.records.length - 1; r >= 0; r--) {
                if (this.records[r].recid == arguments[a]) { this.records.splice(r, 1); removed++ }
            }
            for (let r = this.summary.length - 1; r >= 0; r--) {
                if (this.summary[r].recid == arguments[a]) { this.summary.splice(r, 1); removed++ }
            }
        }
        let url = (typeof this.url != 'object' ? this.url : this.url.get)
        if (!url) {
            this.localSort(false, true)
            this.localSearch()
        }
        this.refresh()
        return removed
  }

```

**Comment by mpf82** [comment]
> how can i use this method

You call it with an arbitrary number of recids as argument.

    w2ui['grid'].remove(2, 5, 6);

Docs: http://w2ui.com/web/docs/1.5/w2grid.remove

**Comment by mansurdegirmenci** [comment]
Was it that simple :( i have to read the documentation.
sorry thanks

**Comment by mansurdegirmenci** [comment]
I used the method you said, it works, thank you. 
but there is an error after using the remove method. I am using "autoload=false" from grid properties. When you use the remove method, the number of lines in the grid decreases. The autoload feature comes into play and detects as if there is a new data. in short, the row count of the grid should be updated after the remove method.


![Animation10](https://user-images.githubusercontent.com/38755096/126849836-273cc2e7-d833-4959-b48a-a791563df075.gif)
