### ISSUE TITLE
Get back the old styles

### ISSUE THREAD

**Issue by boumboum** [vitmalina/w2ui#2082]
Since you've changed the "old" look and feel all my sites were broken.
I've actually liked the old look and colors. That was a true w2ui style! :-) Now all fields and grid sections (like the header, and the toolbar) are bigger and wider, nothing fits to my pages. It means a huge rework task for me!
And it is not even nicer, but I know, there's no accounting for taste.
So is it possible to get back tol old css styling but with the new functionalities?
Just replacing the new css file with the old one doesn't work.

**Comment by mrg2001** [comment]
I am sorry it broke for you. We have started v 2.0, which is in the current master and this work is in progress. However, there is v 1.5 branch, which is probably what you are using. There will be just bug fixes there, no new features, but you can download latest version there that will look the same, see https://github.com/vitmalina/w2ui/tree/w2ui-1.5/dist
