### ISSUE TITLE
Grid Inline edit not working after reach end of row via keyboard tab

### ISSUE THREAD

**Issue by LucaGabi** [vitmalina/w2ui#2084]
**Short description**
Grid inline edit not working after reach end of row via keyboard tab.

**What is current behavior**
No more inline edit allowed

**What is desired behavior**
Initial intended behavior.

**Link to jsfidle/codepan with sample code**
http://w2ui.com/web/demos/#/grid/21

**Steps to reproduce or sample** 
Enter edit mode and tab till end of row then try to enter edit mode again.

**PLEASE HELP ME FIX THIS**

MORE DETAILES
If checkbox is toggled with mouse inline edit is available again. 
(if you don't have a checkbox at the end but a list you are stuck)
(maybe it stays in edit mode ... state)

**Comment by LucaGabi** [comment]
I fixed it adding an if to skip hidden columns:

js```
 // need timeout so, this handler is executed last
                        setTimeout(function () {
                            switch (event.keyCode) {
                                case 9:  // tab
                                    var next_rec = recid;
                                    var next_col = event.shiftKey ? obj.prevCell(index, column, true) : obj.nextCell(index, column, true);
                                    // next or prev row
                                    if (next_col == null) {
                                        var tmp = event.shiftKey ? obj.prevRow(index, column) : obj.nextRow(index, column);
                                        if (tmp != null && tmp != index) {
                                            next_rec = obj.records[tmp].recid;
                                            // find first editable row
                                            for (var c = 0; c < obj.columns.length; c++) {
                                                if(obj.columns[c].hidden) continue; /////     <-------------- fix
                                                var edit = obj.getCellEditable(index, c);
                                                if (edit != null && ['checkbox', 'check'].indexOf(edit.type) == -1) {
                                                    next_col = parseInt(c);
                                                    if (!event.shiftKey) break;
                                                }
                                            }
                                        }

                                    }
                                    if (next_rec === false) next_rec = recid;
                                    if (next_col == null) next_col = column;
                                    // init new or same record
                                    el.blur();
                                    setTimeout(function () {
                                        if (obj.selectType != 'row') {
                                            obj.selectNone();
                                            obj.select({ recid: next_rec, column: next_col });
                                        } else {
                                            obj.editField(next_rec, next_col, null, event);
                                        }
                                    }, 1);
                                    if (event.preventDefault) event.preventDefault();
                                    break;

                                case 13: // enter
                                    el.blur();
                                    var next = event.shiftKey ? obj.prevRow(index, column) : obj.nextRow(index, column);
                                    if (next != null && next != index) {
                                        setTimeout(function () {
                                            if (obj.selectType != 'row') {
                                                obj.selectNone();
                                                obj.select({ recid: obj.records[next].recid, column: column });
                                            } else {
                                                obj.editField(obj.records[next].recid, column, null, event);
                                            }
                                        }, 1);
                                    }
                                    if (el.tagName.toUpperCase() == 'DIV') {
                                        event.preventDefault();
                                    }
                                    break;

                                case 27: // escape
                                    var old = obj.parseField(rec, col.field);
                                    if (rec.w2ui && rec.w2ui.changes && rec.w2ui.changes[col.field] != null) old = rec.w2ui.changes[col.field];
                                    if ($(el).data('old_value') != null) old = $(el).data('old_value');
                                    if (el.tagName.toUpperCase() == 'DIV') {
                                        $(el).text(old != null ? old : '');
                                    } else {
                                        el.value = old != null ? old : '';
                                    }
                                    el.blur();
                                    setTimeout(function () { obj.select({ recid: recid, column: column }); }, 1);
                                    break;
                            }
                            // if input too small - expand
                            expand.call(el, event);
                        }, 1);
```

**Comment by LucaGabi** [comment]
It still has problems if there are many columns ...

**Comment by LucaGabi** [comment]
No response .. like the project is not being maintained any more .... 
I'm surprised to see that ui improvements are  considered to have priority over bugs and useful functionalities ...

**Comment by mpf82** [comment]
Do not worry, this project is definitely maintained. However, currently @vitmalina and I are the only ones actively writing PRs and we have jobs, family, etc., too.

Any help in maintaining the project is greatly appreciated.

Cheers, Mike

**Comment by vitmalina** [comment]
I looked at the problem again and I see that it was fixed. It was fix differently then what you suggested. But now once you are in edit mode
- you can tab and it will go to the next field, including jumping to the next row
- you can shift+tab and it will go to previous field
- at the first row, first field, shift+tab will stay in the field
- at the last row, last field, tab will stay in the field
- enter key goes to next row, same column
- shift+enter goes to previous row, same column.
