### ISSUE TITLE
Sort after filtering clearing records

### ISSUE THREAD

**Issue by ricardo-r2ac** [vitmalina/w2ui#2085]
**Short description**
When I call **Sort method** after custom filtering the grid, clear all records

**What is current behavior**
I am using this to make custom filtering:
       grid.searchData = [{ type: 'custom' }];
       grid.last.searchIds = [....];
       grid.total = grid.last.searchIds.length;
       grid.buffered = grid.total;
       grid.refresh();

After that, when I call SORT method, **It clears all records in grid**

Any tips to solve that ?

**Comment by mpf82** [comment]
Can you please provide a Fiddle/Bin/Pen to demonstrate the issue?

**Comment by mpf82** [comment]
Closing issue: no response
