### ISSUE TITLE
form.validate() returns false and rollback to origin value

### ISSUE THREAD

**Issue by iapyeh** [vitmalina/w2ui#2108]
For a field of type "int" with options {min:1, max:40, silent:false}. If a user inputs "abc". it is auto corrected  to "".  If a user inputs "500", it is auto corrected to 40. If a user inputs "10.2", it is auto corrected to "10". For all three cases, form.validate() is always "true". 

I'd like to suggest an option that for all three cases, there is no auto-correction.  The form.validate() returns false and the value has been rollback to origin value.

**Comment by mansurdegirmenci** [comment]
Can you share the jsfiddle?

**Comment by iapyeh** [comment]
Hi, please check the attached issue2108.zip. There is a 2108.html in unzipped folder. Please start from it.
Originally, I encountered this problem in WKWebkit on MacOS (v11.4).
With the 2108.html, I found the behavior is the same as in the Safari, but with a little bit difference in the Chrome.
The same thing is that form.validate() reports no error in both browsers for invalid values.

Thanks for your help.

[Issue2108.zip](https://github.com/vitmalina/w2ui/files/7218478/Issue2108.zip)

**Comment by mpf82** [comment]
I've created a fiddle from your archive: http://jsfiddle.net/t5rvz2oq/

I can/will **not** look into it, as I don't have a Safari browser.

In Chrome everything seems to be working as expected, plus I cannot even input characters in those integer input fields.

---

How to easily create a jsfiddle: 

Pick one of the [w2ui demos](http://w2ui.com/web/demos) that comes closest to the issue, click on "fiddle with code online", modify fiddle as needed. (Currently, for grids, you *must* select JQuery 3.4 or newer - the preselected JQuery will not work with w2ui 2.0!)

**Comment by iapyeh** [comment]
Hi Mike, 

Thanks for your help about creating the fiddle page.

Because I am using the w2ui in a native app with WKWebkit on MacOS. In such environment,  the Safari can reproduce the same behavior. 

By the way, there is a behavior can be reproduced In the Chrome:
1.  firstly input 40
2. delete the 40 with backspace
3. hit ENTER

Then an empty string as a new value will be triggered. If focus field turns to others, then the original focused int field would stay in state of having empty string.

**Comment by vitmalina** [comment]
I agree that `silent` is not logicaly correct. I have remove it and replaced with `autoCorrect`. Now, if `autoCorrect=true`, which is default, it will enforce min/max. Also `form.validate()` will return proper errors when autoCorrect is false. Please not, it is only for min/max. If format is not valid, it will silently correct it (or set to empty string). However, number field will not let you type letters.
