### ISSUE TITLE
[Feature Request] Turn w2field types into classes

### ISSUE THREAD

**Issue by mpf82** [vitmalina/w2ui#2114]
Currently w2field is a class of it's own with the type being just a string property and there are a lot of ``switch (this.type) {`` checks throughout the various functions.

The advantage of each type being its own class (e.g. w2fieldInt, w2fieldText, w2fieldEnum, w2fieldFiel, ...) would be, that those would be easy to sub-class in a custom context and they would also be a good starting point at writing an "independent" w2field type.

This would probably mean a lot of refactoring, so we should discuss if the benefits justify the work required.

My current use case is, that I need a w2field of type 'file' that gets serialized to the DB as base64 (which is currently our default) and I need a different w2field of type 'file' that will be saved to disc on the server and only the relative filepath will be stored in the DB.

To distinguish those two, I could probably fiddle with the postData to pass the extra info - however, since we're using some hundred w2forms in our project, it is not intuitive to my co-workers to do it this way.

Using a different w2field type that can be modified at a central place in the code would be much more maintainable, IMHO.

Currently, creating a custom w2field type that does the same as a w2field of type 'file' would mean to duplicate a ton of code only for the sake of passing an additional parameter to postData.

---

Another benefit could be, that we could turn really *every* w2field type into a class to make sure, they are supported as both stand-alone fields, form fields and as fields in w2grid editing. 

Currently the form supports more field types than the stand-alone w2field and the grid also has it's own set of editable "field" types.

**Comment by vitmalina** [comment]
I think it is probable the right way to do. May be not each own class, but more live one for simple fields, such as int, hex, text, and another one is for drop down functionality. Not sure yet. But definitely agree that it needs refactoring in some way. Probably es6 classes with extend is the best way.

Form has some types that do not make sense as standalone, I think. For example, map and array. However, I might be wrong. 

Also, I think that `addType` and `removeType` should be removed in favor of class inheritance. Same as `w2obj.*.prototype` should be refactored with class inheritnce.

**Comment by vitmalina** [comment]
Removed `addType` and `removeType`. Implmented w2field as ES6 class and it can be extensible so you can create custom types. However, for types supported now, there is only one class. Here is an example how to do custom field types and use some of the fields functionality

https://w2ui.com/web/demos/#/fields/10
