### ISSUE TITLE
[Feature Request] Additional Formatting for Summary Cells

### ISSUE THREAD

**Issue by tpdietz** [vitmalina/w2ui#2137]
Currently, a summary cell is formatted the same as its corresponding 'editable' object.  This is problematic when you want the summary cells to be formatted differently than the grid cells.  For example, say a grid column allows integers only and its editable object is:

`{ type: 'int', inTag: 'maxlength=5', min: 0, max: 10000, max_allowed: '9,999' }`

However, the summary value must be the **average** of the columns, in which case, the summary editable object might be something like:

`{ type: 'float:2' }`

A recommended solution could be to add an extra 'editable' column attribute for a summary cell.  Then, the getCellEditable() function could be passed a 'summary' flag and it would then determine which of the 'editable' objects to return based upon that 'summary' flag.

I would be happy to supply more justification if you feel it is needed.

**Comment by vitmalina** [comment]
I did no understand your solution, `getCellEditable()` return object for inline editing. 

However, I did some adjustments and now you can format summary cells differently from normal cells, here is an example
```
            { field: 'fname', text: 'First Name', size: '30%', sortable: true,
                render(rec, { value, summary }) {
                    return !summary ? value : {
                        html: w2utils.formatNumber(value),
                        style: 'text-align: right'
                    }
                }
            },
```
see https://w2ui.com/web/demos/#/grid/14
