### ISSUE TITLE
grid spreadsheet copy paste error 

### ISSUE THREAD

**Issue by ooo4321** [vitmalina/w2ui#2160]
![bandicam 2021-11-30 17-45-11-405](https://user-images.githubusercontent.com/12015510/144080309-65fb351b-a372-4414-9a4a-2a9478a44123.gif)

**Comment by ooo4321** [comment]
I configured the grid by adding selectType: 'cell' and nothing else, the recid of the rows is set and are distinct.

When i copy the cell values to excel it works, no problem but when i try to copy the values from excel to the grid it works except that it's nullifing the first value of the row below of the last pasted row ... So in the example i am pasting 3 cells from excel it works but the problem is that it changes also the 4th ... Any ideea ?

**Comment by ooo4321** [comment]
the columns are configured as follows 

 { field: 'tip', text: 'Tip', size: '110px', sortable: true, resizable: true, required: true,
                editable: { type: 'list', items: ['Principal','Secundar','Terti'], filter: false, showAll: true, 
                            }
            },
            { field: 'text', text: 'Cod Caen', size: '45%', sortable: true, resizable: true, searchable: true, required: true,
                editable: { 
                    openOnFocus: true,
                    type: 'list', 
                    minLength: 3, 
                    url : 'https://api.something.com/v1/caen/caen',
                    method: 'GET',
                    match : 'contains',
                    }
            },
            { field: 'text2', text: 'Locatie', size: '45%', sortable: true, resizable: true, searchable: true, required: true,
                editable: { 
                    openOnFocus: true,
                    showAll: true,
                    type: 'list', 
                    url : 'https://api.something.com/v1/caen/locatie',
                    method: 'GET',
                    match : 'contains',
                    }
            },

**Comment by ooo4321** [comment]
I am doing the copy/paste with crtl + c /ctrl + v tried both chrome and firefox ...

**Comment by mpf82** [comment]
There's already two open issue about this:

https://github.com/vitmalina/w2ui/issues/1266

https://github.com/vitmalina/w2ui/issues/1892

Basically, it's somewhat Excel's fault for adding an additional ``"\n"`` to the copied data.

You could also argue that it's w2ui's fault for not handling Excel's faulty clipboard data correctly ...

You can try to apply the fix mentioned in #1892 (modify ``onPaste``).
