### ISSUE TITLE
column chooser missing in 2.0 ?

### ISSUE THREAD

**Issue by ooo4321** [vitmalina/w2ui#2161]
![w2ui_app](https://user-images.githubusercontent.com/12015510/144093074-6c326de3-92f9-48ea-8725-d20a1ff8f8dd.png)

**Comment by ooo4321** [comment]
hello, is there a reasonable simple way to activate the column chooser in 2.0 ?

**Comment by mpf82** [comment]
For some reason the default value for ``grid.show.toolbarColumns`` changed from ``true`` to ``false`` in this commit: https://github.com/vitmalina/w2ui/commit/67e3ed8636d3d9a69e782c4f01783c4fc0f096fc#diff-ff4cd19e64b5e90c7000b2c6cb45730d9b88e68ec7444b36909564585e422332

@vitmalina Do you know why? Should it stay like this?

@ooo4321 Simply set ``grid.show.toolbarColumns`` to true in the grid options

Fiddle: http://jsfiddle.net/kvp07x8a/ (based on https://w2ui.com/web/demos/#/grid/22)

**Comment by ooo4321** [comment]
thanks a bunch, works great :)

**Comment by mpf82** [comment]
Re-opening, waiting for a reply from Vitali.

**Comment by vitmalina** [comment]
Yes, I made it hidden by default on purpose in the attempt to make UI less "busy" for users. I think it is going to stay hidden by default. However, as @mpf82 correctly noted, it is easy to turn it on. I also think that the better way would be to make this popup show when you click right button on any column. It is what happens in dev tools network for example. I like it better this way, but it is not yet implemented.
