### ISSUE TITLE
Question related to expandable grid or column groups

### ISSUE THREAD

**Issue by mansurdegirmenci** [vitmalina/w2ui#2162]
I have a data list. When there is a change in this list, for example, I save the insertion and update operations as "json". Which method should I use when displaying this json data? Grid inside the grid, "column groups" or expandable grid?

![image](https://user-images.githubusercontent.com/38755096/144674420-bd9a2b52-9de0-43be-b991-b64c4d061486.png)

I need to set it to coincide with each line.
![image](https://user-images.githubusercontent.com/38755096/144674841-af1ae32d-7638-4b63-97cd-9471a13ab160.png)

**Comment by vitmalina** [comment]
Neither :). I personally dislike expandable grids and grid inside the grid as a UI solution in general. I prefer overlay for this purpose, or sidebar panels. It is up to you what you use, generally if data is similar as the one in the grid, use expendable grid, here is an example https://w2ui.com/web/demos/#/grid/7

Please do not submit questions here. Stackoverflow, or the like, man!
