### ISSUE TITLE
inline grid list field children

### ISSUE THREAD

**Issue by ooo4321** [vitmalina/w2ui#2168]
![Untitled-1](https://user-images.githubusercontent.com/12015510/144730364-04dd1a1a-d481-49a3-a443-293bd9ab6095.png)

**Comment by ooo4321** [comment]
I am trying to configure the combo/list inline grid in order to show the results grouped and i am not sure if there is already a way to do it as it is right now in 2.0 out of the box

**Comment by ooo4321** [comment]
at the moment i have the list/combo configured with url: param with the backend returning an array like : [['id'=>'1','text'=>'item1'],['id'=>'2','text'=>'item2']] and works great BUT,

is there a reasonable simple way to configure the list/combo css using the array like : 
[['id'=>'1','text'=>'item1','children'=>[
['id'=>'1','text'=>'subitem1'],['id'=>'2','text'=>'subitem2'],
]],
['id'=>'2','text'=>'item2','children'=>[
['id'=>'1','text'=>'subitem1'],['id'=>'2','text'=>'subitem2'],
]]]

**Comment by vitmalina** [comment]
Please submit questions elsewhere. These issues are for bugs/feature requests.
