### ISSUE TITLE
Consultation on making a request 

### ISSUE THREAD

**Issue by tsubayan** [vitmalina/w2ui#2169]
I'm creating pull request about https://github.com/vitmalina/w2ui/issues/2136
This issue occur on Jquery version >=3.2.0 with  w2ui-1.5 branch.
My fix code is removing recs.scrollTop() from w2ui-1.5 branch like current master(w2ui-2.0)
However, when I change w2grid.js(1.5) then such bug occur using Jquery version < 3.2.0.
So, Can I change the code?

**Comment by vitmalina** [comment]
Please submit the PR to 1.5 branch, not master
