### ISSUE TITLE
[BUG] Advanced Search closes unexpectedly after selecting an enum/list item

### ISSUE THREAD

**Issue by mpf82** [vitmalina/w2ui#2174]
**Short description**
If the advanced search contains a list/enum field, selecting an item closes the advaced search.

**What is current behavior**
...

**What is desired behavior**
Advanced Search should stay open (just like when selecting a date / color)

**Link to jsfidle/codepan with sample code**
https://w2ui.com/web/demos/#/grid/16

https://user-images.githubusercontent.com/10152404/145787298-945495d8-88a8-40b2-947a-5379ca9769c9.mp4

**Comment by HeshamAlnood** [comment]
Advanced Search is not working with me at all !

**Comment by vitmalina** [comment]
Fixed.
