### ISSUE TITLE
Advanced search seems doesn't work on the demo section

### ISSUE THREAD

**Issue by happy014** [vitmalina/w2ui#2177]
**Short description**
The advanced search examples don't work properly. Until last week I'm pretty sure they worked, in fact, I've used one of them to take a test.
This is one of the examples in the Demos section that doesn't work. Clicking on the button search, the popup closes without producing any effect.

I was using that in my application, including directly the link to the js and CSS files from the example below (I know it's not the best way to use this wonderful library). Today the advanced search feature seems to doesn't send any parameters to the request, then the table refreshes the data without applying filters. My application has the same issue.

[https://w2ui.com/web/demos/#/grid/16](url)

**Comment by mikeduglas** [comment]
Advanced search doesn't work completely in the demos.
