### ISSUE TITLE
Crash my grid after last update

### ISSUE THREAD

**Issue by anotte** [vitmalina/w2ui#2182]
**Crash my grid after last update**

... After this update w2ui 2.0.x (nightly) (12/28/2021, 8:35:25 PM), my grid stop to work

**What is current behavior**

... don´t show the grid data

![image](https://user-images.githubusercontent.com/2053464/147964844-ac715e85-58cd-4403-9642-8625cf11e8e4.png)

**What is desired behaviour**

...

**Link to jsfidle/codepan with sample code**

...

**Steps to reproduce or sample** 

...

**Comment by vitmalina** [comment]
Rebuilt JS. Should fix the issue. Demos work, which a linked through rawgit. https://w2ui.com/web/demos/#/grid/1

**Comment by mpf82** [comment]
Demo seems to be broken: https://w2ui.com/web/demos/#/grid/16 

> jQuery.Deferred exception: t is not defined getCellValue@https://rawgit.com/vitmalina/w2ui/master/dist/w2ui.min.js:85:31694

w2ui 2.0.x (nightly) (1/4/2022, 10:17:27 PM)

**Comment by vitmalina** [comment]
Fixed. Checked the demos - all good.
