### ISSUE TITLE
Grid Inline Editing demo is not working

### ISSUE THREAD

**Issue by idrakschlr** [vitmalina/w2ui#2183]
the demo is not working:

![Screenshot from 2022-01-05 19-05-54](https://user-images.githubusercontent.com/97185440/148258254-09dd0f83-1935-4f79-9d71-981a5264d6d0.png)

**Comment by mpf82** [comment]
Possibly duplicate of #2182

**Comment by vitmalina** [comment]
I was able to repeat this bug. It is due to refactoring. It is fixed now.
