### ISSUE TITLE
Programmatically apply changes and save row

### ISSUE THREAD

**Issue by idrakschlr** [vitmalina/w2ui#2184]
**Short description**
we are trying to change values of a column through javascript but the save button is not enabled.

```
w2ui.grid_1_toolbar.on('click', function (event) {

    if (event.target == 'process') {
        var g = w2ui.grid_1.records.length;

        for (lines in w2ui.grid_1.records) {
            if (parseInt(lines) < g) {
                w2ui.grid_1.set(parseInt(lines) + 1, {
                    "changes": {
                        "COLUMN_1": w2ui.grid_1.get(parseInt(lines) + 1).COLUMN_1,
                        "COLUMN_2": w2ui.grid_1.get(parseInt(lines) + 1).COLUMN_2
                    }
                });
                w2ui.grid_1.postData['header'] = {
                    "type": "PROCESS",
                    "LENGTH": g
                };
            }
        }
        w2ui.grid_1.save();
    }
});
```

**What is current behavior**
changes array is empty

**What is desired behavior**
changes to be sent to server for saving

**Comment by mpf82** [comment]
w2ui related properties have to be encapsulated in a "w2ui" object since w2ui 1.5

e.g. ``record.changes`` must be ``record.w2ui.changes``

Related issues: #1384 and #1351

**Comment by vitmalina** [comment]
What about this https://w2ui.com/web/docs/2.0/w2grid.mergeChanges

**Comment by idrakschlr** [comment]
Thanks for your support.

We have resolved the issue.

Regards
Idrak

**Comment by idrakschlr** [comment]
we added highlighted code to the logic and it worked

![image](https://user-images.githubusercontent.com/97185440/148670940-d96c1e46-b6ad-40e3-b041-cc510999e19b.png)
