### ISSUE TITLE
[BUG] Opening ES6 demo breaks all other demos

### ISSUE THREAD

**Issue by coltonfischer** [vitmalina/w2ui#2187]
**Short description**
When you hover over a grid column header there is a JavaScript error occurring that causes tooltips to not show for the grid column header.

**What is current behavior**
Grid column header tooltips do not show when you hover over the grid column header.

**What is desired behavior**
Grid column header tooltips will show when you hover over the grid column header.

**Link to jsfidle/codepan with sample code**
[Simple Grid Demo](https://w2ui.com/web/demos/#/grid/1)

**Steps to reproduce or sample** 
Hover over any of the grid column headers in the sample grid demo.  If you open the console you should see an error stating: `Uncaught TypeError: Cannot read properties of undefined (reading 'columnTooltipShow') at HTMLTableCellElement.onmouseenter`

**Comment by mpf82** [comment]
I cannot reproduce the mentioned error, neither with https://w2ui.com/web/demos/#/grid/1 nor with https://w2ui.com/web/demos/#/grid/31 - I tested with Firefox and Chrome.

When you check your browser's debugger, what w2ui version do you see? Maybe your browser uses a cached version?

The current version is `w2ui 2.0.x (nightly) (1/8/2022, 4:08:28 PM)`

https://rawgit.com/vitmalina/w2ui/master/dist/w2ui.min.js

![grafik](https://user-images.githubusercontent.com/10152404/148792055-c87018aa-f6a3-47de-b0af-df6f7e237fb7.png)

**Comment by coltonfischer** [comment]
I think it was a caching issue as to why the simple grid was giving the error.  However, it still seems to happen for the ES6 grid here: https://w2ui.com/web/demos/#/combo/14.

I found that if I go to the ES6 grid first then the error happens on all the other demo grids.  So I think there is only really an issue with the ES6 grid.

**Comment by mpf82** [comment]
True, probably because now there's 2 versions of w2ui loaded at once.

**Comment by vitmalina** [comment]
Fixed. Now es6 version loads in `<script type="module">` and no longer ovewrites global grid
