### ISSUE TITLE
Move from 1.4.2 to 1.5 popup form shows data from last open

### ISSUE THREAD

**Issue by miless1997** [vitmalina/w2ui#2192]
**Short description**
When i open popup from selected item in grid, fields are from last form open (or empty if first).

**What is current behavior**
On initial open, fields are blank, click other tab and first tab refreshes. Close form, select other grid item, open form and values from first selected item disaplayed

**What is desired behavior**
Form should show correctly selected record values

**Steps to reproduce or sample** 
1. select grid item
2. open popup form
3. values from last open (or default if first open)
4. click 2nd tab, return to first and values correct
5. close form
6. select other grid item
7. open popup form
8. values from last open
9. ... continues

**Comment by vitmalina** [comment]
It seems to me that this behavior is correct. Since form remembers its state, and can be used for add or edit, once form is rendered, you need to fill it with record you want to edit or call `form.clear()`.

**Comment by miless1997** [comment]
Hi,
The form seems to have the correct record – if I break on the extend near the botton or in the onOpen event and look at “record”, it is the correct data.  It just seems like an initial refresh issue… if I click on tab2, then click back to tab1, the data is correct too.

$().w2popup('open', {
                title: 'Venue',
                body: '<div id="form" style="width: 100%; height: 100%;"></div>',
                style: 'padding: 15px 0px 0px 0px',
                width: '500%',
                height: 625,
                modal: true,
                showMax: true,
                onToggle: function (event) {
                    $(w2ui.popupForm.box).hide();
                    event.onComplete = function () {
                        $(w2ui.popupForm.box).show();
                        w2ui.popupForm.resize();
                    }
                },
                onOpen: function (event) {
                    event.onComplete = function () {
                        // specifying an onOpen handler instead is equivalent to specifying an onBeforeOpen handler,
                        // which would make this code execute too early and hence not deliver.
                        $('#w2ui-popup #form').w2render('popupForm');
                        if (IsValidFormRecord(record) && record.recid != 0) {
                            $('#modifiedby')[0].innerText = record.modifiedby.toString();
                        }
                        if (userRoleId.toString() != "1" && userRoleId.toString() != "16")
                            w2ui['popupForm'].tabs.hide('tab2');

                        if (w2ui['popupForm'].record['recid'] == null || w2ui['popupForm'].record['recid'] == "0") {
                            w2ui['popupForm'].record['isdeleted'] = w2ui['popupForm'].fields[1].options.items[0];
                            w2ui['popupForm'].record['venuecategorycolor'] = w2ui['popupForm'].fields[2].options.items[0];
                        }
                        w2ui['popupForm'].refresh();
                        w2ui['popupForm'].tabs.click('tab1'); //force first tab to be selected by default
                    }
                },
            });


            w2ui['popupForm'].record = jQuery.extend({}, record); //needs to be a copy of record, not a pointer to it!

        }

**Comment by miless1997** [comment]
Hi,
I moved the jquery extend statement in to the scope of the onOpen() function of the popup rather that it just being in the scope of $().w2popup('open')  and it seems to work – any issues that you can think of?

***@***.***


From: miles copperheadsoftware.com
Sent: Monday, January 31, 2022 1:55 PM
To: vitmalina/w2ui ***@***.***>; vitmalina/w2ui ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [vitmalina/w2ui] Move from 1.4.2 to 1.5 popup form shows data from last open (Issue #2192)

Hi,
The form seems to have the correct record – if I break on the extend near the botton or in the onOpen event and look at “record”, it is the correct data.  It just seems like an initial refresh issue… if I click on tab2, then click back to tab1, the data is correct too.

$().w2popup('open', {
                title: 'Venue',
                body: '<div id="form" style="width: 100%; height: 100%;"></div>',
                style: 'padding: 15px 0px 0px 0px',
                width: '500%',
                height: 625,
                modal: true,
                showMax: true,
                onToggle: function (event) {
                    $(w2ui.popupForm.box).hide();
                    event.onComplete = function () {
                        $(w2ui.popupForm.box).show();
                        w2ui.popupForm.resize();
                    }
                },
                onOpen: function (event) {
                    event.onComplete = function () {
                        // specifying an onOpen handler instead is equivalent to specifying an onBeforeOpen handler,
                        // which would make this code execute too early and hence not deliver.

                        $('#w2ui-popup #form').w2render('popupForm');
                        if (IsValidFormRecord(record) && record.recid != 0) {
                            $('#modifiedby')[0].innerText = record.modifiedby.toString();
                        }
                        if (userRoleId.toString() != "1" && userRoleId.toString() != "16")
                            w2ui['popupForm'].tabs.hide('tab2');

                        if (w2ui['popupForm'].record['recid'] == null || w2ui['popupForm'].record['recid'] == "0") {
                            w2ui['popupForm'].record['isdeleted'] = w2ui['popupForm'].fields[1].options.items[0];
                            w2ui['popupForm'].record['venuecategorycolor'] = w2ui['popupForm'].fields[2].options.items[0];
                        }
                        w2ui['popupForm'].refresh();
                        w2ui['popupForm'].tabs.click('tab1'); //force first tab to be selected by default
                    }
                },
            });


            w2ui['popupForm'].record = jQuery.extend({}, record); //needs to be a copy of record, not a pointer to it!

        }

**Comment by vitmalina** [comment]
seems fine
