### ISSUE TITLE
Fill in the blank when zooming

### ISSUE THREAD

**Issue by akrostar** [vitmalina/w2ui#2196]
**Short description**
A clear and concise description of the problem

Zooming has a blank area that cannot be filled

**What is current behavior**
...

**What is desired behavior**

Fill in the blank when zooming

**Link to jsfidle/codepan with sample code**
...

**Steps to reproduce or sample** 
...
![image](https://user-images.githubusercontent.com/87679912/155715125-2d22a8f4-2d91-473a-9b2f-5d97710a0991.png)

**Comment by vitmalina** [comment]
I cannot repeat this problem. Since there is no response for jsFiddle request, closing the issue.
