### ISSUE TITLE
theme

### ISSUE THREAD

**Issue by zfranco55** [vitmalina/w2ui#2198]
Is it possible to change the theme ?

**Comment by vitmalina** [comment]
Yes, it is. I no longer update dark theme in the project, but in my work I use multiple themes (including dark one). Basic approach is to link `w2ui.css` and then link some `w2ui-custom.css`, where you overwrite based on your needs. The reason for custom file is to be able to update future versions of w2ui easier. Then you just replace w2ui.css and still can use your `w2ui-custom.css`
