### ISSUE TITLE
given formHTML is not longer rendered with latest w2ui JS-Code

### ISSUE THREAD

**Issue by miwern** [vitmalina/w2ui#2202]
**Short description**
If you define a w2form and give them the html behavour by formHTML, that html Part is not rendered into the Page (using the latest w2ui-es6.js from the dist directory).

**What is current behavior**
the html code given by formHTML is not rendered to its anker div

**What is desired behavior**
the html code given by formHTML is rendered to its anker div

**Link to jsfidle/codepan with sample code**

**Steps to reproduce or sample** 
.
[index-html.txt](https://github.com/vitmalina/w2ui/files/8363606/index-html.txt)

**Comment by vitmalina** [comment]
I tried you example, and it seemed to work for me. I did setup a bigger height, as it would not show nicely. Also, it seems to be working here https://w2ui.com/web/demos/#/form/1

I would still recommend to use auto-generated forms. They are much more robust and there are many options to do the form in the way works for you. However, if you do want to use a custom one, you should start with auto-generated one and then modify it in the way you need.

**Comment by vitmalina** [comment]
Closing the issue, if it is still a problem, please re-open and provide jsFiddle example where it is not working
