### ISSUE TITLE
when w2grid is shown rows with status "selected" change to unselected

### ISSUE THREAD

**Issue by ralonsoreyes** [vitmalina/w2ui#2204]
w2ui vs 2.0

- Project w2ui with w2layout,
- several w2grid in memory, not shown in GUI at once.
-  I change a w2grid by another in the same panel.
- There are records with "selected" status in w2grid before being shown but when w2grid is shown they change the status to unselected.
- debugging w2ui library... I think that I have detected the possible issue:
when I change a w2grid by other the event "render" is called and inside this function a "reset(true)" method is called removing the former selection in the w2grid.
I have commented the line and all seems to work now, but I dont know if this is the best solution.

![image](https://user-images.githubusercontent.com/48027343/162931436-a6a1bac6-7e02-4903-8d0f-78e5e25090af.png)

**Comment by vitmalina** [comment]
I removed clear selection from `reset` method. I added it to `clear` method.
