### ISSUE TITLE
Context menu icons get cut off

### ISSUE THREAD

**Issue by squadjot** [vitmalina/w2ui#2207]
The bottom of the menu icons for Context Menus get cut off.  (tried in Edge and Chrome)
https://w2ui.com/web/demos/#/combo/12

If we change the display attribute to _block_ instead og _inline-block_, it seems to fix the issue. 

[class*=" w2ui-icon-"]:before, [class^=w2ui-icon-]:before {
    font-family: w2ui-font;
    **display: block;**
    vertical-align: middle;
    line-height: 1;
    font-weight: 400;
    font-style: normal;
    speak: none;
    text-decoration: inherit;
    text-transform: none;
    text-rendering: optimizeLegibility;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
}

**Comment by vitmalina** [comment]
Fixed as suggested, pushed rebuilt JS and CSS, it will take a few min to propagete

**Comment by vitmalina** [comment]
checked on w2ui, seems to work fine now

**Comment by squadjot** [comment]
Nice!, thank you!
