### ISSUE TITLE
Position of icons in toolbar menu

### ISSUE THREAD

**Issue by squadjot** [vitmalina/w2ui#2208]
The positioning of the [toolbar menu icons](https://w2ui.com/web/demos/#/toolbar/1), is a bit off.

I propose the following change to margin property:  

.w2ui-toolbar .w2ui-scroll-wrapper .w2ui-tb-button .w2ui-tb-icon {
    float: left;
    width: 22px;
    **margin: 3px 0 0 1px;**
    text-align: center;
}

**Comment by vitmalina** [comment]
I checked it agains many icons, and I see it actually depends on the icon. Some icons look centered, some not. But I think it is fixed now
