### ISSUE TITLE
Grid Inline Editing does not work anymore

### ISSUE THREAD

**Issue by ChristianTwuest** [vitmalina/w2ui#2210]
**Short description**
Im trying to inline edit a text field but as soon as the focus is on another element of the grid the text disappears.

**What is desired behavior**
I would expect that the text does not disappear. 

![image](https://user-images.githubusercontent.com/29101349/165032138-67aef1c0-0c56-4503-80d3-e685a62ab00a.png)

**Link to jsfidle/codepan with sample code**
[Link to the demo](https://w2ui.com/web/demos/#/grid/21)

**Steps to reproduce or sample** 
The issue is even reproducable in the demo of the inline editing. Simply add text to a text column and focus on another column and the text disappears. 

Regards
Chris

**Comment by vitmalina** [comment]
Fixed inline editing, sorry it took a while. It was lots of work. New version does not use jQuery anymore and used refactored fields and tooltips. Also this demo https://w2ui.com/web/demos/#/combo/3, will work well
