### ISSUE TITLE
w2grid with column field type as 'date' does not show calendar in advance search

### ISSUE THREAD

**Issue by ralonsoreyes** [vitmalina/w2ui#2211]
v2.0

w2grid:
Column/records with field as 'date' 
or 
searches with field type as date.

Does not show calendar and also the filter not work correctly.

examples:
https://w2ui.com/web/demos/#/grid/3
https://w2ui.com/web/demos/#/grid/5
...
![image](https://user-images.githubusercontent.com/48027343/165922525-6d0979a1-3fae-4d4f-9b56-2899acae1e22.png)

In w2form calendar is running but... Where is the calendar in w2grid advanced search?

**Comment by mpf82** [comment]
Seems all overlay related search fields (list, date, color, ...) are currently broken in advance search.

Related: https://github.com/vitmalina/w2ui/issues/2179
