### ISSUE TITLE
Custom types for Map/Array keys/values

### ISSUE THREAD

**Issue by KyGost** [vitmalina/w2ui#2215]
Is it possible to change the type of map/arrays?
I'm trying to make a form with a map which has both of key and value each as a list input.

**Comment by vitmalina** [comment]
Unfortunately no. It is a plain text field. You can potentially, create a dynamic form where fields would be created automatically as form fields. Then you can use any field types. I think it could be the easiest solution. I think it would not be easy to implement this feature with map/array as there are many types and they will be tedious to do in map array.
