### ISSUE TITLE
w2grid appears when it is unlocalized

### ISSUE THREAD

**Issue by ralonsoreyes** [vitmalina/w2ui#2242]
w2ui vs 1.5

Description
w2grid is rendered using a parent/container selector and appears in the GUI when it should be unlocalized.

Steps:

1.- w2layout and  w2grid (grid1 and grid2).
2.- In layout main panel place grid1.
3.- After this place grid2. both grids "remember" (or something like that) to belong to the panel-main layout, even though currently grid1 is not in the panel.
4.- now grid1 is unlocalized (in memory but not in display)
5.- now, if any website event calls a grid1.render(), it appears in the layout even though it shouldn't because it's not shown in the layout panel.

What is desired behavior
Components not placed in the GUI (they are in w2ui global memory), they should not appear if they are not placed, when calling render() or in general using any other method.

Example:

https://jsfiddle.net/raul1975/2khp53me/21/

**Comment by vitmalina** [comment]
I am not sure I understand what you mean by "unlocalized" does it refer to localization aka translation?

Once grid is rendered, it will remember where it was rendered in `grid.box` property. If you render another grid in the same box, both will remember where they were rendered. But grid does not reappear in the box on its own. You have to render it.

Unfortunately, I do not know a good way to clear `grid.box` property as there is no even that something else is rendered in the same box. Theoretically, you could render a grid as a subgrid. However, there is one clue. Once grid (or other component) is rendered, it will record its name into the `name` attribute of that container. This is how you can know what is rendered in the box.

**Comment by ralonsoreyes** [comment]
Ok,

It seems that it is simply my interpretation of how it should work, which is different from what you thought.

I expected that a w2ui component should not be rendered if it is not currently inside its container, that is, w2grid is not currently in any panel of the layout. it was, but now it's not. (this is what i meant by unlocalized)

I have solved it since my use of the library. I thought it was a workaround, but maybe it's the way to do it

in my event of my application, before rendering w2grid I do a check:

if (w2ui.layout.get('main').content.name == w2ui.grid.name) w2ui.grid.render();

I expected that this check should be done by the library internally within the render function, but maybe I was wrong.

Greetings and thanks for your time.
