### ISSUE TITLE
[Bug] fiddle with code online

### ISSUE THREAD

**Issue by mpf82** [vitmalina/w2ui#2247]
The "fiddle with code online" link in the demos opens a fiddle with only https://rawgit.com/vitmalina/w2ui/master/dist/w2ui.min.css set as external resource.

The JS file https://rawgit.com/vitmalina/w2ui/master/dist/w2ui.min.js is not set in the fiddle and currently must be added manually.

**Comment by vitmalina** [comment]
It was only true for `type=module` examples
