### ISSUE TITLE
Please add language support(Chinese Taiwan).

### ISSUE THREAD

**Issue by WenSheng-tw** [vitmalina/w2ui#2257]
**Additional context**
zh-tw.json
[https://app.box.com/s/uyyr01zs78812m2vod6vlu0i0722xdyi](https://app.box.com/s/uyyr01zs78812m2vod6vlu0i0722xdyi)

**Comment by AlexKovynev** [comment]
@WenSheng-tw you can suggest PR. Look at this two.

https://github.com/vitmalina/w2ui/pull/2236/files
https://github.com/vitmalina/w2ui/pull/2239/files

**Comment by WenSheng-tw** [comment]
Thank you!! already  PR.
