### ISSUE TITLE
suggestion for locking

### ISSUE THREAD

**Issue by rolfn** [vitmalina/w2ui#226]
w2form has a lock function for the whole form. Is it possible to add separate lock functions for each tab?

...Rolf

**Comment by edomato** [comment]
This is something interesting to have, and I'm also in the need of other kind of locking.

What I'm needing (that right now I'm implementing outside W2UI but hope to make a pull request soon) is the possibility to disable all the form fields so in that way, if you have a form with tabs for example you can still visit each tab, view the content of the whole form and not being able to modify it.

Maybe this solution could be extended to the tab locking feature requested here, so you can disable (or enable) just some tabs of a form.

Just my two cents 😃

**Comment by mpf82** [comment]
implememtend in PR #1704 - this issue can be closed
