### ISSUE TITLE
Grid reorder column not work when set grid.url (get data from url)

### ISSUE THREAD

**Issue by vinhpt2** [vitmalina/w2ui#2262]
Grid reorder column not work when set grid.url = an Url (get data from url). Data is fetch and display ok but cannot reorder column any more
If set grid.records = an Array is Ok (no error)

**Comment by vitmalina** [comment]
I recently refactored column re-order. I checked your specific use case and it seems just fine for me. Please create a jsFiddle where you can demonstrate the problem.

**Comment by vitmalina** [comment]
I have change default demo to grid with url, all is good. https://w2ui.com/web/demos/#/grid/25. Closing the issue
