### ISSUE TITLE
Latest 08/08/2022 build breaks the grid context menu. [Reproducer: https://jsfiddle.net/ewcgapd8/1/]

### ISSUE THREAD

**Issue by NoelSMartin** [vitmalina/w2ui#2268]
**Short description**
Latest 08/08/2022 build breaks the grid context menu
Was ok on the 06/30/2022 build

**What is current behavior**
Context menu on grid causes a script error
`Uncaught TypeError: Cannot destructure property 'x' of 't.originalEvent' as it is undefined.`

**What is desired behavior**
No script errors

**Link to jsfidle/codepan with sample code**
https://jsfiddle.net/ewcgapd8/1/

**Steps to reproduce or sample** 
Right click in grid and watch console for error

**Comment by vitmalina** [comment]
This has been fixed. It will be working in today's build
