### ISSUE TITLE
Problem insert list or combo field in popup

### ISSUE THREAD

**Issue by peruginia** [vitmalina/w2ui#2269]
I have a problem when i put list field  in popup... 
the popup work and is draw fine but it seem no event work...

this is a test definition (working on old w2ui.js)

```
<div id="popupnewauth" style="display: none; width: 450px; height: 260px; overflow: hidden">
  <div id="popup1_title" rel="title">
      test
   </div>
   <div rel="body" style="padding: 10px; line-height: 150%">    
      <div class="w2ui-field">
         <label>User : </label>
	   <div>
	      <input type="list" id="wSelectAuthUser" class="form-control" placeholder="Select user..."  />					
	   </div>
      </div>
   </div>
   <div rel="buttons">
      <button id="btnSalvaAuth" class="w2ui-btn" onclick="save();">Save</button>
   </div>   
</div>	

```
   $('#wSelectAuthUser').w2field('list', {
	  name   : 'wSelectAuthUser', 
          url: "?getUserList=1",
          method  : 'POST', 
	  openOnFocus: true,
	  minLength  : 1,
	  recId      : 'id',
	  recText    : 'text'          
   }); 
   $('#popupnewauth').w2popup();
   
when i write in the  list the url is not called and there is no way to open the combo with the mouse.

Also using a static list es. 
var people = ['George Washington', 'John Adams', 'Thomas Jefferson', 'James Buchanan', 'James Madison',
    'Abraham Lincoln', 'James Monroe', 'Andrew Johnson', 'John Adams', 'Ulysses Grant', 'Andrew Jackson',
    'Rutherford Hayes', 'Martin Van Buren', 'James Garfield', 'William Harrison', 'Chester Arthur',
    'John Tyler', 'Grover Cleveland', 'James Polk', 'Benjamin Harrison', 'Zachary Taylor', 'Grover Cleveland',
    'Millard Fillmore', 'William McKinley', 'Franklin Pierce', 'Theodore Roosevelt', 'John Kennedy',
    'William Howard', 'Lyndon Johnson', 'Woodrow Wilson', 'Richard Nixon', 'Warren Harding', 'Gerald Ford',
    'Calvin Coolidge', 'James Carter', 'Herbert Hoover', 'Ronald Reagan', 'Franklin Roosevelt', 'George Bush',
    'Harry Truman', 'William Clinton', 'Dwight Eisenhower', 'George W. Bush', 'Barack Obama'];

  $('#wSelectAuthUser').w2field('list', {
	  name   : 'wSelectAuthUser', 
          items: people
   }); 
in the popup not work...

**Comment by vitmalina** [comment]
Can you please create a jsFiddle where you demonstrate the problem

**Comment by peruginia** [comment]
this is a very basic demo

https://jsfiddle.net/3m4pkrh6/3/

if you open popup the list dropdown will not work

**Comment by AlexKovynev** [comment]
Magic but it work with  function OpenPopup() {
var people = ['George Washington', 'John Adams', 'Thomas Jefferson', 'James Buchanan', 'James Madison',
'Abraham Lincoln', 'James Monroe', 'Andrew Johnson', 'John Adams', 'Ulysses Grant', 'Andrew Jackson',
'Rutherford Hayes', 'Martin Van Buren', 'James Garfield', 'William Harrison', 'Chester Arthur',
'John Tyler', 'Grover Cleveland', 'James Polk', 'Benjamin Harrison', 'Zachary Taylor', 'Grover Cleveland',
'Millard Fillmore', 'William McKinley', 'Franklin Pierce', 'Theodore Roosevelt', 'John Kennedy',
'William Howard', 'Lyndon Johnson', 'Woodrow Wilson', 'Richard Nixon', 'Warren Harding', 'Gerald Ford',
'Calvin Coolidge', 'James Carter', 'Herbert Hoover', 'Ronald Reagan', 'Franklin Roosevelt', 'George Bush',
'Harry Truman', 'William Clinton', 'Dwight Eisenhower', 'George W. Bush', 'Barack Obama'];
setTimeout(() => { $('input[type=list]#wSelectAuthUser').w2field('list', { items: people }) }, 1000)
$('#popupnewauth').w2popup();
}


This is important $('input[type=list]#wSelectAuthUser') cause it not work only by id:))

**Comment by vitmalina** [comment]
Here is working example https://jsfiddle.net/19a2jqme/2/

And please format your functions when you post. It is hard to read otherwise!
```
function OpenPopup() {
    var people = ['George Washington', 'John Adams', 'Thomas Jefferson', 'James Buchanan', 'James Madison',
        'Abraham Lincoln', 'James Monroe', 'Andrew Johnson', 'John Adams', 'Ulysses Grant', 'Andrew Jackson',
        'Rutherford Hayes', 'Martin Van Buren', 'James Garfield', 'William Harrison', 'Chester Arthur',
        'John Tyler', 'Grover Cleveland', 'James Polk', 'Benjamin Harrison', 'Zachary Taylor', 'Grover Cleveland',
        'Millard Fillmore', 'William McKinley', 'Franklin Pierce', 'Theodore Roosevelt', 'John Kennedy',
        'William Howard', 'Lyndon Johnson', 'Woodrow Wilson', 'Richard Nixon', 'Warren Harding', 'Gerald Ford',
        'Calvin Coolidge', 'James Carter', 'Herbert Hoover', 'Ronald Reagan', 'Franklin Roosevelt', 'George Bush',
        'Harry Truman', 'William Clinton', 'Dwight Eisenhower', 'George W. Bush', 'Barack Obama'];
    $('#popupnewauth').w2popup({ 
        async onOpen(event) {
            await event.complete;
            $('#w2ui-popup #wSelectAuthUser').w2field('list', {
                name: 'wSelectAuthUser',
                items: people,
                method: 'POST',
                openOnFocus: true,
                minLength: 1,
                recId: 'id',
                recText: 'text'
            });
        }
    });
}
```
