### ISSUE TITLE
problem in format function in w2field.js

### ISSUE THREAD

**Issue by peruginia** [vitmalina/w2ui#2279]
The online demo and if i don't change locale it works because group is equal at this.options.groupSymbol and the regExp is never called

i put a breakpoint in function format() at line 820 in w2field.js or at line 20970 in w2ui.js
   
in the console i have : 
   val = '20,000%'
   group = '.'
   this.options.groupSymbol = ','

the command :
      val.replace(new RegExp(group, 'g'), this.options.groupSymbol)

return
      ',,,,,,,' 

i have replaced with :
     val.replace('/' + group + '/g', this.options.groupSymbol)

and it return (corrected)
    '20,000%'

**Comment by AlexKovynev** [comment]
@peruginia you can suggest PR:)
