### ISSUE TITLE
Feature Request: download online data for drop down list

### ISSUE THREAD

**Issue by beza2000** [vitmalina/w2ui#2280]
The ability to download online data for drop down list (combo type) in ver.2.0.
Now it does not work  
`w2form.fields[some].options{ type:combo, url: some_url}`
or
```
$('input[type=combo]').w2field('combo', {
            url: 'autocomplete.pl',
          });
```

**Comment by vitmalina** [comment]
Yes, will implement. During the refactor it did not get converted.

**Comment by ratones** [comment]
Any updates on this?
I would like to create a set of Angular components for w2ui and this is a must for my application.

**Comment by yodes69** [comment]
Any estimate as to when this will be completed?
Thanks
