### ISSUE TITLE
Bug: need to specify items in form.fields[some].options

### ISSUE THREAD

**Issue by beza2000** [vitmalina/w2ui#2281]
**Short description**
An exception occurs if **items** are not specified in field when I create the **form**.

**What is current behavior**
I do not shure if it is a bug or not, but in ver.1.5 it worked without errors.
ver.1.5:
```
{
        field: 'user',
        type: 'combo',
        required: true
      },
```
But in version 1.5, the filling of my **items** occurred at the URL
ver.2.0 - Now I need to specify **items**:
```
{
        field: 'user',
        type: 'combo',
        options: {
          items: [],
        },
        required: true
      },
```
In ver.2.0  an exception occurs with the old code:
w2ui.js:18654 Uncaught TypeError: Cannot read properties of undefined (reading 'forEach')
    at w2form.setFieldValue (w2ui.js:18654:41)
    at w2form.refresh (w2ui.js:20087:18)
    at w2form.render (w2ui.js:20158:18)
    at $.fn.w2render (w2ui.js:21979:68)
    at event.onComplete (mail.js:316:53)
    at Dialog.trigger (w2ui.js:247:74)
    at w2event.finish (w2ui.js:44:28)
    at w2ui.js:3163:23

**What is desired behavior**
Do not require the existence of **items**

**Comment by vitmalina** [comment]
Fixed, now it will not produce an error
