### ISSUE TITLE
Blocking error in validating field with minLength

### ISSUE THREAD

**Issue by gregoriopellegrino** [vitmalina/w2ui#2284]
**Short description**
When trying to validate a form with a field in which the `minLength` is set to a number and `required` option is set to `true`, if the field is blank an error is generated in the console and validation stucks.

**What is current behavior**
Validation fails. In the developer console I see:

```
Uncaught TypeError: Cannot read properties of null (reading 'length')
```

**What is desired behavior**
Validation corrected, reporting the error, indicating that the field requires a minimum number of characters.

**Link to jsfidle/codepan with sample code**
https://jsfiddle.net/r8f07Ln5/

To reproduce click on `Validate`

**Comment by vitmalina** [comment]
This has been fixed. I just verified, it is working fine now
