### ISSUE TITLE
Record not sent to server for saving when w2utils.settings.dataType = 'HTTP'

### ISSUE THREAD

**Issue by gregoriopellegrino** [vitmalina/w2ui#2285]
**Short description**
I've set `w2utils.settings.dataType = 'HTTP'` and the requests sent to the server for saving the record have record's data empty: `https://server.com/proxy.php?cmd=save&recid=4000000&name=my-form&record=`

**What is current behavior**
Record data is empty.

**What is desired behavior**
Sending the record data.

**Link to jsfidle/codepan with sample code**
https://jsfiddle.net/bapu1ys0/

**Comment by gregoriopellegrino** [comment]
Upon investigating, I realized that `w2utils.clone(self.record)` returns an empty object.

**Comment by gregoriopellegrino** [comment]
Checking again now the url is: `https://autori.effata.it/new_proxy.php?cmd=save&recid=40010732&name=diritti-form&record=%5Bobject+Object%5D`

**Comment by gregoriopellegrino** [comment]
The problem seems in:
```
Object.keys(postParams).forEach(key => url.searchParams.append(key, postParams[key]))
```
Since it doesn't work with objects.

**Comment by gregoriopellegrino** [comment]
I think a similar approach is needed: https://github.com/knowledgecode/jquery-param

**Comment by AlexKovynev** [comment]
HTTPJSON also not working. Generate url like https://server.com/proxy.php?0=%7B&1=%22&2=r&3=e&4=q&5=u&6=e&7=s&8=t&9=%22&10=%3A&11=%7B&12=%22&13=c&14=m&15=d&16=%22&17=%3A&18=%22&19=s&20=a&21=v&22=e&23=%22&24=%2C&25=%22&26=r&27=e&28=c&29=i&30=d&31=%22&32=%3A&33=1&34=%2C&35=%22&36=n&37=a&38=m&39=e&40=%22&41=%3A&42=%22&43=f&44=o&45=r&46=m&47=%22&48=%2C&49=%22&50=r&51=e&52=c&53=o&54=r&55=d&56=%22&57=%3A&58=%7B&59=%22&60=t&61=e&62=s&63=t&64=%22&65=%3A&66=%22&67=f&68=o&69=o&70=%22&71=%7D&72=%7D&73=%7D :(
