### ISSUE TITLE
Some form examples from demos not work (click "save")

### ISSUE THREAD

**Issue by akpatternica** [vitmalina/w2ui#2288]
https://w2ui.com/web/demos/#/form/1
https://w2ui.com/web/demos/#/form/3

**Comment by vitmalina** [comment]
It took me some time to rework demos. But now they use es6 only, which is nice

**Comment by beza2000** [comment]
This is a strange solution to the problem. 
I see a BUG here - form.save() does not work. Incorrect conversion of the data for the request to form.save().
