### ISSUE TITLE
Grid & Edit: Form not showing selected grid row after re-creation

### ISSUE THREAD

**Issue by ejstembler** [vitmalina/w2ui#2302]
**Short description**

I'm implementing the [Grid & Edit](https://w2ui.com/web/demos/#/combo/2) example.  Additionally, I have a date range picker which retrieves data based on the date range, and recreates the grid + form with the data returned for the date range.

This works good the first time it is created.  The user clicks a row in the grid and the row data displays correctly in the form. 

When the user selects a new date range, and the new grid & form are created, the new data correctly displays in the grid. However, when the user clicks a row, nothing is displayed in the form. I can see the `this.get(sel[0])` has the correct data, but it never shows in the form.

I'm wondering if I need to clear something in w2ui if I re-create the grid and form?    Or, maybe something is getting disconnected from being re-created?

**What is current behavior**

Upon re-creation of the grid and edit form, the selected row is not displayed in the form fields.

**What is desired behavior**

The selected grid row should be displayed in the form fields

**Link to jsfidle/codepan with sample code**

https://codepen.io/ejstembler/pen/dyevajE

**Steps to reproduce or sample** 

![codepen](https://user-images.githubusercontent.com/45985338/190923818-49c10223-6485-407c-ba92-65c3c7a4cbec.gif)

**Comment by vitmalina** [comment]
You do not need to initialize layout/grid/form each time you update records. Here is the corrected codeped: https://codepen.io/vitmalina/pen/qBYXaMa

**Comment by ejstembler** [comment]
Thanks @vitmalina!
