### ISSUE TITLE
Searching all fields in grid: Uncaught TypeError

### ISSUE THREAD

**Issue by mike-seger** [vitmalina/w2ui#2306]
w2ui.js:2937 Uncaught TypeError: Cannot read properties of null (reading '0')
at w2ui.js:2937:58
at Array.map ()
at w2ui.js:2931:48
at Array.forEach ()
at w2ui.js:2923:34
at w2ui.js:648:45
at Array.forEach ()
at Query.each (w2ui.js:648:20)
at Utils.bindEvents (w2ui.js:2921:25)
at w2grid.refreshSearch (w2ui.js:15067:17)

The following example results in the error as soon as a search is done:
https://mike-seger.github.io/grid-experiments/w2ui/regression/001.html

The following example contains the fix and results in no error:
https://mike-seger.github.io/grid-experiments/w2ui/regression/001-fixed.html

Created this pull request:
https://github.com/vitmalina/w2ui/pull/2305

**Comment by vitmalina** [comment]
Fixed and merged
