### ISSUE TITLE
w2ui.grid on mobile show soft keyboard.

### ISSUE THREAD

**Issue by WenSheng-tw** [vitmalina/w2ui#2308]
I found a problem when I tested w2ui.grid on my mobile phone.
It always shows the soft keyboard when I touch the grid content.
Can I turn off the display of the software keyboard?

**Comment by vitmalina** [comment]
Please specify what modbile phone it was and what version of w2ui did you use?

I might have an idea what is going on. To capture grid focus state, there is a hidden input control that gets focus when grid is in focus. It might be triggering the soft keyboard. Need to investigate

**Comment by WenSheng-tw** [comment]
> Please specify what modbile phone it was and what version of w2ui did you use?
w2ui 2.0 last update.

> 
> I might have an idea what is going on. To capture grid focus state, there is a hidden input control that gets focus when grid is in focus. It might be triggering the soft keyboard. Need to investigate
I'm waiting for your replay, Thank you!
I view w2ui source code and only can search 'onTouchStart', no other information.

**Comment by WenSheng-tw** [comment]
I found a solution.
File w2grid.js
method: render(box)
line: 5471

`                            (w2utils.isIOS ? 'readonly' : '') +'></textarea>'+ // readonly needed on android not to open keyboard`

change to:

`                            'readonly' +'></textarea>'+ // readonly needed on android not to open keyboard`

**Comment by vitmalina** [comment]
Fixed, however can any one check if it is working fine on Android now. I do not own one.

**Comment by vitmalina** [comment]
Done. Can you test again?
