### ISSUE TITLE
Ошибка даты на русском

### ISSUE THREAD

**Issue by megellano** [vitmalina/w2ui#2329]
**Short description**
В русской локализации 31 декабря это СУББОТА
В английской 31 декабря это ВОСКРЕСЕНЬЕ

**What is current behavior**
Как испаравить

**What is desired behavior**
...

**Link to jsfidle/codepan with sample code**
...

**Steps to reproduce or sample** 
...

**Comment by AlexKovynev** [comment]
give a screenshots. Here https://w2ui.com/web/demos/#/fields/2 all correct.

**Comment by vitmalina** [comment]
По русски неделя начинается с понедельника по английски с воскресенья. И соответственно нарисованы дни недели, поэтому кажется что как будто ошибка но ее нету.

**Comment by vitmalina** [comment]
I found one bug related to date time saving in US. In November 6th was repeated twice in the calendar. It is fixed now. 

Since there is no other response to this issue, I am closing it.
