### ISSUE TITLE
during on grid reload , Cannot read properties of undefined (reading 'w2ui.expanded') 

### ISSUE THREAD

**Issue by beompyohong** [vitmalina/w2ui#2343]
**Short description**
A clear and concise description of the problem
the code is working v1.5 
but i got error as below in  v2.0 

"Cannot read properties of undefined (reading 'w2ui.expanded') " 

**What is current behavior**
...

**What is desired behavior**
...

**Link to jsfidle/codepan with sample code**
...

**Steps to reproduce or sample** 
...
![error](https://user-images.githubusercontent.com/80137279/206141172-3f8fd460-ee35-4549-b8b7-6c479b673268.PNG)

the grid reload screen 
![grid_reload](https://user-images.githubusercontent.com/80137279/206141463-e98a443e-c164-4e64-be15-e56fe07c674c.PNG)

**Comment by vitmalina** [comment]
I think I fixed it. However, to be fully sure, can you please create a jsfiddle page with the error. It is hard to find the line, as you are using compiled w2ui.js, and the lines do not match in my version.

Anyway, I hope it is fixed.

**Comment by beompyohong** [comment]
Hi vitamlina, 

Thank you very much for your reply. 

below is the jsfiddle example on v2.0

It's working on v1.5 of grid , but still got error on v2.0 on "**grid.columns**"

Pls click button "change columns" on jsfiddle
 
https://jsfiddle.net/m3ws9154/6/

**Comment by beompyohong** [comment]
Hello Vitali,

Thank you very much for your reply.


below is the jsfiddle example on v2.0

It's working on v1.5 of grid , but still got error on v2.0 on "
*grid.columns*"

Pls click button "change columns" on jsfiddle

https://jsfiddle.net/m3ws9154/6/

2022년 12월 11일 (일) 오전 11:40, Vitali Malinouski ***@***.***>님이
작성:

**Comment by vitmalina** [comment]
Fixed. Your js fiddle will work with latest files: here is the link, https://jsfiddle.net/o093nqyk/2/

**Comment by beompyohong** [comment]
Hello Vitali,

Great!!    w2ui is Great one.

Actually, I didn't think you reply to this request.

Thank you very much.



2022년 12월 12일 (월) 오전 1:57, Vitali Malinouski ***@***.***>님이
작성:
