### ISSUE TITLE
w2form v2.0 - problems with error message processing when loading data from a remote source

### ISSUE THREAD

**Issue by heady-yar** [vitmalina/w2ui#2345]
Sending an error message from the server

**{status: 'error',  message: 'Error message...'}**

does not display an error message in the web browser.

An attempt to process the error message on its own using the onLoad event does not lead to success, since the event.detail.date attribute contains the Response object instead of data.
The w2form.js code (lines 988 to 1010) does not contain support for processing the response in the format shown above.

**Comment by vitmalina** [comment]
I think you need to send 
```
{ error: true, message: 'Error message...' }
```
But you were right that with onLoad event you could not change it. I have fixed that. Now, first of all, `event.detail.data` will have right object with data returned from the server. You can modify it and set `error = true` and then it will display error message.
