### ISSUE TITLE
w2form v2.0 - Generation of the change event in the absence of a change in the field value by the user, when a user enters a value in a field, attributes value.current and value.previous have the same value

### ISSUE THREAD

**Issue by heady-yar** [vitmalina/w2ui#2350]
w2form v2.0 - generates a change event for 
all of its fields when displayed in the 2layout panel 
or w2popup window (perhaps in the refresh() function).
The event object has the following values
```
event.detail.value.current: ""
event.detail.value.previous: undefined
```
or 
```
event.detail.value.current: ""
event.detail.value.previous: null
```
When generating the Change event on user input in the field, attributes event.detail.value.current and event.detail.value.previous have the same value, which is also an error.

**Comment by vitmalina** [comment]
Can you provide a PR with a fix?

**Comment by heady-yar** [comment]
> Can you provide a PR with a fix?

I've never done this before and I'm a small expert in JavaScript, but I can give it a try. How fast should this work be done?
