### ISSUE TITLE
A few issues when drag-resizing panels

### ISSUE THREAD

**Issue by blitz-research** [vitmalina/w2ui#2353]
First, when you're in the middle of resizing a panel, nearby text occasionally gets selected then deselected. You can reproduce the issue with any of the demos, eg:

https://w2ui.com/web/demos/#/layout/8

If you grab the divider between 'left' and 'main' and drag it towards 'left', the 'left' text occasionally gets selected/deselected in kind of a random way. If you drag out of bounds of the layout, all sorts of text on the page starts get selected.

The previous split.js lib I used didn't have this problem so I had a quick peek at the code and it sets some 'selectstart' event 
listener to NOOP - looks like the author had similar problems 'coz there's comment in there "Disable selection. Disable!"

Here's a link to that code in case it's useful:
https://github.com/nathancahill/split/blob/f9d7b974d24287864792347edd2c76581f117a22/packages/splitjs/src/split.js#L534

The second problem I'm having is that you can cometimes 'let go' of the divider but it'll still follow the mouse around. Very hard
to reproduce but it seems to happen most often if you try to quickly 'click-drag-release' on a divider. The mouse pointer briefly
turns into a 'warning' icon when this happens so it may be the mouse has 'left' the divider by the time the drag happens?

**Comment by blitz-research** [comment]
OK, possible solution: I tried simply adding an 'event.preventDefault()' at the top of the 4 'mousedown' handlers for the resizers, and it seems to have fixed both problems for me.

**Comment by vitmalina** [comment]
Can you please send a pull request with the fix?

**Comment by blitz-research** [comment]
I'm kind of new to web development so I was a bit unsure of what I needed to do but I can give it a go.

Apart from any changes in 'src', I'm guessing I also need to commit the newly generated output in 'dist' after running 'npx gulp'?

Anything else?

**Comment by blitz-research** [comment]
OK, PR is up, I commited the changes to 'dist' too which makes the PR look a lot busier than it is, please let me know if that's wrong.

**Comment by vitmalina** [comment]
It is enough to just commit changes in `/src` folder
