### ISSUE TITLE
w2alert() button focus

### ISSUE THREAD

**Issue by WenSheng-tw** [vitmalina/w2ui#2357]
The w2alert('Error', 'Notice') open dialog but not focus on [ok] of button.
I'm must modify it to:
w2alert('Error', 'Notice').then(function(e){
  $('#w2ui-popup .w2ui-popup-buttons .w2ui-btn:last-child').focus();
});

Can you help me to change it to the first button or the last button to get the focus and set it to the default value?

**Comment by vitmalina** [comment]
Actually, no focus on any button is an intended behavior. Though in case of an alert, there is only one button in case of a confirm or prompt there could be multiple buttons and it is wrong to set focus on any, as user could accidentally click enter or space and trigger unintended button. User can use esc key to close dialog or tab key to navigate through the buttons. If you want to focus a specific button, you are welcome to do what you are doing.
