### ISSUE TITLE
[BUG] w2ui grid: load more spinner not resized to full width - NOTE: easy to fix!

### ISSUE THREAD

**Issue by H-Lo** [vitmalina/w2ui#2381]
**Short description**
Load more spinner is not resized to full width.

w2ui grid version: **2.0.nightly.2023-01-16**

**Steps to reproduce or sample** 
Open any grid that has to load more records and see a spinner.

<hr/>

The problem is "display:block" is used for table row TR to show the spinner:

```
<tr id="grid_GRID_NAME_rec_more" style="display: block;">
	<td colspan="2000" class="w2ui-load-more">
		<div>
			<div style="width: 20px; height: 20px;" class="w2ui-spinner"></div>
		</div>
	</td>
</tr>
```

The right way to show it would be "<b>display:table-row;</b>"

The bug can be fixed by adding this CSS line:

`tr#grid_GRID_NAME_rec_more { display:table-row !important; }`

But it would be better to have it fixed rather than fixing it outside w2ui grid especially because **!important** modifier is not a good way to go.

**Comment by vitmalina** [comment]
PR request with a fix merged
