### ISSUE TITLE
 Uncaught RangeError: Value , out of range for Number.prototype.toLocaleString

### ISSUE THREAD

**Issue by rtco2020** [vitmalina/w2ui#2385]
update google chrome to Version 110.0.5481.100 (Official Build) (64-bit),
when show w2ui popup form, list not working and get the following error in console : 
w2ui.min.js?query=string:2 Uncaught RangeError: Value , out of range for Number.prototype.toLocaleString options property useGrouping
    at Number.toLocaleString

**Comment by tpdietz** [comment]
I have this same issue and it happens in Chrome but NOT Firefox.  I noticed that it seems to occur in formatNumber():

return parseFloat(e).toLocaleString(w2utils.settings.locale, s)

The problem looks to be that the 's' options object contains the useGrouping property.  In Firefox, it is a valid value (true), whereas, in Chrome, the value is a comma, ','.

Is anyone working on this?

@rtco2020 did you ever get a response or a fix for this?

**Comment by tpdietz** [comment]
BTW, I found the problem.  The w2ui code incorrectly sets the useGrouping option from the format() function via the call to formatNumber().  w2ui sets it to options.groupSymbol, which is a character (',') and not one of the valid options as stated in the documentation.

I haven't the time to figure out how to make the fix here, but if you want to contact me, see my email in my profile.

**Comment by vitmalina** [comment]
I think it is fixed here https://github.com/vitmalina/w2ui/issues/2340
