### ISSUE TITLE
w2ui form via get and drop list via get error in 2.0 works in 1.5

### ISSUE THREAD

**Issue by ooo4321** [vitmalina/w2ui#2410]
Hello, thanks and great work with 2.0 I am trying to migrate from 1.5 and I have a question : 

**1. I have a normal w2ui form where records are sent via PHP GET in this JSON format : 

{"status":"success",
"record":
{"field1":"something",
"country":{"id":4324,"text":"Something"}
}}**

2. The problem I am getting in 2.0 is with the country field in a form defined like this : 

{ field: 'country', type: 'list', required: true,
    options: {
        url: 'https://api.something.com/get',
        method: 'GET',
        showAll: false,
    }
},

3. This exact setup worked in 1.5 but in 2.0 for the dropdown list when I get the results from the server I get this error : 

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'forEach')
    at w2field.findItemIndex (w2ui-2.0.min.js:449:10718)
    at w2field.refresh (w2ui-2.0.min.js:420:262)
    at w2form.setFieldValue (w2ui-2.0.min.js:392:19262)
    at w2form.refresh (w2ui-2.0.min.js:417:2727)
    at w2ui-2.0.min.js:392:27605

Is there a change in the format mentioned at 1 ?

**Comment by vitmalina** [comment]
Can you provide the json file your server returns?

**Comment by ooo4321** [comment]
well the server response for the form is like this : 

{"status":"success",
"record":
{"field1":"something",
"country":{"id":4324,"text":"Something"}
}}

The php code is a function that returns a JSON formated array like this : 

                $record = [
                    'field1'=>'something',
                     'country'=>['id'=>4324,'text'=>'Something']
                ];
            }
        }

        return (["status"=>"success","record"=>$record]);

Field1 for example gets populated correctly in the form field1 with value something but the drop down gives the error ...

**Comment by ooo4321** [comment]
In 1.5 the JSON bellow used to work for  https://something.com/api/form but in 2.0 doesn't ... 

{"status":"success",
"record":
{"field1":"something",
"country":{"id":4324,"text":"Something"}
}}

**Comment by ooo4321** [comment]
switching to combo the field parses the JSON ... so it seems not to work only on list ...

**Comment by ooo4321** [comment]
found it ...

**Comment by vitmalina** [comment]
You are right, the `records` should be array. But you have `records` (without `s`) and it is an object

**Comment by vitmalina** [comment]
Please close the issue if it is all resolved
