### ISSUE TITLE
Close w2Confirm with Enter

### ISSUE THREAD

**Issue by blitz-research** [vitmalina/w2ui#2425]
Hi, is there some way to close a w2Confirm dialog using the Enter key to select 'Ok'? It looks like 'Esc' already selects 'Cancel', but Enter doesn't do anything and you need to manually click 'Ok'.

See the w2Confirm example here:

https://w2ui.com/web/demos/#/popup/7

**Comment by WenSheng-tw** [comment]
The method can solution your question!!

let popupBtnFocus=function(){
	$('#w2ui-popup .w2ui-popup-buttons .w2ui-btn:last-child').focus();
};
w2confirm('Delete it?', 'Note!!').then(function(){popupBtnFocus();});
