### ISSUE TITLE
the grid with advanced search can't remove saved search item

### ISSUE THREAD

**Issue by khuatbaha** [vitmalina/w2ui#2442]
**Short description**
With version 2.0, the grid with advanced search can't remove saved search item

**What is current behavior**
can't remove saved search items

**What is desired behavior**
user can remove saved search

**Link to jsfidle/codepan with sample code**
the code in the demo: [https://w2ui.com/web/demos/#/grid/16](https://w2ui.com/web/demos/#/grid/16)

**Steps to reproduce or sample** 
1. open the demo from [https://w2ui.com/web/demos/#/grid/16](https://w2ui.com/web/demos/#/grid/16)
2. create Advanced Search with las name value is "doe" then click search
3. click "Save" to save search 
4. remove search condition by click "X" button
5. click "Search All Fields" to get saved searches items => the list items don't have the remove button

**Comment by alexkuznetsov** [comment]
I have researched the problem and can create PR

**Comment by khuatbaha** [comment]
@alexkuznetsov thank for your PR. With this typo fix, this issue is resolved.

**Comment by alexkuznetsov** [comment]
@khuatbaha you are welcome 👍

**Comment by alexkuznetsov** [comment]
@vitmalina Can you review my PRs?
