### ISSUE TITLE
Inline editing, add extra field

### ISSUE THREAD

**Issue by neoedmund** [vitmalina/w2ui#2445]
**Describe the problem your feature will solve.**
My records has a key field named `xid` which is `int` type. I'd like to send this `xid` when saving the inline editing.

**Describe the solution you'd like**
I found event `onSave` of grid, but don't know how to do the job correctly. please help.

**Describe alternatives you've considered**
Can I using xid to replace builtin recid ? How?

**Additional context**

**Comment by neoedmund** [comment]
I just added `recid` into json with value of `xid`.  works for some extent.

**Comment by alexkuznetsov** [comment]
In the configuration for a grid component you can assign any property from row as 'recid' - for example 'xid'. 
`recid` is just a record identifier, so, if 'xid' can be treat as identifier - just do it.

Example:

```
let grid = new w2grid({
   recid: 'xid',
   ...rest config
})
```
