### ISSUE TITLE
How to do infinity scroll load more records programmatic ?

### ISSUE THREAD

**Issue by neoedmund** [vitmalina/w2ui#2446]
**Describe the problem your feature will solve.**
Showing images according to the records loaded in the grid below the grid. scroll to the end of the images, need to load more records programmatic.

**Describe the solution you'd like**
a method like grid.loadMore(100)

**Describe alternatives you've considered**
Idk

**Additional context**
Thanks.

**Comment by alexkuznetsov** [comment]
@neoedmund 

Have you tried https://w2ui.com/web/docs/2.0/w2grid.skip ?

This may help you with your task.

**Comment by neoedmund** [comment]
Thank you , I wil try it later.

**Comment by neoedmund** [comment]
`skip()` will remove previous loaded records, how can I keep them?

**Comment by alexkuznetsov** [comment]
@neoedmund 
well, you can cache them before the action.

you can combine theese steps for achive desired result:
   - manually load data  from backend with our  limit / offset
   - add loaded data to the grid, e.g. append rows one by one
   - scroll the view to the first loaded row using https://w2ui.com/web/docs/2.0/w2grid.scrollIntoView

**Comment by alexkuznetsov** [comment]
@neoedmund 

Befor all, try also just scroll the view to the last row using https://w2ui.com/web/docs/2.0/w2grid.scrollIntoView
I not checked, but, in my opiniton, this sholuld trigger load records and loaded records whould be appended to the current rows
