### ISSUE TITLE
Column auto resize since 1.5 => 2.0

### ISSUE THREAD

**Issue by TheFast99** [vitmalina/w2ui#2450]
Hi

Since I upgraded 1.5 to 2.0, the auto resize when i double click on the column resizer seems to not work.
The autoResize property on column class is still at true.
Is it just me and i'm missing something since the upgrade or an actual bug ?

Thanks

**Comment by vitmalina** [comment]
Did you try with the lasted built in the /dist folder in master branch? I think the was a fix for it already

**Comment by TheFast99** [comment]
Just try it, it works.
Just a little thing, if i have an icon before the text, the resizer seems to not take the icon size into account, just the text to resize.
But not very important for me.

Thank you.

**Comment by vitmalina** [comment]
The issue with icon might be due to it is not loaded in time it is sampled for width. It should work with icons. I think if you preload icon in some hidden div, then it should work

**Comment by TheFast99** [comment]
yeah thx, i added icons after request.
