### ISSUE TITLE
Landing page description of size/deps is incorrect/incomplete.

### ISSUE THREAD

**Issue by nexushoratio** [vitmalina/w2ui#2466]
**Short description**
The landing page makes two claims:

1. Only 115KB
2. No External Dependencies

However, it is not clear how that number is calculated.
```
$ ls -lh
total 660K
-rw-r--r-- 1 nexus nexus 441K Nov  6 17:26 w2ui-2.0.es6.min.js
-rw-r--r-- 1 nexus nexus 214K Nov  6 17:26 w2ui-2.0.min.css
```
```
$ gzip -9 * ; ls -lh
total 204K
-rw-r--r-- 1 nexus nexus 111K Nov  6 17:26 w2ui-2.0.es6.min.js.gz
-rw-r--r-- 1 nexus nexus  92K Nov  6 17:26 w2ui-2.0.min.css.gz
```
```
$ xz -9 * ; ls -lh
total 180K
-rw-r--r-- 1 nexus nexus 94K Nov  6 17:26 w2ui-2.0.es6.min.js.xz
-rw-r--r-- 1 nexus nexus 81K Nov  6 17:26 w2ui-2.0.min.css.xz
```
```
$ brotli -9j * ; ls -lh
total 188K
-rw-r--r-- 1 nexus nexus 99K Nov  6 17:26 w2ui-2.0.es6.min.js.br
-rw-r--r-- 1 nexus nexus 86K Nov  6 17:26 w2ui-2.0.min.css.br
```

**What is desired behavior**
Update the page to say one of the below:
- Details on how the number is calculated
- The complete library and required CSS is only 204KB (minified and compressed)
- There is a single external dependency in the form of the required CSS (another 92KB, minified and compressed)

**Comment by vitmalina** [comment]
You are right. The size calculation did not include CSS, which is technically needed. I think it would be fair to include CSS size too. Website is updated.

https://rawgit.com/vitmalina/w2ui/master/dist/w2ui.es6.min.js - 120kb
https://rawgit.com/vitmalina/w2ui/master/dist/w2ui.min.css - 93kb
