### ISSUE TITLE
Select/Unselect Records Through Checkbox Only, Grid Inline Editable trigger

### ISSUE THREAD

**Issue by elfwine** [vitmalina/w2ui#2468]
**Request 1) Select/Unselect Record Through Checkbox only**
Given with this [grid example](https://w2ui.com/web/demos/#/grid/10), row/s can be selected and unselected through checkbox or any click on row/cell.
Is there any way that any click on row/cell won't select/deselect row selection/s?

**Request 2) Grid's Cell Inline Editable Trigger**
Inline editable is trigger by double-click, there are some request that the editable cell can be triggered by just one-click. 
I can come-up with the solution of calling onEditField in onClick event, but it would be nice if there's a built in settings for this.

**Comment by vitmalina** [comment]
add this event to the grid
```js
    onClick(event) {
       	if (event.detail?.column != null) {
        	event.preventDefault()
        }
	  },
```
