### ISSUE TITLE
List with remote source only works once

### ISSUE THREAD

**Issue by alex77h** [vitmalina/w2ui#2475]
Seems like picking one item of a list with remote source only works once. Clicking again to pick onother item creates an error in js console.
For example look at https://w2ui.com/web/demos/#/fields/6 choose one Name of the List, then try to pick onother one.
Tested in Edge and Firefox.

**Comment by dv1x3r** [comment]
Hi @alex77h , dropdown fixes were applied today, so now it should work as expected.

**Comment by alex77h** [comment]
seems to work now, thanks!
