### ISSUE TITLE
How to use w2ui-2.0 in react?

### ISSUE THREAD

**Issue by yang5355** [vitmalina/w2ui#2480]
![Snipaste_2023-12-25_15-30-28](https://github.com/vitmalina/w2ui/assets/59274878/35ba1f96-9620-4159-ac05-c2da3590302d)
![image](https://github.com/vitmalina/w2ui/assets/59274878/cebd4075-b810-461c-b015-425c4cf6b05c)

**How do I write this component if I want to return it?**

please help me

**Comment by yang5355** [comment]
Error message:
![image](https://github.com/vitmalina/w2ui/assets/59274878/4861bf65-432d-4a45-9132-2f161aed0538)

**Comment by vitmalina** [comment]
@yang5355, w2ui is framework agnostic, and was not developed for any particular framework. Latest version has no dependencies. But to use it with React, you will have to write your own React component that implements grid (and other controls). I have done it in the past for Vue and Lit, but it has been a while ago. Basic approach is to write component that receives grid config file as json attribute and from there on, grid would do the rest. Good luck.
