### ISSUE TITLE
Clicking in a grid without records generates script error

### ISSUE THREAD

**Issue by NoelSMartin** [vitmalina/w2ui#2482]
**Short description**
Clicking in a grid without records generates script error

**What is current behavior**
Clicking anywhere in the grid with no errors generates this error

**What is desired behavior**
no error

**Link to jsfidle/codepan with sample code**
[JSFiddle](https://jsfiddle.net/xjtn6akw/)

**Steps to reproduce or sample** 
...
![image](https://github.com/vitmalina/w2ui/assets/79912980/489c4a2a-d377-46fa-925d-2a0b2b493edb)

**Comment by vitmalina** [comment]
I tried in your JSFilddle and I do not see any error. Can you check. It might have been fixed

**Comment by NoelSMartin** [comment]
Yes seems good now. Thank you.
