### ISSUE TITLE
Deselecting a row with a mouse click stopped working. 

### ISSUE THREAD

**Issue by jankrnavek** [vitmalina/w2ui#2488]
There is a regression with the new night version, w2ui 2.0.x (nightly) (1/16/2024, 10:44:40 AM).
Deselecting a row on grid with a mouse click stopped working.   

WIth holding CTRL deselecting working.

It looks like some issue on  onSelect  event...

**Comment by vitmalina** [comment]
It is working in demos, here for example: https://w2ui.com/web/demos/#/grid/1

**Comment by jankrnavek** [comment]
There is still a problem with the event w2grid.onSelect.
This event is not called when a row is deselected with only a mouse click.
With both mouse click and SHIFT together, w2grid.onSelect is called correctly.

You can check it out here:
https://w2ui.com/web/demos/#/grid/10

**Comment by jankrnavek** [comment]
There is still a problem with the event w2grid.onSelect.
This event is not called when a row is deselected with only a mouse click.
With both mouse click and SHIFT together, w2grid.onSelect is called
correctly.

You can check it out here:
https://w2ui.com/web/demos/#/grid/10





S pozdravem / Best regards,

Ing. Jan Krňávek
---
mobil: +420 603 563 516
email: ***@***.***
skype: hanz.krnavek (Jan Krňávek, Brno, Czech Republic)
web: www.mydjango.cz
datová schránka: 4scyx8e
kancelář: Lazaretní 4298/11a, 615 00 Brno-Židenice

=======================================================================
vývoj webových aplikací v Django, Python a Vue.js
vývoj mobilních aplikací pro Android
=======================================================================
Zachovávejte prosím historii zprávy. / Please keep the message history.


út 6. 2. 2024 v 21:03 odesílatel Vitali Malinouski ***@***.***>
napsal:
