### ISSUE TITLE
Weird ENTER key behavior in Inline Edit with selectType = Cell

### ISSUE THREAD

**Issue by mkaramizrakli** [vitmalina/w2ui#2495]
### Discussed in https://github.com/vitmalina/w2ui/discussions/2491

<div type='discussions-op-text'>

<sup>Originally posted by **mkaramizrakli** February  8, 2024</sup>
Hi all, not sure this is the right place to ask this, but I have a problem with w2grid in Inline Edit mode, when selectType is set to "CELL".
I want to enter to edit mode using the ENTER key. It works for the first time, but when I move to next column using arrow keys and click ENTER again, the previous column is being edited. 

Here is the link for the fiddle: [https://jsfiddle.net/mkaramizrakli/grqzuLhj/11/](https://jsfiddle.net/mkaramizrakli/grqzuLhj/11/)

Thanks in advance!

</div>

**Comment by vitmalina** [comment]
I noticed that you use older version. If you can use lastest from dist folder it seems to work. Here is the link with example https://jsfiddle.net/9wuvc1bd/8/. Though here, I used es6 version, but with jquery version it should be all working too. Just use the files from `/dist` folder

**Comment by mkaramizrakli** [comment]
Thank you very much! It's solved as you suggested.
