### ISSUE TITLE
Как в форме в полях вывести Label большой длины, что бы не срезалось наименование поля 

### ISSUE THREAD

**Issue by IgorLelyakov** [vitmalina/w2ui#2502]
Как вывести Label большей длины, что бы не срезалось наименование поля 
![image](https://github.com/vitmalina/w2ui/assets/79909671/5241022d-0584-4db2-9fc3-060569a88e86)

**Comment by vitmalina** [comment]
You can do it with variable `span` properties. Here is an example. https://w2ui.com/web/demos/#/form/12. If this is not sufficient for you, you may consider custom HTML form (not generated html).

**Comment by IgorLelyakov** [comment]
Большое спасибо, разобрался со span, скажите, а что значит -"consider custom HTML form (not generated html)"? 
Можете на примере пояснить?
