### ISSUE TITLE
Form in a popup

### ISSUE THREAD

**Issue by GInHell** [vitmalina/w2ui#2507]
Form in a popup:

When using the "formHTML" property, if there is a field with type textarea, other fields that are below this field and buttons do not appear on the form.
[https://jsfiddle.net/inhell/354kutfg/1/](url)

![image](https://github.com/vitmalina/w2ui/assets/151744576/fde292fe-7ea1-41f6-941d-5805692ebc2f)

Here, if the field type is replaced from textarea to input
https://jsfiddle.net/inhell/ogj38tqf/

![image](https://github.com/vitmalina/w2ui/assets/151744576/e04fc67f-c422-4559-bf47-b3ddaa1ac668)

**Comment by mpf82** [comment]
Not a w2ui issue. Textareas are not self-closing tags, please use ``<textarea name="comment"></textarea>`` 
(instead of ``<textarea name="comment" />``).

https://jsfiddle.net/1Ldx7hwn/

![grafik](https://github.com/vitmalina/w2ui/assets/10152404/1985e4bf-94fb-4ae2-b1a2-6b3529b864e8)

**Comment by mpf82** [comment]
@GInHell No need to apologize. By the way, the w2form "auto templates" can help you to avoid such issues, by generating the HTML for you based on the field type, see https://w2ui.com/web/demos/#/form/2
