### ISSUE TITLE
Popup window from another popup window with forms

### ISSUE THREAD

**Issue by GInHell** [vitmalina/w2ui#2514]
Hello, great team!
Tell me please, how to open a new form in a popup window from the current one popup correctly ?
If I open a new popup window, my window is empty without fields and buttons...

https://jsfiddle.net/7L86ng2b/

**Comment by vitmalina** [comment]
You can just use current popup and output content inside of it. If you must open another popup, then close previous. Here is the code that works https://jsfiddle.net/fnbwuLrt/2/

By the way, you cannot open more then one popup at a time. If you need more then one, then you can use messages as here: https://w2ui.com/web/demos/#/popup/5
