### ISSUE TITLE
Экранная форма не масштабируется на весь экран при открытие окна на весь экран 

### ISSUE THREAD

**Issue by IgorLelyakov** [vitmalina/w2ui#2515]
Добрый день!
При открытии окна на весь экран (нажать символ прямоугольник в правом верхнем углу окна) не масштабируется на весь экран форма. 
Пример кода прилагаю.
Подскажите пожалуйста как скорректировать.
![image](https://github.com/vitmalina/w2ui/assets/79909671/7ff9f080-bbe6-4da6-99c3-ec1638aa3442)
[forma.txt](https://github.com/vitmalina/w2ui/files/15199096/forma.txt)

**Comment by vitmalina** [comment]
You either need to set container width to 100% or user a layout. Here is an example https://w2ui.com/web/demos/#/combo/8

**Comment by IgorLelyakov** [comment]
Установил ширину контейнера на 100% - не помогло
