### ISSUE TITLE
Inline Editing -> Record editable: false has no effect

### ISSUE THREAD

**Issue by ziehm** [vitmalina/w2ui#2527]
**Short description**
Refer to demo: https://w2ui.com/web/demos/#/grid/21

Record 9 has editable: false but can be edited anyway. The setting has no effect.

**What is current behavior**
Record 9 has editable: false but can be edited anyway. The setting has no effect.

**What is desired behavior**
All records expect record 9 can be inline edited.

**Link to jsfidle/codepan with sample code**
https://w2ui.com/web/demos/#/grid/21

**Comment by vitmalina** [comment]
It actually needs to be inside `w2ui` object... `records[..., { recid: 1, w2ui: { editable: false }}]` I fixed the example
