### ISSUE TITLE
V2.0 w2field does not support validate

### ISSUE THREAD

**Issue by introspection3** [vitmalina/w2ui#2539]
**Short description**
A clear and concise description of the problem

**What is current behavior**
 v2.0 not support
**What is desired behavior**
support 

**Link to jsfidle/codepan with sample code**
 
![image](https://github.com/vitmalina/w2ui/assets/12368358/beeaf352-8862-478e-8c81-d64b465f7dcf)

**Steps to reproduce or sample** 
...

**Comment by vitmalina** [comment]
you should attach to onChange event for the field (it is an input field anyway) and do validation there.
