### ISSUE TITLE
 v2.0 grid toolbar toolbarAdd,toolbarEdit,toolbarSave etc. tooltips don't support w2utils.locale

### ISSUE THREAD

**Issue by introspection3** [vitmalina/w2ui#2540]
v2.0 grid toolbar toolbarAdd,toolbarEdti,toolbarSave etc. tooltips don't support  w2utils.locale

**Comment by vinhpt2** [comment]
Also the field label of type='checkbox' in w2form DO NOT support w2utils.locale.

**Comment by vitmalina** [comment]
Can you create JS fiddle were the issue is demonstrated, please.

**Comment by vinhpt2** [comment]
About

> Can you create JS fiddle were the issue is demonstrated, please.

About checkbox please go to https://nut.applicationjs.com/index.html

Thanks!

**Comment by introspection3** [comment]
> Can you create JS fiddle were the issue is demonstrated, please.

sorry,we can't use it as our network forbbiden. but this bug is very  obvious
