### ISSUE TITLE
Make w2ui compatible with CommonJS code

### ISSUE THREAD

**Issue by sankargorthi** [vitmalina/w2ui#266]
It'd be great if the `w2ui` components get added in a modular, CommonJS pattern to be universally used. The current pattern assumes a global `w2ui` instance that map to a global jQuery object.

`w2ui`, `w2obj` and `w2utils` should be exposed on the root object, whatever it is (node, module, export, etc) instead of assuming it is being run in a global context.

**Comment by mordonez-me** [comment]
Does this work? I am trying to use it like the example and it keeps saying "jQuery is not defined", source: /Users/mordonez/repositories/clever_chat/node_modules/requirejs/bin/r.js (392)

**Comment by giladno** [comment]
https://github.com/vitmalina/w2ui/pull/1437
