### ISSUE TITLE
Sort on Date or number fields, it is not working correctly

### ISSUE THREAD

**Issue by avacondios** [vitmalina/w2ui#270]
When you sort a date or number columns, it is sorting as a string,

**Comment by rsaungc** [comment]
Sorry to add new item to this issue. 

How about numbers with link?  For example,

<a href="other_page.php?q=1">1</a>
<a href="other_page.php?q=2">2</a>
<a href="other_page.php?q=3">3</a>
<a href="other_page.php?q=14">14</a>

If I sort that column,  "14" will be between "1" and "2"

it won't solve correctly for these links.

**Comment by mpf82** [comment]
@rsaungc You could probably write your own sort function, based on PR #1504
