### ISSUE TITLE
White space when resizing layout

### ISSUE THREAD

**Issue by wedoodevelopment** [vitmalina/w2ui#272]
Hi Vitali,

First of all I wanna say that I like the w2ui library. I wanna use it for one of my next projects, so I was playing around with the layout manager and I wanted to use the layout manager in fullheight as you mention here: https://github.com/vitmalina/w2ui/issues/105. When I resized that layout (for example 1024x768), some white space (probably the scrollbar sizes) popup on the right and the bottom (click on image else you can't see it). That only happend in IE and Firefox, not in Chrome. Hope you can fix it. The code I've used is below.

![layout](https://f.cloud.github.com/assets/5625696/1285281/88c814ea-2fa5-11e3-81df-d8f578c59955.png)

``` html
<html>
<head>
<link rel="stylesheet" type="text/css" media="screen" href="http://w2ui.com/src/w2ui-1.2.min.css" />
<script type="text/javascript" src="http://code.jquery.com/jquery-1.10.1.min.js"></script>
<script type="text/javascript" src="http://w2ui.com/src/w2ui-1.2.min.js"></script>
<script>
$(function () {
    $('#layout').w2layout(
    {
        name: 'appLayout',
        padding: 5,
        panels: [
            { type: 'top', size: 100, resizable: true, style:'background-color:#CCC;' },
            { type: 'left', size: 250, resizable: true, style:'background-color:#CCC;' },
            { type: 'main', style:'background-color:#FFF;' },
            { type: 'right', size: 150, resizable: true, style:'background-color:#CCC;' },
            { type: 'bottom', size: 60, resizable: true, style:'background-color:#CCC;' }
        ]
    });
})
</script>
<body>
    <div id="layout" style="position:absolute; top:0px; left:0px; bottom:0px; right:0px;"></div>
</body>
</html>
```

**Comment by ImAbhishekTomar** [comment]
I am having same with the W2Grid.
