### ISSUE TITLE
How to add/change/remove a toolbar or tabs of a layout panel (after render)?

### ISSUE THREAD

**Issue by wedoodevelopment** [vitmalina/w2ui#274]
I expected the option to change the toolbar or tabs of a layout actually here:
http://w2ui.com/web/docs/w2layout.set

**Comment by MarioDelgadoSr** [comment]
This is a fidldle showing how to dynamically add a toolbar to a layout: http://jsfiddle.net/UberMario/91pd3wc4/

The only way I got it to work was to first have any empty object assigned to the toolbar property of the layout.
