### ISSUE TITLE
Row grouping

### ISSUE THREAD

**Issue by vitmalina** [vitmalina/w2ui#280]
How about row grouping?
Row grouping is very much needed in many commercial applications. Row grouping can be used for sub-totals as well as for many other purposes. I found a good example of row grouping at http://mleibman.github.io/Slic....
w2ui grid seems to have the best rendering engine.
It would be great if w2ui grid provided the row grouping functionality. Can you consider the row grouping functionality in your development plan?
Thanks,
Hoon

**Comment by Kirua88** [comment]
Hi,

Is row grouping will coming soon or it will never be release ?

**Comment by mrg2001** [comment]
Row grouping is supported in current master version. In the record, you can define object children and those will be grouped. 
```js
records: [
{ recid: 1, title: "some", w2ui: { children: [{ recid: 2, title: "other" }] }
...
]
```

**Comment by mrg2001** [comment]
Combining with colspan should allow you to achieve this. Colspan example is
``js
records: [
{ recid: 1, title: "some", w2ui: { colspan: { field: 2 } }
...
]
``

**Comment by alexey-vasyunin** [comment]
@mrg2001  I mean this: http://ui-grid.info/docs/#/tutorial/209_grouping

**Comment by mrg2001** [comment]
Yes, this can be done with 
```js
records: [
{ recid: 1, title: "some", w2ui: { children: [{ recid: 2, title: "other" }] }
...
]
```
You can nest children as well. You will need 1.5

**Comment by alexey-vasyunin** [comment]
No, it's not grouping plain data.  For example, load plain records http://w2ui.com/web/demos/data/list.json into grid, and try to build grid and subgrids (and sub-sub-sub...) by 1 or 2 or 3 attributes.  In angularjs ui-grid you just add into the columns group properties (for example):
`{ field: 'email', caption: 'Email', size: '40%', sortable: true, **grouping: {groupPriority: 0},** },`
and grid build tree automaticaly, you don't need to build data-tree (parent-children) in records.

It's very helpful when you need build tree (grouping) from database query (select * from table) and very helpful when you need regrouping on fly.
