### ISSUE TITLE
Nested layout issues

### ISSUE THREAD

**Issue by vitmalina** [vitmalina/w2ui#294]
I think I found a bug in 1.3. When defining a layout within a layout and putting a grid in the inner layout you run into an undefined error. I did a small jsfiddle to demonstrate the problem. http://jsfiddle.net/powerondude/L8UAP/

**Comment by mpf82** [comment]
It seems the issue no longer exists in 1.5 and can be closed.

Updated fiddle: http://jsfiddle.net/L8UAP/7/
