### ISSUE TITLE
Sub Grid scroll bar will disappear after expand some rows.

### ISSUE THREAD

**Issue by cooperwu** [vitmalina/w2ui#298]
you can visit above page, which is based on the demo 
http://w2ui.com/web/demos/#!grid/grid-7
Sub grid,

on the page, http://jsfiddle.net/Ybb9P/1/
if you expanded the first 3 rows, the scroll bar of 1st and 2nd will disappear.

**Comment by mpf82** [comment]
Since sub grids are no longer officially supported in 1.5 (see [updated fiddle](http://jsfiddle.net/Ybb9P/23/) with link to current sources) and the [grid-7](http://w2ui.com/web/demos/#!grid/grid-7) demo now points to tree-like grids, this issue can probably be closed
