### ISSUE TITLE
How to use namespace?

### ISSUE THREAD

**Issue by avacondios** [vitmalina/w2ui#302]
Hi, 
your work is excellent. I want to move all the global variables that you use (w2ui,.w2....) under of specific namespace. In the projects that I am participating, it is not permitting to use global variables without a specific namespace. Can you guide me, how to do that  ?

BR/Antonis

**Comment by vitmalina** [comment]
With es6 modules file, now there is no globals at all. You have to import them. See `/dist/w2ui.es6.js`. For backward compatibility, it will register globals as it was.
