### ISSUE TITLE
Wrong row range in grid footer

### ISSUE THREAD

**Issue by rolfn** [vitmalina/w2ui#308]
The footer information "x-y of z" seems to be wrong. The example http://w2ui.com/web/demos/#!grid/grid-13 shows 13 rows but the footer says "1-14 of 18" (14 rows).

**Comment by mpf82** [comment]
The example moved to http://w2ui.com/web/demos/#!grid/grid-15 (Simple Search)

It's correctly showing "1-13 of 18"

The issue seems to be fixed. Closing.
