### ISSUE TITLE
Render function for grid columns resets changed cell values

### ISSUE THREAD

**Issue by agzamovr** [vitmalina/w2ui#367]
If render function used for grid column then after editing cell value are resetted back to old value. This issues could be shown if for column fname on demo page http://w2ui.com/web/demos/#!grid/grid-21 we specify render function as follows:

``` JavaScript
render: function (record, index, column_index) {
              return '<b>'+ record.fname + '</b>';
       }
```

**Comment by remmel** [comment]
It's looks like the data modified is not store in the same place/array anymore in w2ui 1.5:

```javascript
render: function (record, index, column_index) {
  var fname = record.fname;
  if (record.w2ui && record.w2ui.changes && typeof record.w2ui.changes['fname'] != 'undefined') {
    fname = record.w2ui.changes['fname'];
  }
  return '<b>'+ fname + '</b>';
}
```
