### ISSUE TITLE
Failed to load resource: the server responded with a status of 405 (Method Not Allowed) 

### ISSUE THREAD

**Issue by kiruja** [vitmalina/w2ui#379]
The w2ui Grid is giving below error when I try to pull my json which is in the same server , but I am using HTTPS.

Failed to load resource: the server responded with a status of 405 (Method Not Allowed) 

URLs of JSON and WEB application are in the same server.

COuld you please suggest.?

**Comment by greatlake5** [comment]
I use w2ui grid to load data from  Aweb api service

**Comment by vitmalina** [comment]
You should set w2utils.settings.RESTfull = true any where before you use grid. Please refer to documentation as it is all covered there.

**Comment by zzxBear** [comment]
Failed to load resource: the server responded with a status of 404 (Not Found)
