### ISSUE TITLE
 fill a grid from an array

### ISSUE THREAD

**Issue by chalchis** [vitmalina/w2ui#383]
hello
I'm trying to
insert based columns returned in a JSON array
in the grid empty

this my code

```
      jQuery('#main').w2grid({
        name: 'grid_asignaciones', 
        msgRefresh: 'cargando datos...',
        //url: '/recurso/dorecurso/lista_roles',
        header: 'Listado de cuentas',
        show: {
            header: true,
            toolbar: true,
            toolbarSearch: false,
            toolbarColumns: false,
            lineNumbers: true,
            selectColumn: true,
            expandColumn: false,
            footer: true
        }, 
        recordsPerPage: 50,
        fixedBody : true, 
        fixedRecord : true,
        multiSelect: true,                   
        columns: [              
            //{ field: 'recid', caption: 'key', size: '50px', resizable: false },
            { field: 'camporelleno', caption: '', size: '100%', resizable: false },
        ],              
        onLoad: function(target, eventData)
        { 
            var serverJSON = jQuery.parseJSON(eventData.xhr.responseText);              

            if(serverJSON.status_respuesta === 'false')
            {
                dialogo.dialogo_error_recurso(serverJSON.mensaje_respuesta);
            }  
        }
    });
```

//image
http://imagizer.imageshack.us/v2/800x600q90/850/u8l1.png

![grid_empty](https://f.cloud.github.com/assets/2206648/1915294/6aef8b34-7d65-11e3-8e70-2a2655657b4a.png)

Is it possible to implement something?

```
        var arr = [];

            for (var c =0; c<5; c++)
            {
                 var obj = {
                            field: 'data_'+c,
                            caption: 'tex_'+c,
                            size: '30%'
                        };

                arr.push(obj);
            }

            console.log(arr);

    w2ui['grid_asignaciones'].addColumn.apply(w2ui['grid_asignaciones'], arr);
```

course and try and not work for me:-S     

or I have to make a FOR

example:
     for (var i = 0; i < json.listado_respuesta.length; i++)
      {
        w2ui['grid_asignaciones'].addColumn({ field: json.listado_respuesta[i].columReal, caption:   json.listado_respuesta[i].descampo, size: '30%' });
       }

regards

**Comment by anuptilak** [comment]
Hi Vitmalina,
I'm trying to add all columns dynamically and tried same method as given above but its not working out. 
` var columnsName = getSelectedColumns();
                         //   columnsName = columnsName.reverse();
                            console.log(columnsName);
								//w2ui['grid'].load('detail-report/type:getDetailReport;'+postData);
								try{w2ui['grid'].destroy();}catch(e){}
								
								 $('#grid').w2grid({ 
       								 name: 'grid', 
								        show: {
								            lineNumbers: true,
								            footer: true
								        },
       									columns:[],
								        
   									 });  
								// w2ui['grid'].addColumn(columnsName);
								w2ui['grid'].addColumn(columnsName);
								// w2ui['grid'].refresh()
							//	 w2ui['grid'].load('detail-report/type:getDetailReport;'+postData);
								
							});	

				        function getSelectedColumns()
				        {
				        	var Id=$("#showCoulmns").data('selected');
				        	var returnColumnName = [];
				        	$.each(Id,function(index,value){

				        		/*returnColumnName.push({field:value.id,
				        							   caption:value.text,
				        							  })*/
				        			var obj = {field:value.id,
				        					   caption:value.text,

				        			};
				        		returnColumnName.push(obj);
					        	//returnColumnName +=' {field: "'+value.id+'", caption: "'+value.text+'", size: 100  },';

					        });

					        //returnColumnName +="]";
					        //console.log(returnColumnName);
					        return returnColumnName;
				        }`
I'm doing something wrong?

**Comment by mrg2001** [comment]
Please create jsFiddle

**Comment by anuptilak** [comment]
Hi,

Issues sorted. I guess size is also compulsory parameter. Can we have
updated documentation saying which are compulsory parameters and which are
optional? Function definition says it need object or array but doesn't say
which are compulsory and which are optional. If we have these also, we
don't have to wonder around it.
