### ISSUE TITLE
Suggest Grid Event for returning Record Count

### ISSUE THREAD

**Issue by anandbohra** [vitmalina/w2ui#385]
Hi I have created a Service method which populate data  for Grid & at the same time assign Total record in static variable.

Now second function is called to get value from static variable but problem is since its ajax call, many a time it gets called before first method & hence actual grid records are not know.

will you suggest, how do I get grid record count & show it on label out side your grid.

Grid is populated based on ASPX page jquery sliders & hence its dynamic grid (Grid with dynamic where condition to populate)

your reply will be highly appreciated.

**Comment by jackryu** [comment]
Hello I am try to load data in w2ui grid using ASMX service but its not working.

> please share "w2ui['MyGrid'].load('../DiamSearchService.asmx/GetFilteredGrid');"  "GetFilteredGrid" service code this is help full for me.

issue on Get : #1561
