### ISSUE TITLE
w2form() method can't handle 'selected' option.

### ISSUE THREAD

**Issue by emadurandal** [vitmalina/w2ui#41]
Hello,
I found that w2form() method can't handle 'selected' option as following...

``` javascript
$('#form').w2form({
    name     : 'form',
    url      : 'server/post',
    fields: [
        { name: 'field_enum', type: 'enum', required: true},
            options: {
                items: [{id:0, text:'Adams, John'}, {id:1, text:'Johnson, Peter'}, {id:2, text:'Lewis, Frank'}, {id:3, text:'Cruz, Steve'}, {id:4, text:'Donnun, Nick'}],
                selected: [{id:1, text:'Johnson, Peter'}]  // <- not working!
            }
        }
    ],
    }
});
```

Instead, I tried w2field method. but, this method can't handle 'required' option.

``` javascript
$('input[name="field_enum"]').w2field({
        type: 'enum',
        items: [{id:0, text:'Adams, John'}, {id:1, text:'Johnson, Peter'}, {id:2, text:'Lewis, Frank'}, {id:3, text:'Cruz, Steve'}, {id:4, text:'Donnun, Nick'}],
        selected: [{id:1, text:'Johnson, Peter'}], // <- working!
        required: true // <- not working!
    }
);
```

Would you be able to check this problem?

(Sorry for my broken English. I'm not native english writer.)

**Comment by uvijaybhaskar** [comment]
Hi Vitmalina,

This is vijay, I am using options selected inside searches like following,but it is not working please help me.
<script>
var numbers =['1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17'];
------ W2UI Grid Code ------
 searches: [
            { field: 'recid', caption: 'ID ', type: 'int' },
            { field: 'lname', caption: 'Last Name', type: 'text' },
            { field: 'fname', caption: 'First Name', type: 'text' },
            { field: 'email', caption: 'Email', type: 'list', options: { items: people,selected : {'5'}}}, //--> Not Working
            { field: 'sdate', caption: 'Start Date', type: 'date' }
        ]
</script>

Thanks,
Vijay

**Comment by weshprod** [comment]
Not working for me either
I'm using 1.4.3

Is there any workaround or fix to make it work ?

**Comment by vitmalina** [comment]
Please provide a jsFiddle as an example.

**Comment by weshprod** [comment]
Hello,


Thanks for your reply.
I actually found a way around by setting the record node with the selected item to force it


Best regards


PS : By the way : great framework !







................................................................................................................



Le Responsable
Olivier SIVRIERE


................................................................................................................














WESH PROD Studio

1800
 Avenue André Lasquin

74700 Sallanches
tel : +33(0)4.50.47.55.36
os@weshprod.com - www.weshprod.com


....................................................................................
................................................................................................................





Le 7 déc. 2015 à 18:19, Vitali Malinouski <notifications@github.com> a écrit :


Please provide a jsFiddle as an example. 
—
Reply to this email directly or 
view it on GitHub.
