### ISSUE TITLE
Single cell style

### ISSUE THREAD

**Issue by felixakiragreen** [vitmalina/w2ui#426]
Currently rows can have highlights & text color and cells can be formatted either as a date, currency, &c — but is there any easy way of highlighting / stylizing single cells?

**Comment by nbsynch** [comment]
This looks like it no longer works in the current 1.5rc1.  Is this something that will get added back in?

**Comment by mpf82** [comment]
@nbsynch please look at https://github.com/vitmalina/w2ui/issues/1387 and https://github.com/vitmalina/w2ui/issues/1351#issuecomment-255384351

Cheers =)

**Comment by nbsynch** [comment]
@mpf82 

Thanks for your quick reply, it works now.
