### ISSUE TITLE
Grid fixed column

### ISSUE THREAD

**Issue by ghost** [vitmalina/w2ui#461]
Is there any possibility to fix first or last column?
It will be good for line numbers, or action buttons, when table is too wide
STH like this http://www.jeasyui.com/tutorial/datagrid/datagrid5_demo.html

**Comment by jroddrof** [comment]
Hi,

I know this is a pretty old chain, but has there been any progress on the column freezing?

Thanks.

**Comment by mpf82** [comment]
@jroddrof frozen/fixed columns are implemented in 1.5, simply add `frozen: true` to the column properties.

Example: https://jsfiddle.net/e9ggtox9/4/

**Comment by jroddrof** [comment]
Just to make sure, is 1.5 stable?

**Comment by mrg2001** [comment]
yes
