### ISSUE TITLE
Request: Replace inline-javascript and inline-css by eventbinds and classes

### ISSUE THREAD

**Issue by vandernorth** [vitmalina/w2ui#492]
We're developing an application and would love to apply a strict Content-Security-Policy (see http://content-security-policy.com/) which means the browser wont allow any inline styling ( ```style="display:none" ``` etc.) or inline javascript ( ```<td onlick="w2ui[grid].click()" > ``` etc.).

Instead you should use ```class="hidden"``` and something like ```$('.w2ui-grid').on('click', 'td', function() {});```

Any change you're willing to implement this in the (near-) future?

**Comment by psiinon** [comment]
Any update on the chances of at least having an option not to use inline scripts?
I've got a project I'd like to use w2ui on, but inline scripts will be a blocker for that :(

**Comment by vitmalina** [comment]
@pslinon thank you for you post. I agree that inline CSS and JS should be avoided. But I do not think it would be right to ban it. It is up to developer how to use it. Internally w2ui has all important css in separate files, but there are still some style tags.

**Comment by psiinon** [comment]
I'm not asking you to ban it, just provide an option for w2ui not to use inline javascript. I'm working on a project where security is very important, and we've decided that inline javascript is too dangerous and will be blocked by our CSP. This means we now cant use w2ui.
