### ISSUE TITLE
w2ui 1.3.2 doesn't work with FontAwesome 4.0

### ISSUE THREAD

**Issue by digulla** [vitmalina/w2ui#508]
There are two problems:
1. FontAwesome 4.0 uses the `<i>` element so `<span>` no longer works.
2. For some reason the `font-family` from `w2ui-reset` takes precedence over the CSS from FA.

Workarounds:

I commented out the line in w2ui-1.3.2.css:

```
.w2ui-reset * {
  color: default;
  /*font-family: Verdana, Arial;*/
```

And I replaced the two `<span>` elements next to `w2ui-tb-image` in w2ui-1.3.2.js.

Afterwards, this works in a toolbar:

```
{ type: 'menu', id: 'addMenu', icon: 'fa fa-plus', caption: 'Add ...', items: [ ...
```

**Comment by guillaumeguerin** [comment]
Problem still exists in w2ui 1.5.
I also put the w2ui CSS before the font awesome CSS, still doesn't work.

I made a simple jsfiddle : https://jsfiddle.net/Shal/0hcctstc/

**Comment by mpf82** [comment]
add the ``fa`` class, too:

https://jsfiddle.net/0hcctstc/1/
