### ISSUE TITLE
Internet Explorer (All versions 8+) does not allow the user to use the scroll bar with an enum or list

### ISSUE THREAD

**Issue by jon-statemn** [vitmalina/w2ui#562]
The problem is related to the monitor method which is trying to detect the position using the offset.  When the user clicks on the scrollbar the monitor method is fired which effectively resets the enum/list and closes it.

The scrollbar stays open and is usable when the content of the monitor method is commented out.  The application appears to run as expected after this change.

**Comment by Dazorn96** [comment]
Still having on IE 11.
Resolved with this fix:
- Removed `helper.find('input').on('blur')` on line **17188**
- Added this event to the **helper** after line **17208**:
`helper.on('blur', function (event) {
                $(obj.el).css('outline', 'none');
                $(this).find('input').val('');
                obj.refresh();
                $(obj.el).triggerHandler('blur');
                if (event.stopPropagation) event.stopPropagation(); else event.cancelBubble = true;
                if (pholder != null) $(obj.el).attr('placeholder', pholder);
            });`
