### ISSUE TITLE
w2ui Demos aren't working

### ISSUE THREAD

**Issue by funkytaco** [vitmalina/w2ui#578]
Demos aren't working today. They worked yesterday (about 17 hours ago when I looked at them). Happening on the ones I tested at random, i.e.
http://w2ui.com/web/demos/#!sidebar/sidebar-1

See Javascript console.

Uncaught SyntaxError: Unexpected token <

**Comment by adilek** [comment]
It seems the same issue with new demos. It shows Uncaught SyntaxError: Unexpected token ;

**Comment by funkytaco** [comment]
The demos are working for me http://w2ui.com/web/demos/#!sidebar/sidebar-1

**Comment by vitmalina** [comment]
Working for me too

**Comment by adilek** [comment]
Sorry, I was testing with corrupted js files.

On Saturday, July 25, 2015, Vitali Malinouski <notifications@github.com>
wrote:

> Working for me too
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vitmalina/w2ui/issues/578#issuecomment-124862477>.
>


-- 
Adil Aliyev
Mobile: +99450 244 07 07
PGP: 0x17A71712
Website: http://adil.az

*Please don`t print this e-mail unless you really need to!*
