### ISSUE TITLE
Custom column filters below headers

### ISSUE THREAD

**Issue by balaka4** [vitmalina/w2ui#583]
Not sure if this is doable now, but I couldn't find anything in the documentation to allow for me to do so.

Is there any way to be able to insert custom column filter components right below the headers (e.g. select, multiselect, text input, etc.)?

Attached is an mockup of what I am looking for.

![mockup_filter - list 08](https://cloud.githubusercontent.com/assets/7883168/3637998/34a6f55a-102f-11e4-8f05-a8661be973d0.png)

**Comment by bwl21** [comment]
What a pity ... Is there a fundamental problem? It is what the regular Excel user expects.

**Comment by chalchis** [comment]
hey
you can apply your own search filter
I did something ejm


![screen_filtros](https://cloud.githubusercontent.com/assets/2206648/11738016/805ae762-9fa4-11e5-9ca6-c456b9f3852e.gif)

**Comment by bwl21** [comment]
Yes, I know, and I did this. But the style as proposed by balaka4 would be a bit more user friendly.

nevethless. you seem not to use the builtin search. could you please tell a bit more how you implemented this?

Thanks.

**Comment by chalchis** [comment]
Yes of course
use a library item to apply a popover
http://sandywalker.github.io/webui-popover/demo/

to send the data to the server and the library w2ui
it can be filled did doing a reload:

```javascript
.
.
.
.
w2ui['gridaspirantes'].url = '/aspirantes/modaspirantes_lista_filtrado';
w2ui['gridaspirantes'].postData['keycamp_grid'] = jQuery('#tx_camp_sel').val(); 
w2ui['gridaspirantes'].postData['filtros_grid'] = JSON.stringify(array_filtros);                                   
w2ui['gridaspirantes'].reload();
```
php is my back end

```php
.
.
.
.

$resultadoJson = array(
											"status_respuesta" 	=> "true",	
											"status"			=> "success",//parametro del grid									
		                					"mensaje_respuesta" => "correcto.",
											"total" 			=> $total_aspirantes,//parametro del grid																		
											"header" 			=> "Resultado de la busqueda (".$total_aspirantes.")",//parametro del grid
											"records" 			=> $datos_aspirantes//parametro del grid									
										);
						
						echo json_encode($resultadoJson);
```
