### ISSUE TITLE
Problems with extended Array prototype

### ISSUE THREAD

**Issue by MarcelCremer** [vitmalina/w2ui#592]
w2ui uses for...in loops for iteration over arrays. That's bad, if the prototype is extended with other methods like in Ext.JS.

The for...in loops should be replaced by a safer way, than iteration over the array prototype.

**Comment by mkhahani** [comment]
I acknowledge the issue. [Here's an example in StackOverflow](http://stackoverflow.com/questions/8665446/where-does-proto-get-added-to-array). It says:

> ...
> for (var foo in obj) is actually a way of looping Objects - not Arrays. it works on arrays as well, because they are kind of like Objects as I mentioned.

> but it's the wrong thing to do, especially when you work with a prototypical framework or you are not sure of all the code you run and how it has affected the prototype chain. if you mean to use what is known as an 'associative array' in other languages, simply use an Object.

> In mootools, you can use Object.each(function(value, key) {}); to iterate them.

> Or: in your loop check to see if the item hasOwnProperty:

```javascript
for (var data in dataArray) {
    if (dataArray.hasOwnProperty(data)) {
        // avoids working with prototype.
    }
}
```

**Comment by vitmalina** [comment]
This issue was fixed about a year ago. All iterations over arrays where done properly (without for in). If you see a place where it is not the case, please report that specific place. I am closing this issue.

**Comment by mkhahani** [comment]
w2forms => validate() => line 356:
```
if (showErrors) for (var e in eventData.errors) {
...
```

**Comment by vitmalina** [comment]
Just accepted a pull request that fixes first item you metioned, see https://github.com/vitmalina/w2ui/pull/1037/files. 

Also provided a fix for other issue mentioned.

**Comment by mkhahani** [comment]
Thanks for the fix.
