### ISSUE TITLE
Feature request: datetime type support

### ISSUE THREAD

**Issue by itrukw** [vitmalina/w2ui#613]
Hello,
I often phase the issue in the databases I need to deal with that I do have a date & time in one timestamp field as a string (e.g. 20140806101000). I wrote my own render function to display it nicely and internationally correct in the Grid (e.g. 06.08.2014 10:10:00) but I face the next issue in the search area now. I would like to search in between two datetime areas. As I understand w2ui supports currently just date or time.  Therefore a string based datetime type (YYYYMMDDhhmmss) would be nice as well a combined selection in the search somehow like in those samples:
  
![datetimepicker](https://cloud.githubusercontent.com/assets/7671720/3824320/af21e7e0-1d45-11e4-844b-f736144deb55.png)

Maybe you do have a suggestion for a workaround. It would be for example nice to be able to define the possibilities of a search type. It would work for me if I could define a in between for the text type in the search. 
Thanks!

**Comment by hansgru** [comment]
Any news on this ? Especially for Grids it is required to have only one column.

Thank you.

**Comment by aadrian** [comment]
+1

**Comment by mpf82** [comment]
Implemented in 1.5, issue can be closed.

**Comment by aadrian** [comment]
When will be 1.5 released?

**Comment by mpf82** [comment]
> When will be 1.5 released?

Sometime this year (2016), eventually:

> Guys, I promise to release 1.5 this summer. ([source](#1278))

But you can already use 1.5, it's pretty stable. Just use the files from the w2ui master repository.

**Comment by aadrian** [comment]
> But you can already use 1.5, it's pretty stable. 

They're not present in a bower or npm (or other) repository to manage them automatically :).
