### ISSUE TITLE
[REQ] Slider Component

### ISSUE THREAD

**Issue by amanu** [vitmalina/w2ui#66]
a slider is quite usable as a form component since it's much easier for the user to just drag and quickly change values instead of typing them. 
an example: http://dev.sencha.com/deploy/ext-3.3.1/examples/slider/slider-field.html

if the drag handle is rendered a little bigger, than it's very helpful on touch devices too.

jQuery UI also seems to have a nice one: http://jqueryui.com/slider/ but is really a very heavy component.
Even if it can do ranges: http://jqueryui.com/slider/#range  it's missing a "drag" on the range: this would allow to use it for **time interval selections** (one of the most used cases for range selections) :(

regards.

**Comment by gpetrov** [comment]
Slider will be really nice it is a shame that you decided not to implement it. Even in HTML5 there is a build-in one. Any support for that?

**Comment by aadrian** [comment]
+1

**Comment by hansgru** [comment]
The slider is really an important component, as it's more user friendly for many combinations than plain numerical fields that need complicated validation.

**Comment by Tooa** [comment]
+1

**Comment by vitmalina** [comment]
Since no further response, closing the issue.

**Comment by user1713952** [comment]
Hi, I am also interested in having sliders! I am building a scientific application for which it is very useful. Any chance we can get that implemented? I am willing to help implementing it if you give me directions. Thanks
