### ISSUE TITLE
Minified version of Javascript shows syntax errors in eclipse

### ISSUE THREAD

**Issue by m-kumaran** [vitmalina/w2ui#676]
Hi

First of all thank you for this awesome library.
Just wanted to highlight this low priority issue, so that this library would be looking clean in eclipse IDE.
The eclipse default javascript validator  shows 44 syntax errors in a minified version (1.4.1) of w2ui js file.

For time being, I have ignored it my project.  Would it be possible to fix these syntax errors?

I have even tried the nightly version (1.5) and it has 38 syntax errors.

Thanks in advance.

Cheers
Kumaran

**Comment by mpf82** [comment]
Closing issue: the current code shows no eslint errors
