### ISSUE TITLE
Uncaught exception in Grid view (when trying to reorder records)

### ISSUE THREAD

**Issue by Altynbek** [vitmalina/w2ui#679]
I've found a problem in your demo when I was looking for a suitable grid view control.
When I tried to reorder rows in grid I`ve got errors which you can see in attached screenshot :
![reordering rows error](https://cloud.githubusercontent.com/assets/3014574/4403825/10002650-44a9-11e4-8b1b-4ffd0e6949a4.png)
Errors occured in this controll:
http://w2ui.com/web/demos/#!grid/grid-26

You can reproduce these errors by doing the next steps (tested on Google Chrome browser 37.0.2062.124 m):
1) Press left mouse button on the row you want to reorder and then release it.
2) Try to move selected rows
3) Press any key to stop reordering (In this case the selection will not disappear)
4)  Open browser console (developer tools) and you will see the error details

**Comment by mpf82** [comment]
I can't reproduce this in 1.5

This issue can probably be closed, unless someone creates a fiddle with the current 1.5 sources to demonstrate that the issue still exists.

**Comment by mpf82** [comment]
Closing this issue: missing reproducer, no response, cannot reproduce.
