### ISSUE TITLE
grid dblClick, event return recid

### ISSUE THREAD

**Issue by Bastiani** [vitmalina/w2ui#684]
Hi, the grid dblClick event return recid, onClick return event object correct.
v1.4.2
![event_bug](https://cloud.githubusercontent.com/assets/9096756/4569352/95caee4c-4f48-11e4-9eb9-cd72bf9d7479.jpg)

**Comment by quagliarellamichel** [comment]
I solved it like this

onDblClick: function(event) {
    w2ui.grid.select(event.detail.recid);
    EditRow();
}
