### ISSUE TITLE
Grid: editable list issue

### ISSUE THREAD

**Issue by MrNikosia** [vitmalina/w2ui#689]
Hey Vitali,

I encountered a new issue with the grid.

But first i like to understand your vision on drop-down lists in grids.
The value of the dropdown field doesn't seem to be a simple id, but rather an object={id:...,text:...}.
This seems to be the case for setting & getting.
However when populating the grid, i set the field-value to an id integer instead of the {id:...,text....}
This seems to work as well, but is that the correct way???
And is there a mode where getting and setting works with pure id's instead of objects?
(so the text gets looked up dynamically from the source (items))

Fyi: i don't use the url to set and get the grid records, i use my own ajax mechanism,
(which loads multiple grids and forms simultaneously)
and i use grid.add for setting and grid.records for getting data. 

When i want to save the grid, i convert the list field value from object to its id like field=field.id

The problem that i have is when i add a new blank row and want to select somthing from the list there is a js error, it is below in the screenshot.
I altered your code to include a check if oldvalue===null to make it work.

I think the reason it fails is because of the way i add a new record, 
first i create it in the table, so it has an id, and after it is loaded into the grid with grid.add,
now the dropdownlist has a value of null instead of an object with {id:null:text:''}, so that's where w2ui gives an error unless i change the code as illustrated below!

![image](https://cloud.githubusercontent.com/assets/8783911/4650809/d123b656-5496-11e4-8f97-efa7bafc7815.png)

![image](https://cloud.githubusercontent.com/assets/8783911/4655198/2843355a-54c0-11e4-9bd3-623a8789c989.png)

**Comment by ermanoj** [comment]
Hi 
how to add cascading dropdown column in w2grid.
mean when i select country than get state data and bind in ddl state than city data
