### ISSUE TITLE
form demo not working

### ISSUE THREAD

**Issue by zcxkkk** [vitmalina/w2ui#702]
http://w2ui.com/web/demo/form
in this page,
form demo not working,  
  field:  Multi Select
not working in chrome 31
not working in firefox 32.0
not working in IE 10, IE8

**Comment by weshprod** [comment]
Selected items are not showing with enum type
{ field: 'field_enum', type: 'enum', required: true, 
                            options: { items: ['Adams, John', 'Johnson, Peter', 'Lewis, Frank', 'Cruz, Steve', 'Donnun, Nick'], selected:[{id:0,text:"Adams, John"}] } }

Am I missing something ?

**Comment by vitmalina** [comment]
I saw your comment on #41, No need to post it twice :).

Just a though, if it is a form, you should not be using selected for the field, but rather setting record object to desired value. 
```
form.record['field_enum'] = [{id:0,text:"Adams, John"}];
```

Or possibly just setting (assuming items on the drop down are not dynamicly loaded)

```
form.record['field_enum'] = 0;
```

I bet this will do the trick.

**Comment by daggetlover** [comment]
I am trying a multiselect droplist in a form in-line and cannot seem to get it to populate. Example;
			fields: [
				{ field: 'groupname', type: 'text', required: true },
				{ field: 'groupdesc', type: 'text', required: true },
				{ field: 'assign', type: 'enum', items: assetList }
			],
When I click I see the telltale blue outline around the text field but no droplist. If I try the selected data as above and I do see the selected data but no droplist to pick from.

Any thoughts?

**Comment by daggetlover** [comment]
Multiselect droplist;  How do I change the items in the droplist dynamically?

**Comment by mrg2001** [comment]
If you use a form, you can update items array for the field, and then call form.refresh().
