### ISSUE TITLE
w2gid: custom recid field not recognized if records defined 

### ISSUE THREAD

**Issue by chsymann** [vitmalina/w2ui#707]
I get the "ERROR: Cannot add records without recid. (obj: .." when I'm initializing the w2grid like follows:

``` javascript
$(function () {
    $('#grid').w2grid({
        name: 'grid',
        recid: 'myid',
        header: 'List of Names',
        columns: [
            { field: 'fname', caption: 'First Name', size: '30%' },
            { field: 'lname', caption: 'Last Name', size: '30%' },
            { field: 'email', caption: 'Email', size: '40%' },
            { field: 'sdate', caption: 'Start Date', size: '120px' }
        ],
        records: [
            { myid: 1, fname: "Peter", lname: "Jeremia", email: 'peter@mail.com', sdate: '2/1/2010' },
            { myid: 2, fname: "Bruce", lname: "Wilkerson", email: 'bruce@mail.com', sdate: '6/1/2010' },
            { myid: 3, fname: "John", lname: "McAlister", email: 'john@mail.com', sdate: '1/16/2010' },
            { myid: 4, fname: "Ravi", lname: "Zacharies", email: 'ravi@mail.com', sdate: '3/13/2007' },
            { myid: 5, fname: "William", lname: "Dembski", email: 'will@mail.com', sdate: '9/30/2011' },
            { myid: 6, fname: "David", lname: "Peterson", email: 'david@mail.com', sdate: '4/5/2010' }
        ]
    });
});
```

seems like the grid is not checking for a custom defined recid in this case. I see the problem in w2grid.js near this comment:

``` javascript
// check if there are records without recid
```

**Comment by jackryu** [comment]
Hello i have facing same issue so i need to add below code.
or this issue is permanently fixed in another update.
 
/```
/ check if there are records without recid
    if (records) for (var r = 0; r < records.length; r++) {
        if (method.recid && typeof records[r].recid == 'undefined') records[r].recid = records[r][method.recid];
        if (records[r].recid == null || typeof records[r].recid == 'undefined') {
             console.log('ERROR: Cannot add records without recid. (obj: '+ object.name +')');
             return;
        }
        object.records[r] = $.extend(true, {}, records[r]);
    }
```
