### ISSUE TITLE
Expanding row in grid does not work correct in Master branch

### ISSUE THREAD

**Issue by Snylten** [vitmalina/w2ui#711]
Expanding a row in a grid makes the grid look very strange. The code is:

```js
onExpand: function (event) {
   $('#'+ event.box_id).css({ margin: '0px', padding: '0px', width: '100%' }).animate({ height: '105px' }, 100);
   setTimeout(function () {
      $('#'+ event.box_id).load('process_grid.php', {"recid":event.recid, "cmd":"get-record" });
      w2ui.grid_comp_users.resize();
   }, 300);
},
```

In the expanding area the left column is filled with "+", that belongs to the row below the expanded area.

This error does not exists in the 1.4.x. I downloaded a Master branch from 10:th of October, and the error did not exists in that branch version.

I also get an error message in the console when rendering the grid: ReferenceError: event is not defined. Looking in the code w2ui.js 1089:

```js
function active (new_w2ui_name) {
        if (new_w2ui_name == null) return w2ui_name;
        var obj = w2ui[new_w2ui_name];
        if (obj && obj.focus) {
            if (obj.focus.call(obj, event) === false) return false; <<-- The error
        }
        w2ui_name = new_w2ui_name;
        return true;
    }
```

**Comment by mrg2001** [comment]
Sub-grids were rewritten. There were too many problems with current approach and now it is different in 1.5.x, See https://github.com/vitmalina/w2ui/blob/master/demos/examples/grid-7.html
