### ISSUE TITLE
Error counting total records with summary records

### ISSUE THREAD

**Issue by natxocc** [vitmalina/w2ui#733]
When using summary records and infinite scroll, when you reach to query next 100 records, there is a popup message telling a difference from total records from grid and total records returned from server.

This causes to inicial offset and return to first row again. There is no possible to use infinite scroll with summary records using php server.

To check this you can add a summary record in runtime when user php server and see that there is difference in total records from grid to real.
![totalrecords](https://cloud.githubusercontent.com/assets/1172351/5116755/315b09b2-704d-11e4-85fb-e15b771e830f.jpg)

**Comment by dalmatele** [comment]
I think we have a problem with this function:
- If my server has a lot of records (about 1 million) and my request has some filters, so I must process data to get the total (this work takes a lot of time to finish) ==> Our web page will be slow ==> I think we should support one more feature is: we should add a flag to let datagrid knows if we have more page to get, do not only base on total param.
Ex: if has_next_page = 1 ==> will load more data and vice versa if has_next_page = 0

**Comment by gungoromer** [comment]
I returned summary rows only first page and it's worked. Thanks.
