### ISSUE TITLE
onAdd event.onComplete called twice even though event.preventDefault() was called

### ISSUE THREAD

**Issue by chsymann** [vitmalina/w2ui#737]
I detected some weird behaviour while handling the event.
Actually I want to stop the add event with event.preventDefault() in some cases. I'm expecting that event.onComplete just gets called if I did not prevent the event.
Running the following code and clicking the "+ Add" button brings up two alerts saying "I'm done", even though I called preventDefault on the event.

``` javascript
$('#grid').w2grid({
    name: 'grid',
    header: 'Add Test',
    show: {
        toolbar: true,
        toolbarAdd: true
    },
    columns: [
        { field: 'recid', caption: 'ID', size: '50px', sortable: true, attr: 'align=center' }
    ],
    records: [
        { recid: 1}
    ],
    onAdd: function(event) {
        console.log(event);
        event.preventDefault();
        event.onComplete = function() {
            alert("I'm done");
        }
    }
});
```

Here is a fiddle that shows my problem: http://jsfiddle.net/e1x4yfs5/3/
please click the "+ Add" button in the toolbar and watch the alerts. Why is onComplete called twice even if I prevented the event?

**Comment by williamtrout** [comment]
I am running 1.4.3 and experiencing the same symptom.

**Comment by jerrade** [comment]
Same thing with 1.5 rc1
[http://jsfiddle.net/jerrade/4umnoypd/1/](http://jsfiddle.net/jerrade/4umnoypd/1/)

**Comment by mpf82** [comment]
Fixed, closing issue
