### ISSUE TITLE
type=int clears field when moving between tabs 

### ISSUE THREAD

**Issue by Snylten** [vitmalina/w2ui#743]
When moving to second tab, the field with type=int is cleared...

Happens only when "groupSymbol"    : "" 

Seems that formatNumber does not support empty groupSymbol...

fields: [
            { field: 'customer_number', type: 'int', required: true,
                html: {  
                    caption : 'CustomerId',  
                    attr    : 'style="width: 350px"',
                    text    : '',
                    span    : 7,
                    page    : 0
                }
....

tabs: [
            { id: 'tab1', caption: 'Customer' },
            { id: 'tab2', caption: 'Information'},

....

**Comment by mpf82** [comment]
I can't reproduce this in 1.5

Tested with ``"groupSymbol"    : ""`` and ``"groupSymbol"    : ","``

This issue can probably be closed, unless someone creates a fiddle with the current 1.5 sources to demonstrate that the issue still exists.
