### ISSUE TITLE
Parse Json object before POST web services

### ISSUE THREAD

**Issue by kahchun** [vitmalina/w2ui#759]
Hi Vitmalina, good day.

I found an issue here, where i'm failed to POST JSON object through form to server API. which show me error message : success: false msg: "Content type 'application/x-www-form-urlencoded;charset=UTF-8' not supported"

I tried to POST form by using AJAX with no issue, therefore i believe issue caused by object format is not match to server end API. Is there any method or property i can apply to reformat json object before i POST to server API like parse function?

Looking for your quick reply, thanks in advance.

**Comment by mpf82** [comment]
no response, closing issue
