### ISSUE TITLE
global scope for w2ui while working in meteor

### ISSUE THREAD

**Issue by gooderist** [vitmalina/w2ui#763]
Hello, thanks for the great library (especially for Grid!)

I am using w2ui in a meteor project and it doesn't seem like w2ui, w2obj, or w2util are given global scope with the way meteor loads external js files. To get the library working for now, I took out the "var w2ui = w2ui || {}" and replaced it with "w2ui = {}" (did the same with w2obj and w2util).

**Comment by KrishnaPG** [comment]
For those who are looking for similar thing on how to make W2UI grid integrate and work with Meteor collections, here is something that may help: http://live.my-classes.com/blogs/post/15

**Comment by pdavidow** [comment]
http://docs.meteor.com/#/full/structuringyourapp mentions the client/compatibility directory for compatibility JavaScript libraries that rely on variables declared with var at the top level being exported as globals.
