### ISSUE TITLE
Suffix render bug on list when <input> was not visible on init

### ISSUE THREAD

**Issue by aetna-softwares** [vitmalina/w2ui#780]
Hi,

I have list fields which are hidden and then shown depending on user choice. In this case, the suffix rendering is not good because it has been computed when the <input> has a 0px height : 
![image](https://cloud.githubusercontent.com/assets/8860618/5619430/224c8442-9522-11e4-99f2-98ce5adfee19.png)

![image](https://cloud.githubusercontent.com/assets/8860618/5619436/3eab4128-9522-11e4-9067-64f04cc2ef8d.png)

I workarround the problem by re-compute it when I display the field : 

``` javascript
$(_self.elInput).data('w2field').options.suffix = '<div class="arrow-down" style="margin-top: '+
        ((parseInt($(_self.elInput).height()) - 6) / 2) +'px;"></div>';

$(_self.elInput).data('w2field').refresh();
$(_self.elInput).data('w2field').addSuffix();
```

I think that we should have a "show()" or "render()" function on field object that should take care of redraw everything cleanly

**Comment by mpf82** [comment]
Can this be reproduced with the latest sources?
Can you create a fiddle to demeontrate the issue?

**Comment by aetna-softwares** [comment]
wow, this is old. not sure I am still using this code somewhere :(

i'll try to find this and tell you

**Comment by mpf82** [comment]
@aetna-softwares I'm just looking into some of the older issues, seeing if I can fix them or if they can be closed.

Cheers =)

**Comment by mpf82** [comment]
No response, no reproducer, closing issue.
