### ISSUE TITLE
Feature Request: Namespaced css classes

### ISSUE THREAD

**Issue by VoiceOfWisdom** [vitmalina/w2ui#790]
In [src/less/src/common.less](https://github.com/vitmalina/w2ui/blob/aa364dd39b4425265f40e92650fd669ddc3803fc/src/less/src/common.less#L66-L95) there are css rules defined for `input`, `select`, and `textarea` elemnts. These are not specified with any w2ui specific class. This causes the elements on my page to look different when I reference w2ui's css file.

I could fix this by setting my styles to `!important`, this is a poor fix though. 

Would it be acceptable add a class selector of `.w2ui`, or something like it, to all those selectors?

**Comment by VoiceOfWisdom** [comment]
This would require any inputs dynamically inserted by w2ui to have that class added to them.

**Comment by bbottema** [comment]
Actually, those styles are maiming another thridparty library I'm using, so I can't fix it easily. I'm using textAngular in an unrelated portion of the page, but the buttons are messed up.

**Comment by VoiceOfWisdom** [comment]
I ended up removing the offended styles from the css, I didn't need w2ui's styling on those elements. Better for the library to do it out of the box, that was an easy fix though.

**Comment by vitmalina** [comment]
Agree. I haver moved those classes under .w2ui-reset rule, so they should be ok now. Thanks.

**Comment by VoiceOfWisdom** [comment]
:+1:  Thank you @vitmalina.
