### ISSUE TITLE
Dynamic Columns

### ISSUE THREAD

**Issue by anandbohra** [vitmalina/w2ui#797]
Hi Vitmalina,
I am planning to use your grid to replace my WPF based application.
What I am looking for is, in WPF I populate my grid based on user selected columns like I gave them list of say 10 columns in check list box, now whatever users selects that columns appear in grid.

Can the same be possible in your W2UI grid ? 
Since as per documentation columns has to be supplied in advance.

please suggest method or link to study further if its possible.

Thanks in advance.

Anand

**Comment by vitmalina** [comment]
Please submit only bug reports here. All questions should go to the website comments section.
