### ISSUE TITLE
How to work with tabs?

### ISSUE THREAD

**Issue by matthjes** [vitmalina/w2ui#8]
Hi,

I'm having some problems working with tabs. For example, how do I set their contents after defining them using w2tabs? How do I get their size (width + height)? I thought that I can just use the selected-tab selector to get the current tab. 

Could you please provide an example how I can add, e.g., a simple div or paragraph to a tab?

**Comment by tristenator** [comment]
i hate to re-open this discussion, but i'm struggling with tab "content" too.

if i do what you suggest and put the tabs inside a layout and then change the content of the layout on an onChange event of the tab, then the entire panel - including the tabs - gets replaced with the content.

how can i set the *content* of a tab to a w2ui object, say for example a w2grid object?

**Comment by tristenator** [comment]
oh sorry i only just realised what @matthjes was saying. use two panels, one for the tabs ("top") and one for the tab content ("main").

**Comment by vitmalina** [comment]
Also, please note that layout panels support tabs now. You can attach create tabs in the layout panel directly and then you do not need to have them in a different panel. See http://w2ui.com/web/docs/w2layout.panels

**Comment by tristenator** [comment]
oh wow, that's even better, thank you for your help!
