### ISSUE TITLE
Handle to grid scrollbar

### ISSUE THREAD

**Issue by mugitty** [vitmalina/w2ui#802]
I want to modify the column width.  I tried the following:
w2ui['draw'].columns[{ field: 'draw', caption: 'Draw', size: width }];
w2ui['draw'].refresh();

This should have displayed the horizontal scrollbar, since, the width is larger than the panel, but, I cannot see the scroll bar.  Is there a way to display the horizontal scroll bar always?

How to trigger when grid’s  vertical scroll bar is added, removed or scrolled?   How to retrieve scroll position?  How to scroll to a particular position?

**Comment by vitmalina** [comment]
Please post your questions to w2ui.com comments section or stackoverflow. The issue section is only for bugs.
