### ISSUE TITLE
Grid show {header: false} Doesn't Work in Firefox

### ISSUE THREAD

**Issue by iGeechee** [vitmalina/w2ui#803]
The feature to show or hide the grid's header isn't working on Firefox (35).  The header always shows no matter what.  It does, however, work when I test it in IE9.

**Comment by vitmalina** [comment]
I tested in both w2ui 1.4.2 and 1.5.x nightly and there is no problem in FireFox 35.0 on mac. Please specify what version of w2ui and FireFox you experiencing problems and on what platform. Also, paste sample code.

**Comment by iGeechee** [comment]
Thanks for the prompt response, and sorry for the awful delay bruh!  Got kidnapped by another project...

It's Firefox 35.0.1 (if the .0.1 makes a difference) and w2ui 1.4.2 on Win 7 x64.  And actually, if I go to the demo page, http://w2ui.com/web/demos/#!grid/grid-3, the show/hide header works just fine.

```
var LIMIT = 300;
init();

function init()
{
    $(document).ready(function() {
        $('#grid').w2grid({
            name: 'grid',
            header: 'No Show',
            show: {
                header:false,
                footer:true,
                toolbar:true
            },
            fixedBody: true,
            autoLoad: true,
            url: myUrl,
            recid: 'unique_ID',
            columns: [
                {field: 'UNIQUE_ID', caption: 'Column 1', size: '100px', max: '100', sortable: true},
                {field: 'colm_2', caption: 'Column 2', size: '80px', max: '80', sortable: true},
                {field: 'colm_3', caption: 'Column 3', size: '190px', max: '190', sortable: true}
            ],
            postData: {
                limit: LIMIT,
                startDate: today,
                startTime: changeMidnight0to12(currTime)
            }
        });
    });  // end $(document).ready
} // end init()
```

**Comment by vitmalina** [comment]
Ok. If all is fine, then I am closing this issue.

**Comment by iGeechee** [comment]
Well, I'm not sure...  Shouldn't the initial setup of:
```
show: {
    header:false,
    footer:true,
    toolbar:true
}
```
be enough to turn the header off, without having to issue:
```
w2ui.grid.show.header = false;
w2ui.grid.refresh();
```
