### ISSUE TITLE
How do I make a drop list get new API results each time vs. filtering original results?

### ISSUE THREAD

**Issue by clambmt** [vitmalina/w2ui#805]
# summary

How do I get a W2UI list field to call my API each time the user enters
another character? Right now, the list field will call the API once and each
character entered after that will filter the original list instead of
requesting a new list.

# details

**gui**
    a grid which contains a column of list fields
    items from the list fields are fetched from a URL

**data**
    8,101,521 records
      311,597 records per 1 character search (average)
       11,984 records per 2 character search (average)
          461 records per 3 character search (average)

**need**
    filter the list as the user types
    must show matches for any number of characters entered

**main problem**
    311,597 records is too many records to search, return, and load into dropbox.
    This will put undo load on the db, the connection, and definitely the dropbox.

**solution 1**
    In the API, limit the returned records as follows
        1-2 character search - return first 400 matching records
        3+ character search  - return all matching records

**solution 1 problem**
How do I get a W2UI list field to call my API each time the user enters
another character? Right now, the list field will call the API once and each
character entered after that will filter the original list instead of
requesting a new list.

**Comment by vitmalina** [comment]
Please do not submit questions here. This place is only for bugs.

**Comment by vitmalina** [comment]
This seems to work as you want it: http://w2ui.com/web/demos/#!fields/fields-6
