### ISSUE TITLE
IE11 - Grid Inline Edit - text selection

### ISSUE THREAD

**Issue by SVO404** [vitmalina/w2ui#813]
http://w2ui.com/web/demos/#!grid/grid-21
Text can't be selected in IE11, when editing a field (any type).

**Comment by n3tfr34k** [comment]
```javascript
$(this.box).on('selectstart', function () { return false; }); // fixes chrome cursor bug
```
https://github.com/vitmalina/w2ui/blob/master/src/w2grid.js#L3859

https://github.com/vitmalina/w2ui/pull/891

**Comment by vitmalina** [comment]
I have implemented and push change where all these lines are removed. There were in other places too. It seems to be working properly everywhere.
