### ISSUE TITLE
w2grid - horizontal scrollbar broken on { fixedBody: false } grids

### ISSUE THREAD

**Issue by ilanc** [vitmalina/w2ui#815]
Thanks for w2ui the grid is a excellent and more full featured than many others I've tried including ng-grid / ui-grid, extjs grids, and jqxGrid. 

I'm having trouble with the horizontal scrollbar though. It appears that the horizontal scrollbar isn't rendered with { fixedBody: false } grids. 

See example here:
See http://jsfiddle.net/ilancopelyn/q18dq8ja/2/

Thanks.

**Comment by vitmalina** [comment]
This was 1.4.x issue. In current master it is fine. I have fixed it in 1.4 branch and recompiled latest code. Download: https://raw.githubusercontent.com/vitmalina/w2ui/w2ui-1.4/dist/w2ui.js or https://raw.githubusercontent.com/vitmalina/w2ui/w2ui-1.4/dist/w2ui.min.js and all will be good

**Comment by ilanc** [comment]
Thanks for that. Is there a way to include extra space so that the horizontal scrollbar doesn't obscure the bottom-most row? I hacked it like this: line 5582:
```javascript
var calculatedHeight = w2utils.getSize(columns, 'height')
                    + w2utils.getSize($('#grid_' + obj.name + '_records table'), 'height')
                    + 16; // HACK - additional vertical space for horizontal scrollbar
```

**Comment by ilanc** [comment]
Actually please ignore. I've upgraded to 1.5.x (nightly) where I see you've fixed this issue. Thanks

**Comment by vitmalina** [comment]
I am glad it is working in 1.5.x. Also please note that frozen columns are in1.5.x too. I will look into the issue with 1.4.2 and will try to fix it.
