### ISSUE TITLE
Grid Column Tooltip?

### ISSUE THREAD

**Issue by hansgru** [vitmalina/w2ui#816]
Hi,
Is there a Grid Column Tooltip?

I can't find in the docs any :(.

**Comment by vitmalina** [comment]
There is no tooltip for the grid column

**Comment by fungms** [comment]
@hansgru you can do trick like:

field.caption = "\<div style="text-align:center" title="your_tooltip"\>your caption \</div\>

**Comment by eliavmaman** [comment]
You can solve it like this 
```caption: 'FieldName <i style=" position: absolute !important;top: 0 !important;right: 0 !important;bottom: 0 !important;left: 0 !important;" class="col-title" title="Your Tooltip text"></i>'```

**Comment by mpf82** [comment]
In case someone else stumbles upon this topic, here's some working code:


```
.tt{ position: absolute !important;top: 0 !important;right: 0 !important;bottom: 0 !important;left: 0 !important; }

var c1= 'First Name' + '<i class="tt" title="Your Tooltip text"></i>';
var c2 = '<div title="This is a tooltip ...">Last Name</div>';
$(function () {
    $('#grid').w2grid({ 
        name: 'grid', 
        columns: [                
            { field: 'fname', caption: c1, size: '30%' },
            { field: 'lname', caption: c2, size: '30%' },
            { field: 'email', caption: 'Email', size: '40%' }
        ]
    });    
});
```

fiddle: http://jsfiddle.net/kwpd6dm6/
