### ISSUE TITLE
Grid causes text selection issue in combo-1 demo

### ISSUE THREAD

**Issue by stegjws** [vitmalina/w2ui#819]
In the demo:   http://w2ui.com/web/demos/#!combo/combo-1

Click "Some HTML" in the side bar.  The displayed text on the right cannot be selected.

If I take it to jsfiddle and do not select a grid first.  Then click "Some HTML", the text is selectable.  After clicking on Grid1 or Grid2 and then returning to "Some HTML" the text is no longer selectable.

After the grid is loaded into the main content panel, it is somehow blocking the ability to select text from then on, even when the html is loaded into the main content panel.

**Comment by vitmalina** [comment]
I have fixed it in both 1.4 branch and current master. I did not update demos, as it is pointing to the old lib. However, if you download latest lib from 1.4.x branch - all will be fixed.
