### ISSUE TITLE
Grid Column Header Tooltip!

### ISSUE THREAD

**Issue by hansgru** [vitmalina/w2ui#820]
Please add support for Grid Column Header Tooltip.

In many applications the grid column header names need an extra explanation, and usually this is provided in the tooltip.

**Comment by vitmalina** [comment]
When you are defining column, add hint property and it will become a hint.

**Comment by hansgru** [comment]
> When you are defining column, add hint property and it will become a hint.

I was trying with "title" (like in HTML) or "tooltip" property (like other frameworks do it) :).
Please update the docs for this, since IMO it's not intuitive that the property is called 'hint'.

Thank you.

**Comment by vitmalina** [comment]
ok

**Comment by vitmalina** [comment]
I am going to rename hint -> tooltip everywhere in the library
