### ISSUE TITLE
Advanced search ends with issue (1.4.2)

### ISSUE THREAD

**Issue by MarkusAholainen** [vitmalina/w2ui#823]
Hi,

Thanks for the great web framework!

There is an issue on the w2ui-1.4.2.js line 2316 (function localSearch).

Now the ends with matches also with strings that are one character shorter than the search string regardless of the content. E.g. record value "Apple" will give errorneous match with ends with search string "Banana". There is fix below.

is
--
  case 'ends':
  case 'ends with': // need for back compatib.                                                                                                                                                     if (val1.indexOf(val2) == val1.length - val2.length) fl++; // do not hide record                                                       
 --
Fixed version
--
  case 'ends':
  case 'ends with': // need for back compatib.                                                                                                                                                     if (val1.indexOf(val2) >= 0 && val1.indexOf(val2) == val1.length - val2.length) fl++; // do not hide record                                                       
 --
 
Regards,
  Markus Aholainen

**Comment by vitmalina** [comment]
I incorporated the change and rebuilt JS. See https://raw.githubusercontent.com/vitmalina/w2ui/w2ui-1.4/dist/w2ui.js.

In the future please consider submitting pull requests.
