### ISSUE TITLE
please add pagination for grid (hurry up)

### ISSUE THREAD

**Issue by i900916** [vitmalina/w2ui#824]
pager pagination for grid.
this feature is very useful and powerful.
please add this for 1.5 nightly version.

**Comment by vitmalina** [comment]
Infinite scroll is very useful and powerful :). Please note that it will pull more records from the server as user scrolls. I have had pagination in 1.3, but it has been refactored. Overall I have exceptionally positive feedback about it, both from the community and from the projects I am involved it where I can talk to users. Therefore I will not be working to add it back. In general on the internet people are switching to infinite scroll as it is the future.

If you must have pagination - it is not that hard to add it as a custom feature. Good luck.

**Comment by i900916** [comment]
infinite scroll  feature has buffer data ?

**Comment by i900916** [comment]
cache data?

**Comment by vitmalina** [comment]
http://w2ui.com/web/demos/#!combo/combo-9

**Comment by sullyf50** [comment]
The grid is good design but 
It has few issues to display 12000 records takes time it get the data is few seconds and when it display 
It takes 20-40 seconds
