### ISSUE TITLE
ERROR: The parameter "name" is not unique. There are other objects already created with the same name (obj: grid).

### ISSUE THREAD

**Issue by i900916** [vitmalina/w2ui#825]
console log this error, at first display is good,but  second third  refresh grid has happend this error.
so what's wrong?please check this error.

**Comment by vitmalina** [comment]
This is not a error inside the lib. It is error in your code. You are recreating the same object, which you can just reuse. Or if you must recreate - then destroy first.

**Comment by i900916** [comment]
Thank you for your guidance.
