### ISSUE TITLE
Unable to create jqueryUI select menu, etc. inside w2ui layout

### ISSUE THREAD

**Issue by ppearson111** [vitmalina/w2ui#833]
Love this framework but running into issues porting existing code into w2ui layouts... basic example is a simple jqueryUI selectmenu:

W2UI Layout pane content:

    <select id="sel_menu">
        <option>one</option>
        <option>two</option>
    </select>'

Then inside script:

    $( function() {
        $('#sel_menu').selectmenu();
    });

The select menu is styled after the jqueryUI them but the dropdown is never invoked when the select menu is clicked.  This works perfectly when --outside-- of the w2ui layout, but doesn't work within it.  Am I missing something (entirely possible!) or is this a bug?  Thanks so much.

**Comment by vitmalina** [comment]
Only bugs here. All questions to w2ui.com or stackoverflow.com. Attach to http://w2ui.com/web/docs/common.onRefresh and you should be fine.
