### ISSUE TITLE
Data and event handlers lost when layout content is changed

### ISSUE THREAD

**Issue by dhagrow** [vitmalina/w2ui#835]
I'm trying to use w2ui with other JS libraries such as Knockout.js. I can set the content of a layout panel to an element bound by Knockout, and everything works fine. However, if I set the content of that pane to anything else, then set it back to the Knockout element, all event handlers on the element and it's children have been removed.

I suspect that this is due to a call to [jQuery.html](http://api.jquery.com/html/#html-htmlString):

>When .html() is used to set an element's content, any content that was in that element is completely replaced by the new content. Additionally, jQuery removes other constructs such as data and event handlers from child elements before replacing those elements with the new content.

I have tried to work around this by removing elements from the DOM before switching content, but there appear to be timing issues, and I haven't been able find a reliable solution.

I've run into the same problem with other JS libraries that add data and event handlers to elements.

**Comment by vitmalina** [comment]
There is an event called onRefresh for the panel. It is called when panel content is refreshed. If you attach to this event and do knockout binding in onComplete clause, it should fix the problem.

FYI: Please only submit bugs here. All questions on w2ui.com or stackoverflow.com
