### ISSUE TITLE
Issue on onblur on date field

### ISSUE THREAD

**Issue by ChandrakantaPal** [vitmalina/w2ui#838]
If you press tab when current focus is on a date field,then the overlay will appear again but focus moved to next field.

**Comment by vitmalina** [comment]
I cannot repeat this issue in my test environment. Can you please post sample code and what browser/os you see the issue.

**Comment by KITSChandrakantaPal** [comment]
http://w2ui.com/web/demos/#!forms/forms-2
on windows 7
Browser : firefox 30.0

**Comment by KITSChandrakantaPal** [comment]
I have forked and made some fixes. Please have a check.

**Comment by ChandrakantaPal** [comment]
Additionaly check here too .. http://w2ui.com/web/docs/form/fields-date
on windows 7
Browser : firefox 30.0
