### ISSUE TITLE
GRID: data spans multiple cells.

### ISSUE THREAD

**Issue by gmhawash** [vitmalina/w2ui#841]
You have the header spanning multiple columns.  Is there a way to have a data cell for a specific row span multiple cells?

**Comment by vitmalina** [comment]
This feature is on the road map but has not yet been implemented

**Comment by stuta** [comment]
This is really needed feature. Should be span: n in the column definition.

**Comment by vitmalina** [comment]
Row span is already implemented. However, it is on in column definitions, but in record. Here is the demo https://w2ui.com/web/demos/#/combo/3, basically, in the needed record, you say what fields and how much you want colspan to be 

```js
 records: [
  { recid: 1, name: 'Some name', w2ui: { colspan: { name: 2 }}}
  ...
]
```
