### ISSUE TITLE
Grid onSave event not being called

### ISSUE THREAD

**Issue by misterkevinliu** [vitmalina/w2ui#842]
I may very well be mistaken, but I am having trouble calling the onSave event. I was able to find the same error in this demo: http://w2ui.com/web/demos/#!grid/grid-17. If I am reading the code correctly, when the save button is clicked in the toolbar, there should be an alert that states "save". Right now, no alert occurs. Likewise, I am having trouble calling the onSave event in my own program. 

Thanks,

Kevin

**Comment by ppearson111** [comment]
+1 on this issue -- I've seen this as well.  onSave() isn't getting called. thx for posting. -Paul

**Comment by vitmalina** [comment]
Confirmed & fixed.

**Comment by pdavidow** [comment]
It's broken again.

**Comment by vitmalina** [comment]
Please note that in 1.4.x version, there are two events onSubmit and onSave. First one is triggered when save button is clicked and when data is submited to the server. Second one is clicked when server responds back. In 1.5.x branch, the onSubmit event is removed and onSave is triggered instead.
