### ISSUE TITLE
"Reload data in the list" toolbar button not working

### ISSUE THREAD

**Issue by misterkevinliu** [vitmalina/w2ui#845]
http://w2ui.com/web/demos/#!grid/grid-21

When "reload" button is clicked, nothing happens - I am experiencing that within my application as well.

Thanks,

Kevin

**Comment by vitmalina** [comment]
If you grid is connected to the remote source (grid.url is not empty), it will refresh from remote source. Otherwise, nothing happens. What did you expect to happen?

**Comment by mpf82** [comment]
@mrg2001 This can probably be closed due to inactivity.

**Comment by mpf82** [comment]
Closing issue: no response, no reproducer
