### ISSUE TITLE
How Can I help your project?

### ISSUE THREAD

**Issue by HamirDhanquer** [vitmalina/w2ui#849]
Hi, Vitmalina. 

I liked your project. I'm very interesting in contributing with it. What do you recomend for someone as I? 

Sorry my wrongs, I'm not native english speaker.

**Comment by vitmalina** [comment]
It all depends what you like to do. Many people contribute by fixing bugs that they find and they need fixing, other people help with the questions on github and forum. I am no longer able to answer questions on the forum and if you can do this, it would be great. Also, if you are pationate about testing, you can help with that too.

**Comment by HamirDhanquer** [comment]
Thanks for your answer.
I will check some way of help your work. Because at moment, I've have less knowledge about javascript. But I'm studying.
