### ISSUE TITLE
The parameter "name" is not unique. There are other objects already created with the same name (obj: myGrid).

### ISSUE THREAD

**Issue by greatlake5** [vitmalina/w2ui#853]
I created a new asp.net web application (MVC) in Visual Studio 2013
then add a test page W2UITest.cshtml
copy and pasted the sample code from W2UI grid simple grid, then select the view in browser. However, I can not get the sample to work and always got error: "The parameter "name" is not unique. There are other objects already created with the same name (obj: myGrid)." Please Help!!!!

My code is the following:

<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<link rel="stylesheet" type="text/css" href="http://w2ui.com/src/w2ui-1.4.2.min.css" />
<script type="text/javascript" src="http://w2ui.com/src/w2ui-1.4.2.min.js"></script>

<div>
    <input type="button" value="Load" onclick="LoadData();" />
    <div id="myGrid" style="width: 100%"></div>
</div>

<script type="text/javascript">
    function LoadData() {
        $(myGrid).w2grid({
            name: 'myGrid',
            columns: [
                { field: 'fname', caption: 'First Name', size: '30%' },
                { field: 'lname', caption: 'Last Name', size: '30%' },
                { field: 'email', caption: 'Email', size: '40%' },
                { field: 'sdate', caption: 'Start Date', size: '120px' },
            ],
            records: [
                { recid: 1, fname: 'John', lname: 'Doe', email: 'jdoe@gmail.com', sdate: '4/3/2012' },
                { recid: 2, fname: 'Stuart', lname: 'Motzart', email: 'jdoe@gmail.com', sdate: '4/3/2012' },
                { recid: 3, fname: 'Jin', lname: 'Franson', email: 'jdoe@gmail.com', sdate: '4/3/2012' },
                { recid: 4, fname: 'Susan', lname: 'Ottie', email: 'jdoe@gmail.com', sdate: '4/3/2012' },
                { recid: 5, fname: 'Kelly', lname: 'Silver', email: 'jdoe@gmail.com', sdate: '4/3/2012' },
                { recid: 6, fname: 'Francis', lname: 'Gatos', email: 'jdoe@gmail.com', sdate: '4/3/2012' },
                { recid: 7, fname: 'Mark', lname: 'Welldo', email: 'jdoe@gmail.com', sdate: '4/3/2012' },
                { recid: 8, fname: 'Thomas', lname: 'Bahh', email: 'jdoe@gmail.com', sdate: '4/3/2012' },
                { recid: 9, fname: 'Sergei', lname: 'Rachmaninov', email: 'jdoe@gmail.com', sdate: '4/3/2012' }
            ]
        });

    }

</script>

**Comment by vitmalina** [comment]
It is generally not a problem. You try to create grid two times, so it fails the second. If your grid config did not change, then this error can be completely ignored. If you want to have clean code, you can just add a check before createing a gid
```js
if (!w2ui[grid_name]) $().w2grid()
```
