### ISSUE TITLE
w2ui Grid: Blank row at bottom of list

### ISSUE THREAD

**Issue by gmhawash** [vitmalina/w2ui#854]
I have my grid initialized using a `url` to fetch the records, and now when the grid paints or refreshes, it adds a `<tr>` at the bottom with a width equals to the number of items in the list.  It looks related to the scroll function but I cannot figure out how to get rid of it.

![image](https://cloud.githubusercontent.com/assets/47986/6965993/79f94dd4-d90a-11e4-8080-8381c26acc0e.png)

The data is as follows:
```json
{"records":[{"recid":1,"recorded_on":"2015-04-02","status_name":"Completed"},{"recid":4,"recorded_on":"2015-04-08","status_name":"Never started"},{"recid":2,"recorded_on":"2015-04-08","status_name":"Partial complete"},{"recid":3,"recorded_on":"2015-04-08","status_name":"Partial complete"}]}
```

And the code is:
```js
 showStatusForm = function(event) {
            var url = '/participants/50/client_manager/enrollments/1/statuses/:id/edit.js';
          
            $.get(url.replace(/:id/, event.recid))
              .complete(function(data, status, xhr) {
                $('#status-form').html(data.responseText);
              })
          }
$('#client_manager_current_statuses').w2grid({
            name   : 'current_statuses',
            method: 'GET',
            show_extra: false,
            columns: [
              { field: 'recorded_on', caption: 'Date', size: '30%' },
              { field: 'status_name', caption: 'status', size: '50%' },
              { field: 'remove', size: '18%',
                render: function(record, index, col_index) {
                  var html = '<a class="btn deletebutton" data-confirm="Are you sure?" data-remote="true" rel="nofollow" data-method="delete" href="/participants/50/client_manager/enrollments/1/statuses/:id.js">Delete</a>';
                  return html.replace(/:id/, record.recid);
                }
              },
            ],
            url: '/participants/50/client_manager/enrollments/1/statuses.js',
            onClick: showStatusForm
          });
```
What can I do to remove the extra row?

**Comment by vitmalina** [comment]
You server should return total, which is a total number of records in the data set. It should be returns in the json on the top level. Then it all be peachy :).

See http://w2ui.com/web/docs/grid/overview#data-structures, the data structure it expects back.

**Comment by dwarika4u** [comment]
w2ui Grid: Getting extra column on right side of grid. It is coming dynamically while adding data or loading data from DB through Ajux calling from CS file. check with below screen shot.
![gridpic](https://cloud.githubusercontent.com/assets/15045888/10388398/4acbdc08-6e87-11e5-80ca-7e10fd005250.PNG)



![gridcode](https://cloud.githubusercontent.com/assets/15045888/10388412/5ed0071a-6e87-11e5-9729-7e2c4d7ac6c3.PNG)

![gridhtml](https://cloud.githubusercontent.com/assets/15045888/10388414/65ec1034-6e87-11e5-80a9-ac3de8bc6c56.PNG)

**Comment by dwarika4u** [comment]
Please help as i try every thing ,also try with CSS.

**Comment by vitmalina** [comment]
Extra column will appear if there is a need for scrollbar or there was a need for scrollbar. Try to increase the size of the container where you output the grid. 

Or try setting grid.fixedBody = false. Then it should auto expand if needed. The container div have to be flexible in that case.
