### ISSUE TITLE
Render event in editable records in grid

### ISSUE THREAD

**Issue by alexey-vasyunin** [vitmalina/w2ui#856]
I have own render function on column, this column is editable. And after edit cell value in the grid, render function use old values. In edit mode cell show new value.

**Comment by chalchis** [comment]
try to add later
w2ui['grid_name'].save();


would be desirable
see the script

**Comment by alexey-vasyunin** [comment]
I get nothing from .getChanges() after .save()
https://jsfiddle.net/130f5e99/1/
Try to change lastnames and press 'Get changes'. Result after .save() in console.

**Comment by chalchis** [comment]
try active toolbar

 show: { 
            toolbar: true,
            footer: true,
            toolbarSave: true
        },

check demo
http://w2ui.com/web/demos/#!grid/grid-21

**Comment by alexey-vasyunin** [comment]
sorry, my jsfiddle link has https prefix, but need http for js-libraries load
But anyway I've understood I need use this.getCellValue() instead of record.fieldname in render function. Thank you!
