### ISSUE TITLE
dynamic create tabs in form been invisible or unrespondable.

### ISSUE THREAD

**Issue by hawkxu** [vitmalina/w2ui#861]
If the tabs create after the parent form, then the tabs been invisible.
If the tabs create before the parent form, then the tabs been unrespondable.

please look at: http://jsfiddle.net/zgcxfmnq/3/

**Comment by vitmalina** [comment]
Neither of two is a correct way. Once the form is displayed in a container, you should not mess with the container content, as form will rewrite it as necessary. You could put tabs in a different container and then hook it to what you needed in the form (similar to your way #1). But better way would be to use tabs property of the form. See http://w2ui.com/web/docs/w2form.tabs. 

Once form has created tabs, you can get its object and modify it. It will be in form.tabs property or in w2ui object.
