### ISSUE TITLE
Twitter Bootstrap Theme?

### ISSUE THREAD

**Issue by hansgru** [vitmalina/w2ui#865]
Hi,

Is there any Twitter Bootstrap Theme for W2UI?
I know that the the standard w2ui theme is very compact, but having TW support would be of great help since many projects already use it.

**Comment by vitmalina** [comment]
w2ui should not overlap with bootstrap. So, you can include any bootstrap theme.

**Comment by hansgru** [comment]
> w2ui should not overlap with bootstrap.

But I need the W2UI components to also have the Bootstrap look and feel like the rest of the stuff that's in the page, hence my question for a "Bootstrap Theme for w2ui".

Just dropping new components in a page that has Bootstrap can't possibly make them look and behave like Bootstrap. That's why many libraries have some sort of theme or extension to make that happen:

e.g. DataTables has such a theme:
https://www.datatables.net/examples/styling/bootstrap.html

or KendoUI:
http://demos.telerik.com/kendo-ui/bootstrap/

or ExtJS:
http://bootstrap.newbridgegreen.com/view/

**Comment by bwl21** [comment]
@hansgru do you have a solution to give a w2ui app a bootstrap look and feel?
