### ISSUE TITLE
multiselect - no-autoclose and no-duplicates

### ISSUE THREAD

**Issue by KrishnaPG** [vitmalina/w2ui#869]
Thanks for this good library - this is very helpful.

Was testing this multiselect option on the demo site and found two issues - wondering how to overcome them:
     1. After every select, the dropdown is closing, which makes it very difficult for the user to select multiple items (say 10 or so). Is it possible to ctrl+select the items while it is open (or checkbox perhaps)?
     2. Another important issue is: once an item is selected, it should not be available for selection again. Right now that is not the case and duplicates are possible (screenshot below). How to avoid these duplicates situation?

![image](https://cloud.githubusercontent.com/assets/4610831/7218485/0d46c850-e68f-11e4-9edb-6ac2d1f4933f.png)

**Comment by vitmalina** [comment]
1. If you select with keyboard the popup stays :). While using keyboard, if you type some text, it will filter the list, you select hitting enter, it selects and clears the input, you type some more to filter again, use up/down key, find record, hit enter, and so on.

With mouse each selection is one at a time

2. If you look here, http://w2ui.com/web/demos/#!fields/fields-4, I cannot select two of the same items. In current version, I know that you can set a property (filter: false) and then it will not filter dublicates.

**Comment by mpf82** [comment]
@KrishnaPG Did @vitmalina answer your questions? Can this issue be closed?

**Comment by KrishnaPG** [comment]
Thanks. please close it.
