### ISSUE TITLE
Columns reorder and sort

### ISSUE THREAD

**Issue by Rimokas** [vitmalina/w2ui#875]
Hi,
If I let to w2grid have a columns reordering possibility, then I can't to do sorting for columns. How to resolve that ?

**Comment by vitmalina** [comment]
see http://w2ui.com/web/docs/w2grid.onSort. You should be abel to listen on it, cancel it and do your own sorting. Or look at onColumnClick

**Comment by Rimokas** [comment]
Hi Vitaly,

Tried you sugestion... Sorry, but boths - sort and columnClick events are not working. Grid style - cell. All columns have reordering possiblity. I'm using "columnDragEnd" event, and that this is working. Can't to do sorting ... w2ui from gitHub downloaded at 27 of 04 ...

**Comment by Rimokas** [comment]
OK - columnClick event is working now ... something maybe was wrong in mine side . I did some changes, and added "sort" in "columnClick" event. I'll post how I success ...

**Comment by Rimokas** [comment]
It works fine ... Thanks ... :)
