### ISSUE TITLE
<input> in w2grid.toolbar cannot be focused with mouse

### ISSUE THREAD

**Issue by studentiks** [vitmalina/w2ui#878]
Code that reproduces problem:

    $('#main').w2grid({
      name: 'testgrid',
      show: {
        toolbar: true
      },
      columns: [],
      records: [],
      toolbar: {
        items: [
          {
            type: 'html',
            html: '<input type="text" placeholder="try focus me"/>',
            size: '100px'
          }
        ]
      }
    });

Impossible to focus with mouse on `<input>` inside w2grid.toolbar

Thank you, Vitali!

**Comment by vitmalina** [comment]
Fixed some time ago. It is pushed to the repo. Now, if there is an input, it will work.
