### ISSUE TITLE
mergeChanges two issues

### ISSUE THREAD

**Issue by githabas** [vitmalina/w2ui#879]
Recently I have made some corrections to mergeChanges function. It solves two problems for me:

1) If field name has `-` in his name `eval('record' + key + ' = changes[c][s]')` produces error "ReferenceError: invalid assignment left-hand side".

2) If `field type` is of type `list` or `combo`, merged result was just `[Object]`.

Here is my corrected function. I will be glad if you find corrections useful:

```javascript
mergeChanges: function () {
    var changes = this.getChanges();
    for (var c = 0; c < changes.length; c++) {
        var record = this.get(changes[c].recid);
        for (var s in changes[c]) {
            if (s == 'recid') continue; // do not allow to change recid
            if(typeof changes[c][s] === "object") changes[c][s] = changes[c][s].text;
            try { 
                eval('record[\'' + s + '\'] = changes[c][s]');
            } catch (e) {
                console.log('ERROR: Cannot merge. ', e.message || '', e);
            }
            delete record.changes;
        }
    }
    this.refresh();
},
```

**Comment by vitmalina** [comment]
Appreciate your contribution. I have looked at the diff and I think that your code does not do all the use case. Here is a diff

![screen shot 2015-05-02 at 3 02 40 pm](https://cloud.githubusercontent.com/assets/561995/7442941/6c747b4a-f0dc-11e4-82b8-44db4b5497b3.png)
 
For example, it will not merged nested rules. if records
```
records: [
 name: { fname: 'first', lname: 'last' }
]
```
it will not work with it. 

However, those two use cases that you mentioned need to work too. We need to find a solution that works for all of them. Also, if it the future you can submit pull requests, it will be easier to contribute.

**Comment by githabas** [comment]
Sorry I can't find grid example with this records structure
```
records: [
 name: { fname: 'first', lname: 'last' }
]
```

**Comment by vitmalina** [comment]
I think it should be like this
```
records: [
 { name: { fname: 'first', lname: 'last' } }
]
```

You can create an example and then add columns like
```
columns: [
{ field "name.fname", caption: 'First Name' }
]
```

**Comment by githabas** [comment]
Now it merge nested records too.
