### ISSUE TITLE
grid.add requires "recid" field when recid property is not "recid"

### ISSUE THREAD

**Issue by tristenator** [vitmalina/w2ui#883]
if i set the recid property for the grid to be something like "hash" for example (instead of the default "recid") then the add method will subsequently reject any record without a field named "recid".

as a result i *have* to have "recid" present as a field even if i'm using "hash" as the unique record identifier.

**Comment by vitmalina** [comment]
Please specify version which you used. If you used 1.4.x branch, try wit this https://raw.githubusercontent.com/vitmalina/w2ui/w2ui-1.4/dist/w2ui.js, which will become 1.4.3

**Comment by tristenator** [comment]
sorry to take a while to get back to you. this is in version 1.4.2.

i've coded a work-around, so i'm ok for now - but i'll be sure to try 1.4.3 when it's released.

thanks again vitman :)
