### ISSUE TITLE
w2grid.stateSave - save column ordering

### ISSUE THREAD

**Issue by prosconi** [vitmalina/w2ui#885]
http://w2ui.com/web/docs/w2grid.stateSave

It would be nice if ``w2grid.stateSave`` would also preserve column ordering when the user re-orders the columns.

Or maybe I'm doing it wrong?

**Comment by vitmalina** [comment]
I agree.

**Comment by prosconi** [comment]
Actually, I figured out that ``stateSave`` does save the order while serializing the array, but ``stateRestore`` does not apply the order of the columns.

**Comment by mpf82** [comment]
I have a fix prepared, that will restore the column order, still waiting until my other pull request is merged.

**Comment by mrg2001** [comment]
Merged all pull requests

**Comment by mpf82** [comment]
Can be closed, implemented in w2ui 1.5, see  #1206
