### ISSUE TITLE
the list field ignored tabindex attribute

### ISSUE THREAD

**Issue by hawkxu** [vitmalina/w2ui#887]
I want to specify tabindex to field, but the list ignored it.
please see a simple example at http://jsfiddle.net/zgcxfmnq/5/

**Comment by vitmalina** [comment]
Fixed the problem. You can download https://raw.githubusercontent.com/vitmalina/w2ui/w2ui-1.4/dist/w2ui.js, which will be 1.4.3 in close future. It has some more fixes in the 1.4 branch.
