### ISSUE TITLE
w2grid.clear() and subsequent w2grid.add() performance.

### ISSUE THREAD

**Issue by tristenator** [vitmalina/w2ui#889]
hey, i'm having troubles with the performance of w2grid where i'm sometimes adding a number of individual records.

i see in your w2grid.add method you ask:

            this.refresh(); // ??  should it be reload?

and i'd say it would be nice to have a choice :)

60 add() calls can take as much as 5 seconds, due to the 60 refreshes that happen along with it.

maybe an optional second parameter to the method to allow me to control whether i want to refresh on add() or not? something like Refresh (true by default to not break legacy code.)

i could then defer a total refresh or hit up refreshRow() for each if need be.

and thanks for the library dude, it's really good.

**Comment by vitmalina** [comment]
The add method can take an array of records and, not just a single record. Then it will refresh one time, when the entire array is added. Also, you can push records directly to records array and call refresh on your own.

**Comment by tristenator** [comment]
yep, i've settled on pushing records directly.

also, i've just got to say that the performance numbers i earlier reported aren't true - there was an issue in my native renderer and it's not a w2grid performance issue at all. sorry! i've edited it out of my original post.

**Comment by vitmalina** [comment]
Awesome. Thanks.
