### ISSUE TITLE
Grid UI Issue 

### ISSUE THREAD

**Issue by shridhar286** [vitmalina/w2ui#890]
Hi, 
I am having some weird UI issue. when i open the screen grid looks like this.
Attaching Screenshot..
![memoscreen1](https://cloud.githubusercontent.com/assets/12396664/7568030/2371a154-f81e-11e4-888d-878bf573347d.JPG)

If i Double click / start inspect element or resize column using mouse.. it gets resized in perfect manner..
check screenshot..
![memoscreen2](https://cloud.githubusercontent.com/assets/12396664/7568042/2c6b692a-f81e-11e4-9af2-6f69d237e359.JPG)

following is Code of my Grid..

$('#balanceLrsGrid').w2grid({
        name: 'balanceLrsGrid',
        columns: [
            {field: 'recid', caption: 'Cons No', size: '65px', },
            {field: 'city', caption: 'City', size: '95px', },
            {field: 'city_id', hidden: true},
            {field: 'lr_no', caption: 'Lr. No.', size: '55px', },
            {field: 'consignee', caption: 'Consignee', size: '150px', },
            {field: 'consignee_id', hidden: true},
            {field: 'qty', caption: 'Qty', size: '40px', },
            {field: 'weight', caption: 'Weight', size: '55px'},
            {field: 'date', caption: 'Date', size: '75px;', },
            {field: 'pay_type', caption: 'Pay Type', size: '65px', hidden: true},
            {field: 'pay_type1', caption: 'Pay Type', size: '65px', },
            {field: 'ch_total', caption: 'Total', size: '65px', },
        ],
    }); 
w2ui['balanceLrsGrid'].load('/Transactions/loadBalanceLrs');

**Comment by vitmalina** [comment]
I do not see what's wrong with your grid. Can you explain it?

**Comment by shridhar286** [comment]
Please Check the 'Balance Lrs' Grid in both the screenshots..
I have the DIV of Size 720px. and i m using grid inside this div.
I adjusted  column width as per required.. to display content properly.. 
W2ui grid adjusts outer area automatically, even if total of all columns width is not same as outer container.. 
It was proper before.. i hv no idea why its not adjusting while page load.
it is getting adjusted properly when i double click on grid / start Inspect Element..

**Comment by vitmalina** [comment]
The grid will take up the entire space in the div at the moment it is inserted. It will not resize itself if you change container div size. You will need to call grid.resize() method to do that. What I think is happening, at the moment when grid is inserted, the container div has wrong size (possibly due to browser rendering). When layout is resized, it will cascade resize event to all elements in it. Therefore, when you resize layout, grid picks up the size. If you insert grid into layout panel, then it will take care of itself. However, if you insert html and then grid inside, you might need to call grid.resize() manually.

**Comment by shridhar286** [comment]
I Already Tried grid.resize().
w2ui['balanceLrsGrid'].load('/Transactions/loadBalanceLrs');
w2ui['balanceLrsGrid'].resize();

If you want to check.. please check the link 

http://transport.shridharsakharkar.com/
Username / Password : user / user
1) Transactions -> Memo -> View /Edit
2) Double click on any row in the grid

**Comment by shridhar286** [comment]
There is one more issue.. Search in grid is previously working on Enter after entering text.. now its working on focus out.. 
is there anything i m doing wrong?

**Comment by vitmalina** [comment]
I tried to login, but user/user is not working.

As for search. I have tried and in my master branch it is working fine.

**Comment by mpf82** [comment]
I haven't encountered the issue either.

Since OP did not provide a way to reproduce the issue (e.g. a jsfiddle) his can probably be closed.

As for search, I can confirm that both focus-out *and* Enter are working fine.
