### ISSUE TITLE
Don't do ajax reload at stratup if records are provided

### ISSUE THREAD

**Issue by gadelat** [vitmalina/w2ui#892]
Currently, w2grid always reloads records at render time if url property is provided. For me, this is undesirable since splitting loading of grid to two http requests generates overhead (backend framework needs to load twice) and slows down considerably, but I still need later sorting and stuff through AJAX. My suggestion therefore is to not reload grid by AJAX at init time if both "url" and "records" are provided.

**Comment by gadelat** [comment]
I found this can be achieved like this: 
```javascript
$('#grid').w2grid({
		name: 'grid',
		columns: some_columns,
        records: some_records,
        onRefresh: function(bla) {
            this.url = some_url;
        }
});
```
I still think this should be default behaviour, though

**Comment by vitmalina** [comment]
Thanks for your suggestion. The easiest way is to not set url property when creating a grid. URL property can be set at any time after that and calling .reload() will trigger pull from the server. 

You can do this
```
$('#grid').w2grid(...)
grid.url = 'some_url'
grid.reload()
```

If url property is set, it does not matter if you set .records property, it will still going pull it from server.

On the other hand, the grid should pull records only one time when it is rendered (refresh does not pull records). If there is second request, I will track it down and fix. However, it is possible, you render grid twice.
