### ISSUE TITLE
single quote in w2grid recid prevents click-to-select?

### ISSUE THREAD

**Issue by tristenator** [vitmalina/w2ui#893]
hey vman, i'm not 100% sure on this just yet but i thought i'd go ahead and post it.

in 1.4.2 when one of my recid values contains a single quote, it appears i cannot click that row to select it.

ctrl-click-dragging a record prior and over the row allows it to be marked as selected and then normal behaviour, ie: getSelection, et al. work fine. so it appears to just be an initial click problem.

cheers

**Comment by vitmalina** [comment]
I have fixed this issue in current master branch. I think it is not worthwhile to fix it in 1.4.x branch.

**Comment by tristenator** [comment]
ok dude, thanks again
