### ISSUE TITLE
Allow to disable skipClicks

### ISSUE THREAD

**Issue by gadelat** [vitmalina/w2ui#895]
User experience of Master -> Detail demo is fine in w2ui 1.4.2 release, but it sucks in development version because of annoying focus behaviour. User needs to click twice in development version if he wants to select another row in another grid.

Reproduce like:
1. Click on first row in Master grid
2. Click on first row in Details grid
3. Click on second row in Master grid

Demo: http://jsfiddle.net/chaq7ssd/

**Comment by vitmalina** [comment]
Yes. Agree. However, I am dissatisfied how sub grids work. I will be refactoring it completely. Implementation in 1.4 branch is not very useful. I think it should be one grid, not another grid when you open up nested grid. It should be parent -> child records, not grids.

Thanks for putting jsfiddle.

**Comment by gadelat** [comment]
In my use case, I don't really use it in parent -> child relationship way. I show two grids with static data and user selects which rows in these grids should be paired together. Then he clicks the button, these rows disappear and process repeats until nothing is left to pair.

**Comment by vitmalina** [comment]
What about two grids side by side?

**Comment by gadelat** [comment]
Yes, that's how I'm doing it. I'm just saying that if you solve this issue by implementing parent-child mechanism, it may not help in my case (because it's unknown which records are childs of which records beforehand).

**Comment by ceedriic** [comment]
Hello vitmalina, first thanks for that great project!

I need to build a huge TreeTable (something like http://www.java2s.com/Code/JavaImages/SmartGWT-TreeTableWithFrozenColumnsSample.PNG).

I've seen that for some time you mentioned that subgrid is broken and that you're gonna redo it,  so I guess I need to wait for the new parent->child mechanism (I cannot use 1.4, timestamp field mostly).

I guess my questions are:
1) By parent->child mechanism, you mean an API like the Sidebar? that would be great.
2) Any idea when a working prototype will be available?
3) Is there something I can do to speed that up (test, donation, whatever)?

**Comment by vitmalina** [comment]
Yes, the idea for sub grids is as your screenshot. I have not scheduled time to work on it as of yet, and probably it is a few months out.

**Comment by mpf82** [comment]
In 1.5 it's not neccessary to click the grid(s) twice.

Updated fiddle: http://jsfiddle.net/chaq7ssd/1/

Tree-like grids are also part of 1.5

I'd say, this issue can be closed.
