### ISSUE TITLE
Auto-generated form drop-list width

### ISSUE THREAD

**Issue by koprulu** [vitmalina/w2ui#899]
This width seems to be computed from the longest item in the list. 

For long lists, the vertical scrollbar appears, and causes the horizontal scrollbar appear unnecessarily.

Would it be possible to increase the computed width by scrollbar width?

**Comment by vitmalina** [comment]
Good observation, I have noticed it too. Will fix.

**Comment by vitmalina** [comment]
Fixed this issue in the current master. There was already logic to adjust width based on scrollbar. I have just fixed it. I will keep an eye on it to make sure it works without unnecessary scrollbars.
