### ISSUE TITLE
http://w2ui.com/web/demos/#!grid/grid-21 has bug

### ISSUE THREAD

**Issue by pdavidow** [vitmalina/w2ui#900]
It appears that http://w2ui.com/web/demos/#!grid/grid-21 has bug:
If I simply tab through the fields (thus enabling inline editing), some
of the fields (Combo, Select) will show a small red triangle in upper
right indicating they have changed.  But nothing changed, only tabbing
occurred.

**Comment by edgarz** [comment]
I could not see this effects on firefox and chrome.
But if I try to change the colum list (with an existing contact), this change is ignored.

**Comment by pdavidow** [comment]
@edgarz I have the problem on Chrome browser. Simply double-click in top left grid cell and start hitting tab, and this is what I see:

![image](https://cloud.githubusercontent.com/assets/220924/7751198/bce71762-ffa6-11e4-9872-407be9c402a5.png)

**Comment by vitmalina** [comment]
I can repeat the issue. Will look into it. I have noticed that the drop down for example, did not have empty option, because of this it picked up first one. As for drop lists, they indeed did not work properly. Looking into it...

**Comment by vitmalina** [comment]
I have fixed in master branch. There were too many changes that make it hard to fix in 1.4 branch. Here is an example with new master branch http://jsfiddle.net/w9fvgog6/

**Comment by pdavidow** [comment]
I tried the fiddle, but tabbing isn't working properly.
