### ISSUE TITLE
Feature Request: Styling grid records with classes

### ISSUE THREAD

**Issue by deployable** [vitmalina/w2ui#904]
It would be much cleaner to add/remove classes to rows/cells instead of manipulating style strings. It's also a bit annoying that `style` becomes a reserved word for field definitions but I doubt that can be fixed. 

    record['style'] = 'background-color: #FFFFFF;'

Could be done as

    record['_custom_class'] = 'white-bg'

or to support multiple classes more easily. 

    record['_custom_class'] = [ 'white-bg' ]

This also allows the selected rows to be styled differently based on record rather than the single selection style current supported. 

Our use case really is to provide multiple styles based on a number of record fields so requires some calculation of the class/style for a record. This requires a function with access to the record

    record['_custom_class'] = ( record )->
      doSomeProcessingBasedOnRecordAndReturnTheClassName(record)

The same "class per column/field" setup could be used as `style` currently uses.

**Comment by vitmalina** [comment]
Now, we have a lot of customization items in the record array. All of them will be moving to w2ui object inside each record. So there will be no record.style, but record.w2ui.style, etc. I have converted some of them already. 

As for adding class, I think it is a good idea. Will do.

**Comment by deployable** [comment]
I'll PR the code I used in 1.4 to add string classes and classes derived from functions. It was fairly simple. 

Good to hear the w2ui scope has been added =)

**Comment by mpf82** [comment]
implemented as `record.w2ui.class = string/object` in 1.5, issue can be closed

**Comment by deployable** [comment]
@mpf82 thanks for the update.
