### ISSUE TITLE
Combo/list behaviour in editableField

### ISSUE THREAD

**Issue by sairum** [vitmalina/w2ui#906]
Editable fields are surely an important feature of grids. For "constrained" cell content (i.e., only a fixed set of values is allowed), drop down menus are a must, and w2ui has both combo, list and the HTML *select*. The problem with the two w2ui widgets is that:

* 'list' apparently expects a grid field of type object (e.g.  `{ id:0, text:'Example' }` ) which is not easily sortable
* combo also accepts lists of type `['first','second',etc.]`(unindexed) and thus work with textual values in grid cells. The problem with combo is that when the dropdown menu opens one has to type something, otherwise only the selected value appears... the 'showAll' option (which appears in 1.4 documentation) doesn't work anymore (but would be much appreciated!)

In this context, my aim is to have two tables:

1 'groups'  `{recid: text, color: color)`
2 'inds' `{recid: text, color: color [hidden], group: text}`
 
Table 'groups' defines a name (recid) and a color for groups, and new groups can be added. Names can be changed (except for the Default group) and colors are picked from a color picker. So far all is well...

Table 'inds' defines individuals which should be classified by 'groups'. The idea is to have an hidden column 'color' with the color of the group which name is in column 'group'. This way, the visible group's cell can be formatted to have the name of the group over a corresponding background color. Because the field is textual (not an object) one can sort individuals by group. But to use an editable cell of type 'list' with an underlying grid cell of type text all editing/saving stuff must be done manually on 'onChange' method of grid. Besides, I use the hack of nulling the 'changes' attribute of the record to avoid the 'red triangle', as I save the record automatically (to avoid usage of save button on grid)

The problem is that each time an 'inds' group is picked/changed, the list menu should be updated with all the items available in 'groups'. This is done on 'onEditField' method of 'inds' but then a strange behavior appears: sometimes the list menu has only 'Default', sometimes it has all the entries available in 'groups'. Look in Jsfiddle http://jsfiddle.net/sairum/tLwxsnxq/

Can anyone understand this problem? When I double clicked the cell slowly, most of the times it works as expected. But even then, the menu with only 'Default' pops up!

Antonio

**Comment by vitmalina** [comment]
I would appreciate if you use gituhub issue for bug submission, and not to express your opinion or struggles to make things work. Please use comments on w2ui.com and/or questions on stackoverflow.com for that.

**Comment by sairum** [comment]
That's right! My fault

Antonio

**Comment by vitmalina** [comment]
No problem. Sorry if I sounded rude. :(

**Comment by sairum** [comment]
Yep, I was a little disappointed. To tell you the true it made me search 
for a w2ui replacement, but the only option, so far, is JQuery UI or 
Bootstrap. Unfortunately, none of them implement the "logic" plus the 
simplicity of w2ui (e.g. using "in memory" objects) which makes the 
design of interfaces so easy! So, no hard feelings!

Did you ever consider the issue I was talking about? Because I think it 
qualifies as an issue. The combo behaves as expected (with both index 
and unindexed lists of items) but the 'list' apparently only accepts 
indexed lists to behave correctly (you can feed it with a simple list, 
but it will return an index object). I suppose this is responsible for 
the behavior showed in the JSfiddle. Sometimes the drop down menu of a 
list field gets updated with all items, sometimes only the value already 
in the cell does appear.

1) If you use a combo you don't need any of the hacks I used, everything 
works perfectly and is programmed cleanly. However, it is a pain for the 
user because it has to type in each entry.

2) If you use an object in the table, then the list behaves as expected 
(again with no hacks) but you cannot sort it without additional 
programming! Plus, rendering the cells is harder.

I'm in the verge of publishing a small software for force-directed 
network layouts using d3.js and w2ui. It reads a network file produced 
by a widely used program in biology and draws a beautiful network in SVG 
which is editable (users can change colors, make legends, delete nodes 
or links, etc.). So far I've implemented the second option, which works 
without issues, but I'm not glad with it as a user cannot sort the 
groups because they are objects in the grid.

Best regards

António

**Comment by vitmalina** [comment]
I see. Let me try to respond to your issues.

1. Sortable. Both list and combo expect an array. In the case of list you provide an array of objects of { id: , text: }. However, it is easily sortable with JS built-in .sort method of the array object, which take a comparison operator. Here is how you sort it by text values

```js
var items = [ { id: 1, text: 'some' }, { id: 2, text: 'another' }]
items.sort(function (a, b) { if (a.text == b.text) return 0; return a.text > b.text ? 1 : -1; });
```

2. As for showAll that was in 1.4 branch, it was deprecated in favor of compare function. What compare allows is to defined how you want to filter items on any property. The object does not have to have just id and text, it can have anything else in it. Id and text are used internally, but other methods will be carried along.

```js
$(...).w2field({ 
   type: 'list',
   ... 
   compare: function (item, search) { console.log(item, search); return true }
});
```

However, I do recognize that sometime filtering just need to be turned of, therefore, there is a property called filter and if set to false, it will not apply any filtering at all. So, instead of showAll: true, you can setup filter: false, and it would do that same thing. I thought that filter is a better name since it now uses compare function for filtering.

There was recently a pull request that fixed some problems in merging the records in the grid. See https://github.com/vitmalina/w2ui/pull/884. It might help you with grid editing.

I have updated your fiddle http://jsfiddle.net/tLwxsnxq/40/. Added filter: false there.

**Comment by sairum** [comment]
Dear Vital

The 'filter' attribute solved it, as it allows the combo to show 
everything. Therefore the associated grid field can be a 'string' and 
becomes sortable! The program is finished and I'm now writing the 
associated paper to be submitted to Molecolar Ecology. There I'll 
reference both w2ui and d3.js as two excellent javascript libraries! 
Let's hope it is accepted for publication...

Thanks for this great library!

Sincerely yours

Antonio

**Comment by vitmalina** [comment]
Great. Thanks for letting me know. Please send me a link when it is published.
