### ISSUE TITLE
Make the server API REST like

### ISSUE THREAD

**Issue by aadrian** [vitmalina/w2ui#909]
Please consider making the API REST like.

An example:
http://docs.sencha.com/extjs/5.1/5.1.0-apidocs/#!/api/Ext.data.proxy.Rest

This would allow a much easier W2UI integration in the different projects, languages and frameworks.

Thanks in advance.

**Comment by vitmalina** [comment]
You probably mean RESTFUL, not just REST API. Both are supported, see http://w2ui.com/web/docs/w2utils.settings and find dataType property. If you switch to RESTFUL, it will start sending all this **funny** verbs. I, personally, do not like restful as all it is is another level of complexity that is unnecessary. And in the same way as SOAP has died, RESTFUL will die. It will be just REST APIs.

**Comment by aadrian** [comment]
> Both are supported

Thank  you. I missed that line between the many locale settings :).

>  I, personally, do not like restful as all it is is another level of complexity that is unnecessary.

At least with ExtJS, using this mode, the integration with a server is trivial, no special connector is required. Many server implementations do this out of the box, so in the client only specifying the URLs is mostly enough.
