### ISSUE TITLE
Cell render method is called several times with same parameters

### ISSUE THREAD

**Issue by hansgru** [vitmalina/w2ui#910]
The cell render parameter seems to be called several times with the same parameters.
See here in the console log:
http://jsfiddle.net/607c0uxf/

I only added a console.log to this example: http://w2ui.com/web/demos/#!grid/grid-21

**Comment by vitmalina** [comment]
You console.log() was inside a for loop. Here is the correct version. http://jsfiddle.net/607c0uxf/1/

**Comment by hansgru** [comment]
> You console.log() was inside a for loop.

Yes, sorry: JSFiddle wrapping :(.
