### ISSUE TITLE
Multi-select in grid cell

### ISSUE THREAD

**Issue by hansgru** [vitmalina/w2ui#911]
Is it possible to have a "multi-select" in a grid cell ?
So the "Multi-Select" field from this example: http://w2ui.com/web/demos/#!forms/forms-2

in a Grid column?

Thank you.

**Comment by hansgru** [comment]
It seems that the search popup is accepting the 'enum' type, but the grid itself is not :( , it gives the following error :
```
ERROR: input types "enum" and "file" are not supported in inline editing.
```

**Comment by vitmalina** [comment]
Yes. Multi select in the inline editing is turned off. The reason is because it requires more space then just the column width. I have thought about implement it and played with it, but it did not feel and behave nicely (IMHO).

**Comment by hansgru** [comment]
> Multi select in the inline editing is turned off. The reason is because it requires more space then just the column width. 

One could require the user to give those columns more width, or render an elipsis button.

In most cases only a few values are required to be rendered, but not being able to do this at all is limiting: now instead of a simple editable grid, an extra "detail" form is required only to edit one field :( ).

The inline grid edit also allows to edit efficiently many fields before saving: having an extra form, breaks this too :(.

**Comment by aadrian** [comment]
Please turn the multiselect inline editing on.

We need this functionality too, and now are using other frameworks for those screens just to be able to achieve such behavior :(.

Regarding the place problem, I think the default behavior for the multiselect (in a grid or not) could be not to span new lines but to hide text on the left, like it happens now even with HTML text fields when the width is smaller than the text length.

Thanks in advance.

**Comment by vitmalina** [comment]
In the grid.js, comment out these lines:
```js
            if (['enum', 'file'].indexOf(edit.type) != -1) {
                console.log('ERROR: input types "enum" and "file" are not supported in inline editing.');
                return;
            }
```
line 2210-2213, and see how it behaves.

**Comment by aadrian** [comment]
> In the grid.js ...line 2210-2213, and see how it behaves.

Unfortunately it's not working correctly: 
  - it's not rendering as in a form
  - I can select one element, but it's constantly hiding, so I can't select another one.
  - It picks wrongly when a field "value" changed

I did the change and added an example: https://github.com/aadrian/w2ui/commit/9d806636ef78159d11b0310d66abb2c765b59c24
grid-27 in the 'https://github.com/aadrian/w2ui/tree/multi_select_grid' branch
(it's based on the grid-21 example with an extra 'enum' column only)

**Comment by gpetrov** [comment]
Will this ever be addressed? It will be very valuable - please reopen and implement

**Comment by jonny64** [comment]
Please reopen limited implementation at least
