### ISSUE TITLE
Grid captions to be required only once?

### ISSUE THREAD

**Issue by hansgru** [vitmalina/w2ui#913]
IMHO the Grid column captions should be required only once: in the column definitions.
If the ```searches:[ ]```property is used, and no captions are defined, than "undefined" is displayed as a label for each field:
http://jsfiddle.net/dj38qcm7/

This ```caption``` property in 'searches' should be optional, and only as an override if the column's ```caption``` property should differ from the searching popup (e.g. in the grid there's not enough width and an shorter version is used).

Thank you.

**Comment by vitmalina** [comment]
Fixed the undefined issue, however, I disagree that search captions should match columns.

**Comment by hansgru** [comment]
>  however, I disagree that search captions should match columns.

Not always, but in most cases it is: in most business applications the users are too used to Excel, and expect those columns to match exactly.

**Comment by vitmalina** [comment]
When defining a column, you can specify 
```js
{..., seacharable: true } 
// OR
{..., seacharable: 'date' } 
```
and if you do, it will auto create search. See http://w2ui.com/web/docs/w2grid.columns

**Comment by hansgru** [comment]
@vitmalina 
> When defining a column ... it will auto create search

Thank you for the example, but is it possible to define this way inline to the column further search options too ?  For simple examples like yours, I was already using the inline mode, but we have fields where selects or multi-selects are required for filtering.

**Comment by vitmalina** [comment]
Interesting, but the idea was that if search is simple, then added a field in column definition makes it quick and easy to define search in one line.

**Comment by vitmalina** [comment]
I have added logic if searchable is an object, then it will create search based on it adding column.field and column.caption.
