### ISSUE TITLE
Select item not working in w2ui.sidebar.topHTML

### ISSUE THREAD

**Issue by mretich** [vitmalina/w2ui#915]
When I use a <select><option>whatever</option></select> field inside the w2ui.sidebar.topHTML then the select do not open.
(Dropdown is not showing)
This works in 1.4.2 & 1.4.x (nightly) flawless.

For what i can say, this is not a CSS issue. CSS 1.5 and w2ui 1.4.x JS is working.
CSS 1.4.x and w2ui 1.5 JS or CSS 1.5 and w2ui 1.5 JS is not working.

Hope you understand what i´m talking about :)

**Comment by vitmalina** [comment]
Yes, indeed it was not working. The reason is that now sidebar has a focused state and clicking on topHTML will focus sidebar. I have fixed that so that if there is a control, then it retains focus and sidebar does not get focused
