### ISSUE TITLE
Grid Add should show new row

### ISSUE THREAD

**Issue by pdavidow** [vitmalina/w2ui#916]
If I have a grid list extending past the bottom of the visible grid, a newly added row will not be visible. It should be.

In addition, clicking toolbar Add in http://w2ui.com/web/demos/#!grid/grid-17 does not (apparently) add anything.

**Comment by vitmalina** [comment]
1. I do not understand what you mean by "If I have a grid list extending past the bottom of the visible grid, a newly added row will not be visible". Grid implements virtual scrolling and it might not be in the doc if you have lots of items. But it will be when you scroll
2. This example just demonstrates how to add a "Add" button and wire events to it. You will need to code the logic of it.

**Comment by adilek** [comment]
You can call the w2ui.grid.scrollIntoView() method after adding the new row for achieving what you want.

**Comment by vitmalina** [comment]
Closing this issue as it appears to be abandoned by original author.
