### ISSUE TITLE
w2sidebar scrollIntoView is not always scrolling far enough

### ISSUE THREAD

**Issue by TrevorPT** [vitmalina/w2ui#917]
In a sidebar with many items, scrollIntoView doesn't always scroll far enough.  
see http://jsfiddle.net/mtnsutso/

1. click on "goto 0", selects node0
2. click on "goto 10", selects and scrolls to node10
3. click on "goto 99", selects node99 but only scrolls about 10 items
4. click on "goto 0", selects node0 but only scrolls back to around node10

This was using w2ui 1.4.2, with either Chrome or nw.js 0.12.0

In scrollIntoView: function (id) is
```javascript
if (offset + item.height() > body.height()) {
    body.animate({ 'scrollTop': body.scrollTop() + body.height() / 1.3 }, 250, 'linear');
}
if (offset <= 0) {
    body.animate({ 'scrollTop': body.scrollTop() - body.height() / 1.3 }, 250, 'linear');
}
```
I think this should be
```javascript
if (offset + item.height() > body.height() || offset <= 0) {
    body.animate({ 'scrollTop': body.scrollTop() + offset - body.height() / 2 }, 250, 'linear');
}
```
as in either case, the offset from the current scrollTop is already calculated.

I'm unsure what `body.height() / 1.3` was intended to do, I'm thinking it was to not just move the item to the top of the tree when scrolling forward; by using `+ offset - body.height() / 2` it moves the item approximately to the centre.

Thanks for a terrific UI library, it fit well into our nw.js project.

**Comment by vitmalina** [comment]
You are right, there is a bug. I have fixed it with your suggesting, just added item height into equation. The reason for 1.3 was is when you use keyboard to go down, it would scroll 70% of the height. Same when going up. A bit more then half.
