### ISSUE TITLE
grid column resize handle floats away from cursor

### ISSUE THREAD

**Issue by pdavidow** [vitmalina/w2ui#923]
Try resizing Grid column in
http://w2ui.com/web/demos/#!grid/grid-11
The cursor does not stay attached to the resize handle.

Same problem for Layout handles: http://w2ui.com/web/demo

**Comment by vitmalina** [comment]
I do not understand what you mean. Can you provide a screenshot or a video? 

Resize handle has css property cursor, and as you move it should move with it. I checked in Chrome/FF on mac and it seems to be fine.

**Comment by pdavidow** [comment]
What I meant was that mouse cursor does not remain on column break when column is resized, but rather shifts off considerably.

**Comment by vitmalina** [comment]
Grid does not move mouse cursor in javascript. I have no clue what's going on.

**Comment by myidol** [comment]
how can I change the width of box in this libary?? I mean In my box I have button and I want when the user click on this button suddenly the box change width (100%=>50%) or inverse

**Comment by vitmalina** [comment]
Closing due to poor description of the problem.
