### ISSUE TITLE
Controlling record visibility in grid

### ISSUE THREAD

**Issue by blinskey** [vitmalina/w2ui#924]
Is there any way to manually toggle the visibility of a record in the grid? I'd like to implement a filtering mechanism that would temporarily hide certain records without actually deleting them.

Thanks for the great library!

**Comment by aadrian** [comment]
> Is there any way to manually toggle the visibility of a record in the grid?

Since W2UI does not have a ```DataStore``` *(e.g. like ExtJS)* that the users could configure/override, the only way I can think about is not to use the ```url``` property of the grid, but in your own code to load the ```record``` array with data you want to display from a separate source. There, in your separate source you could filter stuff and re-render.

**Comment by blinskey** [comment]
Thanks for the suggestion! I'm doing something similar right now by manually saving and removing records and then restoring them after the filter is cleared. The only problem with these sorts of approaches is that this is an editable grid, so we need to preserve changes to filtered-out records and restore the full set of changes before submitting them to the server -- workable, but less than elegant.

**Comment by vitmalina** [comment]
You can use same thing internally used for local search. If you set grid.last.searchIds, add something to searchData array and refresh, it will do the trick
```js
w2ui.grid.last.searchIds = [5, 6];  // note, this is not recid, but index in grid.records array
w2ui.grid.searchData = [1]; // does not matter what is here, just need to be non empty array
w2ui.grid.refresh()
```

**Comment by blinskey** [comment]
Thanks!

On Sat, Jun 6, 2015 at 12:24 PM, Vitali Malinouski <notifications@github.com
