### ISSUE TITLE
Feature request: nullable or empty values on grid search.

### ISSUE THREAD

**Issue by polkduran** [vitmalina/w2ui#925]
It would be great to have an option to be able to perform a search with empty values (nullable types).
Maybe a checkbox "empty value" and an option on the column and searches objects (allowEmpty).

![image](https://cloud.githubusercontent.com/assets/4704913/7981465/fa80bfbe-0aa6-11e5-8ef4-144d54441171.png)

Use case, we integrated the w2ui grid (which is great by the way) and we want to perform a search for empty values within a column but we are not able to do it.

Thanks.

**Comment by aadrian** [comment]
@polkduran 
Those values are also needed, but I don't think that using checkboxes is the best idea.

Look at this query builder (filter) component:
http://mistic100.github.io/jQuery-QueryBuilder/
![jquery_builder_null_exmple](https://cloud.githubusercontent.com/assets/140953/8004947/e43f61ae-0b84-11e5-8be1-3e124f29c2ab.png)


It's much better when these options are **the operator**. This way is also much easier to convert the search parameters to a Query.

**Comment by polkduran** [comment]
@aadrian yes you are right, that seems a better option to support nullable values and maybe much more simpler to integrate.

**Comment by vitmalina** [comment]
I have implemented these filter, but by default they are turned off. You will need to turn them on by setting show.searchNull to true. The reason they are turned off by default is because for a regular user they will look cryptic but I want clean user experience for non-programmers too.

**Comment by polkduran** [comment]
Great, thanks @vitmalina, as we are using version 1.4 I didn't find the option.
Can we consider the master branch as stable? or is there a roadmap for version 1.5?
We would like to migrate to the latest version to have this option (nullable) as the 'less' and 'more'.

**Comment by vitmalina** [comment]
Current master branch is not stable yet. It will be 1.5 some time in the future.
