### ISSUE TITLE
How test w2ui?

### ISSUE THREAD

**Issue by hansgru** [vitmalina/w2ui#931]
I saw that there's a ```/qa``` and a ```/test``` directory, but still don't really have an idea how is w2ui tested or is supposed to be tested, how is the coverage, regression, etc. ?

Or is there another project responsible to test w2ui automatically ?

**Comment by vitmalina** [comment]
There are some unit tests in /qa folder, it uses qunit for it. I think there are about 300 tests. The coverage is not complete, but it is a good start. In the /test directory there are sample grid, form, popups that I use for manual testing, especially when adding features.
