### ISSUE TITLE
Record "editable:false" does not work for columns of type "checkbox"

### ISSUE THREAD

**Issue by hansgru** [vitmalina/w2ui#932]
Record "editable:false" does not work for columns of type "check" :(.

See http://jsfiddle.net/xLgp2Ltb/  where the first two rows/records should not be editable: the check column is still editable, not just visually, but also the "Get Changed" button will output those changed values.

**Comment by vitmalina** [comment]
Fixed in both current master and 1.4.x branch. You can download latest from /dist folder in corresponding branch.
