### ISSUE TITLE
Incorect post data when multiple toggle fields in form

### ISSUE THREAD

**Issue by githabas** [vitmalina/w2ui#934]
Here jsFiddle that explains the issue http://jsfiddle.net/5ncv1rb7/12/

Set "Enabled" to true, "Active" to false. Press "Save". Form post data sent:
record[active]	0
record[enabled] true

Set "Enabled" to true, "Active" to true. Press "Save". Form post data sent:
record[active]	true
record[enabled] 1

Set "Enabled" to false, "Active" to true. Press "Save". Form post data sent:
record[active]	1
record[enabled] false

***
I would suggest changing 
`value_new = ($(this).prop('checked') ? true : false);`
to
`value_new = ($(this).prop('checked') ? 1 : 0);`

I'm not quite sure if this fully fixes the issue but for me it works fine now.

**Comment by loxiw** [comment]
```javascript
case 'toggle':
                        if (w2utils.isFloat(value)) value = parseFloat(value);
                        $(field.el).prop('checked', (value ? true : false));
                        this.record[field.name] = (value ? 1 : 0);
                        break;
````
