### ISSUE TITLE
'select' field does not render

### ISSUE THREAD

**Issue by koprulu** [vitmalina/w2ui#936]
'select' field does not render in auto-generated forms. It is displayed as an empty text input instead.

Interestingly it shows up in the demo page : http://w2ui.com/web/demos/#!forms/forms-2
but not in the fiddle link in the same page.

Looking at the source code, one expects to see '<select>' tag generated, but  inspector shows 

```html
<input id="field_select" type="text" name="field_select">
  <option value="fist"></option>
  <option value="second"></option>
</input>  
```

**Comment by vitmalina** [comment]
If you set 
```
$(field).data('selected', { id: 1, text: 'some' });
```
you need to refresh it too
```
$(field).w2field().refresh();
```

**Comment by koprulu** [comment]
The issue is not related to selection. It is about the the 'select' type field not showing up at all.
