### ISSUE TITLE
[1.5 nightly] getCellHTML use wrong date format

### ISSUE THREAD

**Issue by n3tfr34k** [vitmalina/w2ui#939]
![ChromeDev](http://fs2.directupload.net/images/150615/ipfj8bhm.png)

w2utils.formatDate(unixTimestamp, formatString) called with formatted date instead of unix timestamp.

Using dd.mm.yyyy format and the the sends something like this (unix timestamp):

```
records: [
   {LFDNR: 1, F1STR: "jkjkjkjk", F1NUM: 2, F1DATE: 1433030400000, F1CHAR: "1",…}, ...
]
```

**Comment by n3tfr34k** [comment]
Ok it's not a bug from the library. I think, the date format from the server should be the same like in the w2ui configuration.

So I managed to send the same date format like in the locale settings from the grid. Now it works like a charm, but german localization is messed up. When I choose a date with the datepicker 'dd.mm.yyyy' the library convert it to 'mm.dd.yyyy' format and breaks.

**Comment by n3tfr34k** [comment]
This commit should solves the problems with some date formats. Also the en-us.json date_format was different from the default in w2utils.js.

**Comment by vitmalina** [comment]
Fix for this is coming in https://github.com/n3tfr34k/w2ui/commit/74c45580fcc79e7d33fd817d31c352bbce64c3be, I am going merge it, so, I am closing this request. Thanks.
