### ISSUE TITLE
Toolbar and Tabs out of view

### ISSUE THREAD

**Issue by seduardo** [vitmalina/w2ui#94]
When the window or popup window is small neither toolbar or tabs has how scroll it to see that elements out of window.

**Comment by dpmcmlxxvi** [comment]
Any progress on this? How about grouping out-of-view toolbar items into a drop down menu?

**Comment by mpf82** [comment]
> Any progress on this? How about grouping out-of-view toolbar items into a drop down menu?

The current 1.5 master supports scrolling left/right in the toolbar if the items don't fit in the visible area.

![2016-02-17 09_27_46-nemetris web template - v0 5](https://cloud.githubusercontent.com/assets/10152404/13103755/e1baa68e-d558-11e5-9f28-0958825341df.png)

**Comment by dpmcmlxxvi** [comment]
Ah, should have updated before commenting. Thanks.

**Comment by dpmcmlxxvi** [comment]
This works if the toolbar is added to the panel's "toolbar" property. It doesn't seem to work if a toolbar is added as the panel's content.

**Comment by mrg2001** [comment]
Yes, it is implemented in current master branch. Closing the issue.
