### ISSUE TITLE
Add a way to load a tab from url

### ISSUE THREAD

**Issue by Delgan** [vitmalina/w2ui#945]
I wondered if it was possible to add a method to load the contents of a tab from the result of an ajax request?

This function is available for the popup module and is very useful, it would be just as much for w2tabs.

**Comment by vitmalina** [comment]
I see. However, the tabs do not have content div, like layout or popup. It will not know where to load it. I think you can just use a layout. A panel in the layout supports tabs and then layout has load method. Thanks for suggestion, though.
