### ISSUE TITLE
How to get first recid of a grid.

### ISSUE THREAD

**Issue by Ramkumarvannappagari** [vitmalina/w2ui#947]
How to get first recid of a grid after any action like Search or Sort performed in W2ui grid. I want to select first row of grid every time when grid is refreshed.

**Comment by ppearson111** [comment]
+1.  This will be very handy to know.  Thx.

**Comment by Ramkumarvannappagari** [comment]
Thanks for update on this issue Mr.Paul.

**Comment by vitmalina** [comment]
This is no method, but it could be this.
```js
function selectFirst(grid) {
	if (grid.last.searchIds.length == 0) {
		grid.select(grid.records[0].recid);
	} else {
		grid.select(grid.records[grid.last.searchIds[0]].recid);
	}
}
```

**Comment by Ramkumarvannappagari** [comment]
Thank you so much Mr. Vitali Malinouski, How can we call this i mean, what is grid parameter here.

**Comment by vitmalina** [comment]
what ever $().w2grid(...) returns
