### ISSUE TITLE
Release v1.4.3 ?

### ISSUE THREAD

**Issue by hansgru** [vitmalina/w2ui#948]
Please release v1.4.3 

We can't use Bower directly from the 1.4 branch (bower supports this), because the w2ui project "published" in the Bower repo is:
https://github.com/vitmalina/w2ui-dist
not 
https://github.com/vitmalina/w2ui

Thank you.

**Comment by vitmalina** [comment]
The reason I created w2ui-dist is because if you install with bower, it will bring all the repo. All the help files, test, etc. Which I felt was not necessary. I will release 1.4.3. soon. Thanks.

**Comment by aadrian** [comment]
> The reason I created w2ui-dist is because if you install with bower, it will bring all the repo.

If you also use Bower for **w2ui**, instead of **w2ui-dist** , than the files in ```w2ui/libs/``` can be excluded from Git, so the repo will be smaller.

**Comment by aadrian** [comment]
see https://github.com/vitmalina/w2ui/pull/961
