### ISSUE TITLE
grid select row fron array

### ISSUE THREAD

**Issue by chalchis** [vitmalina/w2ui#949]
hello
I'm trying to select records from an array
but it does not work me

this is work
w2ui['gridmaterias_planacad'].select(0,1,2);

i`m usiing v 1.4.2

 ```javascript
//my code
	w2ui['gridmaterias_planacad'].on('load', function(target, eventData) 
       	{
       		eventData.onComplete = function()
       		{
		    	//resultado
			    var resultado = jQuery.parseJSON(eventData.xhr.responseText);

			    //preguntar si hay algo que seleccionar
			    if (resultado.preseleccionar.length > 0)
			    {
			    	//separar array en comas
			    	var recid_seleccionar = resultado.preseleccionar.join();
			    	console.log(recid_seleccionar);			    

			    	w2ui['gridmaterias_planacad'].select(recid_seleccionar);
			    }
			}
		});

```

I hope you can help me
I welcome your comments

**Comment by loxiw** [comment]
I think you're sending an string (which .select() isn't able to read)

**Comment by chalchis** [comment]
a temporary solution that I do not like

´´´javascript
w2ui['gridmaterias_planacad'].on('load', function(target, eventData) 
       	{
       		eventData.onComplete = function()
       		{
		    	//resultado
			    var resultado = jQuery.parseJSON(eventData.xhr.responseText);

			    //preguntar si hay algo que seleccionar
			    if (resultado.preseleccionar.length > 0)
			    {
			    	//recorrer
			    	for (var i = 0; i < resultado.preseleccionar.length; i++) 
			    	{
			    		w2ui['gridmaterias_planacad'].select(resultado.preseleccionar[i].recsel);
			    	}		    			    	
			    }
			}
		});
```

**Comment by vitmalina** [comment]
Here is how to do it
```js
grid.select.apply(grid, [1,2,3]);
```
Looks pretty for me :)

**Comment by chalchis** [comment]
excellent work!!!!
