### ISSUE TITLE
Limit Scrollspeed by wheel or click

### ISSUE THREAD

**Issue by tausday** [vitmalina/w2ui#952]
Hello,

at first i must tell u that i like u're grid. it has a very good performance an many supported functions.
But if a user scrolled by wheel or clicked on overflow Y buttons the grid shoud scrolled only one row at this time.

It is possible to add this function?
Add the moment the scroll speed is set from OS

Thanks for help

**Comment by tausday** [comment]
Hello,

i habe searched a little bit to find my own "help"

Here is an example for scrolled by wheel only one row


```javascript
dieses_grid = document.getElementById("grid_auftragsliste_records"); //find the grid from w2ui
dieses_grid.addEventListener('mousewheel', wheel); //define the eventlistner for  IE9, Chrome, Safari, Opera
dieses_grid.addEventListener('DOMMouseScroll', wheel);  //eventlistener for Firefox :/ Firefox

function wheel(event) {
	console.log("TEST");
    var delta = 0;
    if (event.wheelDelta) delta = event.wheelDelta / 120;
    else if (event.detail) delta = -event.detail / 3;

    handle(delta);
    if (event.preventDefault) event.preventDefault();
    event.returnValue = false;
}

function handle(delta) {
    var time = 1;                    //Speed of scroll
	var distance = 17;       //distance by one scroll by mouse(row height)
    
    $('#grid_auftragsliste_records').stop().animate({
        scrollTop: $('#grid_auftragsliste_records').scrollTop() - (distance * delta)
    }, time );
}

```

Now we only must add an Listner for scrollbuttons :).

I Hope u add something like this to u're code

**Comment by vitmalina** [comment]
Since no further response, closing the issue.
