### ISSUE TITLE
PHP MySQLi extension support

### ISSUE THREAD

**Issue by kn007** [vitmalina/w2ui#954]
Hello, maybe w2ui could support the mysqli extension, because the mysql extension has been deprecated since PHP 5.5. The mysqli or PDO extension should be used instead. The mysql extension has been removed since PHPNG(PHP 7) .
I am write a new one(w2db.php) to support the mysqli extension. :)
https://github.com/kn007/w2ui-w2db-mysqli.php
Thank you.

**Comment by vitmalina** [comment]
w2db.php is not part of this project. This is more just like an example how to do it. Plus it is not actually scope of this project. :)

**Comment by kn007** [comment]
Got it, Thank you. 
Actually I created this issue just want to help people in need.

**Comment by vitmalina** [comment]
Sure, it sounds good. Thanks.

**Comment by bwl21** [comment]
> Got it, Thank you.
> Actually I created this issue just want to help people in need.

HI, did you rewrite w2db.php to make use of PDO? I am facing the same problem now, and wonder if somebody has already done this.

**Comment by bwl21** [comment]
Hi @kn007, did you rewrite w2db.php to make use of PDO? I am facing the same problem now, and wonder if somebody has already done this.
