### ISSUE TITLE
How to style W2UI grid table? I want to add borders to column headers and different colours to particular cells. Please help

### ISSUE THREAD

**Issue by rajb21** [vitmalina/w2ui#955]

**Comment by aadrian** [comment]
> and different colours to particular cells.

Row formatting examples:
http://w2ui.com/web/demos/#!grid/grid-2

Cell formatting examples:
http://w2ui.com/web/demos/#!grid/grid-23
by defining a renderer and there you can add a div/span with a specific ID or class to have a particular style.

> I want to add borders to column headers
For this you would need to override ```.w2ui-col-header``` for all columns.

If you want to address individual column headers, you can use the "col" property as a CSS selector. See here:
http://jsfiddle.net/s3yxvytm/

with: 
```css
td[col="1"].w2ui-head {
    border:solid 3px black !important;
}
```
you can select the data column 1 and style it with a different border.

**Comment by rajb21** [comment]
Thanks for the reply.Its working fine.. :)

**Comment by vitmalina** [comment]
@aadrian - thanks for answering this question
