### ISSUE TITLE
Local Sort but remote data?

### ISSUE THREAD

**Issue by hansgru** [vitmalina/w2ui#956]
Is it possible to have remote data but local sort ? I couldn't find out how to configure such a scenario.

This is especially required for inline editable grids: the data must be remote: to be able to load and save it, no paging is required (since the user edits the data and must see the changed cells), but  the user should be able to multi-sort so that it can easier figure out what to change.

Thank you.

**Comment by edgarz** [comment]
just delete url attribute, and you are local.
i did it like that:
grid.backup_url = gird.url:
delete grid.url;
...
manage the local things
...
grid.url = grid.backup_url ;

**Comment by hansgru** [comment]
@edgarz 
Thank you.

It is a very ugly hack though :), and I'm not sure that I can cover all the situations, since the user can reload the grid, filter, etc.

**Comment by edgarz** [comment]
i think the ugly hack is not to decide if you are remote or not!

**Comment by edgarz** [comment]
on the other hand, if you reload data, changes are lost too, so you have to to ask if record.changes is empty or not before.

**Comment by edgarz** [comment]
i think you should have a look on your use-case before asking for un-needed features.
....but i have seen similar questions several times.
i had the same issue, when i tried to re-render a grid that i dismissed before, and wanted to get the old sort, the old filters...
i think this was a use-case, as i had to manage millions of records with long query-times.
and vitali helped me with this hack.
i think your solution would be to use the event onChange, to set your data to be local, and onSave change it back to remote.

**Comment by hansgru** [comment]
@edgarz Thank you for the details.

> i think you should have a look on your use-case before asking for un-needed features.

I don't think this is an "un-needed" feature :). I used it in **all** projects so far and it is present in other RIA  frameworks where the user can fine-tune if the ```sort/search/filter/highlight/paging``` is remote or local, independent on the ```load/re-load/save``` operations. 

> i think your solution would be to use the event onChange, to set your data to be local, and onSave change it back to remote.

Thank you very much. I'll use for now this trick. 

I still think that something like:
```javascript
{
  sortMode: 'local' // allowed values: 'local' or 'remote'
  // ,filterMode: 'local'
  // ,'pagingMode: 'local'
}
```
would be self describing and user friendly :).

**Comment by edgarz** [comment]
you can do it easyly.
just do the prototype on w2uigrid, it is expandable.
something like
w2uigrid.prototype.sortmode = function(mode){
   this.onSort = function(){}
}
... ok, it will not be so easy, but i did some hacks like this before....
for me, i love w2ui, as there is no pagination, and i can work on full datasets, everything reflected by server-data.
how can you exspect your users-aim to sort or filter on the little data-part they see in the moment?

**Comment by edgarz** [comment]
on the other hand, you could change to really local datasets.
do an onLoad, and an onSave (push the record-changes in it) ajax call.

**Comment by hansgru** [comment]
> how can you exspect your users-aim to sort or filter on the little data-part they see in the moment?

That's unfortunately a requirement in many business applications. Sometimes there are many columns, the data in cells is complicated, or there are just more rows than would fit on the screen, so the users need these features while inline editing.

> i love w2ui, as there is no pagination, and i can work on full datasets, everything reflected by server-data.

I also like that functionality very much and was using it with ExtJS even before w2ui had it, but in many cases really does not depend on me as a developer but what the customers request.

**Comment by edgarz** [comment]
but i still think, the problem is not w2ui but your application design.
i worked with tables with over 100 complex columns, and every application has to decide weather to work local or remote.
the user has to know if sort is local or remote...
ok, if i fetch all the rows, it makes sense.

by the way where do you come from?

**Comment by hansgru** [comment]
> ok, if i fetch all the rows, it makes sense.

Exactly. After automatically filtering the data on the server based on "user rights" in many grids the remaining number of rows is not that huge, so the user can work more like it is used to work with Excel: inline (with the added benefit that some rows or even cells can be easily made read-only). Till ~2000 rows seems to work without problems with actual browser and hardware, even if the user has several browser tab with such grids.

> by the way where do you come from?

DE, but doing projects in FR, NL and UK too :).

**Comment by edgarz** [comment]
write me an email: ezwischenbrugger@gmail.com
i have same fun with customers...
i did a great excel and pdf client based export, maybe interesting for dich.

**Comment by edgarz** [comment]
vienna

**Comment by edgarz** [comment]
Hab da mal nen Java-rest-service, der 1:1 entity vs. w2ui mappt. hab deinen mirage gesehen, könnte ja irgendwie dieselbe idee sein.

**Comment by edgarz** [comment]
mein approach ist einfach.
DB = w2ui!
meine idee ist einfach, dass ich eine db ohne code ins w2ui bekomme, 
klar aber nicht unumgänglich ist noch der entityManager, den man aber über eclipslink auch dynamisch machen könnt

**Comment by hansgru** [comment]
> Hab da mal nen Java-rest-service, der 1:1 entity vs. w2ui mappt.

Wir haben Grails Scaffolding benutzt: http://blog.toubiweb.com/getting-started-with-grails-scaffolding/
Ein komplettes DB-Modell kann so mit ExtJS oder KendoUI (oder w2ui bald) als GUI generiert werden.
Ich darf leider den Generator nicht publizieren (der Kunde will es nicht :( ).

> hab deinen mirage gesehen, könnte ja irgendwie dieselbe idee sein.

Das Mirage=Projekt gehört https://github.com/takezoe . Mirage ist sehr praktisch um SQLs auszulagern (DB-Spezialisten können getrennt arbeiten), oder auch für dynamische SQLs (dynamic als SQL kommentar)

**Comment by hansgru** [comment]
> mein approach ist einfach.
> DB = w2ui!

https://github.com/vitmalina/VitsDB ?

> meine idee ist einfach, dass ich eine db ohne code ins w2ui bekomme

Wir müssen den Code leider generieren, da es immer wieder ausnahmen gibt, also braucht man immer wieder Anpassungen :) )

**Comment by edgarz** [comment]
Genau das mach ich,so wie gwt.
Am 23.06.2015 17:45 schrieb "Hans" <notifications@github.com>:

**Comment by vitmalina** [comment]
I see you switch to German (I think), which I niht firshtein. I hope the issue was resolved. Please reopen it if not. As for VitsDB - it is really, really old. Like 5 years old. Never had time to finish it. :)

**Comment by neoedmund** [comment]
8 years passed, and it's my first time trying to use w2ui. thanks for the lib.
I think the needs is straightforward, and should save alot of time when a query on server side takes some time.
But I also find that when I load 2000+ records, the json size is 300KB, the request takes about 50 ms, but the delay can be seen by eyes are coming from the re-rendering of the grid. So I guess the hack also needed to improve the rendering performance...
Of course, it's enough if we can choose to use small sized data.
Thanks all.
