### ISSUE TITLE
w2utils.locale() allow Object as parameter

### ISSUE THREAD

**Issue by hansgru** [vitmalina/w2ui#957]
In w2utils.locale() please allow an Object as parameter too.
In this case it should simply use it as a 'settings' object.

So if the 'locale' parameter is an object other than a String, than a function like the 
'success' function should be called with 'locale' instead 'data' parameter.

This would allow to avoid a server roundtrip and an easier customization.

Thank you.

**Comment by aadrian** [comment]
See the change in this branch:
https://github.com/aadrian/w2ui/tree/locale_as_object_setting

this commit more precisely:
https://github.com/aadrian/w2ui/commit/86117d056c7be4a7dba31ce7e1307af948b78517

**Comment by vitmalina** [comment]
Changes look great. I took the liberty to merge them into master from your branch. Thanks.
