### ISSUE TITLE
Locale for Date does not seem to work at all for 1.4.2 :(

### ISSUE THREAD

**Issue by hansgru** [vitmalina/w2ui#963]
Changing the locale for Date does not seem to work at all for 1.4.2 :(
I used the standard inline example, loaded the 'de-de.json' locale, changed to formatting to correspond with the one in the locale (and removed some columns for readability)

http://jsfiddle.net/wew2x23d/3/

It does not seem to work however: not for rendering, but also not when editing a field :(.

**Comment by n3tfr34k** [comment]
It is fixed in master branch for 1.5 version.

**Comment by hansgru** [comment]
> It is fixed in master branch for 1.5 version.

Thank you for the information.

Unfortunately 1.5 does not seem to be released soon :(.

**Comment by vitmalina** [comment]
You need to download locale files from 1.4.x branch, as there were some changes in current master in regards to data. Here is a link for you https://github.com/vitmalina/w2ui/blob/w2ui-1.4/src/locale/de-de.json

**Comment by vitmalina** [comment]
Close this issue if it works.

**Comment by hansgru** [comment]
it works with the unpublished 1.4.x branch.

**Comment by vitmalina** [comment]
I released 1.4.3. Now you can download it from website or using bower. All fixes should be there.

**Comment by hansgru** [comment]
Fantastic! It all works now. Thank you.
