### ISSUE TITLE
[REQ] Want pagination back. 

### ISSUE THREAD

**Issue by keekun** [vitmalina/w2ui#964]
Thank you for your excellent library.

I implemented v1.4.2 into our team's internal management system, but it performed very slow and lag when I put all 7000+ local records with more than 40 columns. At last, I turned back to 1.2.1, which is smooth and excellent.
I know v1.4.2 can scroll well on a large amount of rows and a few columns, but it seems cannot handle large column amount very well.
Infinity scroll is very cool, but somebody like me would be happy if pagination can be optional.

**Comment by vitmalina** [comment]
Column virtualization is coming. I also need it right now for a project where number of columns should be up to 702. I would say within a month. 

As for pagination, I am determined not to return it. However, I have some pointers for you. In current master, there are two more grid properties: vs_start and vs_extra. They define when virtualization will kick in and how many extra records to display on top and bottom.
