### ISSUE TITLE
Can not activate tabs of an inner layout

### ISSUE THREAD

**Issue by fatihgenc** [vitmalina/w2ui#965]
Tabs element of the main layout works but tabs of inner layout not became active. 
I created a fiddle that demonstrates the issue
http://jsfiddle.net/u7j4v0nd/1/

**Comment by vitmalina** [comment]
You mean you click on the left tab and it is not making it active, right? Confirmed. Will look.

**Comment by mpf82** [comment]
Issue still exists in 1.5

Updated fiddle with 1.5 sources: http://jsfiddle.net/u7j4v0nd/4/

**Comment by mrg2001** [comment]
I spent a few hours trying to fix it, but failed. Any help appreciated.

**Comment by fatihgenc** [comment]
Issue disappeared with jquery >= 2.2.2
http://jsfiddle.net/u7j4v0nd/5/

**Comment by mpf82** [comment]
Closing issue: fixed with JQuery 2.2.2+, cannot reproduce with JQuery 3.4.1 either
