### ISSUE TITLE
onRender sidebar call twice

### ISSUE THREAD

**Issue by igorhaf** [vitmalina/w2ui#971]
```javascript
$('#sidebar-components').w2sidebar({
        name: 'sidebar-components',
        nodes: [],
        onRender: function (target, eventData) {
        	eventData.onComplete = function () {
        		console.log("test");
        	}
	    }
    });
```
result:
test
test

**Comment by vitmalina** [comment]
I have checked in current master branch - all is good. On render is called one time. Can you provide what version you use and also create a jsFiddle for it.

**Comment by vitmalina** [comment]
Since no further response, closing the issue.

**Comment by omiinaya** [comment]
my onRenders are also called twice...
