### ISSUE TITLE
Doubleclicking a row in the re-order demo breaks the function

### ISSUE THREAD

**Issue by Connum** [vitmalina/w2ui#972]
Go to http://w2ui.com/web/demos/#!grid/grid-26 and doubleclick on a row - now it won't leave the dragging-mode no matter what you do. Clicking another row makes things just worse, as more and more rows are being dragged and the script almost gets unresponsive.

**Comment by vitmalina** [comment]
Yes. Reorder records has some problems. Will fix.

**Comment by frontyard** [comment]
This happens with single click (selection) on a row as well.

Any progress?

**Comment by Connum** [comment]
Seeing that this has meanwhile been addressed and fixed, I will close this issue.
