### ISSUE TITLE
Textarea in a Popup is unresponsive to js functions

### ISSUE THREAD

**Issue by davidzweig2** [vitmalina/w2ui#973]
If I create a textarea within a popup, I am unable to read/write it's value (the contents). I have tried with JQuery ( $("#myTextArea").val() ) and plain Javascript. I can set a value via the console, and read it back with js, but this value does never appears onscreen in the textarea.

    <div id="input_popup" style="display: none; width: 400px; height: 200px; overflow: auto">
	    <div rel="title">
	        Paste the text in the textbox:
	    </div>
	    <div rel="body">
	        <div style="padding: 10; font-size: 11px; line-height: 150%;">Paste the text in the box below. A newline is recognised as a 
	            <textarea id="myTextArea" rows="4" cols="50">At w3schools.com you will learn how to make a website. We offer free tutorials in all web development technologies. 
				</textarea> 
	        </div>
	    </div>
	    <div rel="buttons">
	        <button class="btn" onclick="alert('parse!')">Parse</button>
	    </div>
	</div>

Maybe has something to do with 'display:none', and the browser not bothering to update it at a later time, even though the display mode has changed? Meanwhile I am using the simplemodal plugin, which works ok, but is not as pretty.

Great library, thanks. :-) 
![capture](https://cloud.githubusercontent.com/assets/5949672/8393554/51168a42-1d1d-11e5-86a4-c6d532b60716.PNG)

**Comment by vitmalina** [comment]
You probaly created text area from HTML that is already on the page. Therefore, you have 2 textareas on the screen and brother takes wrong one. Use
```js
$('#w2ui-popup textarea').val() 
```
