### ISSUE TITLE
w2ui does not work with PrototypeJS

### ISSUE THREAD

**Issue by xijun-j** [vitmalina/w2ui#978]
I used jquery and Prototypejs with w2ui, but it doesn't work.

this is my code:
http://jsfiddle.net/baohu/8yen59ce/13/

When I comment "prototype.js" and "$j = jQuery.noConflict();",
used just only jquery  it works fine.
How do i fix it?

thanks

**Comment by vitmalina** [comment]
Unfortunately, right now w2ui expects that $ is jQuery. There is no way around it at the moment. I will see if I can fix it.

**Comment by vitmalina** [comment]
I think I found an easy solution. See attached commit. you will need to download /dist/w2ui.js with this change.

**Comment by xijun-j** [comment]
hi, @vitmalina 
Thank your greate job!
I try following source, it not yet works fine, I get this error:
SCRIPT438: Object doesn't support property or method userExist
can you tell me how can I fixed it? 
thanks!

```
<!DOCTYPE html>
<html>
<head>
    <title>W2UI Demo: layout-1</title>
    <link rel="stylesheet" type="text/css" href="https://raw.githubusercontent.com/vitmalina/w2ui/515381f1f1ced5305cf4ec27250fefc5ef6d5b2d/dist/w2ui.css" />
	<script src="http://prototypejs.org/assets/2007/1/18/prototype.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js"></script>
	
	<script type="text/javascript">
		$j = jQuery.noConflict();
	</script>
	
	<script type="text/javascript" src="https://raw.githubusercontent.com/vitmalina/w2ui/515381f1f1ced5305cf4ec27250fefc5ef6d5b2d/dist/w2ui.js"></script>
	
</head>

<body>
	<div id="layout" style="width: 100%; height: 400px;"></div>
</body>

<script type="text/javascript">
$j(function () {
    var pstyle = 'border: 2px solid #dfdfdf; padding: 5px;';
    $j('#layout').w2layout({
        name: 'layout',
        padding: 4,
        panels: [
            { type: 'top', size: 50, resizable: true, style: pstyle, content: 'top' },
            { type: 'left', size: 200, resizable: true, style: pstyle, content: 'left' },
            { type: 'main', left:206, style: pstyle, content: 'main' },
            { type: 'right', size: 200, resizable: true, style: pstyle, content: 'right' }
        ]
    });
});
</script>

</html>
```

**Comment by vitmalina** [comment]
Please create jsFiddle for the example. I have modified the code so that $ is passed to the constructor and thus not required to be a global. Theoretically prototype should work.

**Comment by xijun-j** [comment]
hi, @vitmalina 

Thank you immediately reply.
I have create the example in the following url. Can you help me?
http://jsfiddle.net/baohu/8yen59ce/20/

thanks again

**Comment by vitmalina** [comment]
Your jsfiddle does not work
