### ISSUE TITLE
Colspan for Columngroups after add or remove columns in W2UI Grid

### ISSUE THREAD

**Issue by rajb21** [vitmalina/w2ui#980]
I am using columngroups and columns. Columngroups have specified colspan.
But after adding or removing columns, its alignment changes.
Is there any way to make the colspan dynamic?
Thank you in advance.

**Comment by rajb21** [comment]
Hi Vitmalina,
Could you please help me with this? Its really urgent.
Thank you.

**Comment by vitmalina** [comment]
You will most likely need to do pull refresh, grid.refresh() should do. It should work in dynamic nature. If it does not help, please create jsFiddle where I can see the problem.

**Comment by rajb21** [comment]
Please check below jsFiddle:

http://jsfiddle.net/api/post/jquery/2.1/

Add new column "Middle name " in the table,It will get added in column group "contact details" but I want to add it under column group "Name Details".
This is happening because colspan for column group "Name details " is 2.
How can I make this colspan dymanic? so that it will be 3 as I add column middle name to it.

Thank you.

**Comment by vitmalina** [comment]
span is a property in columnGroups array. You can change it dynamically. The only known problem is that you cannot have hidden columns, you will need to remove (or add them).

**Comment by vitmalina** [comment]
Since no further response, closing the issue.
