### ISSUE TITLE
Add tooltip with cell value only if ellipsis is present!

### ISSUE THREAD

**Issue by hansgru** [vitmalina/w2ui#981]
One much valued feature for data sensitive business applications is the possibility to show the value of a cell in a tooltip, only if the cell has an ellipsis style applied to it, i.e. the width of the column cuts a part of the displayed cell value.

Please add such a feature to w2ui too.

Without such a feature, the user tries to constantly resize the columns, just to see some hidden values, and in many cases this is not even possible since there's not enough place horizontally.

Thank you.

**Comment by vitmalina** [comment]
If grid.show.recordTitles is true, which is default value, then it will display the title when you more over a cell and wait there. It uses HTML title="" property. You can also provide your own title functions if for the column you define title: function () {}, similar as render: function. Do you think some other funcionality is needed?

Also, using custom rendered you can create your own content and tooltips with w2tag() and/or w2overlay()

**Comment by hansgru** [comment]
> Do you think some other funcionality is needed?

Yes. The problem is that the tooltip on each cell is not wished, it's counter-productive and users don't want it. It's only required when the text in a cell is hidden partially by the ellipsis or overflow/hide.

**Comment by vitmalina** [comment]
Agree. Also, I do not like regular HTML title="", it is slow. I would rather create a tooltip for it.

**Comment by vitmalina** [comment]
Since no further response, closing the issue.
