### ISSUE TITLE
Selection in sub-grid selects in main grid as well

### ISSUE THREAD

**Issue by Connum** [vitmalina/w2ui#982]
In the sub grid demo: http://w2ui.com/web/demos/#!grid/grid-7
1. Click on the first "+" to show the sub grid
2. Select multiple rows in the sub grid via single-click-dragging

Result: In addition to the rows in the sub grid, the same number of selected rows is being selected in the main grid below.

**Comment by vitmalina** [comment]
Yes, I think the bug. I will be refactoring subgrids completely, will address it then.

**Comment by vitmalina** [comment]
Subgrids are refactored. All changes in current master
