### ISSUE TITLE
locale not translating some parts.

### ISSUE THREAD

**Issue by exemony** [vitmalina/w2ui#985]
Hope someone could help me, it used to work til 2 weeks or so.

In locale files those words are added, and as I said before, it used to work properly. If any code is needed I will be pleased to add it.

Thats the way i'm loading my locale:

```javascript
 $(document).ready(function () {
   w2utils.locale('../locale/w2ui/es-es.json', function () {
   grid.layout.refresh();
  });
 });
```

![locale](https://cloud.githubusercontent.com/assets/13198103/8520000/ec456e74-23d6-11e5-990d-b96d8cc01d5b.jpg)

**Comment by Connum** [comment]
¡Hola!

Did it just stop working without any update of the library? In that case, it would be rather inexplicable... Did you check the console, is there any error output? 

Saludos

**Comment by exemony** [comment]
¡Hola! 

Actually there's nothing new, neither errors. I can't understand it, i really can't. It wouldn't be a problem but it also doesn't format dates, and that, is a huge issue as I cannot work with any dates.

If anyone have something in mind that could help, I would appreciate it.

**Comment by vitmalina** [comment]
There was some change in locale files (date_format and date_show, I think). You will need to donload new locale files from master/src/locale, if you use current master.

**Comment by exemony** [comment]
Sorry vitmalina, but I have the same version of locale that you have in the master. Although you have corrected the issue #978 in the .js files, has that one something to do with that?

Thanks and great job ;)

**Comment by vitmalina** [comment]
Please create jsFiddle, I cannot replicate problem otherwise.

**Comment by exemony** [comment]
Hi @vitmalina , 
First of all thanks for all your support and your great library, that actually works phenomenal.
Secondly, I have to say that I don't know why this error happens but it only happens sometimes, I think is a problem with the server side reloading the locale or something.

In jsFiddle works perfectly with local data. So, if you want you can close this thread. Sorry I can't help more about this small problem that it happened to my job with your library. If it happens that I find out that it is a problem with W2ui, i'll make another issue thread about it.

Thanks again, and excuse my english as it's not my native tongue language... in fact neither my second language.

Regards, **eXemonY**

**Comment by vitmalina** [comment]
If it is a problem with a remote datasource, can you create an example on some of your servers and post a link so that I can see the problem. I am looking for a minimal example that has the problem.

**Comment by exemony** [comment]
Sorry for the late answer, I'll try my best to make an example, but I'm not sure if I would be able to do it, as they are Servers just for clients. Hope I can create a small one this weekend and give you a link by Monday-Tuesday. Can't promise anything. Thank you again

**Comment by vitmalina** [comment]
ok

**Comment by vitmalina** [comment]
Since no further response, closing the issue.
