### ISSUE TITLE
w2tag displayed only once after keypress except if an error is raised

### ISSUE THREAD

**Issue by Delgan** [vitmalina/w2ui#986]
I face a strange behavior of w2tag amd w2fields custom inputs (using Firefox, I do not know about the others browsers).

In fact, I try to display a tag when the user types something in an input, to display a message if he wrote a `char` rather than an `int` for example.

So I created my own type of input as indicated in the documentation, and I linked it to my DOM input.

Here is what happens:
* If I write a first letter in the field, the tag is displayed correctly.
* If I write a second letter, the tag disappears but never reappears.
* If I attach the event `.on("click")` instead of `.on("keypress")`, it works.
* If any error is raised after the display request, it works.

You can see all of this by visiting this link: http://jsfiddle.net/q4kjaa31/3/

Anyone have an explanation and solution for this strange problem please?

**Comment by Delgan** [comment]
This works a little better using version 1.5, the message is displayed one for two: http://jsfiddle.net/q4kjaa31/4/

**Comment by vitmalina** [comment]
The reason it is hiding is because there is internal logic to hide tag when char is typed (if it is input). I have implemented an option to enable/disable that. By default it is enabled. I have refactored w2tag to allow few new things to better do validation. Here is a link to jsFiddle (it links 1.5.x nightly version)

Also, here is the list of options you can submit to w2tag
```js
options = $.extend({
    id              : null,     // id for the tag, otherwise input id is used 
    html            : text,     // or html
    position        : 'right',  // can be left, right, top, bottom
    left            : 0,        // delta for left coordinate
    top             : 0,        // delta for top coordinate
    style           : '',       // adition style for the tag
    css             : {},       // add css for input when tag is shown
    "class"         : '',       // add class for input when tag is shown
    onShow          : null,     // callBack when shown
    onHide          : null,     // callBack when hidden
    hideOnKeyPress  : true,     // auto hide if input changed or key pressed
    hideOnBlur      : false     // auto hide if input changed or key pressed
}, options);
```
