### ISSUE TITLE
w2ui grid request interval

### ISSUE THREAD

**Issue by supasteri** [vitmalina/w2ui#987]
Hi there

I love this library, and have been using the grid combo editable functionality. In this case I needed to be able to control the combo (with remote data source) I had a requirement to be able to control the interval for the ajax callout, so I made the following changes in the w2ui-1.4.2.js (Apologies if this approach is not cool, but I am fairly new to Git and not sure how the whole Pull thing works...)

=======================
FROM: (line 10724)
      ...
      markSearch      : false
   };
TO:
   ...
   markSearch      : false,
   interval        : 0             // how long to delay the ajax call for
};

=========================
FROM: (line 10750)
    if (options.url) this.request(0);
TO:
    if (options.url) this.request(options.interval);

=======================
FROM: (line 11643) 

    if (typeof interval == 'undefined')  interval = 350;

TO:
    if (typeof interval == 'undefined') {
                if (options.interval && options.interval > 0)
                        interval = options.interval;
                else
                        interval = 350;
   }

**Comment by vitmalina** [comment]
I integrated the changes, but please submit a pull request next time. It would be a good time to learn how to do it :). Also, note that you will need to change /src/* filtes, because they are bundled together by Grunt and put into /dist/* folder.
