### ISSUE TITLE
grid records update hiding data

### ISSUE THREAD

**Issue by collanders** [vitmalina/w2ui#991]
If I set the grid records to a new dataset with more data, the data past the last record is not visible while scrolling.

I've noticed that if I reset the total number of records it fixes the issue
eg.            
w2ui.grid.records = newDataSet;
w2ui.grid.total = w2ui.grid.records.length;  // this line fixes it

**Comment by vitmalina** [comment]
I am glad you found a solution. The reason total is there is because when the data source is remote, it will only send first set of records, but I need to know how many more on the server.

**Comment by collanders** [comment]
Thanks Vitaly

I've been using your grid on a couple of small projects and I've got to say
it's an awesome piece of work.  It's very easy to configure and offers a
lot of features while staying really responsive.  As a programmer it
inspires me to write better code.  Thanks for everything you've done.

Chris

**Comment by vitmalina** [comment]
Thanks for the positive feedback.
