### ISSUE TITLE
infinite local search

### ISSUE THREAD

**Issue by birkaf** [vitmalina/w2ui#992]
Hello
I have same problem. I use local search in grid but then enter the query the first row show "undefined" second row show find result but search loops and if a i cannot delete symbol from search query (and all handler onrow not working). I can stop search only if I click on close button in search area
![w2ui](https://cloud.githubusercontent.com/assets/1826792/8640034/551576fe-28f2-11e5-82f9-8fa5323126ba.png)

I use w2ui-1.5.0.min.js

Grid initialization:

$('#grid').w2grid({
        name   : 'grid',
        header : 'Список групп',
        msgDelete: 'Вы уверены что хотите удалить запись?',
        show   : {
            header 		  : true,
            toolbar 	  : true,
            footer		  : true,
            lineNumbers	  : true,
            toolbarDelete : true,
            toolbarAdd    : true
        },
        url : {
            remove	: 'group2/getGroup.php',//'server/side/path/to/remove',
            save	: 'group2/getGroup.php'
        },
        columns: [
            { field: 'g_name', caption: 'Имя группы', size: '30%',sortable: true },
            { field: 'g_outDateOrder', caption: 'Дата приказа УЦ ДОСС', size: '20%',sortable: true },
            { field: 'g_outNumOrder', caption: 'Номер приказа УЦ ДОСС', size: '20%',sortable: true },
            { field: 'g_dateTransfer', caption: 'Дата зачисления', size: '120px',sortable: true },
            { field: 'g_dateDeduct', caption: 'Дата отчисления', size: '150px',sortable: true }
        ],
        multiSearch: false,
        searches: [
            { field: 'g_name', caption: 'Имя группы', type: 'text' }
        ],
        onAdd: function(event) {
            $().w2popup('open', {
                title	: 'Создание новой группы',
                body	: '<div id="formAddGroup" style="width: 100%; height: 100%;"></div>',
                style	: 'padding: 15px 0px 0px 0px',
                width	: 750,
                height	: 600,
                onOpen	: function (event) {
                    event.onComplete = function () {
                        $('#w2ui-popup #formAddGroup').w2render('addGroupForm');
                        $('#formAddGroup').find('input[name=prof_list]').attr('placeholder', 'Выберите тип обучения')
                            .prop('readonly', true);
                    }
                }
            });
        },
        onDblClick: function(event) {

            var rec = this.get(event.recid);
            console.log(rec);
            console.log("dblClick");
            w2ui['editGroupForm'].record = rec;
            $.when(getProf(w2ui['editGroupForm'].record.g_type_edu)).then(function(){
                w2ui['editGroupForm'].set('g_eduProf', { type: 'list',options:{items: serProfArr}});
                serProfArr="";
            });
            w2ui['editGroupForm'].refresh();
            $().w2popup('open', {
                title	: 'Редактирование карточки группы',
                body	: '<div id="formEditGroup" style="width: 100%; height: 100%;"></div>',
                width	: 750,
                height	: 600,
                modal   : true,
                onOpen	: function (event) {
                    event.onComplete = function () {
                        $('#w2ui-popup #formEditGroup').w2render('editGroupForm');
                        $('#formEditGroup').find('input:text, textarea, select').attr('disabled','disabled');
			            $('#formEditGroup').find('input[name=save_edit]').attr('disabled','disabled');
		            }
                }
            });
        },
        onDelete: function(event) {
            var sel = w2ui['grid'].getSelection();
            console.log(event);

            
        }
    });
    w2ui['grid'].load('group2/getGroup.php');
    w2ui['grid'].on('*', function (target, eventData) {
        console.log(target);
        console.log(eventData);
    });

**Comment by vitmalina** [comment]
Can you create a jsFiddle to illustrate the problem.

**Comment by birkaf** [comment]
I send you email 15 July file in attachment illustrated this problem.
I will try to create jsFiddle...

**Comment by vitmalina** [comment]
Since no further response, closing the issue.
