### ISSUE TITLE
Read the column data in the grid

### ISSUE THREAD

**Issue by ueoka** [vitmalina/w2ui#994]
Example to get the record from PHP

	$Json['columns'][]= (array('field' => 'recid','caption' => 'No','size' => '50px',
						'resizable' => true,'sortable' => true,'style' => 'text-align: right','render' => 'int'));
	$Json['columns'][]= (array('field' => 'website','caption' => 'WEB SITE','size' => '40px','title' => '',
						'resizable' => true,'sortable' => true,'style' => 'text-align: center'));
	$Json['records'][]= 
					(array(
							'recid'				=> 1,
							'website'			=> 'http://www.realmax.co.jp/'
					));
	echo json_encode($Json);

Properties of the grid
	var main = {　grid:{
		name:'gmain'
	}};

If there is no columns in the property, it does not appear correctly

**Comment by vitmalina** [comment]
you must have at lease one column. It should not be a problem to create a generic one and map your data there.

**Comment by ueoka** [comment]
Example was bad.
