### ISSUE TITLE
Using nanoScroll with w2ui

### ISSUE THREAD

**Issue by atari83** [vitmalina/w2ui#995]
Hey there,
I'm trying to integrate nanoScroll with w2ui Layout , but I fail each time.
Actually I've a Sidebar in my layout and wish to use nanoScroll jQuery library for vertical scrollbar.

Can you show me a snippet code about how to accomplish that task ?

Thank you,

**Comment by vitmalina** [comment]
I am not familiar with nanoScroll, but I would suggest you initiate scroll in onRefresh event in the onComplete clause.

**Comment by atari83** [comment]
Ok, let me check this .. I'll update here. Thanks.

**Comment by atari83** [comment]
Well, I just came up with below code, now at least see the nanoScroller ... but it is kinda messy .. I mean I see two scrollbars, one is nanoscroller which appears but not working , the other one is firefox default scrollbar which is active.

		onRefresh: function(event) {
    	    	$('.w2ui-sidebar-div').addClass('nano');
    	    	$('.nano').nanoScroller();
		}

**Comment by atari83** [comment]
Hello  vitmalina ,
I just quit using nanoScroller and instead used slimScroll and as you suggested I override onRefresh() event and it just did the trick ;)

Thanks,
