### ISSUE TITLE
maxDropWidth for MultiSelect

### ISSUE THREAD

**Issue by atari83** [vitmalina/w2ui#997]
Hello,
Well, I have so many items with small length (each 10 characters at most) , but the width of the input element is 800px. As I see currently the drop-down menu is getting initialized with same width as input which is not good. 
Could we have MaxDropWidth parameter just like MaxDropHeight ?!

Thanks,

**Comment by vitmalina** [comment]
Added maxDropWidth

**Comment by atari83** [comment]
Thank you!
